### ISSUE TITLE
 SpeckFileReader class

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1004]
Currently many renderables have code for reading speck files, which contain many similar lines around reading files as well as checking for things like `line.substr(0, 10) != "texturevar"` .

We should make a generic class that can read speck files and pass the row and column data to the renderables, or provides a more specific interface for reading the files.

**Comment by micahnyc** [comment]
closing with: https://github.com/OpenSpace/OpenSpace/pull/1585

**Comment by alexanderbock** [comment]
Oh yea.. forgot that we had an issue for it
