### ISSUE TITLE
Perform shading/Atmosphere interaction can create unexpected behavior

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1008]
When looking at the night side of a planet, it is dark. If you then uncheck perform shading, the night side becomes light, if you then try to goto the surface on the night side, once you enter the atmosphere, it becomes dark again. 

While this is technically correct, it is not an intuitive behavior causing confusion. Proposed solution would be to turn off the atmosphere when perform shading is off, or potentially adjust some of the params.

**Comment by hedbergj** [comment]
#966 ?

**Comment by micahnyc** [comment]
Also to address here:

- Night layers
- 'sun overhead' setting in atmosphere
