### ISSUE TITLE
Scaling and Atmosphere is not compatible

### ISSUE THREAD

**Issue by liuloppan** [OpenSpace/OpenSpace#1014]
When changing the scale of Earth or Mars while having atmosphere enabled there are visual artifacts due to precision errors.

**Comment by jccosta** [comment]
@liuloppan I tested both, Earth and Mars (pics added), and didn't get any issues. Can you provide a record session file with the problems
![OpenSpace_000000](https://user-images.githubusercontent.com/874760/83152778-30c1c800-a0cc-11ea-90ef-f6177e664388.png)
![OpenSpace_000001](https://user-images.githubusercontent.com/874760/83152783-315a5e80-a0cc-11ea-8fac-68a820147d42.png)

**Comment by liuloppan** [comment]
Tried now and could not reproduce on master. When running on our 'project/spvl' branch the issue is still there. It has not been updated since March I believe so maybe this has been fixed since I wrote this issue. I will close since it is not reproducable on master.
