### ISSUE TITLE
Touch is interpreted as mouse input

### ISSUE THREAD

**Issue by Mik-pe** [OpenSpace/OpenSpace#1018]
If OpenSpace is started on a touch-enabled device (e.g. Win10 with touchscreen), touch input is sent to OpenSpace as mouse input.

When touch-interacting with the application, this gives a ghost-input which is hidden from the touchmodule, producing a slight drift when using touch-input.

**Dev note:**
With the current GLFW implementation, which is based off a touch-branch, there is a field which interprets touch input and passes it along as mouse input to the application. This is flipped by an internal switch in the opaque `_GLFWWindow` struct, which we really can't access and change. No current functions in the glfw-branch allows for any change of this flag.

If we were to disable this touch input-bypass completely, touch within the application will function differently, as an example:
The web-gui currently relies on receiving mouse inputs, and don't know about any touch-input. Clicking on buttons work fine, but dragging sliders and storing a "down/up" state of the finger does not work.

**Comment by liuloppan** [comment]
This is definitely a concern for the touch application. I think it is essential at least for the STENA project that you can deactivate touch in space while still allowing GUI interaction (for example when camera is flying and retargetting aim/anchor). Currently there is nothing preventing a user from purposefully or accidentally messing up the camera navigation.
I do believe a long term solution would be to keep the touchmodule and the touch->mouse reinterpretation separate ie whenever using touch module the reinterpret is deactivated. This will give us better control over the input that is sent to OpenSpace and would allow us to create a better touchtable experience. This will require some extended work on getting desirable touch functionality back to the GUI but I think it will open up more possibilites for the OpenSpace navigation. What should be done until january is another question.
