### ISSUE TITLE
Segments Property for satellites causes crash

### ISSUE THREAD

**Issue by liuloppan** [OpenSpace/OpenSpace#1023]
The interval on segment property is set to a very high value which causes a crash if you try to interact with the slider at any point. Should be set to more reasonable values.
Also "EnableFade" value is not accessible

**Comment by GPayne** [comment]
I pushed a fix for this to branch **issue/1023**. You can now manipulate the segment slider (has reasonable limits) without crashing, and the rendering will update appropriately.
I removed a fade property because there is a fade sub-property under "Appearance" that can be manipulated.

**Comment by liuloppan** [comment]
Looks good, ready for merge.
