### ISSUE TITLE
Add an option to add external modules

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1047]
1 . Provide a list of folders that are treated the same as the `modules` folder in OpenSpace itself
2. Define a plugin API that modules can use to create DLLs that get linked in real time

**Comment by dtorban** [comment]
Just in case you are interested, I did something similar for my own development purposes (I didn't want to worry about linking my external libraries into the core system): 

https://github.com/dtorban/OpenSpace/commit/1df95ca3633e0b582c4ceed7dcc2b99bc7f882dd

Who knows, maybe it would be helpful when you develop this functionality.  I only tested on Linux, but it should work on Windows and Mac as well.

**Comment by alexanderbock** [comment]
Closing it as a wontfix, since #2 doesn't make much sense with our current architecture an #1 can be solved by just adding the external model into the `modules` folder
