### ISSUE TITLE
Change keybinding for trails

### ISSUE THREAD

**Issue by liuloppan** [OpenSpace/OpenSpace#1055]
The current keybinding 'h' stands for 'hide' but this is not very intuitive as we are now hiding and showing multiple things with our keybindings. This should be changed to 't' for trails in a similar fashion as 'l' represents 'labels'.

**Comment by alexanderbock** [comment]
h -> t

and at the same time

w -> b

**Comment by alexanderbock** [comment]
In this case, T toggles _all_ trails, rather than planetary ones.  Shift+H keybind disappears but action is still added.  Same for toggling moon trials
