### ISSUE TITLE
Edge glitch on milky way galaxy

### ISSUE THREAD

**Issue by liuloppan** [OpenSpace/OpenSpace#1059]
![galaxyedgebugmark](https://user-images.githubusercontent.com/6057854/73390283-0e629e00-42d6-11ea-92b1-571b85cadc97.png)

There is an edge glitch on the galaxy rendering

**Comment by Mik-pe** [comment]
Some more info on this: 

It seems to be related to the downsampling of volume rendering and only appears in one half of the volume that is rendered. It is also only visible during downsampled volume rendering, which makes me think that it's related to the directions of the downsamples in some way?

Image below is an over-exaggeration of the artifact (volume rendered as white):
![bild](https://user-images.githubusercontent.com/5653426/73430083-76000400-433d-11ea-9f12-a4504be6f3ea.png)

**Comment by alexanderbock** [comment]
Has been fixed at some point
