### ISSUE TITLE
miklyway sphere should have higher resolution asset

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1060]
Now that we have 4k and 10bit projectors.

**Comment by alexanderbock** [comment]
Marking this as fixed .. the `milkyway_textures` HttpSynchronization downloads two textures:
1. DarkUniverse_mellinger_4k.jpg
2. DarkUniverse_mellinger_8k.jpg

but we use the 4k by default because of the performance impact of the 8k
