### ISSUE TITLE
AA lines makes trails disappear on mac

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1065]
Using glLineWidth > 1 is not working on the mac. so when zooming close to an object the trails are disappearing.

**Comment by hedbergj** [comment]
... and I don't think it will ever be > 1 on mac:
https://community.khronos.org/t/gllinewidth-gives-gl-invalid-value-for-widths-1/69023/3
(one reason we switched to windows for the dome machine)

**Comment by jccosta** [comment]
Fixed in 11aa87bd3624e3fd73fb9d6160b61b2c33aa32e4

**Comment by alexanderbock** [comment]
Close the ticket, then ;)
