### ISSUE TITLE
Use a shadow mapping approach to 67P image projection to not project images in 'shadow' areas

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#109]
<a href="https://github.com/alexanderbock"><img src="https://avatars.githubusercontent.com/u/4921724?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexanderbock](https://github.com/alexanderbock)**
_Friday Jul 01, 2016 at 12:19 GMT_
_Originally opened as https://github.com/OpenSpace/OpenSpace-Development/issues/111_

----

Parts of the comets that are self-shadowed should not be projected on

![Comet](http://i.imgur.com/6jXOa8G.png)

**Comment by alexanderbock** [comment]
![Imgur](http://i.imgur.com/Yo5RRIE.jpg)

**Comment by emiax** [comment]
Pushed to feature/rosetta-shadowmapping.
Yet to be reviewed/tested and integrated into develop.

**Comment by alexanderbock** [comment]
Fixed in 6d56b1d38a1a40d8606dfbdff80dfa7311a66efe
