### ISSUE TITLE
Sphere/Grid Rending Issue

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1102]
When viewing the RenderableGrids, there is a "twinkling" issue. Seems to be an old issue that has come back. To view, just enabled the radio sphere and fly out to it.

**Comment by liuloppan** [comment]
We have also observed some "twinkle" issues with the planetary Orbits for our project, could it be the same?

**Comment by jccosta** [comment]
@micahnyc @alexanderbock 
I added a temporary solution to this issue in commit 2c1035f05dd1bc6a3542a7e4f9553c44db2fe326 in branch issue/1102.
I would like to talk to Alex before adding a final solution here.

**Comment by alexanderbock** [comment]
Closed in 5c5d9f36ebecbf33e31106fd18796f543d54be34
