### ISSUE TITLE
How to auto-generate Lua documentation for Renderables etc

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#111]
<a href="https://github.com/alexanderbock"><img src="https://avatars.githubusercontent.com/u/4921724?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexanderbock](https://github.com/alexanderbock)**
_Friday Jul 08, 2016 at 08:58 GMT_
_Originally opened as https://github.com/OpenSpace/OpenSpace-Development/issues/113_

----

In order to see which Key-Value pairs are supported, what the supported values are, etc.  RIght now, it is near impossible to deduce the possible options for Renderables in the scene description files

**Comment by nusic** [comment]
### Idea 1: 
Supported Key-Value pairs for a particular class could be stored in source. I.e. each class that reads data from a .mod file (e.g. `RenderableModel`) could have associated a `ghoul::Dictionary` defining all valid keys, each mapping to descriptions of supported values. An example would be


`ghoul::Dictionary supportedInput;
supportedInput.setValue("Name", STRING_ANY);
supportedInput.setValue("Shading.Fadeable", BOOL_ANY); 
..
const std::vector<std::string>& 
supportedInput.setValue("Rotation.Source", );


`

`
{
  Renderable {
    Type: ["RenderableModel", "RenderableGlobe", ...],
  }
}
`

**Comment by nusic** [comment]
## Idea 1:
Supported Key-Value pairs for a particular class could be stored in source. I.e. each class that reads data from a .mod file (e.g. RenderableModel) could have associated a a specification (could be something similar to a ghoul::Dictionary) defining all valid keys, each mapping to descriptions of supported values. Initialization of such a specification could look something like

```
ghoul::DictionaryKeyValueSupport supportedInput;
supportedInput.add("Name", STRING_ANY);
supportedInput.add("Shading.Fadeable", BOOL_ANY); 
supportedInput.add("Body", STRING_ANY_OF({"SUN", "EARTH", ... }));
supportedInput.add("Rotation.Source", STRING_ANY_OF(SpiceManager::ref().getAllFrames()))
supportedInput.add("SomeInteger", INTEGER_IN_RANGE(0, 10));
supportedInput.add("YetAnotherNestedDictionary", DICTIONARY_ANY);
RenderableModel::SUPPORTED_INPUT = supportedInput; // set static variable
```
### Pros
1. Automatically generate documentation
2. Automatic validation of input (e.g `RenderableModel::SUPPORTED_INPUT.satisfiedBy(inputDict);`
3. Automatic testing (e.g. take a subset of all possible combinations of supported input, instantiate RenderableModels using that input and perform unit tests on those)
4. Allow for dynamic input support (e.g. setting supported based on what SPICE data is available)

### Cons
1. The class `DictionaryKeyValueSupport` would be non-trivial to implement.
2. Can be cumbersome for developers to keep the supportedInput up-to-date when iterating quickly

**Comment by nusic** [comment]
## Idea 2
Supported Key-Value pairs are stored in the modfile .mod file together with the actual Key-Value pairs used for input. E.g, if a key "X" should only be able to map to one of {A, B, C}, then also define the key "X-Support" mapping to {A, B, C}. If a key "Y" has no restrictions, don't specify "Y-Support". A .mod file could then look something like
```
{
    Name = "Earth",
    Parent = "EarthBarycenter",
    Parent-Support: {"EarthBarycenter", "SUN-BARYCENTER", ... },
    Renderable = {
        Type = "RenderablePlanet",
        Type-Support = {"RenderablePlanet", "RenderableGlobe", ... },
        Frame = "IAU_EARTH",
        Frame-Support = {"IAU_EARTH", "IAU_SUN", ... }
        Geometry = {
            Type = "SimpleSphere",
            Type-Support = {"SimpleSphere"},
            ...
        }
    }
}
```

### Pros

1. No need for additional documentation
2. Automated input validation can be done statically or during run time

### Cons

1. When a RenderableModel is update - or when a new type of Renderable is added - all .mod files must be manually updated or they will be left invalid.
2. Mod files may end up becoming a wall of text

**Comment by alexanderbock** [comment]
I like the first idea very much and I don't think it would be too hard to implement... another big con with number 2 is repetition.. every modfile that creates a RenderableModel will have to repeat all of the information.
