### ISSUE TITLE
Only the development team can use the software, is this intentional?

### ISSUE THREAD

**Issue by SevenSpheres** [OpenSpace/OpenSpace#1110]
I downloaded OpenSpace from [here](https://www.openspaceproject.com/version-0151). When I tried to run it I got the message "VCRUNTIME140_1.dll was not found", so I clicked on the [link](https://files.slack.com/files-pri/T1JFEB82Z-FTYGL2SAF/download/vcruntime140_1.dll) to download that file and was asked to "Sign in to AMNH Science Visualization Group". So apparently you have to be part of the development team to properly use the software? I assume this isn't intentional, can someone please clarify?

**Comment by SevenSpheres** [comment]
@375gnu sent me a link with the DLL, so I can use OpenSpace now. Might want to consider fixing that link though.

**Comment by 375gnu** [comment]
That's not a "link to a dll", that's an official m$ distributable VC++runtime installer - https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by SevenSpheres** [comment]
> That's not a "link to a dll", that's an official m$ distributable VC++runtime installer

I realize that. I said "a link *with* the DLL", since the installer obviously included the DLL in question.

**Comment by alexanderbock** [comment]
@SevenSpheres  that was indeed not intentional.   The link was pointing to the internal Slack of one of the partners;  I have changed it to point to the same Microsoft Redistributable that @375gnu has sent to you.

Thanks for reporting!
