### ISSUE TITLE
Texture targets failed to initialize for window 0!

### ISSUE THREAD

**Issue by jichengtao** [OpenSpace/OpenSpace#1111]
After compiled the OpenSpace 0.15.1 under Ubuntu 18.04 successfully, there is an error when running it:
Texture targets failed to initialize for window 0!.
The OpenGL version is 4.6, and GLEW version is 2.1.0.

> 2020-03-08 | 17:30:20.253 | MemoryAwareTileCache | Debug | Resetting tile cache size
> -- | -- | -- | -- | --
> 2020-03-08 | 17:30:20.312 | MemoryAwareTileCache | Info | Tile cache size was reset
> 2020-03-08 | 17:30:20.314 | OpenSpaceEngine | Info | Finished initializing OpenGL
> 2020-03-08 | 17:30:20.314 | main | Debug | Initializing OpenGL in OpenSpace Engine finished
> 2020-03-08 | 17:30:20.314 | SGCT | Info | -------------------------------
> 2020-03-08 | 17:30:20.314 | SGCT | Info | OpenGL error: GL_INVALID_VALUE
> 2020-03-08 | 17:30:20.314 | SGCT | Info | Texture targets failed to initialize for window 0!
> 2020-03-08 | 17:30:20.315 | SGCT | Info | ScreenCapture: PBO rendering enabled.
> 2020-03-08 | 17:30:20.315 | SGCT | Info | Ready to render!
> 2020-03-08 | 17:30:20.315 | main | Info | Starting rendering loop
> 2020-03-08 | 17:30:20.315 | OpenSpaceEngine | Info | Loading asset: default

**Comment by alexanderbock** [comment]
Do you get an error with the rendering itself or "just" an error message in the log?

**Comment by jichengtao** [comment]
Hi @alexanderbock , it' an error message. But, no objects are rendered, the rendering window is only show black screen with the simulation/real time on the top-left of the window.

**Comment by GPayne** [comment]
Hi @jichengtao, can you tell me about the graphics on your system? Are you using an nvidia or amd GPU, or the integrated graphics on your CPU?

Also, I noticed that you replied in issue #1112, that you are having that same problem. Do you always see this texture targets error when you run, or does it sometimes segfault instead (issue 1112)?

**Comment by jichengtao** [comment]
Hi @GPayne , I am using the NVIDIA GPU (GeForce GTX 1050). I always see this error information when I run OpenSpace. 
I also encountered the Segmentation Fault issues. The segfaults are not appearing any more if I remove the  volume.asset (locate in /data/assets/scene/milkyway/milkyway/) and the grids.asset (locate in /data/assets/scene/digitaluniverse/), but I got a black screen no objects are rendered.

**Comment by GPayne** [comment]
Elaboration on @jichengtao 's comment about disabling the **volume.asset** and **grids.asset**: here are step-by-step instructions for how to do this (This is currently necessary when running in linux to prevent a segfault):
1. Edit the file **data/assets/base.asset**, and comment-out the volume asset request:
  `--asset.request('scene/milkyway/milkyway/volume')`
2. Delete the file **data/assets/scene/digitaluniverse/grids.asset**

These changes do not require a re-build of the source code. At this point, OpenSpace will run without crashing but nothing is rendering (black screen mentioned above) right now due to some problem with the newest version of sgct in linux.

**Comment by GPayne** [comment]
This appears to be fixed in new 'linux' branch, commit e6b44b5. No longer segfaults if the **scene/milkyway/milkyway/volume** asset or spherical grids in **data/assetss/scene/digitaluniverse/grids.asset** are enabled.
