### ISSUE TITLE
Globebrowsing tiles are often gone or inside out

### ISSUE THREAD

**Issue by liuloppan** [OpenSpace/OpenSpace#1121]
When we are navigating between planets and abruptly changing anchors we often get partly missed tiles or completely missed tiles (planet completely disppears) which is most easily illustrated where the atmosphere remains. This occur very frequently in our project where we travel between planets and seem to be an issue with all globes to different degrees. 

![bug2](https://user-images.githubusercontent.com/6057854/77050521-2f886680-69ca-11ea-81a8-7a273077bcfa.PNG)
![bug1](https://user-images.githubusercontent.com/6057854/77050522-30b99380-69ca-11ea-816a-b2436e3dd323.PNG)
![bug3](https://user-images.githubusercontent.com/6057854/77050527-31522a00-69ca-11ea-86ed-9beb2d4d3458.PNG)

**Comment by liuloppan** [comment]
@alexanderbock  mentioned this issue may have been introduced by optimizations to the globebrowsing.

**Comment by liuloppan** [comment]
When inactivating 'Adaptive stereoscopic depth' this no longer seemed to be an issue. however this should not affect when NOT running in stereo.

**Comment by GPayne** [comment]
How much of a factor is the changing of anchors? If this isn't much of a problem unless there are frequent and "abrupt" changes, then it would be good to include some specific steps to reproduce the errors.

**Comment by alexanderbock** [comment]
Closing this in favor of #1455 as it is the same issue
