### ISSUE TITLE
Tully galaxy images don't show from both sides in fisheye rendering

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1128]
Probably the front/back face culling setting is wrong when using SGCT fisheye rendering mode?

**Comment by micahnyc** [comment]
When moved to one cube face, then working for both sides.

**Comment by micahnyc** [comment]
bump up from ken murphy

**Comment by Roxeena** [comment]
Related to #1411?

**Comment by alexanderbock** [comment]
aka.  is this still a problem?

**Comment by WeirdRubberDuck** [comment]
This should not have been fixed in #1411, since the Tully galaxies are created using a different renderable (`RenderableBillboardsCloud` rather than `RenderablePlanesCloud`). But guessing a similar fix would solve this :)

**Comment by alexanderbock** [comment]
What that guy said ^^

**Comment by WeirdRubberDuck** [comment]
Never mind!  It is an issue but not in fisheye rendering per se.  They only show one side when the Milky Way Sphere is being rendered, so within a certain distance (the size of our galaxy)
