### ISSUE TITLE
Scintillating stars if FXAA is disabled in Fisheye rendering

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1131]
If FXAA rendering is disabled and rendering happens in fisheye mode, there are problems with the star rendering if stars pass across the seam of cube faces.  It's very subtle

**Comment by WeirdRubberDuck** [comment]
This issue could benefit from some more details: How do we disable FXAA rendering? And maybe a screenshot of the "rendering problems"?

**Comment by GPayne** [comment]
If this is a very subtle effect, perhaps we could remove the "Bug" tag

**Comment by alexanderbock** [comment]
Can no longer replicate this -> closing

To disable FXAA: `openspace.setPropertyValueSingle("RenderEngine.FXAA", false)`
