### ISSUE TITLE
Atmosphere's don't work for non-spehrical planets

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1135]
Jupiter has a non sperical - Radii = { 71492000.0, 71492000.0, 66854000.0 }, and so it's making the atmosphere weird

**Comment by jccosta** [comment]
Micah, 
Because of the way atms are pre-calculated, the planets must be considered perfect spheres.
There is no way around that. Change the Jupiter Radii to:
Radii = { 71492000.0, 71492000.0, 71492000.0 }
