### ISSUE TITLE
problems compiling

### ISSUE THREAD

**Issue by itabhiyanta** [OpenSpace/OpenSpace#1138]
while compiling the open space using [this](http://wiki.openspaceproject.com/docs/developers/compiling/ubuntu) wiki
i see this error
`[ 81%] Building CXX object modules/volume/CMakeFiles/openspace-module-volume.dir/volumemodule.cpp.o
In file included from /home/rohit/Documents/experiments/OpenSpace/include/openspace/properties/numericalproperty.h:104,
                 from /home/rohit/Documents/experiments/OpenSpace/include/openspace/properties/scalar/floatproperty.h:43,
                 from /home/rohit/Documents/experiments/OpenSpace/include/openspace/rendering/renderable.h:31,
                 from /home/rohit/Documents/experiments/OpenSpace/modules/volume/rendering/renderabletimevaryingvolume.h:28,
                 from /home/rohit/Documents/experiments/OpenSpace/modules/volume/volumemodule.cpp:27:
/home/rohit/Documents/experiments/OpenSpace/include/openspace/properties/numericalproperty.inl:26:10: fatal error: glm/ext/matrix_common.hpp: No such file or directory
 #include <glm/ext/matrix_common.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
modules/volume/CMakeFiles/openspace-module-volume.dir/build.make:62: recipe for target 'modules/volume/CMakeFiles/openspace-module-volume.dir/volumemodule.cpp.o' failed
make[2]: *** [modules/volume/CMakeFiles/openspace-module-volume.dir/volumemodule.cpp.o] Error 1
CMakeFiles/Makefile2:2400: recipe for target 'modules/volume/CMakeFiles/openspace-module-volume.dir/all' failed
make[1]: *** [modules/volume/CMakeFiles/openspace-module-volume.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
`
I followed all the previous steps. Kindly suggest what I might be missing.

**Comment by GPayne** [comment]
I recommend checking to see if you cloned the OpenSpace repository with the `--recursive` option. Please verify that the following paths (relative to the base OpenSpace directory) are not empty:

- apps/OpenSpace/ext/sgct/
- ext/ghoul/

**Comment by jccosta** [comment]
Hi @itabhiyanta, would you give another try compiling OpenSpace but now pulling out the current master branch?
We made some changes to the compiling process, and they may solve your issue.
Thanks!

**Comment by GPayne** [comment]
The recent linux fixes have most likely solved this issue.
