### ISSUE TITLE
Orbit line render issue

### ISSUE THREAD

**Issue by liuloppan** [OpenSpace/OpenSpace#1143]
On planetary orbit lines there has appeared a rendering bug that sort of looks like a kink or gap on the line. When running OpenSpace simulation time they do not move and reappear at the same position again after being faded out.[](url)

<img width="128" alt="gap" src="https://user-images.githubusercontent.com/6057854/80566615-ad8d5380-89f3-11ea-8099-3851bf8a6570.PNG">

**Comment by WeirdRubberDuck** [comment]
@liuloppan is this still an issue? Having trouble reproducing the behavior

**Comment by liuloppan** [comment]
@WeirdRubberDuck This was traced to certain graphics cards if I remember correctly, similar to #1142 .I would assume it is still an issue if it hasn't been addressed, but my working machine does not have this problem so I can't confirm right now. But I remember observing this on the test machine we have on floor 5, when accidentally plugging the screen into the wrong port.

**Comment by Roxeena** [comment]
It is still an issue, I noticed it on one of the moon trails around Mars when I tried to reproduce #1142. It is rather difficult to reproduce as it only appears in a small sweet spot at large distances. Does not seem to be graphics card dependent as I have a NVIDIA card.

![renderbug](https://user-images.githubusercontent.com/16215103/110947296-442ede80-8340-11eb-8675-08948a40ac96.png)

**Comment by GPayne** [comment]
I _think_ I can see this kink with my Nvidia card, but it is barely noticeable. I wouldn't have noticed it if not for this issue. Changing number of line segments in the trail does not seem to affect it. Maybe it is more pronounced on some graphics cards.

**Comment by alexanderbock** [comment]
I saw the issue on my Nvidia card, too (see images in #1200)

**Comment by alexanderbock** [comment]
Closed in favor of #1200
