### ISSUE TITLE
Segmentation fault on Ubuntu 18.04

### ISSUE THREAD

**Issue by gitkime** [OpenSpace/OpenSpace#1149]
Segmentation fault if I run OpenSpace
Here is the CMakeFileerror.log output. I got 2 errors
1.
/home/kalilab/OpenSpace/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
 In function ‘main’:
/home/kalilab/OpenSpace/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19:
 error: ‘strtod_l’ undeclared (first use in this function); did you mean ‘strtoull’?
   return ((int*)(&strtod_l))[argc];
                   ^~~~~~~~
                   strtoull
2.
 File /home/kalilab/OpenSpace/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */#include <pthread.h>
int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}
Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/kalilab/OpenSpace/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_b624e/fast"
/usr/bin/make -f CMakeFiles/cmTC_b624e.dir/build.make CMakeFiles/cmTC_b624e.dir/build
make[1]: Verzeichnis „/home/kalilab/OpenSpace/build/CMakeFiles/CMakeTmp“ wird betreten
Building C object CMakeFiles/cmTC_b624e.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_b624e.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_b624e
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b624e.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_b624e.dir/CheckFunctionExists.c.o  -o cmTC_b624e -lpthreads
/usr/bin/ld: -lpthreads kann nicht gefunden werden

I don't Know whats wrong.
If I run OpenSpaceTest I got one error

Asset (Debug)	Initializing asset $root
AssetLoader (Error)	Could not load asset '/home/kalilab/OpenSpace/tests/AssetLoaderTest/failassertion.asset': Error executing script '': ...ilab/OpenSpace/tests/AssetLoaderTest/failassertion.asset:1: assertion failed!
Scene (Info)	Clearing current scene graph
Scene (Info)	Clearing current scene graph
Scene (Info)	Clearing current scene graph
Asset (Debug)	Initializing asset /home/kalilab/OpenSpace/tests/AssetLoaderTest/initialization.asset
Scene (Info)	Clearing current scene graph
OpenSpaceTest is a Catch v2.11.0 host application.
Run with -? for options
-------------------------------------------------------------------------------
LuaConversion Float Fuzz - long double
-------------------------------------------------------------------------------
/home/kalilab/OpenSpace/tests/test_luaconversions.cpp:280
...............................................................................

/home/kalilab/OpenSpace/tests/test_luaconversions.cpp:307: FAILED:
  REQUIRE( value == val )
with expansion:
  inf == 6.6688e+4931

SpiceManager (Info)	Loading SPICE kernel '/home/kalilab/OpenSpace/tests/SpiceTest/spicekernels/naif0008.tls'

Hopefully somebody could help.
Thank you.

<< What did happen? >>

<< Attach screenshots, if possible >>

**Comment by GPayne** [comment]
Hi @gitkime, thanks for trying OpenSpace on linux.
You can ignore that particular AssetLoader test failure right now. Your segfaults are probably the same as mentioned in issue #1111. Please see my latest comments there for how to fix this.
Unfortunately we are still dealing with a rendering issue in the linux version, which we hope to fix soon.

**Comment by GPayne** [comment]
Fixed in new 'linux' branch, commit e6b44b5
