### ISSUE TITLE
Cmake errors when building Openspace under Ubuntu!

### ISSUE THREAD

**Issue by jichengtao** [OpenSpace/OpenSpace#1154]
The CMake errors occur when I run command "cmake .." in the build folder. The error information as following:

### CMake Error at apps/OpenSpace/ext/sgct/src/sgct/CMakeLists.txt:161 (find_package):
  By not providing "FindGLM.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "GLM", but
  CMake did not find one.

  Could not find a package configuration file provided by "GLM" with any of
  the following names:

    GLMConfig.cmake
    glm-config.cmake

  Add the installation prefix of "GLM" to CMAKE_PREFIX_PATH or set "GLM_DIR"
  to a directory containing one of the above files.  If "GLM" provides a
  separate development package or SDK, be sure it has been installed.

NOTE that, I cloned the OpenSpace with the --recursive flag as described on the website.

**Comment by GPayne** [comment]
Fixed in new 'linux' branch, commit e6b44b5
