### ISSUE TITLE
Add a model for a meter stick on planets

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1155]
Need to create a model in, for example, OBJ file format for a meter stick and create an asset for it

**Comment by micahnyc** [comment]
a nonuniformstaticscale could be applied to it so that the size could be changed. This could be done as part of https://github.com/OpenSpace/OpenSpace/issues/2273

**Comment by alexanderbock** [comment]
Yea, closing it in favor of #474 and #2273
