### ISSUE TITLE
Websocket camera state not getting rollY values

### ISSUE THREAD

**Issue by hedbergj** [OpenSpace/OpenSpace#1157]
<< Description of the problem >>
Websocket flightcontroller doesn't transmit the values set for globalRollY and localRollY.

Seems the `flightcontrollertopic.cpp` takes a float from the JSON:

```
 ln 433:    _inputState.axes[std::distance(AxisIndexMap.begin(), mapIt)] = float(it.value());
```

but the `websocketcamerastate.cpp` wants a vect2. 

```
ln 46:     std::pair<bool, glm::dvec2> globalRoll = { false, glm::dvec2(0.0) };
```
The `...roll.second.y` component doesn't get assigned. 

Quickfix, just to show the problem, but certainly *not* the right way to fix it, change `y` to `x` in the following, and then it works.

```
case AxisType::GlobalRollY:
                    globalRoll.first = hasValue || globalRoll.first;
                    globalRoll.second.y = value;
                    break;
```
to:
```
globalRoll.second.y = value;
```
and the same for LocalRollY

Since the websocket input state keys are separate for x and y, it may not need a vector at all. All the other input states (rotate, zoom) seem to work fine.

**Comment by micahnyc** [comment]
This should be updated to just "roll" with a double instead of vec2

**Comment by alexanderbock** [comment]
Removed in ec15624ab056254f1e2883562827667e8ecb2451
