### ISSUE TITLE
Deep Sky Objects Images have incorrect orientation

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1159]
deepsky.asset

From Ken Murphy: "Today I was working with "Deep Space Objects" images in OpenSpace and noticed that they are placed about 180 degrees off from where they should be, for example M1 was near Sagittarius while M7 was near Orion."

From Carter: off around the z axis.

**Comment by micahnyc** [comment]
Can be fixed with:     Transform = {
        Rotation = {
            Type = "StaticRotation",
            Rotation = { 0, 0, 3.14159265359 }
        }
    },

but we should figure out why the speck file is wrong

**Comment by jccosta** [comment]
Looking into the data Brian has provided me, I realize there is a rotation applied to the data. It's not the same rotation you have, though.
The rotation included in the data configuration is:
Rotation = {
Type = "StaticRotation",
Rotation = {3.14159265359, 3.14159265359, 0 }
}
}.
The speck file is not wrong; the data is provided with different coordinates.
@micahnyc can you check the new transformation with Carter?

**Comment by jccosta** [comment]
@micahnyc  did u test the new rotation?
I would like to close this issue for the new release.

**Comment by micahnyc** [comment]
tested and commited. https://github.com/OpenSpace/OpenSpace/pull/1193

**Comment by alexanderbock** [comment]
Closed in 358246dceb925693659c3e67dab972c28aa1fd54
