### ISSUE TITLE
Eclipse shadow doesn't scale with bodies

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1160]
When scaling earth and the moon to to visualize the eclipse, the shadow cast by the moon on the earth stays at a constant size. It should scale with the bodies.

**Comment by jccosta** [comment]
Closed in commit b60c6cd116d7cc3a7ad1e59dcc30a967e82037e2

![Eclipse-Scaled](https://user-images.githubusercontent.com/874760/86272566-c43f5a80-bb9c-11ea-98ed-22da6c52125f.png)
