### ISSUE TITLE
Blank screen rendering on ubuntu linux

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#1163]
I have now compiled https://github.com/OpenSpace/OpenSpace/commit/f6dcbd99d8c614f082f43b0aa889f5497c24cd90 and it works great also on my Ubuntu 18.04. I then tried the rest of the commits in that branch: https://github.com/OpenSpace/OpenSpace/commits/issue/233b . All commits from https://github.com/OpenSpace/OpenSpace/commit/f6dcbd99d8c614f082f43b0aa889f5497c24cd90 until https://github.com/OpenSpace/OpenSpace/commit/94e150f0720ea2699911b94b535adc2cbada3780 does not build. https://github.com/OpenSpace/OpenSpace/commit/94e150f0720ea2699911b94b535adc2cbada3780 builds but gives the issue with "black screen" on my system. I also tried some newer commit (https://github.com/OpenSpace/OpenSpace/commit/f434ef4261a2f4b06f38642207f7944071c58c46)  but it also has this issue. I included a screenshot of the issue.
![openspace_94e150f0720ea2699911b94b535adc2cbada3780](https://user-images.githubusercontent.com/1207291/71725481-5952d800-2e34-11ea-9e96-7144b4bc6928.png)

_Originally posted by @sa5bke in https://github.com/OpenSpace/OpenSpace/issues/233#issuecomment-570570601_

**Comment by GPayne** [comment]
The above comment was originally posted by @sa5bke in issue #233, which is now resolved.

**Comment by jccosta** [comment]
@alexanderbock and @GPayne, I propose we close this issue and open a new issue specifying that the behavior only happens when compiling OS on debug mode on Linux.

**Comment by GPayne** [comment]
Agreed
