### ISSUE TITLE
Create static layer from temporal date.

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1171]
It would be great to take a static layer from the current value of a temporal layer.

For example, I want the VIIRS layer from march 12, 2012 to be a layer on earth that won't change over time. 

This would be helpful in use cases where you want to show earth, and have time advancing.

**Comment by micahnyc** [comment]
(perhaps just an option on the temporal layer to "lock to this date" and it won't updated until set to false.

**Comment by alexanderbock** [comment]
Added two new properties to the temporal tile provider;  a boolean to toggle using of a fixed time and a string to set the fixed time.  That string will not go through the time quanitizer so it has to be a date that the tileprovider understands.

![image](https://user-images.githubusercontent.com/4921724/117547817-f679de00-b031-11eb-9313-5d5191050af5.png)
