### ISSUE TITLE
Add the JWST spacecraft

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1182]
Including trying to get some SPICE information about the proposed orbital location

**Comment by liuloppan** [comment]
I can't seem to find any SPICE data for JWST.
Also on this list of SPICE users it is listed that it does not "Requesting NAIF Help". Same for Parker Solar Probe.
https://naif.jpl.nasa.gov/naif/SPICE_Users.pdf

If anyone has a good idea of other places to look, let me know.
https://naif.jpl.nasa.gov/naif/data_archived.html

**Comment by alexanderbock** [comment]
One option is https://ssd.jpl.nasa.gov/horizons.cgi#top   

They have some information about the JWST, but I'm not sure where the data comes from or its time range
