### ISSUE TITLE
Inconsistent use of 'Transparency' and 'Opacity'

### ISSUE THREAD

**Issue by liuloppan** [OpenSpace/OpenSpace#1196]
Some renderables have an "Opacity" property while some have a "Transparency" property. They have the same functionality but this makes it more difficult to generalize scripting.

For Example this works:

```
openspace.setPropertyValueSingle("Scene.RadioSphere.Renderable.Opacity", 0.5)

openspace.setPropertyValueSingle("Scene.Constellations.Renderable.Transparency", 0.5)
```
but not the other way around.

The case for the grids such as the RadioSphere have a "Transparency" property in the GUI that controls "Scene.RadioSphere.Renderable.Opacity".

This should be generalized so that both can be used interchangeably, or limited to one.

**Comment by liuloppan** [comment]
Do we have a preference to use "Transparency" over "Opacity"  or should both be used? Spontaneously I would think Transparency would be 1-Opacity, but that does not seem to be the current functionality, nor is there really a need to have both. I would personally be fine to ditch "Transparency" and replace with "Opacity", any opinions?

**Comment by hedbergj** [comment]
+1 for Opacity. (You can render a jpg with 50% opacity even though its file format doesn't support transparency.)

**Comment by jccosta** [comment]
The [renderablesphericalgrids](https://github.com/OpenSpace/OpenSpace/blob/master/modules/base/rendering/renderablesphericalgrid.cpp)  shouldn't have transparency, only opacity. 
I removed the alpha channel from the colors and set the value of the opacity.
The opacity variable (from the renderable class) is used to control the rendering order by the use of the renderBin.
In summary, you must use opacity unless you want different behavior (which may be the case for the constellations (I didn't look into the code)).

**Comment by alexanderbock** [comment]
The vote went out in favor of `Opacity`

**Comment by liuloppan** [comment]
Fixed https://github.com/OpenSpace/OpenSpace/commit/41d5a6db5f618b3896eb61ae50d57955b5f948ce
