### ISSUE TITLE
Resetting TileProviders while downloading tiles causes a GDAL error

### ISSUE THREAD

**Issue by nusic** [OpenSpace/OpenSpace#120]
### Reproduce

Quickly zooming in on a ChunkedLodGlobe and press resetTileProviders in GUI
### Initial though

The reset functionality used by TileProvider and TileDataset should ensure that all active worker threads finish their execution before GDAL datasets are closed and deleted.

**Comment by kbladin** [comment]
Can be solved by simply not resetting the AsyncTileProvider when resetting the CachingTileProvider. This means that GDAL will have to finish its current requests but that makes sense anyway since failed requests will finish anyway (by timeout if nothing else).

**Comment by alexanderbock** [comment]
Sounds good to me
