### ISSUE TITLE
Rendering issue with labels on the moon

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1205]
Report from Alex @ NCMNS

•	On the Moon, when Labels are enabled (no labels show up) then turning off “Labels fade in” causes the Moon to disappear.

**Comment by micahnyc** [comment]
labels working for me on the moon @ e5719952b1afd54ce2d825a4a01e72e40e4c8c5b

**Comment by jccosta** [comment]
I will close this one. I tested it, and none of the behavior described happens.
The way the fade-in feature is configured, one must get close to the Moon's surface to see the labels.
The Moon never disappears.
