### ISSUE TITLE
Planet texture alignment (Callisto, Ceres, Jupiter, Titan, Europa)

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1207]
Report from Alex @ NCMNS

•	Callisto textures are misaligned along equator and prime/180th meridian.

**Comment by micahnyc** [comment]
Also on Ceres, Jupiter, Titan,

**Comment by micahnyc** [comment]
Now also reported on Europa. 

I thought it was JPG textures only but it has been reported for the europa wms as well. 

![europa_map](https://user-images.githubusercontent.com/708535/106942568-5474ed80-66f2-11eb-9e54-ecd1c3dc2a5d.gif)

**Comment by alexanderbock** [comment]
The issue is that they are using a different map format than what we use;  the globe browsing uses longitude [-180, 180], see (http://liu-se.cdn.openspaceproject.com/files/solarsystem/planets/earth/earth/textures/v1_v1/earth_bluemarble.jpg  where the 0 longitude is right in the center of the planet.
Voyager on the other hand (see https://astrogeology.usgs.gov/search/details/Europa/Voyager-Galileo/Europa_Voyager_GalileoSSI_global_mosaic_500m/cub  all the way at the bottom), uses "Longitude Domain
    0 to 360", so it is shifted by 180 degrees compared to our rendering.
