### ISSUE TITLE
Asset values for labeling for different bodies are wrong

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1209]
Report from Alex @ NCMNS
•	Labeling of surface features on Venus, Mars, Enceladus, Titan, Pluto, and Charon does not appear unless the “Fade In Starting Distance for Labels” value is increased to be higher than the “Fade Out Starting Distance for Labels” value. These settings have proper values for Mercury and Jupiter’s Galilean moons.

@jccosta  Probably knows and can instruct

**Comment by GPayne** [comment]
Created PR#1215 for this.

**Comment by Roxeena** [comment]
Was this fixed in #1476? If so I suggest we close this issue.

**Comment by GPayne** [comment]
Yes, this was fixed in PR #1476
