### ISSUE TITLE
Transparent trails don't work well when blended with atmosphere

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1217]
Steps to reproduce:
1. Apollo scene
2. Go to 1968 DEC 21 20:00:00
3. Make Apollo 8 Launch trail slightly transparent

![OpenSpace_000000](https://user-images.githubusercontent.com/4921724/85919775-c177f900-b86e-11ea-8309-0caf64879f09.png)

**Comment by alexanderbock** [comment]
It just happened with the ISS trail and even persisted when going back to full opacity.  Something about the binning that is not correctly undone?

**Comment by alexanderbock** [comment]
![OpenSpace_000000](https://user-images.githubusercontent.com/4921724/85944510-855c9b00-b937-11ea-8b4a-dbfb4e0537eb.png)

**Comment by jccosta** [comment]
I developed a proposing solution for this issue (commit e64f557bb4f8732da63e331a9b6c7407ceb9fe8c ).
@alexanderbock, let's talk a bit about it before I create the PR.

**Comment by jccosta** [comment]
![OpenSpace_000000](https://user-images.githubusercontent.com/874760/86050549-04c69900-ba22-11ea-90a1-61057c1702de.png)
Example of the final proposed solution.

**Comment by jccosta** [comment]
Solution added in commit 607a13da310446645d5372abebc8dbce1e4fea11.
