### ISSUE TITLE
Binding a key to "Left" doesn't seem to work

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1218]
openspace.bindKey("Left", "openspace.setPropertyValueSingle('Scene.Apollo12Insigna.Renderable.Opacity',1.0,5.000000E-01)");

**Comment by alexanderbock** [comment]
Shift+KP_1 also doesn't seem to work

**Comment by alexanderbock** [comment]
Shift + Keyboard -> Shift + Keypad

**Comment by micahnyc** [comment]
LEFT

**Comment by WeirdRubberDuck** [comment]
I had no problem binding a key to "Left". Tried using both: `openspace.bindKey("Left", "openspace.time.interpolatePreviousDeltaTimeStep()")` as additional script in profile and adding

```
    {
        Key = "Left",
        Name = "Previous Delta Time Step (Interpolate)",
        Command = "openspace.time.interpolatePreviousDeltaTimeStep()",
        Documentation = "Smoothly interpolates the simulation speed to the previous delta time step, if one exists.",
        GuiPath = "/Simulation Speed",
        Local = true
    },
```
to default_keybindings.asset

**Comment by alexanderbock** [comment]
Must have been my mistake....
