### ISSUE TITLE
Radiosphere Transparency issue

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1221]
If the radiosphere is enabled, but transparency is set to 0, the radiosphere is still writing to the depth buffer

![OpenSpace_000000](https://user-images.githubusercontent.com/4921724/85923465-8932e380-b88b-11ea-80a4-7a0a540a0837.png)

**Comment by jccosta** [comment]
Fixed in commit 9af771b889c5da7fd0de1ee01b8d00390d99d8ef .

**Comment by alexanderbock** [comment]
For future: if you put (closes #9999) into the commit message, GitHub will automatically close issue 9999.

**Comment by jccosta** [comment]
Thanks, @alexanderbock. I didn't know it.
