### ISSUE TITLE
Fisheye rendering mode performance degradation on new SGCT

### ISSUE THREAD

**Issue by jccosta** [OpenSpace/OpenSpace#1226]
The final rendering performance seems to have degraded when in fisheye rendering mode and with the new SGCT.

**Comment by GPayne** [comment]
This needs some quantification, such as the effect on framerate.

**Comment by alexanderbock** [comment]
Closing as performance degradation cannot be reproduced:
Rendering without 3D:   3.35ms
Rendering single.xml @ 1024x1024:  5.2ms total;   5.2-3.35=1.85ms pure rendering
fisheye 180 degrees with 1024 res:   8.6ms total:  8.6-3.35=5.25ms pure rendering / 4 cubes = 1.3125ms per cube
fisheye 360 degrees with 1024 res:  10.5ms total;  10.5-3.35=7.15ms pure rendering / 6 cubes = 1.19ms per cube

So the rendering of OpenSpace to 1024x1024 (on my machine takes) about 1.19-1.85ms.
