### ISSUE TITLE
GlobeBrowsing: Set level-of-detail scale factor based on screen resolution

### ISSUE THREAD

**Issue by nusic** [OpenSpace/OpenSpace#123]
### Background

The class `RenderableGlobe` has a float property called `lodScaleFactor`. The value of `lodScaleFactor` is used by `ChunkLevelEvaluator` which determines the overall texture and heighmap resolution of the `RenderableGlobe`. When the OpenSpace window size is changed, one would usually like to change the value of `lodScaleFactor` accordingly. 
### Question

What is the best way of calculating an optimal value of `lodScaleFactor`, taking into account the current OpenSpace window size?

**Comment by nusic** [comment]
Ideally, you would like to find the mathematical relationship between screenspace pixel resolution and the value of `lodScaleFactor`. Having that, one could set a lower bound on a `RenderableGlobe` screenspace pixel resolution. However, this relationship will probably be quite complicated and a simple approximation may be sufficient(?)

**Comment by alexanderbock** [comment]
My gut feeling would be that there should be a correlation between the field-of-view and the window resolution, giving a angular extent for each pixel. Some along:
We have for example 60 deg horizontal field-of-view for 1920 pixels, meaning that each pixel has an extent of  60/1920=0.03125 degrees

Problems:
1. How to deal with FishEye rendering, where that concept might break down
2. Would it cause a problem in a multi-projector environment where two projectors with different fields-of-view touch
3. The degree/pixel `a` has to be converted using the distance to the object... Maybe `lodScaleFactor` = factor * sin(a) * distance(camera, object)

**Comment by kbladin** [comment]
I would say that this issue is no longer relevant. The screen resolution is not well defined when using multi display systems and screens with different resolutions would cause different LOD across borders which is not desirable. The error metrics, projected area and camera distance that we have right now work well I would say,
