### ISSUE TITLE
Cmake error when trying to include ISWA and/or Kameleon modules

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1233]
![cmake error](https://user-images.githubusercontent.com/8808894/86358483-d211e000-bc6f-11ea-90df-8fcfeceda47a.PNG)

**Comment by WeirdRubberDuck** [comment]
The same goes for the FieldLines and FieldLinesSequence modules

**Comment by alexanderbock** [comment]
Added instructions to compile Boost to the wiki page:

### Compiling Boost
Some of the optional modules have Boost as a dependency, which will need to be compiled separately. See [boost.org](boost.org) for a complete compilation instructions.
1. Download the newest version of the source from [here](https://dl.bintray.com/boostorg/release/).  For example: https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.7z
1. Unpack the boost folder to its final destination
1. Start the Visual Studio x64 native tools command prompt and navigate to the folder
1. In the boost folder, run `bootstrap.bat` and wait
1. Run the `b2` command
1. Add the boost folder as the `BOOST_ROOT` environment variable
