### ISSUE TITLE
SessionRecording feature could use a comment line type in ascii format

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1234]
It would be nice to be able to add commented lines into the file format, for example with a leading # 

I have been writing scripts to concatenate multiple recordings and it would have been neat to be able to add additional information for my scripts directly into the recording

**Comment by alexanderbock** [comment]
Isn't this done @GPayne ?

**Comment by GPayne** [comment]
@alexanderbock Yes, it is in _feature/session-recording-improvements_, but I was going to close this when it gets merged-in.

**Comment by alexanderbock** [comment]
Clsoed in  36bff67
