### ISSUE TITLE
Add the ability for remote webgui's to send commands to the orbital navigator

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1249]
Adding the ability to add a canvas element to the webui that, if not running in OpenSpace directly, it is possible to control the mouse through the webpage

**Comment by liuloppan** [comment]
Do you have a special use case you are thinking of? Isn't this already a possibility if you open the webgui in a broswer?

**Comment by alexanderbock** [comment]
Basically what Micah showed us today

**Comment by micahnyc** [comment]
closed with: https://github.com/OpenSpace/OpenSpace/commit/102454089aa45aadb2f25ab1c759f58ba2939966
