### ISSUE TITLE
Fix the loading of GIBS globebrowsing layers at startup

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1250]
When starting OpenSpace, the GIBS GetCapabilitiesFile is not loaded correctly and throws this warning:

Could not open dataset: https://gibs.earthdata.nasa.gov/twms/epsg4326/best/twms.cgi?request=GetTileService

This prevents the GlobeBrowsing UI from working

**Comment by GPayne** [comment]
I'm not seeing this error right now with the default profile, at least on linux.

**Comment by alexanderbock** [comment]
It's a very intermittent error that I have been unable to track down.  I have the suspicion that it might be related to how fast the datasets returns results and if they might be split into separate packets and not correctly reassembled maybe
