### ISSUE TITLE
Failed to load dataset on initial run

### ISSUE THREAD

**Issue by johnriedel** [OpenSpace/OpenSpace#1260]
When running "bin/OpenSpace" for the first time on Ubuntu 20.04 LTS, some assets fail to load during the initial syncing process due to a capitalization mismatch between the actual filename and the filename referenced in the asset file.

Example output:
...
...
SceneGraphNode (Debug)	Successfully created ephemeris for 'MercuryBarycenter'
SceneGraphNode (Debug)	Successfully created SceneGraphNode 'MercuryBarycenter'
Asset (Debug)	Initializing asset /Code/OpenSpace/data/assets/scene/solarsystem/planets/mercury/mercury_globelabels.asset
SceneGraphNode (Debug)	Initializing: MercuryBarycenter
SceneGraphNode (Debug)	Finished initializing: MercuryBarycenter
Asset (Debug)	Initializing asset /Code/OpenSpace/data/assets/scene/solarsystem/planets/mercury/trail.asset
SceneGraphNode (Debug)	Successfully created renderable for 'MercuryTrail'
SceneGraphNode (Debug)	Successfully created SceneGraphNode 'MercuryTrail'
SceneGraphNode (Debug)	Initializing: MercuryTrail
SceneGraphNode (Debug)	Finished initializing: MercuryTrail
SceneGraphNode (Debug)	Successfully created rotation for 'Mercury'
Layer (Debug)	Initializing tile provider for layer: 'Messenger MDIS [Utah]'
**(Error)	Failed to load dataset: /Code/OpenSpace/data/assets/scene/solarsystem/planets/mercury/map_service_configs/Utah/MessengerMDIS.wms**
...
...
Layer (Debug)	Initializing tile provider for layer: 'Messenger LOI [Sweden]'
Layer (Debug)	Initializing tile provider for layer: 'Messenger SHADE [Utah]'
Layer (Debug)	Initializing tile provider for layer: 'Messenger SHADE [Sweden]'
**(Error)	Failed to load dataset: /Code/OpenSpace/data/assets/scene/solarsystem/planets/mercury/map_service_configs/LiU/Messenger_SHADE.wms**
...
...

Steps to reproduce:
(ref: http://wiki.openspaceproject.com/docs/developers/compiling/ubuntu)
`1) run: openSpaceHome=$HOME/<path_to_source_here>/OpenSpace
2) run: git clone --recursive https://github.com/<github_account_here>/OpenSpace "$openSpaceHome"
3) run: mkdir -p "$openSpaceHome/build"
4) run: cd "$openSpaceHome/build" || exit
5) run: cmake \
-DCMAKE_BUILD_TYPE:STRING="Release" \
-DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-9 \
-DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-9 \
-DCMAKE_CXX_FLAGS:STRING="-DGLM_ENABLE_EXPERIMENTAL" \
-DOpenGL_GL_PREFERENCE:STRING=GLVND "$openSpaceHome"
6) run: make
7) run: "$openSpaceHome"/bin/OpenSpace

`

**Comment by alexanderbock** [comment]
Thanks for the reporting!  I just pushed a fix for this to `master`
