### ISSUE TITLE
"unsorted double linked list corrupted" during initial run

### ISSUE THREAD

**Issue by johnriedel** [OpenSpace/OpenSpace#1262]
When running "bin/OpenSpace" for the first time on Ubuntu 20.04 LTS, the process is aborted during initial syncing with the following output:

...
...
Layer (Debug)	Initializing tile provider for layer: 'Messenger Mosaic2 [Sweden]'
**malloc(): unsorted double linked list corrupted
Aborted**

Steps to reproduce:
(ref: http://wiki.openspaceproject.com/docs/developers/compiling/ubuntu)
`1) run: openSpaceHome=$HOME/<path_to_source_here>/OpenSpace
2) run: git clone --recursive https://github.com/<github_account_here>/OpenSpace "$openSpaceHome"
3) run: mkdir -p "$openSpaceHome/build"
4) run: cd "$openSpaceHome/build" || exit
5) run: cmake
-DCMAKE_BUILD_TYPE:STRING="Release"
-DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-9
-DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-9
-DCMAKE_CXX_FLAGS:STRING="-DGLM_ENABLE_EXPERIMENTAL"
-DOpenGL_GL_PREFERENCE:STRING=GLVND "$openSpaceHome"
6) run: make
7) run: "$openSpaceHome"/bin/OpenSpace

`

**Comment by alexanderbock** [comment]
@GPayne  You got an idea?

**Comment by GPayne** [comment]
I just did a build from scratch. Ran with a fresh sync directory. My version ran fine without the error you described. I am also running Ubuntu 20.04, followed the procedure you outlined.

I am compiling with gcc 9.3.0, CMake 3.16.3. What versions do you have installed, @johnriedel ?

**Comment by johnriedel** [comment]
Hi @GPayne . I have gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2) and cmake version 3.16.3. I've done some digging and the error seems to center on or around modules/globebrowsing/src/layergroup.cpp:129. Here's some of the gdb output that I'm sifting through.

....
print (Debug)	Requesting: scene/digitaluniverse/grids
....
(Debug)	Initializing tile provider for layer: 'Messenger Mosaic2 [Sweden]'
....
Thread 1 "OpenSpace" hit Breakpoint 3, openspace::globebrowsing::LayerGroup::addLayer (this=0x55555875c2f0, layerDict=...)
    at /Code/OpenSpace/modules/globebrowsing/src/layergroup.cpp:117
117	    documentation::TestResult res = documentation::testSpecification(
(gdb) n
229	struct Documentation {
(gdb) n
121	    if (!res.success) {
(gdb) n
125	    if (!layerDict.hasKeyAndValue<std::string>("Identifier")) {
(gdb) n
129	    std::unique_ptr<Layer> layer = std::make_unique<Layer>(_groupId, layerDict, *this);
(gdb) print _groupId
$30 = openspace::globebrowsing::layergroupid::ColorLayers
(gdb) print layerDict
$31 = (const ghoul::Dictionary &) @0x7fffffffb330: {<std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::any, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::any> > >> = std::map with 4 elements = {["BlendMode"] = std::any containing std::string = {
      [contained value] = "Multiply"}, 
    ["Enabled"] = std::any containing bool = {[contained value] = false}, 
    ["FilePath"] = std::any containing std::string = {
      [contained value] = "/Code/OpenSpace/sync/http/mercury_abundance_textures/1/fesimap_02122015.png"}, 
    ["Identifier"] = std::any containing std::string = {
      [contained value] = "fesimap_02122015"}}, <No data fields>}
(gdb) n

Thread 1 "OpenSpace" hit Breakpoint 1, openspace::globebrowsing::TileTextureInitData::TileTextureInitData (original=..., this=<optimized out>)
    at /Code/OpenSpace/modules/globebrowsing/src/rawtiledatareader.cpp:430
430	    initialize();
(gdb) n
malloc(): unsorted double linked list corrupted

Thread 1 "OpenSpace" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

**Comment by GPayne** [comment]
Since you are using gdb to step through the code, I assume you did a _Debug_ or _RelWithDebInfo_ build. Currently, only a _Release_ build will work with gcc. We were seeing strange behavior in glm otherwise.

**Comment by johnriedel** [comment]
Hey @GPayne . Nope, did a release build (-DCMAKE_BUILD_TYPE:STRING="Release").

**Comment by johnriedel** [comment]
The issue appears to be associated specifically with the GDALOpen function within modules/globebrowsing/src/rawtiledatareader.cpp. GDALOpen is sometimes happy with _Code/OpenSpace/sync/http/mercury_abundance_textures/1/alsimap_02122015.png_ and never happy with _Code/OpenSpace/sync/http/mercury_abundance_textures/1/fesimap_02122015.png_.

@GPayne , what version of libgdal-dev do you have installed?

**Comment by GPayne** [comment]
@johnriedel : I have version **3.0.4+dfsg-1build3** of libgdal-dev installed.

**Comment by johnriedel** [comment]
@GPayne That's the version I have too. Hmmm. 

Pulling that GDALOpen() code out of OpenSpace and into a separate test.cpp file and running it against the /OpenSpace/sync/http/mercury_abundance_textures/1/*.png files works fine without error. So the funky behavior happens primarily when inside the OpenSpace code implying that the issue is not with gdal.

My work-around for now is to comment-out the references to the five .PNG local textures (mineral abundance maps) within the OpenSpace/data/assets/scene/solarsystem/planets/mercury/mercury.asset file.

**Comment by johnriedel** [comment]
After commenting-out those five local texture references above, the malloc error is rearing its ugly head elsewhere. Here's the command line output........

...
...
Layer (Debug)	Initializing tile provider for layer: 'Themis IR Night [Sweden]'
Layer (Debug)	Initializing tile provider for layer: 'CTX Mosaic [Utah]'
**(Error)	Failed to load dataset: /Code/OpenSpace/data/assets/scene/solarsystem/planets/mars/map_service_configs/Utah/CTX.wms**
Layer (Debug)	Initializing tile provider for layer: 'CTX Mosaic [Sweden]'
**(Error)	Failed to load dataset: /Code/OpenSpace/data/assets/scene/solarsystem/planets/mars/map_service_configs/LiU/CTX.wms**
Layer (Debug)	Initializing tile provider for layer: 'CTX Blended beta01'
...
...
Asset (Debug)	Initializing asset /Code/OpenSpace/data/assets/customization/gui.asset
WebGuiModule (Debug)	Web GUI server output: No directories to serve. Use --help for more info.

**property_getValue (Error)	/Code/OpenSpace/data/assets/util/webgui.asset:42: : Property with URI 'Modules.CefWebGui.Visible' was not found**
Asset (Debug)	Initializing asset /Code/OpenSpace/data/assets/scene/milkyway/milkyway/volume.asset
...
...
SceneGraphNode (Debug)	Successfully created renderable for '100MlyGrid'
SceneGraphNode (Debug)	Successfully created SceneGraphNode '100MlyGrid'
SceneGraphNode (Debug)	Successfully created renderable for '20GlyGrid'
SceneGraphNode (Debug)	Successfully created SceneGraphNode '20GlyGrid'
Asset (Debug)	Initializing asset /Code/OpenSpace/data/assets/customization/globebrowsing.asset
**print (Error)	No directory specified**
print (Info)	Adding color layer 'OnMarsHiRISELS'
Layer (Debug)	Initializing tile provider for layer: 'HiRISE Local Set'
WebGuiModule (Debug)	Web GUI server output: Serving OpenSpace web content
...
...
print (Info)	Adding height layer 'OnMarsHiRISELS'
Layer (Debug)	Initializing tile provider for layer: 'HiRISE Local Set'
DefaultTileProvider (HiRISE Local Set) (Debug)	Default pixel size overridden: 90
**print (Error)	No directory specified
print (Error)	No directory specified
print (Error)	No directory specified
property_setValue (Error)	/Code/OpenSpace/data/assets/util/webgui.asset:77: : Property with URI 'Modules.CefWebGui.GuiUrl' was not found**
Asset (Debug)	Initializing asset /Code/OpenSpace/data/assets/scene/solarsystem/planets/earth/satellites/satellites.asset
...
...
OpenSpaceEngine (Info)	Running Global initialization scripts
Lua (Debug)	Creating Lua state
Lua (Debug)	Open libraries
ScriptEngine (Debug)	Create openspace base library
ScriptEngine (Debug)	Add OpenSpace modules
OpenSpaceEngine (Debug)	Ignoring non-existing script file: /Code/OpenSpace/scripts/customization.lua
[2020-07-27 15:32:53] [connect] WebSocket Connection iostream transport v13 "" / 101
WebSocket (Debug)	onOpen: WebSocket opened. Client: 127.0.0.1:43193.
WebGuiModule (Debug)	Web GUI server output: Connected to local OpenSpace server

Logging (Warning)	Number of Warnings: 7
Logging (Warning)       Number of Errors: 8
**malloc(): unsorted double linked list corrupted
Aborted**

**Comment by johnriedel** [comment]
I've also seen initial run end with the following......

...
...
[2020-07-27 08:24:58] [connect] WebSocket Connection iostream transport v13 "" / 101
WebSocket (Debug)	onOpen: WebSocket opened. Client: 127.0.0.1:49326.
WebGuiModule (Debug)	Web GUI server output: Connected to local OpenSpace server
Logging (Warning)	Number of Warnings: 7
Logging (Warning)       Number of Errors: 8
**Segmentation fault**

**Comment by johnriedel** [comment]
I'm no longer experiencing this issue. It may have been resolved either through recent OpenSpace code updates or general local system updates. Closing issue.
