### ISSUE TITLE
Adding a shape model for the Itokawa asteroid

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1264]
Following up on an email received a long time ago, it might be time to get the shape model into OpenSpace

The obj file is online:
http://liu-se.cdn.openspaceproject.com/files/solarsystem/missions/itokawa/model/v1_v1/Itokawa_512.obj

**Comment by carteremmart** [comment]
Was the email from my high school students?  Derek Zhang put that in with the kernels for Hyabusa.  There is a shared Google drive with Derek's work that includes the spice setup for all listed missions.

**Comment by alexanderbock** [comment]
It was an email from John Christian from RPI;  Email was from Nov 2018

**Comment by WeirdRubberDuck** [comment]
With the new model loading, ti should be possible to just use the 3D model from NASA:
https://solarsystem.nasa.gov/resources/2377/asteroid-itokawa-3d-model/
