### ISSUE TITLE
Cannot remove assets that have been added at startup

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1267]
Have  a look at the asset removal code in AssetManager. Seemingly, assets that are added from asset files at startup are not added to the list that is checked during asset removal

**Comment by micahnyc** [comment]
yeah this results in the case right now that you can only remove assets that were added at runtime, not at startup. 

I never thought of it as a from asset files vs from scripting.... but I am all for being able to remove any asset.

**Comment by WeirdRubberDuck** [comment]
You're absolutely right @micahnyc. It was a misformulation from my side, since adding the assets during runtime could also be seen as adding them from an asset file ^^'

**Comment by alexanderbock** [comment]
Fixed since asset renewal code
