### ISSUE TITLE
Being able to generate SGCT configuration files through Lua

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#127]
In addition to being able to define the `SGCTConfig` in the `openspace.cfg`, it should also be possible to specify a Lua function with arguments that will generate a passable configuration file for simple cases.
For instance, a `single(x,y)` function that will return the configuration file for the `single.xml` with the resolution of `(x,y)`. The configuration file would then look like:
`SGCTConfig = single(x,y)`
and check at startup whether there is a text-based configuration or a Lua-based configuration

**Comment by nusic** [comment]
Regarding generating SGCT configuration files, I made a simple node script to launch multiple instances of OpenSpace as child processes for speeding up testing of OpenSpace synchronization. Have a look at

https://github.com/OpenSpace/OpenSpace/blob/697afc49596042a9a0e00488746ab1ada5e0ef0c/support/run/run_multiple_nodes.js

Starting up 4 nodes on a Windows machine is done by:
`node support\run\run_multiple_nodes.js bin\openspace\Release\OpenSpace.exe`
