### ISSUE TITLE
DigitalUniverseWin crash to desktop

### ISSUE THREAD

**Issue by webwizard65** [OpenSpace/OpenSpace#1273]
The program crashes to desktop at the beginning with the error "the procedure entry point __gxx_personality_v0 could not be located in the dynamic link library libstdc++-6.dll"

OS is Windows 7 x64, VCredist2019 is currently installed.

**Comment by alexanderbock** [comment]
We are not the people that maintain the Digital Universe atlas application, but I am assuming that it is the same issue that we are having.  With the end of support of Windows 7, it gets harder and harder to continue to support that operating system
