### ISSUE TITLE
OpenSpace Beta 0.15.2 crashes to desktop

### ISSUE THREAD

**Issue by webwizard65** [OpenSpace/OpenSpace#1274]
The program crashes to desktop at the beginning with the error "Unable to find an entry point named GetPointerInfo in USER32.dll"

OS is Windows 7 x64, VCredist2019 is currently installed.

**Comment by alexanderbock** [comment]
Hi,
with the end of Microsoft support in 2020, we also had to drop support for Windows 7 as we can no longer have a machine connected to our continuous integration system that tests whether OpenSpace still works unfortunately.
