### ISSUE TITLE
The launcher shouldn't need to download files that are already on disk

### ISSUE THREAD

**Issue by emiax** [OpenSpace/OpenSpace#129]
Only download files that were not yet downloaded. But also provide an option to overwrite.

**Comment by alexanderbock** [comment]
My idea was that the Launcher saves a single file in which the combination of identifier+version is stored so that only newer files get downloaded

**Comment by emiax** [comment]
Sounds like a easy and good solution :)

**Comment by alexanderbock** [comment]
Actually, per default it doesn't overwrite files; so right now it just touches them to see if they are there and if they are, they will not be downloaded again

**Comment by EricMyers47** [comment]
One way to do this is to maintain a "database" of downloaded files, and where they are, along with metadata like an MD5 as a checksum.   Format doesn't matter to me, but for comparison iTunes does this with an xml file.

**Comment by EricMyers47** [comment]
A quicker workaround would be to get the file length from HTTP headers and check the sizes, and assume it's already downloaded if the file size on disk matches the size from the header.   This will miss small changes that don't change file size, but it will prevent redundant downloads of big files that have not changed.
