### ISSUE TITLE
GIBS data east hemisphere repeated

### ISSUE THREAD

**Issue by carteremmart** [OpenSpace/OpenSpace#1291]
NASA GIBS layers tested with v15.2 and subsequent builds shows data east of Greenwich Prime Meridian copied onto the western hemisphere, i.e. east of the International date line.

While not every layer was tested, every layer that was tried exhibited the same behavior.

![GIBS-prime-meridian-offset-7](https://user-images.githubusercontent.com/70605329/91901422-32bc9980-ec6e-11ea-93ae-5ed9ddfcc25c.jpg)

![GIBS-prime-meridian-offset-8](https://user-images.githubusercontent.com/70605329/91901604-78796200-ec6e-11ea-8373-85afacd22e6e.jpg)

**Comment by alexanderbock** [comment]
I tried to replicate but was unable to;
1. I could find the "Leaf Area Index" in the list of GIBS layers on https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+Available+Imagery+Products#expand-CorrectedReflectance17Products
2. I tried a handful of these and none had any of these issues:


`openspace.globebrowsing.addLayer('Earth', 'ColorLayers', { Identifier = 'AIRS_Precipitation_Day', Enabled = true, Type = 'TemporalTileLayer', FilePath = openspace.globebrowsing.createTemporalGibsGdalXml('AIRS_Precipitation_Day', '2013-05-09', 'Yesterday', '1d', '2km', 'png', 'YYYY-MM-DD') })`
![OpenSpace_000000](https://user-images.githubusercontent.com/4921724/95658453-d2e1ca00-0b1a-11eb-834c-6cd37bb86361.png)



`openspace.globebrowsing.addLayer('Earth', 'ColorLayers', { Identifier = 'AIRS_L2_Temperature_850hPa_Night', Enabled = true, Type = 'TemporalTileLayer', FilePath = openspace.globebrowsing.createTemporalGibsGdalXml('AIRS_L2_Temperature_850hPa_Night', '2002-09-01', 'Yesterday', '1d', '2km', 'png', 'YYYY-MM-DD') })`
![OpenSpace_000001](https://user-images.githubusercontent.com/4921724/95658456-d70de780-0b1a-11eb-9d61-fa29f257c1a8.png)


`openspace.globebrowsing.addLayer('Earth', 'ColorLayers', { Identifier = 'VIIRS_NOAA20_Brightness_Temp_BandI5_Day', Enabled = true, Type = 'TemporalTileLayer', FilePath = openspace.globebrowsing.createTemporalGibsGdalXml('VIIRS_NOAA20_Brightness_Temp_BandI5_Day', '2020-04-25', 'Yesterday', '1d', '250m', 'png', 'YYYY-MM-DD') })`
![OpenSpace_000000](https://user-images.githubusercontent.com/4921724/95658460-e12fe600-0b1a-11eb-8254-45adbf19f2b8.png)


@carteremmart  Could you check if these three have the same issue?  I'm starting to think that the bug might be related to the "GlobeBrowsing" UI which seems to be very buggy over here in EU anyway (i can barely ever use it).  Also, if you have that issue with a specific layer, can you try using the new "GIBS" UI in the same menu for the same layer and see if it makes a difference?
