### ISSUE TITLE
GlobleBrowsing - LOD Scale Factor drops after changing target value

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1292]
After adding a new layer form the GIBS server and then changing the "Target Level of Details Scale Factor", the current LOD scale factor value is first set to the target value, but then continuously lowered over time until reaching a value of approximately 0.9-1.0

Steps to reproduce:
- Add a new layer from the GIBS server through the native globe browsing GUI
- Change target level of detail scale factor of the Earth Renderable to a desired value
- Observe how the "Current level of detail scale value" is first instantly set to the target value, but then starts dropping

**Comment by alexanderbock** [comment]
https://user-images.githubusercontent.com/708535/109526280-62fbbe00-7a80-11eb-995e-ec22bb6a77ab.png
