### ISSUE TITLE
Initialization of RenderableModel assets fail 

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1295]
The Apollo models does not load correctly when loading RenderableModel assets. Some profiles that lead to errors: `apollo_sites`, `apollo8`, `juno`, `mars`, `messenger`, `newhorizons`...

Image shows output for `apollo_sites.profile`

![Errors_loading_apollo_sites](https://user-images.githubusercontent.com/8808894/92591698-ae39ce80-f29e-11ea-9b92-6ad6763fc18e.PNG)

**Comment by alexanderbock** [comment]
Fixed in b694633728ea60715f9aef1864ebdfd70a22ee71
