### ISSUE TITLE
openspace.exe has stopped working

### ISSUE THREAD

**Issue by mecachis** [OpenSpace/OpenSpace#1298]
I get this error message every time I try to launch the program on windows 10. I'm using Beta - Version 0.15.2 and my graphics card is a Nvidia Geforce 920M, which I believe supports OpenGL 3.3. I have installed Visual Studio 2019 and 2013 and have tried to setup permissions for the program folder (I'm not 100% sure I did the latter correctly). Any help much appreciated. Thanks!

**Comment by alexanderbock** [comment]
Do you have any error message in your `log.html`, located in the `logs` folder?  That should contain more information about what went wrong
