### ISSUE TITLE
Add a colored glare to the stars of exoplanet systems

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1305]
Add a glare similar to the Sun's to the star of each exoplanet system. The glare should be tinted in the same color as the star.

The tricky bit is to figure out how to change the color of a texture from within OpenSpace, since that functionality does not exist yet

**Comment by hedbergj** [comment]
Yes Please! 

One thing I've done on my local installation is to add a few more parameters to the plane shader that permit tint/color etc to be applied. This would be nice to have for other thing besides star glares, eg, all the zodiac constellations could be tinted during runtime while the rest stay white, or one could make Orion blue/highlighted without having to alter the original png file. I'm sure there would be other uses cases for a general tint option for RenderablePlanes/Images. Other shaders for DU objects I believe already have such things, so it's fairly straightforward (I think).

And related, if you're going to make the glare scientifically accurate, it would be nice to have the stars of exoplanet be able to be illuminated by colored and different light sources (i.e non Sun position - 0,0,0 is coded into RenderableGlobe as the light source location). I know this was discussed and was on someone's list, but I don't think it ever happened to my knowledge. As it stands, the only way I was able to do it was to make the exoplanets RenderableModels (of textured sphere obj files), which can have non-Sun light sources. 

eg: https://github.com/ccnyplanetarium/addons/blob/master/trappist/screenshots/trappist-planet.jpg

But again, there is no reason that I can see that would prevent RenderableGlobes from also have a lightsource parameter.

**Comment by WeirdRubberDuck** [comment]
Thanks for your input @hedbergj ! Really valuable 👍 

I've also been thinking about the illumination of the exoplanets and that RenderableGlobe's can only be lit up by the Sun as of now... Don't know who's list it's on, but I'll put it on mine as well and discuss it with the others
