### ISSUE TITLE
OpenSpace-0.15.2 Error At Startup

### ISSUE THREAD

**Issue by Neokyuubi** [OpenSpace/OpenSpace#1310]
![Error User32.dll](https://iili.io/2bfSFs.jpg)

Is there any fix please ?

**Comment by alexanderbock** [comment]
Hi Neokyuubi,
do you have some more information about the error?  Is the User32.dll missing from your system?

**Comment by Neokyuubi** [comment]
> Hi Neokyuubi,
> do you have some more information about the error?  Is the User32.dll missing from your system?

Hi,
I didn't think I could have run Windows properly without that DLL 😆

I think it's a problem with the v 0.15.2
Cause I read somewhere that 0.15.0 works fine although I did not had the time to download it.

**Comment by alexanderbock** [comment]
Could you try this one?
http://data.openspaceproject.com/release/0.16.0_RC2/OpenSpace-0.16.0-minimal.zip
You can copy over the `sync` folder from the 0.15.2 version that you have if you don't want to download the files again.

Just a question on the side and out of curiosity:  Where did you read that 0.15.0 works fine?

**Comment by alexanderbock** [comment]
Looking at your screenshot again, that window border around the error message looks strikingly like a Windows 7 window border.  Are you, by chance, running that?

**Comment by Neokyuubi** [comment]
> Could you try this one?
> http://data.openspaceproject.com/release/0.16.0_RC2/OpenSpace-0.16.0-minimal.zip
> You can copy over the `sync` folder from the 0.15.2 version that you have if you don't want to download the files again.
> 
> Just a question on the side and out of curiosity: Where did you read that 0.15.0 works fine?

Ok i will try that and get back to you, hopefully, i didn't delete the 0.15.2 version but i downloaded the 0.15.0 version and it worked.
I don't really remember exactly where, but i remember i typed the entire error from the window error in google.



> Looking at your screenshot again, that window border around the error message looks strikingly like a Windows 7 window border. Are you, by chance, running that?

Yes exactly, it's Windows 7, and in the download page it says "We recommended the latest Windows operating system (Windows 10)." it means windows 7 is gonna work too but it's preferable if it's windows 10, no ?

**Comment by alexanderbock** [comment]
(y)

Basically we write that we recommend Windows 10 because that is what all of our developers and our continuous integration system uses and that we can't make any guarantees that it works on previous OS versions

**Comment by Roxeena** [comment]
Close this?

**Comment by GPayne** [comment]
Recommend closing this due to Windows7

**Comment by alexanderbock** [comment]
Yea; agreed.  We should close this as Windows 7 is no longer supported by Microsoft as of January 14th, 2020

https://www.microsoft.com/en-ww/microsoft-365/windows/end-of-windows-7-support
