### ISSUE TITLE
Handling InteractionMode's dependencies

### ISSUE THREAD

**Issue by nusic** [OpenSpace/OpenSpace#133]
### Background

The class `InteractionMode` is used by `InteractionHandler` to calculate camera position and rotation. However, `InteractionModes` are usually dependent on some state, e.g a `SceneGraphNode` used as a focus node. Currently, the base class `InteractionMode` defines a get/set interface for focus node and stores that focus node internally. 
### Problem

There is no clearly defined and consistent way of handling dependencies to different `InteractionModes`. This is confusing to developers.

Examples:
- If you want to implement a new InteractionMode that has more than just a focus node as dependency (e.g. a secondary focus node) - where should the secondary focus node be stored?
- If you implement a a new subclass of `InteractionMode` (for example "Free-Flight InteractionMode") it inherit an unused focus node

**Comment by nusic** [comment]
### Idea 1
All global state could be stored and maintained in InteractionHandler. On every frame when the current `InteractionMode` should update the camera, an object representing all global state is passed in as an argument to that method. 

### Example 
The `InteractionMode` interface would look something like
```
virtual void updateCamera(
    Camera& , // camera to be updated
    const UserInput&, // mouse position, keys pressed, etc. (a.k.a InputState)
    const InteractionDependencies&, // focus node, groups of nodes, friction coefficients, etc
    double deltaTime) = 0;
```

### Pros
 - Dependencies to different `InteractionMode`s is handled in a uniform way: just add whatever data is needed for the interaction mode in the struct InteractionDependencies. 
 - Interface is simpler (It has only one method as supposed to two* (which is used for synchronizing InputState). However, the caller of the proposed `updateCamera(...)` i.e. `InteractionHandler` can ensure the InputState is synchronized properly.

### Cons
 - ?

-

*. Current interface of `InteractionMode` for updating camera
```
virtual void updateMouseStatesFromInput(const InputState& inputState, double deltaTime) = 0; // called in pre-sync
virtual void updateCameraStateFromMouseStates(Camera& camera) = 0; // called in post-sync
```

**Comment by alexanderbock** [comment]
Need to verify if this is still valid

**Comment by alexanderbock** [comment]
It is not, the `InteractionMode` no longer exists
