### ISSUE TITLE
Add the possiblity to specify Ra, Dec and Distance in StaticTranslation

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1334]
The file `coordinateconversion.h` has a function for doing the conversion from ICRS to galactic cartesian coordinates.

**Comment by micahnyc** [comment]
We want the math version like here to be in a translation class: https://github.com/OpenSpace/ui.openspaceproject.com/blob/master/jwst_scripts/index.html

**Comment by micahnyc** [comment]
Add this this class then have translation use it: https://github.com/OpenSpace/OpenSpace/blob/9ef11c4c0d4c65b9dea351d9380169ef263632d3/src/util/coordinateconversion.cpp
