### ISSUE TITLE
RenderablePlaneProjection has weird specifications for NewHorizons

### ISSUE THREAD

**Issue by kbladin** [OpenSpace/OpenSpace#134]
- The mod file is positioned in data/scene/imageplane but has NewHorizons dependencies
- The mod file specified in the current develop branch has some weird positioning and frame info (Jupiter even though it takes images of Pluto).

``` lua
return {
    -- Latest image taken by LORRI
    { 
        Name = "ImagePlane",
        Parent = "NewHorizons",
        Renderable = {
            Type = "RenderablePlaneProjection",
            Frame = "IAU_JUPITER",
            DefaultTarget = "JUPITER",
            Spacecraft = "NEW HORIZONS",
            Instrument = "NH_LORRI",
            Moving = false,
            Texture = "textures/test.jpg",
        },
        Ephemeris = {
            Type = "Static",
            Position = {0, 0, 0, 1}
        }, 
    },
    -- LORRI FoV square
    {
        Name = "ImagePlane2",
        Parent = "NewHorizons",
        Renderable = {
            Type = "RenderablePlaneProjection",
            Frame = "IAU_JUPITER",
            DefaultTarget = "JUPITER",
            Spacecraft = "NEW HORIZONS",
            Instrument = "NH_LORRI",
            Moving = true,
            Texture = "textures/squarefov.png",
        },
        Ephemeris = {
            Type = "Static",
            Position = {0, 0, 0, 1}
        },
    }

}
```

Compare to the working image projection for Rosetta (after the update of the scene graph which makes rotations follow from parents):

``` lua
    { 
        Name = "ImagePlaneRosetta",
        Parent = "67P",
        Renderable = {
            Type = "RenderablePlaneProjection",
            Frame = "67P/C-G_CK",
            DefaultTarget = "CHURYUMOV-GERASIMENKO",
            Spacecraft = "ROSETTA",
            Instrument = "ROS_NAVCAM-A",
            Moving = false,
            Texture = "textures/defaultProj.png",
        }
    }
```

It has 67P as parent which makes sense since the image should rotate with the comet.
- The update we did for the NewHorizons image planes works when images are taken of Pluto (since Pluto is the parent of the image plane) but as soon as an image is taken of Charon for example, the image is positioned with respect to pluto and not Charon (Which of course makes sense since it has Pluto as parent):

``` lua
    { 
        Name = "ImagePlane",
        Parent = "PlutoProjection",
        Renderable = {
            Type = "RenderablePlaneProjection",
            Frame = "NH_SPACECRAFT",
            DefaultTarget = "PLUTO",
            Spacecraft = "NEW HORIZONS",
            Instrument = "NH_LORRI",
            Moving = false,
            Texture = "textures/squarefov.png",
        }, 
    },
```

In the osirisrex branch we commented out the image planes for NewHorizons since they got positioned wrong.
- Not sure how you actually would want to specify the renderable plane projections. It made sense to put the parent as the object that is being imaged since it will follow its rotations. That works for Rosetta since there is only one 67P but as soon as one instrument is taking images of several objects it doesn't really work. Before the parent was set to the object that takes the images (for example NewHorizons in the first mod specification above) but then the rotation and positioning before the rendering will have to be handled in a special way for the renderable plane projection.

**Comment by kbladin** [comment]
Was this solved @alexanderbock?

**Comment by alexanderbock** [comment]
No, not yet.  We stopped using the Image plane projection in new horizons and it worked for rosetta, so I put it on the backburner

**Comment by alexanderbock** [comment]
This is all not relevant anymore
