### ISSUE TITLE
When using the pixel control, the sizes flicker when moving towards the screen border

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1342]
Seems to be the case with "Camera Position Normal", which is default.

Recording to recreate (flickering happens in the lower right corner near the orbit of Mars)
[exoplanets-flickering.zip](https://github.com/OpenSpace/OpenSpace/files/5395931/exoplanets-flickering.zip)

**Comment by jccosta** [comment]
Fixed. The new solution will require a full pass on assets using the rendering billboards cloud in order to adjust the new max and min billboards' sizes when the sizing control is enabled.

**Comment by alexanderbock** [comment]
https://github.com/OpenSpace/OpenSpace/pull/1354
