### ISSUE TITLE
OpenSpace does not compile without globe browsing module enabled.

### ISSUE THREAD

**Issue by emiax** [OpenSpace/OpenSpace#135]
A linker error is caused by interactionmode.cpp referencing renderableglobe.cpp. Either the globe interaction mode should be moved to the globe browsing module (probably best?) or as a workaround: surround the globe interaction mode by ifdefs.
What do @nusic and @kbladin think?

**Comment by alexanderbock** [comment]
Fixed in 193e2bdc6488c80a2344d8bd8522d9235df92293
