### ISSUE TITLE
Sun star creating issue with planet atmosphere

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1351]
Turning on the MilkyWay->Stars->Sun creates a rendering error in the mars atmosphere. See screenshots for rendering with on and off. 

![OpenSpace_000002](https://user-images.githubusercontent.com/708535/96647215-447bfe00-12fb-11eb-91fa-0e60d4427287.png)
![OpenSpace_000003](https://user-images.githubusercontent.com/708535/96647223-45ad2b00-12fb-11eb-84b4-d0fc0a319e39.png)

**Comment by jccosta** [comment]
This issue also happens in #1093 when the milky way sphere is not enabled. It is fixed in commit 5855671853faeefaa3a382c6276028bdf9123da4 .
