### ISSUE TITLE
OpenSpace crashes when loading without errors

### ISSUE THREAD

**Issue by Aztec2012** [OpenSpace/OpenSpace#1353]
Open Space crashes when loading without errors.
I have windows 10 1909. Log in attach.

[log.zip](https://github.com/OpenSpace/OpenSpace/files/5423247/log.zip)

**Comment by micahnyc** [comment]
Hi @Aztec2012, looking at your log file, there doesn't seem to be any specific issues. My guess is that your GPU doesn't have enough memory to run our default scene. In 0.15.2 our default scene takes almost 4GB of video memory, and looking at your log file, you are running a GT640 which only has 2GB of video memory.

**Comment by Aztec2012** [comment]
> Hi @Aztec2012, looking at your log file, there doesn't seem to be any specific issues. My guess is that your GPU doesn't have enough memory to run our default scene. In 0.15.2 our default scene takes almost 4GB of video memory, and looking at your log file, you are running a GT640 which only has 2GB of video memory.

But my GeForce GT 640 has 4 gb of video. AIDA64 says this info too.

**Comment by GPayne** [comment]
Any thoughts about compatibility with Nvidia GT6xx architecture, @jccosta ?

**Comment by jccosta** [comment]
@Aztec2012, are you trying to run the default scene?
4GB and your GPU model should be enough to run OpenSpace (although, I am not sure about the performance).

**Comment by Aztec2012** [comment]
> @Aztec2012, are you trying to run the default scene?
> 4GB and your GPU model should be enough to run OpenSpace (although, I am not sure about the performance).

Yes i run default scene and default full in HD and FullHD and the same problem is appear.

**Comment by jccosta** [comment]
@Aztec2012, in the openspace.cfg file (in the root of the main folder), in the end of the file, you have:

OpenGLDebugContext = {
   Activate = false,
   ....

Can you activate the OpenGLDebugContext? Just change the false to true in that line.
After you do that, can you paste your log.html here again?
Thank you.

**Comment by Aztec2012** [comment]
> @Aztec2012, in the openspace.cfg file (in the root of the main folder), in the end of the file, you have:
> 
> OpenGLDebugContext = {
> Activate = false,
> ....
> 
> Can you activate the OpenGLDebugContext? Just change the false to true in that line.
> After you do that, can you paste your log.html here again?
> Thank you.

Here is it. Thank you.
[log.zip](https://github.com/OpenSpace/OpenSpace/files/5425631/log.zip)

**Comment by Aztec2012** [comment]
Crash appeared when starting OpenGL loading and in the log is 13 errors lines looks like this: 

**_OpenGL (API) [Error] {1281} | Error | GL_INVALID_VALUE error generated. ObjectLabel: unknown texture object <name>_**

**Comment by Aztec2012** [comment]
In 0.16.1 version the same crash.

**Comment by alexanderbock** [comment]
I'm assuming your on the Slack?   Could you give me a ping there ("Alex Bock")?    Seems there is something weird with the texture/framebuffer generation and it might mean to send a few builds back and forth

**Comment by Aztec2012** [comment]
> I'm assuming your on the Slack? Could you give me a ping there ("Alex Bock")? Seems there is something weird with the texture/framebuffer generation and it might mean to send a few builds back and forth

Yes I am on the Slack but newbie on this. And I have not the same errors in the log file.

**ERROR:viz_main_impl.cc(169)] Exiting GPU process due to errors during initialization**


[debug.zip](https://github.com/OpenSpace/OpenSpace/files/6427074/debug.zip)
