### ISSUE TITLE
Segmentation fault on Linux during the initialization of the Engine

### ISSUE THREAD

**Issue by jccosta** [OpenSpace/OpenSpace#1355]
Segmentation fault on Linux during the initialization of the Engine.
globals variables are null in global::initialize() when it is called inside SGCT.
System crashes during initialization.

**Comment by sa5bke** [comment]
This seems not be a problem anymore, atleast for me on Fedora 32 compiling using clang.

**Comment by alexanderbock** [comment]
This was fixed in 51470c0a0d29327f117d3afe7d759161baf669b1   but it was untested before on Fedora.  Great that it is working!
