### ISSUE TITLE
Play session is not working in current Master

### ISSUE THREAD

**Issue by jccosta** [OpenSpace/OpenSpace#1366]
After recording a session, when one tries to play it, the following message is displayed:

SessionRecording (Error)        Allocation error with script playback from keyframe entry 0
SessionRecording (Error)        Allocation error with script playback from keyframe entry 1
SessionRecording (Error)        Allocation error with script playback from keyframe entry 1710
SessionRecording (Error)        Unknown frame type 114 @ index 1711 of playback file E:\Pessoal\Work\OpenSpace-Current-Master-New\OpenSpace\recordings\test2.osrec

We expected to watch the recorded session, but instead, only a small camera displacement happens.

**Comment by jccosta** [comment]
Example file:
[test-libcurl-certificate.zip](https://github.com/OpenSpace/OpenSpace/files/5476292/test-libcurl-certificate.zip)

**Comment by GPayne** [comment]
Closed in PR#1405
