### ISSUE TITLE
Add Option to Remember Last Profile Run

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#1367]
Launcher reads openspace.cfg and auto-loads the profile specified in that file.
It would be convenient to configure the launcher (e.g. checkbox option) to remember the selected profile so that a user doesn't have to set this every time OpenSpace runs. This option would also prevent the user from having to edit openspace.cfg.

**Comment by alexanderbock** [comment]
We could store the last-selected state in a file in the `cache` directory.  If the file exists, it will read the values and try to set them (values might have been removed since the last startup), otherwise it will use the values from the `openspace.cfg` file

**Comment by alexanderbock** [comment]
Removing this from 0.19.0 to wait for a proper implementation of user-settings for profiles instead

**Comment by alexanderbock** [comment]
Closed in b62e604
