### ISSUE TITLE
Dawn model does not have any color texture

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1378]
As reported by Jacob R

**Comment by alexanderbock** [comment]
I'd argue for a wontfix-for-now as we won't have the new model loading in 0.16.1 and it might be more efficient to just fix it correctly for 0.17.0 instead

**Comment by micahnyc** [comment]
https://nasa3d.arc.nasa.gov/detail/jpl-vtad-dawn

**Comment by alexanderbock** [comment]
wontfix
