### ISSUE TITLE
Insight position is wrong after the end of the spice kernel

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1380]
When starting up the Mars scene, the Insight lander is placed in the Sun as the SPICE kernel information is exceeded.  Maybe a Timelinetranslation that will fix the position to the last known position?

As reported by Jacob R

**Comment by micahnyc** [comment]
Related to: https://github.com/OpenSpace/OpenSpace/issues/1380 (i.e start vs end of spice values.)

**Comment by micahnyc** [comment]
closing as dupe of https://github.com/OpenSpace/OpenSpace/issues/1056
