### ISSUE TITLE
"Use Accurate Normals" on a planet without a heightmap produces errors

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1382]
Toggling  ‘Use Accurate Normals’ creates a constant flow of errors and despawns the exoplanet being viewed, when in render range. If out of render range and toggled, nothing happens. 

/ As reported by Zach S

**Comment by jccosta** [comment]
Fixed in d1e4d7783b49a3968aef939ea8092ab3afad4d27.
