### ISSUE TITLE
MacOS build issue

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1385]
Check if OpenSpace builds on MacOS

**Comment by Roxeena** [comment]
Is this still an issue?

**Comment by alexanderbock** [comment]
Given that we released a MacOS build about a month later and it is compiling right now, I think it's not longer an issue

**Comment by hedbergj** [comment]
Not sure what you mean by "right now" But I can only get it building using Cmake 18.5, restoring the line

```
target_include_directories(Ghoul SYSTEM PRIVATE ${FREEIMAGE_INCLUDE_PATH})
``` 
in Ghoul CMakeLists.txt,

adding another colon here in `ext/ghoul/src/io/texture/texturereaderfreeimage.cpp`:

```
fmt::format("Could not load image ({})", filename),
```

and even then things don't look right. Something's unhappy in the servermodule but the error's not giving me any ideas. The WebGUI doesn't finish loading.

```
2021-03-16 | 11:35:02.350 | ServerModule: Connection | Error | [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: 'i'
```

<img width="1272" alt="Screen Shot 2021-03-16 at 7 50 09 AM" src="https://user-images.githubusercontent.com/7926907/111304572-489f1400-862c-11eb-917c-c3b2ff0f7607.png">

**Comment by alexanderbock** [comment]
I'm having a travel upcoming where I will be without a Windows machine for a while, so I'll have a gander at that then

**Comment by hedbergj** [comment]
I'll chip in to get you a Euro pass so you can travel more often...

**Comment by alexanderbock** [comment]
:D :D    No need;  the moment it is safe enough to travel for real again, I'll catch up on 15 months of missed travel immediately
