### ISSUE TITLE
Launcher issue with multiple instances of SGCTConfig in cfg file

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1386]
Turns out my issue wasn't with the file outside of the config, but rather with two instances of setting SGCTConfig in my .cfg file.

The launcher read the first one, but then when launching openspace, it used the second one. This launching me with a different SGCTConfig then it displayed.

**Comment by alexanderbock** [comment]
I can't replicate that behavior on my end:
```
SGCTConfig = "${CONFIG}/single.xml"
SGCTConfig = "${CONFIG}/single_gui.xml"
```
leads to

![image](https://user-images.githubusercontent.com/4921724/99378288-8d59af00-28c7-11eb-9777-3ff9bed92f2c.png)


leads to

![image](https://user-images.githubusercontent.com/4921724/99378342-99de0780-28c7-11eb-9631-01418017c253.png)

**Comment by micahnyc** [comment]
Seems to be only be an issue with the lua generated ones:
```

SGCTConfig = sgct.config.single{vsync=false}
SGCTConfig = "${CONFIG}/single_gui.xml"
```

**Comment by micahnyc** [comment]
would also be happy to close this with the notion of the openspace.cfg editor as it will not allow this to happen.....

**Comment by Roxeena** [comment]
Should we close this then?

**Comment by micahnyc** [comment]
Yeah I say we close this. Basically it's some example of doing something we don't support. IDK why I made this ticket in the first place. I should have just said to myself: "Having multiple instances of SGCTConfig is not supported"
