### ISSUE TITLE
TaskRunner crashes at Startup

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#1404]
Recent code changes seem to have broken the TaskRunner. When run from commandline or from VisualStudio, it crashes immediately without an error message. The crash happens here:
https://github.com/OpenSpace/OpenSpace/blob/f7cd107744183958c3b906839f5b3bb11376c172/apps/TaskRunner/main.cpp#L120

**Comment by alexanderbock** [comment]
Probably the TaskRunner wasn't adapted to the `globals` change
