### ISSUE TITLE
Sync file failure with error: "URL using bad/illegal format or missing URL"

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#141]
In the Mac OpenSpace Launcher, some files fail to sync with error "URL using bad/illegal format or missing URL". The cause seems to be a carriage return character at the end of the file's local save path (which probably means this isn't a problem on windows) in LauncherLog.html.

**Comment by alexanderbock** [comment]
Potential fix in 1fc8ac8deb63212b67bac3536cfb9c7d2fe77349

All \n and \r characters are removed from the download URLs
