### ISSUE TITLE
Add a 1 AU circle for exoplanet systems

### ISSUE THREAD

**Issue by carteremmart** [OpenSpace/OpenSpace#1413]
Desire ability to toggle a 1 AU comparison circle for scale comparison of exoplanetary systems to Earth's orbit around our Sun.

**Comment by carteremmart** [comment]
The radial grid has a radius of "0.5" for 1 AU.  I would suggest changing this value to 1.0 so we have radial units in AU.

**Comment by WeirdRubberDuck** [comment]
Related to #1178

**Comment by WeirdRubberDuck** [comment]
@carteremmart how did you come to the conclusion that the radial grid has a radius of 0.5 for 1 AU? 🤔 A grid with radius 1.0 and scale 1 AU should generate a grid with a 1 AU radius

**Comment by WeirdRubberDuck** [comment]
Added a ring that can be enabled when needed. Although, could not add a label that displays "1 AU" due to issue #1474

**Comment by carteremmart** [comment]
As long as it says “1 AU circle” in the menu, is good.  Did you verify scale in comparison to Earth orbit?  Thanks.

Sent from my iPhone

On Jan 28, 2021, at 5:34 AM, Emma Broman <notifications@github.com> wrote:

﻿
EXTERNAL SENDER


Added a ring that can be enabled when needed. Although, could not add a label that displays "1 AU" due to issue #1474<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenSpace%2FOpenSpace%2Fissues%2F1474&data=04%7C01%7Ccarter%40amnh.org%7Cb3fbd8b61ce442a6b76608d8c37838f6%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637474268422900748%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yek4tY2AmFUsY6futZhFJMQ3fDvbSiDhVIqokDHvEjU%3D&reserved=0>

**Comment by WeirdRubberDuck** [comment]
Yes, I did!
