### ISSUE TITLE
Crashes at startup

### ISSUE THREAD

**Issue by estrelanova** [OpenSpace/OpenSpace#1414]
Crashes right at startup. I installed Version 0.15.2 first and tried 0.15.1 as well, with the same result. 
I tried to install OpenSpace on two PC, a desktop and a brand new Lenovo Thinkpad. Both running with Windows 10,  with the same result.

Since I'm new to this platform let me know what information you need to help me. I have attached the debug.log to this message. Maybe this is helpful?

Thank you all for your great work.

[debug.log](https://github.com/OpenSpace/OpenSpace/files/5626851/debug.log)

**Comment by estrelanova** [comment]
Problem is solved: when I right-click on the app and choose 'run as administrator' it works. Thanks anyway.

**Comment by alexanderbock** [comment]
There is not much information in the `debug.log` but it might have been related to the location from which you were running the program.  For example, the "Program Files" folder sometimes requires elevated privileges to be allowed to be written to, which we do in the beginning when starting up

**Comment by estrelanova** [comment]
Thank you very much for your answer. So should I move the OpenSpace-folder
to another place if I don't want to open it with a right click?

Am Do., 3. Dez. 2020 um 17:39 Uhr schrieb Alexander Bock <
notifications@github.com>:
