### ISSUE TITLE
Can't proceed with "new profile" in OpenSpace Launcher

### ISSUE THREAD

**Issue by estrelanova** [OpenSpace/OpenSpace#1415]
If I open the Launcher, nothing happens when I press "Start Open Space" and If I fill out a "new profile" and press "save", nothing happens as well, whatever I fill in the form. 

I have attached two screenshots.

Thank you all very much
![OpenSpace Launcher](https://user-images.githubusercontent.com/75349923/100826401-8c458780-345a-11eb-953b-4af6d6f461bd.png)
![OpenSpace new profile](https://user-images.githubusercontent.com/75349923/100826403-8cde1e00-345a-11eb-9c4e-76eb868da158.png)

**Comment by alexanderbock** [comment]
I'm closing this since we have replaced the old launcher with a new one :)

**Comment by estrelanova** [comment]
Great. Thank  you for the information!

Erich




Von: Alexander Bock <notifications@github.com>
Datum: Samstag, 2. Januar 2021 um 23:41
An: OpenSpace/OpenSpace <OpenSpace@noreply.github.com>
Cc: Erich Strehler <info@spacedome.ch>, Author <author@noreply.github.com>
Betreff: Re: [OpenSpace/OpenSpace] Can't proceed with "new profile" in OpenSpace Launcher (#1415)

I'm closing this since we have replaced the old launcher with a new one :)
