### ISSUE TITLE
Exception when adding over 3 exoplanet systems in multiwindow setup

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1439]
For example, this issue occurs when using single_two_win.xml but not when using single.xml

After adding 3 exoplanet systems, adding a fourth one leads to an exception being thrown

![image](https://user-images.githubusercontent.com/8808894/102613223-67c3fd80-4132-11eb-9985-a7b1758a3598.png)

**Comment by alexanderbock** [comment]
Seems to be CEF related as the code that crashes lives in the CrBrowserMain thread
![image](https://user-images.githubusercontent.com/4921724/106448198-bb8c6b00-6482-11eb-95be-43071a60aa50.png)

**Comment by alexanderbock** [comment]
Problem only seems to occur when we have two CEF windows open at the same time.  When starting with `SGCTConfig = "${CONFIG}/single_gui.xml"` and `WebBrowser = { Enabled = false },`  the problem does not occur

**Comment by micahnyc** [comment]
I added 9 exoplanets in single_gui in version 16.0 and it worked fine...

**Comment by micahnyc** [comment]
After further investigation, this seems to be a threading issue around the discs? I have it happening regardless of if I have the browser enabled or not, even tried having the browser be at google.com and just using the console.

In the exoplanetsmodule_lua.ini, if I take out the scripts for adding the orbit discs and habitable zones, then I can add many systems with no crash.

`
// openspace::global::scriptEngine->queueScript(
            //     "openspace.addSceneGraphNode(" + discNode + ");",
            //     scripting::ScriptEngine::RemoteScripting::Yes
            // );
`
So taking out discNode, ring and zoneDiscNode made it not crash

**Comment by WeirdRubberDuck** [comment]
A potential lead: It seems like the crash only happens when a single Exoplanet System is provided as input to `openspace.exoplanet.addExoplanetSystem()`. When providing a list of systems, the crash does not happen. For example, writing this in the console worked just fine: 

`openspace.exoplanets.addExoplanetSystem({"11 Com", "11 UMi", "14 And", "14 Her", "16 Cyg B", "18 Del", "24 Boo"});`

**Comment by WeirdRubberDuck** [comment]
I think this issue can be closed. Can no longer reproduce

**Comment by alexanderbock** [comment]
I wonder where that came from..

but also glad that it is gone   ¯\_(ツ)_/¯
