### ISSUE TITLE
shader linking error in Linux

### ISSUE THREAD

**Issue by wtbgagoa** [OpenSpace/OpenSpace#1442]
Dear developers,

I am running the latest beta-8 (version 0.16.0) of OpenSpace in Ubuntu 20.04 (commit hash indicated in the download page). Compilation goes fine but when loading the default profile, globes and other things like orbit trails of planets in the solar system are not rendered correctly. For example, in the case of the Earth only what appears to be the atmosphere is rendered, but not the remaining features. Looking through the [attached](https://github.com/OpenSpace/OpenSpace/files/5729379/log.txt) log file gives the following error, repeated several times:

```
Error linking program object [LocalChunkedLodPatch Vertex]: 6(54) :
error C0000: syntax error, unexpected integer constant at token "<int-const>"
6(70) : error C0000: syntax error, unexpected integer constant at token "<int-const>"
5: /home/alfonso/OpenSpace/modules/globebrowsing/shaders/blending.hglsl
0: /home/alfonso/OpenSpace/modules/globebrowsing/shaders/localrenderer_vs.glsl
4: /home/alfonso/OpenSpace/modules/globebrowsing/shaders/texturetilemapping.hglsl
3: /home/alfonso/OpenSpace/modules/globebrowsing/shaders/tile.hglsl
6: /home/alfonso/OpenSpace/modules/globebrowsing/shaders/tileheight.hglsl
7: /home/alfonso/OpenSpace/modules/globebrowsing/shaders/tilevertexskirt.hglsl
2: /home/alfonso/OpenSpace/shaders/PowerScaling/powerScalingMath.hglsl
1: /home/alfonso/OpenSpace/shaders/PowerScaling/powerScaling_vs.hglsl
```

I am not sure whether this is something hardware related, but just in case I enclose information about my hardware:
```
# glxinfo | egrep -e 'Dedicated|OpenGL'
Dedicated video memory: 2048 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce MX250/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 455.38
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 455.38
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 455.38
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

```
I am using the latest NVIDIA propietary drivers and I did not have any problem compiling and running the previous beta-7 release.
I would appreciate any hint about how I could fix this issue (if that is possible). Thank you very much.

**Comment by alexanderbock** [comment]
Sometimes, these errors we have with the shaders are due to the line ending.  The error you are getting is in line 70 of the `tileheight.hglsl` (match the 6(70) with the 6:).

You can find the fully processed shader file (the one that actually gets fed to OpenGL) in `cache/LocalChunkedLodPatch Vertex/<some number>/LocalChunkedLodPatch Vertex`.  If you can paste the contents of that here, I can try to better help.
Around line 545, for me it says:  `#define CHUNK_DEFAULT_HEIGHT 0.000000` and I'm assuming that something goes strange there for you

**Comment by wtbgagoa** [comment]
Line ending in line 70 of the file `tileheight.hglsl` seems to be OK for me. 

For me, line 548 of the processed shader file says `#define CHUNK_DEFAULT_HEIGHT 0,000000` so the decimal point is getting replaced by a comma. The complete file is [here](https://github.com/OpenSpace/OpenSpace/files/5761757/LocalChunkedLodPatch.Vertex.txt).

**Comment by alexanderbock** [comment]
Oof.. this took some time to figure out, but I think i got it.   The `std::to_string` function we are using to replace a placeholder with the actual value depends on the locale of your system.  So I'm presuming you have set up your operating system to a language in which , is used as a decimal separator (like German, for example).

Can you try the following:  In the `apps/OpenSpace/main.cpp` somewhere high up among the other `#include` add `#include <clocale>`  and then as the first thing in the main function (should be around line 1016) add:
```
std::setlocale(LC_ALL, "en_US.UTF-8");
```

That should force all locale-based changes to be in US format

**Comment by wtbgagoa** [comment]
Thanks for investigating this issue and finding a solution. I have good and bad news:
bad news: the proposed solution doesn't work for me, after successful compilation I still get the error described in the first post.
Good news: the following workaround works for me:
```
# export LC_NUMERIC="en_US.UTF-8"
# ./OpenSpace
```
Indeed,  I work in a computer with some of its preferences set up for the Spanish language (including the treatment of numbers):

```
# locale -k LC_NUMERIC
decimal_point=","
thousands_sep="."
grouping=3;3
numeric-decimal-point-wc=44
numeric-thousands-sep-wc=46
numeric-codeset="UTF-8"

```
But system language is US English (I have a mixed configuration) so maybe that's the reason why the proposed fix doesn't work for me. In any case I would be fine with the workaround I described. Given that nobody else using Linux seems to have found a similar problem, perhaps this is something that has to do with my own locale configuration.

**Comment by alexanderbock** [comment]
`std::setlocale(LC_NUMERIC, "en_US.UTF-8");`  in the beginning ought to do the same thing as exporting it before starting.
I'll add it to the Linux wiki page as a potential problem.
If you consider it as "fixed" with this, I'd close the ticket?

**Comment by wtbgagoa** [comment]
I tried `std::setlocale(LC_NUMERIC, "en_US.UTF-8");` but still it doesn't pick it up and I get the same error. Most likely there's
something in my local configuration that is preventing your proposed fix from working properly but I have no idea what it can be. 
I consider the addition to the Linux wiki page as the fix (the proposed C++ code fix compiles fine and do not seem to break anything else).
As for me, the ticket can be closed.

**Comment by alexanderbock** [comment]
👍    Thanks for the bug report.   If you come across some potential solution that could work from the C++ side, please let me know so we can fix it for real :)
