### ISSUE TITLE
Voyager scene crashes with Deltatime keybindings

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1445]
When starting the "voyager" scene, it crashes during loading in https://github.com/OpenSpace/OpenSpace/blob/master/src/util/timemanager.cpp#L480  with `index == 13` and `steps.size() == 13` and `i == 3`

**Comment by WeirdRubberDuck** [comment]
Did not manage to reproduce the crash, but found what I believe is the source of the error. When the number of delta time steps was larger than 10, 20 or 30 keybindings were always added, even if the number of delta time steps were a smaller number (e.g. 13 as in the voyager case). The cause should have been the undefined behavior that came from accessing values outside the size of a vector.
