### ISSUE TITLE
Invalid internal format passed to glTexImage2D in texturereaderdevil.cpp

### ISSUE THREAD

**Issue by jccosta** [OpenSpace/OpenSpace#145]
When the image format is equal to IL_LUMINANCE (or IL_LUMINANCE_ALPHA), GL_LUMINANCE (or GL_LUMINANCE_ALPHA) is passed as the internal format of the texture to glTexImage2D. The internal format should be one of the values in Table 1, 2 or 3 in https://www.opengl.org/sdk/docs/man/html/glTexImage2D.xhtml depending on the image type.

**Comment by alexanderbock** [comment]
Closed.  DevIL texture reader will set an internal format of `GL_RED` instead of `GL_LUMINANCE` and `GL_RG` instead of `GL_LUMINANCE_ALPHA`. The drawback with this is that `GL_RED` might not replicate values into the other color channels.
