### ISSUE TITLE
Deep Sky Objects should have "pc" as their main unit and not "Mpc"

### ISSUE THREAD

**Issue by jccosta** [OpenSpace/OpenSpace#1450]
Deep Sky Objects should have "pc" as their main unit and not "Mpc."
Because we are using the wrong unit, objects are positioned in the wrong place in the space.

**Comment by jccosta** [comment]
The maximum scale range must be increased to easier visualization of the objects from different points in space.

**Comment by alexanderbock** [comment]
Closed in 50bae273fb2af5fe2dab96856ab497b648f6ed60
