### ISSUE TITLE
Manhattan is Under Water (errors in 2013 water mask)

### ISSUE THREAD

**Issue by hedbergj** [OpenSpace/OpenSpace#1453]
The default water mask for Earth:

MODIS_Water_Mask/default/2013-08-21/250m

has some major errors around Manhattan (i.e. it's under water)

https://go.nasa.gov/3ou2Bm1

There is a more recent mask that has a better outline of the island

MODIS_Terra_L3_Land_Water_Mask/default/2015-08-21/250m

https://go.nasa.gov/3hZtbkr

![manhattan_water_mask](https://user-images.githubusercontent.com/7926907/104095247-d98bf480-5263-11eb-87a3-1453832c35d1.gif)

**Comment by micahnyc** [comment]
closed with: https://github.com/OpenSpace/OpenSpace/commit/1b0f6b6fa985c245f405c220d26b881eab07151d
