### ISSUE TITLE
Error: ‘HB_SCRIPT_MEDEFAIDRIN’ undeclared under Ubuntu 16.04 and 18.04

### ISSUE THREAD

**Issue by Venustiano** [OpenSpace/OpenSpace#1458]
<< Description of the problem >>

Openspace was not compiled in good order

<< What did you expect to happen >>
I expected Openspace to be compiled in good order

<< What did happen? >>

```
[ 13%] Built target stb_image
[ 13%] Building C object ext/ghoul/ext/freetype2/CMakeFiles/freetype.dir/src/autofit/autofit.c.o
In file included from /home/svcg/source/OpenSpace/ext/ghoul/ext/freetype2/src/autofit/autofit.c:33:
/home/svcg/source/OpenSpace/ext/ghoul/ext/freetype2/src/autofit/afscript.h:248:11: error: ‘HB_SCRIPT_MEDEFAIDRIN’ undeclared here (not in a function); did you mean ‘HB_SCRIPT_MANDAIC’?
  248 |           HB_SCRIPT_MEDEFAIDRIN,
      |           ^~~~~~~~~~~~~~~~~~~~~
/home/svcg/source/OpenSpace/ext/ghoul/ext/freetype2/src/autofit/afshaper.c:89:38: note: in definition of macro ‘SCRIPT’
   89 | #define SCRIPT( s, S, d, h, H, ss )  h,
      |                                      ^
/home/svcg/source/OpenSpace/ext/ghoul/ext/freetype2/src/autofit/afscript.h:302:11: error: ‘HB_SCRIPT_HANIFI_ROHINGYA’ undeclared here (not in a function)
  302 |           HB_SCRIPT_HANIFI_ROHINGYA,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/svcg/source/OpenSpace/ext/ghoul/ext/freetype2/src/autofit/afshaper.c:89:38: note: in definition of macro ‘SCRIPT’
   89 | #define SCRIPT( s, S, d, h, H, ss )  h,
      |                                      ^
ext/ghoul/ext/freetype2/CMakeFiles/freetype.dir/build.make:81: recipe for target 'ext/ghoul/ext/freetype2/CMakeFiles/freetype.dir/src/autofit/autofit.c.o' failed
make[2]: *** [ext/ghoul/ext/freetype2/CMakeFiles/freetype.dir/src/autofit/autofit.c.o] Error 1
CMakeFiles/Makefile2:1802: recipe for target 'ext/ghoul/ext/freetype2/CMakeFiles/freetype.dir/all' failed
make[1]: *** [ext/ghoul/ext/freetype2/CMakeFiles/freetype.dir/all] Error 2
Makefile:170: recipe for target 'all' failed
make: *** [all] Error 2

```
<< Attach screenshots, if possible >>

**Comment by KingArthur10** [comment]
I received the same error last night.  Compiling on Ubuntu 18.04 using GCC-9.  Followed the instructions in the Linux compilation instructions, and I don't think I missed anything.

**Comment by KingArthur10** [comment]
After some investigation, it's the freetype ext library that's included in the project that's causing the issues.  The two languages that are erroring out were both added to the ISO standard in mid 2018, so they're not included in the Ubuntu 18.04 or older libraries.  I was able to push past this issue by just redirecting those languages to different ones in afscript.h.  Not pretty, not the correct way to go, but it got it to push past those errors and continue compiling.

**Comment by Venustiano** [comment]
Sound great!

Could you show the lines you changed?

Thanks

**Comment by alexanderbock** [comment]
Also, if it is something that would be worth placing in the repository; I'd be happy to have a PR for it that changes it for future Linux users
