### ISSUE TITLE
Add http proxy feature for download manager

### ISSUE THREAD

**Issue by emiax** [OpenSpace/OpenSpace#146]
This will allow users to download content even if they are behind a proxy.
GDAL (used in globe browsing) has experimental proxy support as of https://github.com/OpenSpace/OpenSpace/commit/5e2ea10bcd2ae0b4a26a4aa2992de4b8820c2da4

**Comment by alexanderbock** [comment]
wontfix

Suggested solution is to specify the proxy settings globally on the operating system instead
