### ISSUE TITLE
Profile Editor Key binding panel allows for multiple binds of same key

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1461]
We should detect which keys have already been bound for this profile (and potentially in the default keybindings) and not allow those to be selected again.

**Comment by alexanderbock** [comment]
There already should be a warning at runtime when trying to double-bind a key.   I'd not like in principle forbit the double binding as it makes some use cases possible (for example adding my own trails to the `H` key and still make `H` fade all trails.

Agree that the editor should already warn about it and display
