### ISSUE TITLE
Possiblity to control rendering properties of all exoplanet systems simultaneously

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1462]
It would be useful to for example change disc texture, opacity or hide all the uncertainty discs or habitable zones of all exoplanet systems in one command. 

A potential solution would be to expose lua functions that does this and add a section for the exoplanet GUI panel with such controls.

**Comment by alexanderbock** [comment]
Another option is to automatically add a tag to all exoplanet-created systems that can be used in such a UI.  Example: https://github.com/OpenSpace/OpenSpace/blob/master/data/assets/scene/solarsystem/planets/mars/mars.asset#L70
and
https://github.com/OpenSpace/OpenSpace/blob/master/data/profiles/default.profile#L43

**Comment by WeirdRubberDuck** [comment]
Additionally, it would be useful to be able to change the default values used for the exoplanet system rendering (like textures, opacities, etc), before the scene graph nodes are created. Perhaps as properties of the ExoplanetsModule, so they are accessible to the user?

**Comment by WeirdRubberDuck** [comment]
Closed in https://github.com/OpenSpace/OpenSpace/pull/2943
