### ISSUE TITLE
Shift/T to toggle shadows of Pluto and Charon only works on Pluto

### ISSUE THREAD

**Issue by estrelanova** [OpenSpace/OpenSpace#1463]
Shift/T to toggle shadows of Pluto and Charon only works on Pluto, the shadow of Charon remains visible.

I'm using 0.16.0 on a Windows 10 machine.

<< Attach screenshots, if possible >>

**Comment by alexanderbock** [comment]
Thanks!  I just fixed it in `master`.
If you want to hotfix it on your end:
1. Open the data/profile/newhorizons.profile in a text editor
2. Add the Charon changing code to line 197

Before:
```
      "script": "openspace.setPropertyValueSingle('Scene.PlutoShadow.Renderable.Enabled', not openspace.getPropertyValue('Scene.PlutoShadow.Renderable.Enabled'));"
```

After:
```
      "script": "openspace.setPropertyValueSingle('Scene.PlutoShadow.Renderable.Enabled', not openspace.getPropertyValue('Scene.PlutoShadow.Renderable.Enabled'));openspace.setPropertyValueSingle('Scene.CharonShadow.Renderable.Enabled', not openspace.getPropertyValue('Scene.CharonShadow.Renderable.Enabled'));"
```
