### ISSUE TITLE
Error Message in New Horizons Profile

### ISSUE THREAD

**Issue by estrelanova** [OpenSpace/OpenSpace#1464]
The keyboard shortcut 'A' to focus the camera on the New Horizons spacecraft provokes the following error message:

<< Attach screenshots, if possible >>
![Error Message New Horizons](https://user-images.githubusercontent.com/75349923/105572324-c47c8e80-5d56-11eb-8eac-3306e7f7aa7d.png)

**Comment by alexanderbock** [comment]
Thanks for the report;  it's fixed for the next release.
As a hot fix until then:
1. Open the data/profiles/newhorizons.profile in a text edit
2. Remove the \" from line 45

Before:
```
      "script": "\"openspace.setPropertyValue('NavigationHandler.OrbitalNavigator.Anchor', 'NewHorizons');openspace.setPropertyValue('NavigationHandler.OrbitalNavigator.Aim', '');openspace.setPropertyValue('NavigationHandler.OrbitalNavigator.RetargetAnchor', nil);"
```
After:
```
      "script": "openspace.setPropertyValue('NavigationHandler.OrbitalNavigator.Anchor', 'NewHorizons');openspace.setPropertyValue('NavigationHandler.OrbitalNavigator.Aim', '');openspace.setPropertyValue('NavigationHandler.OrbitalNavigator.RetargetAnchor', nil);"
```

**Comment by estrelanova** [comment]
Great, thanks!

Am So., 24. Jan. 2021 um 12:00 Uhr schrieb Alexander Bock <
notifications@github.com>:
