### ISSUE TITLE
Atmosphere culling activates when it should not.

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1465]
For example on earth, when getting a side view from space.

![image](https://user-images.githubusercontent.com/708535/105729964-c92e7780-5efb-11eb-8236-852510f1ebfb.png)

**Comment by micahnyc** [comment]
Attached recording shows issue if started in 1920x1080 (as it requires having the planet/atmosphere right on the edge of screen.
[atmosbug.zip](https://github.com/OpenSpace/OpenSpace/files/6053211/atmosbug.zip)

**Comment by alexanderbock** [comment]
Issue was only happening when the scale of the planet was != 1 in which case the atmosphere radius used to calculate whether it should be culled or not was wrong
