### ISSUE TITLE
Gui resolution bug for retina displays

### ISSUE THREAD

**Issue by kbladin** [OpenSpace/OpenSpace#147]
Most likely introduced in this commit:
https://github.com/OpenSpace/OpenSpace/commit/77db054959aa8c5920e391958f5948cfd8b226c3

The gui window gets clipped as in the image below

<img width="1440" alt="skarmavbild 2016-10-11 kl 18 23 54" src="https://cloud.githubusercontent.com/assets/4128312/19329649/3817ab20-90da-11e6-8e1e-cd44903ffd0c.png">

**Comment by alexanderbock** [comment]
Fixed in 317ecad9ac0b3e23cde6ae73c1c63e90c556dfe1

Reason: The SGCT window scaling factor was not used properly. Updating ImGUI to a newer version enabled this and now allows manual resizing of the framebuffer independently of the window size while keeping the same GUI size
