### ISSUE TITLE
Missing documentation of multiple RenderableGlobe properties

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1470]
For example here: https://github.com/OpenSpace/OpenSpace/blob/08e941d6d96d4f347f17eb4ae84c4882922b1057/modules/globebrowsing/src/renderableglobe.cpp#L117

The documentation should be added by someone who is familiar with the globebrowsing. 

(And yes, missing documentation is a bug to me) 😄

**Comment by alexanderbock** [comment]
:+1:  Agreed,  I think it should be considered a bug
