### ISSUE TITLE
Add a "sphere of closest interaction" in addition to the bounding sphere

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1475]
There are cases where we are in need of navigating inside the bounding sphere of an object, without reducing the size of the bounding sphere. 

For example, the orbit trails has a bounding sphere that covers the entire trail for culling reasons, but that prevents interaction when ending up inside it. This happens for example when focusing on "Earth Trail" from having Earth as focus. The trails could in this case have an interaction sphere with a radius of 0. 

So, the suggestion is: 
Bounding sphere - related to visibility
Interaction / collision sphere - related to interaction

**Comment by micahnyc** [comment]
Like a hitbox in a game. 

We should come up with a better scenario/reason to do this work because targeting trails essentially targets the parent of the trail. So all our solar system trails it would be the same as targeting the sun. 

For trails, something like you suggest in #1232 which allows for movement along the trail would be nice (something we have with spacecraft)

**Comment by alexanderbock** [comment]
Problem is that it's not unambiguous what the parent might be for the user..  the trails of the planets have the solar system barycenter as the parent, but the average user would probably think that the Sun is the parent.  I'd rather argue for being able to specify in the asset file that a scenegraphnode is not camera-targetable and we take it out of the focus list?

**Comment by alexanderbock** [comment]
And yea;  right now we use the same distance for the hitbox and the geometric extent.  That has bitten us a few times already (see Apollo capsule or ISS module).  Would be good to get around the hacky way of solving this by introducing a hit-radius and a bounding-radius

**Comment by WeirdRubberDuck** [comment]
Being able to specify that an asset cannot be used as focus makes a lot of sense to me. I like that idea. It would also bring benefits such as "decluttering" the focus list and UI a bit. And, as Micah is pointing out, focusing a trail essentially means focusing its parent, which doesn't make that much sense..

**Comment by micahnyc** [comment]
We have discussed once or twice being able to focus on the head of the trail (as we usual do by creating a scenegraph node with the same translation)  just today I thought it would also be nice to focus on the tail of a trail as well. So perhaps that is something that could be built into RenderableTrailTrajectory? 

The use case I was thinking of was a spacecraft launch. Perhaps it would be interesting to pin on the launch location, and then watch the earth and the spacecraft diverge.

**Comment by alexanderbock** [comment]
I would not want to move that functionality into the trail class;  in that usecase we should rather have an empty scenegraph node that is the launch location, since it is a pretty specific use case

**Comment by alexanderbock** [comment]
Closes 2aa540a112c8af1164000e16e88b640021c7fe99
