### ISSUE TITLE
No menus in Openspace after ubuntu/linux compile?

### ISSUE THREAD

**Issue by DevinBayly** [OpenSpace/OpenSpace#1479]
I am experiencing a similar issue to #920 , but it's not clear how to resolve my problem based on that issue. 
I compiled OpenSpace project to use inside an ubuntu singularity container, and have managed to launch it graphically on my local HPC using turbovnc, but for some reason, when I hit the 'tab' key I get these 2 errors

```
property_getValue (Error)	[string "openspace.setPropertyValue('Modules.CefWebGui..."]:1: : Property with URI 'Modules.CefWebGui.Visible' was not found

property_setValue (Error)	[string "openspace.setPropertyValue('Modules.CefWebGui..."]:1: : No property matched the requested URI 'Modules.CefWebGui.Visible'
```
In the singularity build file you can see the dependencies I installed, was I missing something by any chance?

```
Bootstrap: docker
From: ubuntu:20.04

%post
	export DEBIAN_FRONTEND="noninteractive"
	apt-get update
	apt-get install -y build-essential software-properties-common
	add-apt-repository ppa:ubuntu-toolchain-r/test
	apt-get update
	apt-get install -y gcc-9 g++-9
	update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
	update-alternatives --config gcc
	apt-get install -y \
	qt5-default \
	gcc-9 g++-9 cmake \
	glew-utils freeglut3-dev libsoil1 \
	libxrandr-dev libxinerama-dev xorg-dev libcurl4-openssl-dev libgdal-dev libxcursor-dev \
	git
	openSpaceHome="/opt/source/OpenSpace"

	git clone --recursive https://github.com/OpenSpace/OpenSpace "$openSpaceHome"

	mkdir -p "$openSpaceHome/build"
	cd "$openSpaceHome/build" || exit

	cmake \
	-DCMAKE_BUILD_TYPE:STRING="Release" \
	-DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-9 \
	-DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-9 \
	-DCMAKE_CXX_FLAGS:STRING="-DGLM_ENABLE_EXPERIMENTAL" \
	-DOpenGL_GL_PREFERENCE:STRING=GLVND "$openSpaceHome"

	make
	chmod a+rwx -R /opt/source/
%environment
```

If there isn't a clear answer perhaps someone could share at least how to do navigation via the command line? I think that would take care of my needs because most of the other aspects of the program are working.

thanks!

**Comment by GPayne** [comment]
Thanks for sharing your Dockerfile, glad you could get the build working that way! No, you weren't missing anything, CEF does not work in linux. The tab key usually toggles the visibility of the menu overlay (which runs on CEF).

However, you have a couple of workaround options on linux:
1. You can bring up the menu in a separate browser window with the URL http://localhost:4680 and you will see & use the menu in the browser exactly as it would be superimposed in the OpenSpace window.
2. Pressing F1 in the OpenSpace window brings up a legacy menu which has most of the functionality of the web-based menu.

**Comment by DevinBayly** [comment]
That's a great workaround, thanks so much! 

I'm still curious about the command line and scripting options for controlling navigation, but I'll try to find more about that in the compiled docs.

**Comment by micahnyc** [comment]
Hi @DevinBayly, we do have some scripting commands to control navigation, however depending on what you want to do, you may have more luck sending navigation commands over our websocket interface. 

For the scripting we have: addGlobalRoll, addGlobalRotation and addTruckMovement. 

For the websocket you send a json packet with the inputstate: `{
      type: "inputState",
      inputState: {values: {
        "zoomIn": 0.00,
        "orbitX": 0.0,
        "orbitY": 0.0,
        "panX": 0.0,
        "panY": 0.0,
        "localRollX": 0.0,
      }`
as exampled here: https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/blob/da6b14e4f2f40a8e6340de3251839ff09970b005/src/components/BottomBar/FlightControlPanel.jsx#L77

**Comment by DevinBayly** [comment]
@micahnyc Excellent! I'll look into that as well. Thank so much for the rapid replies!

**Comment by alexanderbock** [comment]
@GPayne  This can be closed now, right?
