### ISSUE TITLE
No useful error shown if OpenGL version isn't supported

### ISSUE THREAD

**Issue by EricMyers47** [OpenSpace/OpenSpace#148]
OpenSpace requires OpenGL 4.3 or greater.  If a user runs the code with an incompatible version the code throws a cryptic error.  It should print something nice and helpful.  Example:

> File:       /home/brysgo/workspace/OpenSpace/apps/OpenSpace/main.cpp, line 157
>    Function:   int main(int, char**)
>    Assertion:  versionMapping.find(glVersion) != versionMapping.end()    Unknown OpenGL version. Missing statement in version mapping map

At this point it would be useful to print glVersion and a reminder of the requirement.

**Comment by nusic** [comment]
Agreed. Although, since Openspace has a modular approach, I think it makes more sense to specify the OpenGL requirements on a per module basis. My MacBook Pro supports OpenGL 4.1, and I'm running Openspace Core and the globebrowsing module, and that works fine :)

**Comment by EricMyers47** [comment]
You make a good point.   The example above came from someone on Linux with OpenGL 3.10, so nothing would have worked.  So that would have helped to say so in English (or someday Swedish?).    That would just be a test of the overall minimum supported version.

Per module requirements would be good if you get an understandable error message if the requirement can't be met, AND if the module does not load but the app can continue on, and tell them why it cannot load.

**Comment by alexanderbock** [comment]
Fixed in c880ee421a883e3ad0165fef713eac32704d278d

Each OpenSpaceModule has the ability to report it's minimum OpenGL version (default 3.3) and the OpenSpaceEngine checks the supported version against the highest requested one
