### ISSUE TITLE
Mismatch between exoplanet system and star positions

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1492]
See example below on Proxima Centauri

![image](https://user-images.githubusercontent.com/8808894/106901528-2eeae280-66f8-11eb-8a4b-c207ce237c9e.png)

The exoplanets visualization uses the position from `sync/http/digitaluniverse_exoplanets_speck` when possible. However, these are seemingly not matched with the position of the rendered stars

**Comment by jccosta** [comment]
I may be saying something wrong here but, if memory serves me well (not always the case), the last data we get from Brian didn't include new data for the stars. In the picture, we see this difference in dataset calculations (the exoplanets' data is more recent than the stars' data).

**Comment by WeirdRubberDuck** [comment]
That is probably true. When we talked to Brian in October he mentioned that he was working on updating the DU datasets. But thought it should be an issue anyhow, so that we can close it when it is fixed :)

**Comment by micahnyc** [comment]
I have a meeting with Brian on Wednesday and will ask him what his thoughts are. 
In partiview they line up, but that does contain an updated star.speck file.

![image](https://user-images.githubusercontent.com/708535/106939751-ae73b400-66ee-11eb-8a93-7928cc6fad74.png)

**Comment by hedbergj** [comment]
I've been confused about this sort of thing for a while. Not sure I can resolve it, but there's something going on. If you convert the xyz from various speck files for Proxima Cen you get many different RA/DEC values:

i.e from the duExoplanetSpeck:
14h29m49.0719s -62d40m49.793s

from the duStarsSpeck:
14h29m48.2492s -62d40m58.5165s

which don't agree with other sources for where this star is:
i.e. [SIMBAD](http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Proxima+Centauri&NbIdent=1&Radius=2&Radius.unit=arcmin&submit=submit+id
):

14h29m42.9451234609s -62d40h46.170818907s

or [WWT](http://worldwidetelescope.org/webclient/#/place=18.223&ra=14.49530&dec=-62.67940&fov=0.16986)

If you pull the brightstars catalog from SIMBAD, and compare to the OpenSpace DU Stars, there are loads of discrepancies. I guess I'd be interested to know a bit more about how all these speck files are prepared. 

![image001](https://user-images.githubusercontent.com/7926907/108863130-e029bd80-75be-11eb-9dd7-e500a14a9bc2.jpg)

**Comment by GPayne** [comment]
Did any new information or ideas come from the meeting with Brian last month (mentioned above)?

**Comment by micahnyc** [comment]
Still need to update the DU stars. We are working around some issues with importing new GaiaStars, and the ReadFitsTask vs ReadSpeckTask.

**Comment by alexanderbock** [comment]
@WeirdRubberDuck   Updates for this?

**Comment by WeirdRubberDuck** [comment]
Did some checking on my end but also talked to Brian.  The datasets should be aligned now (with the DU Update of 0.20.1), so I consider this closed. 

The exoplanet ring positions should be correlated with the stars dataset, for the stars that appear in the star data file. 

And some interesting point on the relationship between the stars in the exoplanet star dataset VS the
