### ISSUE TITLE
Profile editor: some text text doesn't scale  for 4k screens.

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1493]
As reported by Brian Abbot.

![thumbnail_Screenshot (2)](https://user-images.githubusercontent.com/708535/106942131-cef13d80-66f1-11eb-9d3c-ae7d6a131c50.png)

**Comment by alexanderbock** [comment]
I'm thinking that we define some things in point units and some in pixel units

**Comment by alexanderbock** [comment]
I think it might be fixed now?  At least I don't see the issue here:

![image](https://user-images.githubusercontent.com/4921724/149912461-3a5ffbcb-85f9-49a9-a1b2-bf6c67a77b7a.png)

**Comment by micahnyc** [comment]
tested on 4k screen. made a fix for sgct editor
