### ISSUE TITLE
Ability to see full Pluto trail

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1495]
Current Pluto trail is very short. There is much desire to be able to see more of the Pluto's trail. We have discussed offering a Kepleraian version of the trail as well, but I found not mention of that in other issues.

Here is some info in a recent email with partners: 

>  Pluto in OpenSpace was mostly set-up just for the New Horizons flyby, so near as I can tell the trajectory is by default drawn quite short because of that encounter, and then doesn't seem to have been updated for general solar system use since then. Pluto's position is also determined by a SPICE kernel, which contains the geometric position and motion of Pluto as solved by NASA, however, because Pluto has a very long period, the SPICE kernel driving Pluto which has high precision for the New Horizons encounter isn't very large--only about a century or so. No matter what, OpenSpace currently won't draw a complete orbit for Pluto, but you can still make it longer.
> 
> What can be done?
> 
> In your OpenSpace install go to data\assets\scene\solarsystem\dwarf_planets\pluto and open trail.asset in a text editor (I usually use notepad++ on a PC and textwrangler on mac) (not pluto_trail.asset, which is actually Pluto's orbit around the Barycenter of the Pluto System) on line 20: 
> 
> Period = 365.25
> 
> This is telling OpenSpace how long, in days, to draw the trail. So it's only one year by default, but because there's not enough data you can't put in the true 90,560 days of Pluto's period.
> 
> Through trial and error I found about 50,000 days is the best compromise for OpenSpace so you can change line 20 to:
> 
>  Period = 50000,
> 
> And attached is a file where I've done that already. You could play around with other values, but if you make it too long as soon as OpenSpace no longer has information for Pluto's position it will dump the trail into the Sun, like so:
> 
> OpenSpace_000000.png
> 
> The finally, the way I think it should work: and hopefully we'll see some motion to would be a way to allow OpenSpace to pull from two datasources, using the high precision SPICE kernel for the century or so around our time, and then reverting to a Keplerian set of orbital elements to define the shape of the ellipse at times when the kernel isn't active, which would allow complete, multi-century depictions of Pluto. So maybe one day in the next few years of the grant! But for now this is what we can do.
![download](https://user-images.githubusercontent.com/708535/107130568-c2f5af00-689c-11eb-8d84-87332e9de772.png)

**Comment by micahnyc** [comment]
Here is an code from an asset created by a student. This works, but it's not clear to me why we have a rotation matrix attached to the trail, OR where the values from the matrix came from. Perhaps J2000 related as the data seems to come from here: https://nssdc.gsfc.nasa.gov/planetary/factsheet/plutofact.html under Pluto Mean Orbital Elements (J2000)


`-- kepler translation example (Pluto)
local assetHelper = asset.require('util/asset_helper')
local sunTransforms = asset.require('scene/solarsystem/sun/transforms') -- change/add as necessary

local RotationMatrix = {
    -0.05487554,  0.4941095, -0.8676661   ,
    -0.9938214 , -0.1109906, -0.0003515167,
    -0.09647644,  0.8622859,  0.4971472   ,
}

local orbitalElements = {
    Type = "KeplerTranslation",
    Eccentricity = 0.24880766,       -- e      | How circular the trail is on a scale from 0 (perfectly circular) to 1 (parabola)
    SemiMajorAxis = 5906376272.4364, -- a      | Input in km (convert au to km by AU * 149600000) 
    Inclination = 17.14175,          -- i(ncl) | Input in degrees
    AscendingNode = 110.30347,       -- node   | Longitude of Ascending Node (Ω); input in degrees
    ArgumentOfPeriapsis = 113.7483,  -- peri   | also ω; Longitude of Perihelion/Periapsis-Longitude of Ascending Node
    MeanAnomaly = 14.86832413,       -- M      | gives reference in degrees for location of body on orbit for given point in time
    Epoch = "2000 01 01 00:00:00",   -- J2000; keep date same
    Period = 7821583948.8,           -- period | Orbital period in seconds; Period = [(SemiMajorAxis^3)^0.5] AU * 3.154e7 s/AU
}


local PlutoKeplerTrail = {
    Identifier = "PlutoKeplerTrail",
    Parent = sunTransforms.SolarSystemBarycenter.Identifier,
    Transform = {
        Rotation = {
            Type = "StaticRotation",
            Rotation = RotationMatrix
        }
    },
    Renderable = {
        Type = "RenderableTrailOrbit",
        Translation = orbitalElements,
        Color = { 0.00, 0.62, 0.79 },
        Period = 90527.592, -- [(SemiMajorAxis^3)^0.5] AU * 365 days/AU
        Resolution = 86000
    },
    GUI = {
        Name = "Pluto Trail (Kepler)",
        Path = "/Solar System/Dwarf Planets/Pluto"
    }
}

**Comment by micahnyc** [comment]
Upon further investigation, the rotation matrix is the same as listed in our data/assets/digitaluniverse/grids.asset for eclipticRotationMatrix .  I'm thinking these matrices should be generalized into an asset file that can be used by other assets as we have for things like the sun transforms.

(We could also used spice transforms for this however utilizing the rotation matrix allows for future potential in the 'non-spice' version)

**Comment by alexanderbock** [comment]
iirc, the matrix is the rotation matrix to go from galactic coordinates to the J2000 coordinate system

**Comment by micahnyc** [comment]
closed with: https://github.com/OpenSpace/OpenSpace/commit/e89a6c257df1f2536bff86698a57c082beb78163
