### ISSUE TITLE
Uninformative fatal error on SpecificationError for Modules

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1502]
When defining properties for a module and the configuration dictionary in `openspace.cfg` does not match the specification, an unhandled exception occurs in `main.cpp` and an error message is displayed. However, the error does not include any information about what was wrong in the specification. 

Since we does not have any documentation for the module properties outside of OpenSpace itself, this is a problem. The error message should be more informative about what went wrong 

![image](https://user-images.githubusercontent.com/8808894/107615853-360c7600-6c4d-11eb-9113-c9f37b28bb55.png)

**Comment by WeirdRubberDuck** [comment]
Probable origin of the error: https://github.com/OpenSpace/OpenSpace/blob/9eb9095c127885db7fe3922502d7db52cdf042b5/src/engine/moduleengine.cpp#L61

**Comment by alexanderbock** [comment]
Should be better since dfa223abef9da90570e2d27a31d27cf8d3a439e3 ?

**Comment by WeirdRubberDuck** [comment]
Hm, no. The error still looks exactly the same after that commit 

![image](https://user-images.githubusercontent.com/8808894/107920912-f952be80-6f6d-11eb-9630-b07357cc2b31.png)

**Comment by alexanderbock** [comment]
![image](https://user-images.githubusercontent.com/4921724/107933899-a550d580-6f7f-11eb-9674-0293b930deff.png)
