### ISSUE TITLE
Problem with JSON format in .ostest files of feature/visual-testing-try2 branch

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#1507]
In branch _feature/visual-testing-try2_ in tests/visual/*.ostest files, there is a problem with the JSON format of the files.
Changing `'` characters to `"` and also adding `\` in front of the `"` characters contained within a string fixes the problem for me.
I am testing only linux so I don't want to make these changes and potentially cause problems with the windows version.
However, I imagine the windows JSON parser used would be OK with these changes.

**Comment by micahnyc** [comment]
resolved by using " instead of ' for fully valid json.
