### ISSUE TITLE
Crashes when opening

### ISSUE THREAD

**Issue by estrelanova** [OpenSpace/OpenSpace#1512]
I have installed OpenSpace 0.16.0 for quite a while and it was working fine. But now I can't open it anymore. When I try, nothing happens for a few minutes and finally, the attached error message appears. 
![Error Message OpenSpace](https://user-images.githubusercontent.com/75349923/109381392-884ec780-78da-11eb-908a-84d53de61853.png)

Thank you all for any help.

Have a nice day!

**Comment by estrelanova** [comment]
I know what it was: I changed the til cache size and OpenSpace didn't like it. I changed it back and it works again. Thanks to all.

**Comment by alexanderbock** [comment]
The TileCacheSize directly goes onto your GPU, so the `GL_OUT_OF_MEMORY` error that you get says that OpenSpace tried to upload more data to the GPU than it has memory
