### ISSUE TITLE
Fresh install crashes on first launch

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1514]
When launching OpenSpace for the first time, it often will crash. All subsequent launches work fine.

**Comment by GPayne** [comment]
Are there any associated error messages with the crash?

**Comment by WeirdRubberDuck** [comment]
Tried doing a few fresh installs on some different Windows computers and have not been able to reproduce the crash. For one of the machines I did however have to install the Microsoft Visual C++ Redistributable ([as described on the download page under "Windows users"](https://www.openspaceproject.com/version0161)) to get it to work, and also bypass Windows Defender

**Comment by alexanderbock** [comment]
Can no longer reproduce
