### ISSUE TITLE
Globebrowsing loses level of detail

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1515]
Often when enabling multiple layers, the level of detail drops down very low. 

![image](https://user-images.githubusercontent.com/708535/109526280-62fbbe00-7a80-11eb-995e-ec22bb6a77ab.png)

**Comment by WeirdRubberDuck** [comment]
Related to #1292?

**Comment by alexanderbock** [comment]
Not just related, but duplicate;  closing this in favor of #1292
