### ISSUE TITLE
SpaceMouse3D support/asset

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1518]
Support for the SpaceMouse3D (https://3dconnexion.com/uk/spacemouse/) could provide an improved flying experience. 

As there has been interest in the support slack, some user created resources are  attached here including a diagram of the axis mapping and a first pass at an .asset file. With this note about the axis mapping in the asset file: _"here is another attempt that simply attempts to re-map the xbox gestures -- I can't get the spacemouse axis 0 and 4 to work. I suspect that the joystick implementation isn't as generic as I was hoping for. like axis 2 on the spacemouse seems to have no equivalent."_ 

![20210226_030414556_iOS](https://user-images.githubusercontent.com/708535/109871839-9d5c8b00-7c39-11eb-8def-b6efb1fb02e4.jpg)

[SpaceMouse3D_joystick.asset.txt](https://github.com/OpenSpace/OpenSpace/files/6079146/SpaceMouse3D_joystick.asset.txt)

**Comment by RobWickham** [comment]
I just wanted to add that there is probably a need to test several axis mappings before finding the optimal set for the SpaceMouse. Enabling the axis that are new/unique is a great start, and possibly a sample asset file that demonstrates them would be ideal. It's great that using the native gui allows all of it's axis movement to appear recognized. I'm unsure if using the XBox asset as a template is best or not given how the semantics are so different, but if that's the easiest way forward no complaints here.

**Comment by RobWickham** [comment]
any thoughts about timing or approach for this improvement? If a few of the framework changes go in, I'm happy to invest in the configuration side of things or some initial testing.

**Comment by alexanderbock** [comment]
@RobWickham   The integration is now in the `master` branch and will be in the next release, too.  Test it out when you can and let us know how it works for you.  You can rebind the controls in the asset file, too:
https://github.com/OpenSpace/OpenSpace/blob/master/data/assets/util/default_joystick.asset#L66

**Comment by RobWickham** [comment]
@alexanderbock, is it possible for me to obtain the build prior to the next public release in order to do testing? I'm not savvy enough to perform my own local build I suspect, but with guidance I'm willing to try.

**Comment by alexanderbock** [comment]
Sure! We just create a release candidate:
Download without the data: https://data.openspaceproject.com/release/0.17.-1/OpenSpace-0.17.-1-minimal.zip
Download with data included: https://data.openspaceproject.com/release/0.17.-1/OpenSpace-0.17.-1.zip

We don't have a user-friendly way to change the joystick that is being used.  So after downloading it:
 - Open the `data/asset/util/default_joystick.asset` and in line 138 change `local controller = XBoxController;` to `local controller = SpaceMouse;`
 - When starting OpenSpace under Settings / NavigationHandler uncheck the "Disable all joystick inputs"
 - To fine tune the sensitivity, you can do that under "NavigationHandler / OrbitalNavigator/Joystick Sensitivity"

**Comment by RobWickham** [comment]
Hi Alexander,
I've loaded the minimal using OPENSPACE_SYNC for data and it appears the new SpaceMouse functionality mostly works - what's unexpected is that once I let go of the "stick", all the viewpoint changes somehow return to where they were before I touched the "stick". I expected them to actually modify the view like the mouse actions can. Also, the SpaceMouse buttons don't appear to toggle anything.

Are these limitations perhaps another setting in the asset file for this new input device that can be replicated from the game console controller configuration?

**Comment by Roxeena** [comment]
@RobWickham It sounds like your SpaceMouse doesn’t behave the same way as ours do when it is let go, which version do you have? Something you could try for the axis in the asset file is on the lines 209 to 214 switch the last true to false so:
<pre>openspace.navigation.bindJoystickAxis(controller.Push[1], "Orbit X", false, false, <b>true</b>, 40.0);</pre>
becomes:
<pre>openspace.navigation.bindJoystickAxis(controller.Push[1], "Orbit X", false, false, <b>false</b>, 40.0);</pre>
And do the same for all the lines 209 to 214.

The buttons are supposed to change the roll mode. By default the roll mode is local, meaning that you roll around the forward axis of the camera. The right button switches the roll mode to global, meaning that you will roll around the axis from the camera to the focus instead. The left button switches back to local roll mode again.

**Comment by RobWickham** [comment]
Changing those values to false did the trick! I also had to change the sensitivity to 1. It could use a value even smaller than 1 ideally. The sensitivity is still a bit high, but I'm getting used to the value of 1.

Also, the buttons don't work even if I remove the "perma" from the beginning of those to Bind statements. But, the tilt and push gestures are basically local and global already. Perhaps the system already understands that and the buttons have no meaning?

This build does "pause" quite often, not sure if it's my system or the nature of the build. I'll keep testing though. Using this mouse with the axis you have added is really nice!

**Comment by alexanderbock** [comment]
Could you elaborate what you mean by "pause"?  As that sounds like an unintended bug

**Comment by RobWickham** [comment]
The software appears to hang for a bit over a second every minute or so. I can capture a video of it if that’s helpful.

________________________________

**Comment by RobWickham** [comment]
I've done a test now using my laptop, and the pausing does not happen so I must be having an unusual issue on my desktop computer. Even then, I can't find a pattern or supporting logging in the console window. I launch with the defaults. I will say that the frame rate is higher without the SpaceMouse - expected?

For some reason on my laptop, I must disable atmosphere in order to see the planets. It's as if the atmosphere layer is black, or my laptop does not have the ability to provide the atmosphere capability. On my desktop, it works as expected.

**Comment by alexanderbock** [comment]
Mh.. I haven't seen the framerate issue with the spacemouse on my end.    

1. On your desktop machine, can you go into the `openspace.cfg` and around line 160 change the `Enabled = true` to `Enabled = false` inside the `WebBrowser list and see if the stuttering still persists?
![image](https://user-images.githubusercontent.com/4921724/121345538-4398ea80-c925-11eb-9a23-0ce87261f23f.png)

2. That is odd indeed.  What graphics card is your laptop using?  If no GPU, which CPU is it?   Also could you post a picture here?  If you press F12 while OpenSpace is running, you will find a folder with the startup time in your user/screenshots folder

**Comment by RobWickham** [comment]
Using my desktop PC on build 17, I'm seeing about an 80 fps frame rate. Toggling the disable joystick input does not actually seem to impact that. It could have been the proximity to Earth however. I seem to consistently have faster rates the farther away from objects I am. On build 16, I'm seeing a 140 fps rate when far from Earth, and it drops the closer I get. This seems "normal" to me though, but the 80 fps on 17 vs. the 140 fps on 16 is a surprise. My laptop fps is about 40 on build 17, and it goes down to about 26 as I get close to Earth. On build 16, the fps is generally the same as build 17. The spec of my desktop is: AMD A6-5400K APU 4.30 GHz 16gb RAM. NVIDIA GeForce GTX 950.

What's odd now that I'm switching between 16 and 17 more - the joystick sensitivity on 17 requires me to use a value of 1. Using a value of 1 on build 16 is just so sluggish it's not really usable. It seems there's been some change that impacts the way joystick sensitivity works in build 17 making it very, very sensitive vs. build 16.

Regarding the freezing, that change to the cfg file fixes it. I must use the native GUI under that setting, but the issue does go away when not using that browser control for the GUI. The freeze is about 5 seconds, if that helps. I have made Firefox my primary browser. I could make another (Chrome?) browser my default if that is something interesting.

My laptop is a Lenovo X1 Carbon. Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz, 16gb RAM. The GPU is Intel HD Graphics 520. F12 image attached, before and after toggling the atmosphere, using both builds.

**Comment by Roxeena** [comment]
Hello @RobWickham! I just wanted to let you know that we have taken your feedback into consideration for the 0.17.0 release and we now have two different SpaceMouse versions where the `space-mouse-not-sticky.asset` version would probably suit your SpaceMouse better. For the release you would only need to add that asset to your profile with the profile editor in the launcher and then your SpaceMouse should work.

**Comment by RobWickham** [comment]
Were the data and the images helpful for the topics below?

From: Rob Wickham
Sent: Wednesday, June 9, 2021 11:44 AM
To: OpenSpace/OpenSpace ***@***.***>; OpenSpace/OpenSpace ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OpenSpace/OpenSpace] SpaceMouse3D support/asset (#1518)

Using my desktop PC on build 17, I'm seeing about an 80 fps frame rate. Toggling the disable joystick input does not actually seem to impact that. It could have been the proximity to Earth however. I seem to consistently have faster rates the farther away from objects I am. On build 16, I'm seeing a 140 fps rate when far from Earth, and it drops the closer I get. This seems "normal" to me though, but the 80 fps on 17 vs. the 140 fps on 16 is a surprise. My laptop fps is about 40 on build 17, and it goes down to about 26 as I get close to Earth. On build 16, the fps is generally the same as build 17. The spec of my desktop is: AMD A6-5400K APU 4.30 GHz 16gb RAM. NVIDIA GeForce GTX 950.

What's odd now that I'm switching between 16 and 17 more - the joystick sensitivity on 17 requires me to use a value of 1. Using a value of 1 on build 16 is just so sluggish it's not really usable. It seems there's been some change that impacts the way joystick sensitivity works in build 17 making it very, very sensitive vs. build 16.

Regarding the freezing, that change to the cfg file fixes it. I must use the native GUI under that setting, but the issue does go away when not using that browser control for the GUI. The freeze is about 5 seconds, if that helps. I have made Firefox my primary browser. I could make another (Chrome?) browser my default if that is something interesting.

My laptop is a Lenovo X1 Carbon. Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz, 16gb RAM. The GPU is Intel HD Graphics 520. F12 image attached, before and after toggling the atmosphere, using both builds.
