### ISSUE TITLE
GlobeRotation

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1527]
Similar to the GlobeTranslation, we could have a GlobeRotation, that, given a lat/lon, rotates the node to sit flat on the planet's surface. 

Presumably an implementation of this: https://en.wikipedia.org/wiki/Local_tangent_plane_coordinates

**Comment by hedbergj** [comment]
Lua version here: https://github.com/ccnyplanetarium/addons-examples/tree/master/orient-object-globe

![OpenSpace_000003](https://user-images.githubusercontent.com/7926907/110627436-f9f70300-816f-11eb-93ff-949738caade5.png)
