### ISSUE TITLE
Git-Install on Apple M1 BigSur: Qt5 not found

### ISSUE THREAD

**Issue by Sasatari** [OpenSpace/OpenSpace#1530]
Following instructions on http://wiki.openspaceproject.com/docs/developers/compiling/macos, I come the point where I do:

ccmake -G Xcode ..

I´ll get this:

```
 CMake Error at apps/OpenSpace/ext/launcher/CMakeLists.txt:65 (find_package):
   By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
   asked CMake to find a package configuration file provided by "Qt5", but
   CMake did not find one.

   Could not find a package configuration file provided by "Qt5" with any of
   the following names:

     Qt5Config.cmake
     qt5-config.cmake

   Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
   to a directory containing one of the above files.  If "Qt5" provides a
   separate development package or SDK, be sure it has been installed.

 Configuring incomplete, errors occurred!
```

CCmake outputs "Qt5_DIR Qt5_DIR-NOTFOUND"

I´ve installed Qt5 with homebrew, and also downloaded it from their website. But also entering the qt5-path doesn´t help. I´ve tried:

/opt/homebrew/Cellar/qt@5
/opt/homebrew/Cellar/qt@5/5.15.2

But none of those work. I´m a bit experienced on the command line, but not that much and especially absolutely don´t know Qt5, so I´m stuck here. How to proceed?

**Comment by hedbergj** [comment]
I did get it compiled (just on regular intel Mac) by adding the specific dir to the CMakeLists.txt (~ ln 165):
```
# Qt
# Unfortunately, we have to set this value manually; sigh
# In the future, if the Qt version is updated, just add to this variable ---abock
if (APPLE)
  set(CMAKE_PREFIX_PATH
    "~/Qt/5.6/clang_64/lib/cmake"
    "~/Qt/5.7/clang_64/lib/cmake"
    "~/Qt/5.8/clang_64/lib/cmake"
    "~/Qt/5.9/clang_64/lib/cmake"
    "~/Qt/5.10/clang_64/lib/cmake"
    "~/Qt/5.11/clang_64/lib/cmake"
    "~/Qt/5.12/clang_64/lib/cmake"
    "~/Qt/5.15.2/clang_64/lib/cmake"
  )
endif ()
```
(Though I didn't install qt via brew, but with the regular installer.)

**Comment by Sasatari** [comment]
Thank you, with that I could generate the xcodeproject. It builds, but the app doesn´t show anywhere. I think, now I´m having an XCode issue. No warnings, all fine, but no app.

**Comment by hedbergj** [comment]
hmm - You're doing ALLBUILD? At this point though I'd suggest you check out the OS [slack](https://www.openspaceproject.com/contact) (if you're not already on there already). I know there's at least one other person who got it running on M1. (there's a mac os channel that has some discussion already)

**Comment by Sasatari** [comment]
Thanks, don´t want slack.
Actually XCode was misconfigured and took me a while to correct it, because I´m not very familiar with it.

It now compiles with many warnings and one error:

> Lexical or Preprocessor Issue Group
> /Users/saschakriegel/OpenSpace/ext/ghoul/src/io/model/modelreaderassimp.cpp:38:10: 'assimp/cimport.h' file not found

**Comment by alexanderbock** [comment]
@Roxeena   Do you know what might cause this?  Is it an assimp specific file?

@Sasatari   Maybe it could be related to the AssImp version installed on your machine.  In your CMake, it should mention whether you are using the system assimp or the local assimp version:
![image](https://user-images.githubusercontent.com/4921724/111137984-b5a8a000-857f-11eb-8cd6-2c6203c539eb.png)

`Assimp_DIR` = `Assimp_DIR-NOTFOUND`  means that OpenSpace is using the AssImp version that we provide locally
`Assimp_DIR` = <some path on your system> would mean that it's using the system wide installation.

Imho, we should stop looking for the system-wide installation anyway since it gives us more trouble than it's worth. 

*If* you are using your system assimp, the version that we need might be different from the version that you have.  In that case, I'd suggest to comment out the searching in the CMakeLists file (https://github.com/OpenSpace/Ghoul/blob/master/CMakeLists.txt#L170) and see if it then works.

**Comment by Roxeena** [comment]
> @Roxeena Do you know what might cause this? Is it an assimp specific file?

Yes it is an assimp specific file that is included in modelreaderassimp.cpp. Assimp changed the name of that file in their github on Feb 3, 2012 and the commit is labeled as a breaking change [here](https://github.com/assimp/assimp/commit/6fa251c2f2e7a142bb861227dce0c26362927fbc#diff-add7812d1f7335b84a9316b0e3d923a1fb3e6a55e36c340bc61641663577da74). So if an older version is used then it will likely not work.

**Comment by Sasatari** [comment]
Getting closer:

This is a new MBP (1 week old) and the only things I´ve installed so far were Xcode, homebrew and wine64 (gcenx). Looks like homebrew installed assimp, too, and cmake set the assimp-Dir to:

Assimp_DIR                       /opt/homebrew/lib/cmake/assimp-5.0                                                   

I´ve found two assimp-Dirs in OpenSpace:

OpenSpace/ext/ghoul/include/ghoul/assimp
OpenSpace/ext/ghoul/ext/assimp/include/assimp

So I´ve set the path in CMake to the first one. Then hit "c" - no more errors. Hit "g" - works, too.

Open xcode-project and figured out, that by default the XCode BaseSDK was is not found, set it to "macOS", no more error here.

Changed the assimp-paths in modulereaderassimp.cpp to <ghoul/assimp/*.h> - looks good.
After that, in mesh.h, aabb.h, anim.h, Importer.hpp and cimport.h I could replace the paths with the filenames directly. - looks good.

But now I´m left with an "Invalid preprocessing directive" in config.h:

#cmakedefine ASSIMP_DOUBLE_PRECISION 1

What to do here now?

**Comment by Sasatari** [comment]
I´m not only not knowing what I´m doing, but also impatient, so I´ve comented out line 60 in config.h:

59 #pragma once
60 //#ifndef AI_CONFIG_H_INC
61 #define AI_CONFIG_H_INC

and added line 1016 (before the cmakedefine above):

#if(!defined AI_CONFIG_H_INC)

Xcode was not complaining about this anymore, but now the build fails at "GhoulTest":

ld: library not found for -lassimp.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Sasatari** [comment]
Any ideas here? Still couldn´t compile it. :(

**Comment by Sasatari** [comment]
Still no Open Space for me. :(

**Comment by alexanderbock** [comment]
I'm still looking into it.  The underlying issue is a confusion between the built-in assimp and the system-provided assimp.

**Comment by alexanderbock** [comment]
@micahnyc  fixed it :)
