### ISSUE TITLE
Venus cloud layer

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1534]
We should have a cloud layer for venus. We dont

**Comment by alexanderbock** [comment]
Do we have a data source that we can use?

**Comment by micahnyc** [comment]
https://bjj.mmedia.is/data/venus/venus.jpg from here: https://bjj.mmedia.is/data/venus/venus.html approved by @carteremmart  ....although I'm thinking to hold off adding more image layers to globes until we address https://github.com/OpenSpace/OpenSpace/issues/1207  (even though this one doesn't really apply as the author mentions "The longitude range is 0-360 degrees but since the clouds are constantly changing the 0° longitude has no specific location in the map." )

**Comment by alexanderbock** [comment]
Cloud layer should be shown first and then transition into Magellan layer through a ByLevelTileProvider
