### ISSUE TITLE
RenderableModel - add user specifiable units

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1536]
It would be desirable for the ability to specify the units of a GeomertyFile for a RenderableModel. 

You will see mentions in our code of `-- The scale of the model is in cm; OpenSpace is in m` with a Scale applied to the model. While this method has been used to achieve the same result, it seems a better way would be to add a "Unit" value in the asset dictionary as we do for the RenderableBillboardsCloud . 

(Alternatively some users are rescaling their model before importing, however that method also requires them to know what unit we are expecting, and it would be nice if they didn't have to). 

(as requested by Dan Tell)

**Comment by WeirdRubberDuck** [comment]
Note that the way the units are handled in e.g. `RenderableBillboardsCloud` is really hacky/ugly. If working on this, it would be better to move the unit conversion to `distanceconversion.h` and `distanceconstants.h` 🙂
