### ISSUE TITLE
modern macOS refuses to open binary pkg due to missing code signing

### ISSUE THREAD

**Issue by roycewilliams** [OpenSpace/OpenSpace#1541]
Modern macOS (15.1 and up?) clients refuse to open the binary release pkg files, because they are not signed. This produces a "can’t be opened because Apple cannot check it for malicious software" error.

[Workarounds](https://kb.pulsesecure.net/articles/Pulse_Secure_Article/KB44321) are feasible, but introduce adoption friction that may be confusing for non-technical users.

**Comment by micahnyc** [comment]
Now macos software needs to be notorizted with apple before distribution in order to avoid this error message. https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution  

I would suggest only addressing this if we ever get working on the apple silicon
