### ISSUE TITLE
Equatorial Sphere Labels don't show up

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1542]
To reproduce:
1. Start `default` scene
2. Enable "Equatorial Sphere" and "Equatorial Sphere Labels"  -> No labels show up
3. Enable "Galactic Sphere" and "Galactic Sphere Labels" ->  Degree labels show up for it

**Comment by WeirdRubberDuck** [comment]
They were there, but their static rotation matrices (added in 9b58782771544a7105647d9b5f0026b85aeda301) led to them not facing the camera. Brought back the old transformation matrix to solve the problem, but long term this should get a cleaner solution that makes `RenderableBillboardsCloud` face the camera even if a rotation is being applied
