### ISSUE TITLE
CMake Error with Assimp Library Requiring Target "Minizip"

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#1548]
Happens during CMake Generate step. The CMake error message is:
**CMake Error: install(EXPORT "assimpTargets" ...) includes target "assimp" which requires target "minizip" that is not in any export set.**

Have only seen this on linux so far.
Even with this message, the build is successful, and OpenSpace seems to run fine. However this should be fixed since it may have unknown effects or only cause problems with specific content.

This most likely happened in commit 45b2d0e when ghoul submodule was updated. The change in ghoul was to update the rev of the assimp library:
https://github.com/OpenSpace/Ghoul/commit/1ce3299b7e5e835e52d1758406727d02b080916b#diff-a7e7e2f59b128bdb0aa60f56f5211efefdf83b92994b8f4a5d2e18126a0a14de

**Comment by alexanderbock** [comment]
Also encountering this on MacOS if AssImp is not taken from the system installation.

Seems to be a side effect of us including minizip in SGCT

**Comment by alexanderbock** [comment]
The problem seems to be that we are building AssImp statically, but link against minizip built in SGCT with private visibility.  I tried linking it publically, but it doesn't work.
I don't know why CMake needs to make this stuff so complicated.

Maybe this helps someone to figure it out: https://gitlab.kitware.com/cmake/cmake/-/issues/15415

**Comment by GPayne** [comment]
Commit 7fefbf9 fixes this on linux, so removed linux tag. Have verified this is not a problem on windows, but may still be on Mac.

**Comment by GPayne** [comment]
Model formats that use zip compression seem to be rare, and we apparently aren't using any of them. It's difficult to find models to test with. This is very likely fixed.
