### ISSUE TITLE
Launcher checkboxes hard to read

### ISSUE THREAD

**Issue by EricMyers47** [OpenSpace/OpenSpace#155]
The checkboxes used by the Launcher (eg. for the synchronize feature) are difficult to see, as they just change color from dark to light.  Which is which?   There needs to be some positive indication that the box is checked, such as a check mark in another (contrasting) color.

**Comment by alexanderbock** [comment]
The CSS for that is located in
apps/Launcher/main.cpp
lines 76 to 97

:)

**Comment by EricMyers47** [comment]
Thanks, I'll take a look at it.  Meanwhile, I've at least documented the meaning in the wiki.   It makes sense that light is selected (in a low light environment), but a check mark will be more definite.

**Comment by EricMyers47** [comment]
Note for later, this seems to be how to change the CSS to do this: http://doc.qt.io/qt-4.8/stylesheet-examples.html#customizing-a-qpushbutton-using-the-box-model

**Comment by EricMyers47** [comment]
I like the idea, but I don't like the red (it looks like something is wrong) or the bright green, so I'll change it grey and a more gray green.
