### ISSUE TITLE
Main Asteroid Belt has strong frame drop in default setting for asteroids.profile

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1557]
When loading the asteroids profile in 0.16.0 and enabling the Main Belt scene graph node, the framerate drops significantly.  On my machine from ~450 FPS to about 5 FPS.  Not tested on current `master`

**Comment by WeirdRubberDuck** [comment]
This is fixed on current master, as it was related to #1409. The UpperLimit set for the main asteroid belt was ignored, resulting in all 800k something asteroids being rendered

**Comment by alexanderbock** [comment]
Ah.  Closing then
