### ISSUE TITLE
Profile List not in Alphabetical Order

### ISSUE THREAD

**Issue by hedbergj** [OpenSpace/OpenSpace#1559]
The list of Profiles in the Launcher is not in alphabetical order.

Mac 11.2.3
qt 5.15.2

<img width="404" alt="Screen Shot 2021-04-09 at 10 35 03 AM" src="https://user-images.githubusercontent.com/7926907/114196741-a5d27080-991f-11eb-847f-f8e43c6a46f0.png">

**Comment by alexanderbock** [comment]
We should also check the background color in the QSS to make the text color less atrocious

**Comment by hedbergj** [comment]
In the released 16.0 pkg, the background color is fine. I'm not sure what's different between my compiled version and the release. 
<img width="364" alt="Screen Shot 2021-04-13 at 11 05 00 AM" src="https://user-images.githubusercontent.com/7926907/114575480-32df3780-9c48-11eb-877b-cbb7c11ec083.png">

**Comment by micahnyc** [comment]
micah sort it!!!!! std:sort

**Comment by micahnyc** [comment]
this also is applying to the session recording list
