### ISSUE TITLE
Globebrowsing Temporal Datasets are Limited to 1-28 Days of the Month 

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#1567]
Timequantizer in globebrowsing module was originally written to only support days 1 - 28 so that sets that are incremented monthly would work with all months.
This causes a problem with some data sets that have a start/end date outside of this range.

**Comment by alexanderbock** [comment]
Closed in 6fc1d608e9055b0d74b17302c1cc43ea717733d6

right, @GPayne ?

**Comment by GPayne** [comment]
Fixed in 6fc1d60
