### ISSUE TITLE
The Dynamic Scenegraph behaves weird if objects are in another objects scene radius

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#157]
Example:
Rosetta and Philae have 67PBarycenter as a parent. If Rosetta has a `SceneRadius` value, Philae's position is dependent on the time different. Maybe an off-by-one error?

@emiax

**Comment by micahnyc** [comment]
Recommending to close as it seems we don't have SceneRadius as a property anymore.

**Comment by alexanderbock** [comment]
To add to this:  This was only ever an issue in the dynamic scene graph branch
