### ISSUE TITLE
Eclipse hard shadow umbra

### ISSUE THREAD

**Issue by carteremmart** [OpenSpace/OpenSpace#1570]
The central umbra hard shadow is not showing up.

Hard shadow is needed to specify boundary of totality and it used to work in previous versions (2017 version worked).
![OpenSpace_000006](https://user-images.githubusercontent.com/70605329/116095711-a9335f00-a676-11eb-9dd0-76763d1ce830.png)
![OpenSpace_000007](https://user-images.githubusercontent.com/70605329/116095714-a9cbf580-a676-11eb-9370-0d2e17f23b9e.png)
![OpenSpace_000008](https://user-images.githubusercontent.com/70605329/116095717-aa648c00-a676-11eb-89b7-fc35f03f3f29.png)
![OpenSpace_000009](https://user-images.githubusercontent.com/70605329/116095719-aafd2280-a676-11eb-9ef5-da0684f187c6.png)
![OpenSpace_000010](https://user-images.githubusercontent.com/70605329/116095721-aafd2280-a676-11eb-8fd5-3694139b2b95.png)

**Comment by hedbergj** [comment]
If I turn off the atmosphere I see it. 

https://user-images.githubusercontent.com/7926907/116103859-f8c95900-a67d-11eb-8aef-c6893235a19d.mp4

**Comment by hedbergj** [comment]
(but don't plan any vacations based on it unless you make the earth oblate - it's off by a few km ) 

https://github.com/OpenSpace/OpenSpace/issues/1482

**Comment by micahnyc** [comment]
Turns out the atmosphere has it's own setting for hard shadowing that also needs to be enabled: 
![image](https://user-images.githubusercontent.com/708535/117069607-b4cbf900-acfa-11eb-87d9-d2d03e83c28b.png)

**Comment by alexanderbock** [comment]
So I guess we can close this, right?

**Comment by hedbergj** [comment]
Seems to be working fine if both Atm and Globe have hard shadows checked. But it does bring up the question, where would you hope this sort of thing be documented?

**Comment by alexanderbock** [comment]
We were discussing just this on the Monday meeting and we feel that it ought to be some grouping which would toggle both settings simultaneously.  In a few cases the principle of "a flat list displaying everything", as useful to add something quickly as it is, gets to a limit when different properties directly depend on each other.

**Comment by alexanderbock** [comment]
Closing this as it is not really an issue.  The connection will be addressed by #1618
