### ISSUE TITLE
ISS mean anomaly / position along orbit is ahead 

### ISSUE THREAD

**Issue by carteremmart** [OpenSpace/OpenSpace#1578]
The position of ISS in OpenSpace is ahead of where it is in the Celestrak visualization.  Micah looking at Kepler Translation as it pertains to mean anomaly.

**Comment by micahnyc** [comment]
Screenshot of issue with time shown in both openspace and celestrak simulations:

![image](https://user-images.githubusercontent.com/708535/117070543-dda0be00-acfb-11eb-8f0f-4e5562f3867e.png)

**Comment by alexanderbock** [comment]
See also https://github.com/OpenSpace/OpenSpace/issues/1626#issuecomment-856588703   which shows that the trail based on the "stations" SGN is even *further* ahead

**Comment by WeirdRubberDuck** [comment]
Really perplexed by this issue. Tried reproducing it to get more familiar with Celestrak and was confused about a few things.

1. when going to the time shown in the image in Celestrak now, ISS is in another position (see image below). I guess they must have updated the data? Or are you using some setting that is not apparent from the images?

2. Looking at the orbits around that time on that day, the position over the Earth that the ISS is located at seems very different to me in OpenSpace VS Celestrak. Are we sure that the ISS is using the correct reference frame in OpenSpace?

![image](https://user-images.githubusercontent.com/8808894/124760340-ee0a2a80-df30-11eb-9247-d6ebd4c646ed.png)

**Comment by GPayne** [comment]
Did a check of this today against CelesTrak and ISSTracker.com. OpenSpace's ISS position seems to be about 110 seconds ahead of those.

**Comment by alexanderbock** [comment]
Found the source of this;  when converting the TLE into a SPICE kernel that error disappears.  Might be just a side effect of not using a proper solver for TLE (see #1779)

![image](https://github.com/OpenSpace/OpenSpace/assets/4921724/3b1ade5f-dc7e-45a8-9994-13ed6bf2a3ce)
