### ISSUE TITLE
Voyager 2 Trail has a late start date

### ISSUE THREAD

**Issue by hedbergj** [OpenSpace/OpenSpace#1582]
Voyager 2 was launched on Aug 20, 1977, but the trail for the Earth-Jupiter Cruise starts on Sep 5, so the trail only is visible starting after Voyager 1 launches (on Sep 5).

```
local VoyagerTrailCruiseEarthJupiter = {...
```
Could be changed to:

```
StartTime = "1977 AUG 20",
```

**Comment by micahnyc** [comment]
Closed with: https://github.com/OpenSpace/OpenSpace/commit/b7803688c9c92118bfa51544553cfbecf6ed2db5
