### ISSUE TITLE
VRT layers are not cached with WMSCacheEnabled

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1588]
Currently we have a few layers which are added thru .vrt instead of .wms so that we can 'add transparency'  to the layer. As a result, when the files are loaded, they don't get the WMS caching tags inserted into them they way we do for all other layers. As the .vrt files are ultimately just a wrapper on top of a .wms file, it seems we might be able to dig in and insert the caching tag into the subsequent .wms file.

**Comment by micahnyc** [comment]
+1 for recent prestations

**Comment by alexanderbock** [comment]
That's not possible without manually parsing the VRT file as these files are opaque to us;  we pass the path to the VRT file into GDAL and then get tiles back from it.  OpenSpace doesn't know that a VRT file is backed by a WMS.  In fact it doesn't have to be backed by a WMS in many cases either

**Comment by alexanderbock** [comment]
Maybe a solution would be to use the option in #929
