### ISSUE TITLE
Issue loading prespecified SGCT configuration file through the launcher

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1624]
Repro:
1. Set `SGCTConfig` variable to some configuration file in the `openspace.cfg`
2. Start OpenSpace with the launcher -> configuration file gets correctly selected in the dropdown menu
3. When trying to start, a configuration file with the same name in the **user** folder is being tried to loaded, which fails in general

**Comment by micahnyc** [comment]
likely fixed with: https://github.com/OpenSpace/OpenSpace/commit/48f3f14e8ab50677b3e987b791f9d3bfdd2a9c43  double check that if their is a custom config with the exact file name as a built in or user config that it doesn't match to the built in config.

**Comment by micahnyc** [comment]
tested and working on win/mac

**Comment by micahnyc** [comment]
not fixed when using env var

**Comment by micahnyc** [comment]
fixed with 88708e3bf40162d32724d86c309658568029c593
