### ISSUE TITLE
Eclipse moon issue inside atmosphere

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1629]
Needs to be verified as I thought this was fixed in 0.16.1 but then I tried again and maybe it wasn't.

https://github.com/OpenSpace/scripts/issues/1

**Comment by hedbergj** [comment]
Looks like the atm shader is adding a 'sun' which always appears in front of the other objects in the sky. 

playing with : ` vec4 finalRadiance = vec4(inscatterColor + atmColor, 1.0);` shows this:

![sun-moon-who-is-in-front](https://user-images.githubusercontent.com/7926907/120669722-b570c000-c45d-11eb-846c-539717d5d27c.jpg)

**Comment by hedbergj** [comment]
![OpenSpace_000004](https://user-images.githubusercontent.com/7926907/120672504-5bbdc500-c460-11eb-83c7-f4b685276c24.png)

**Comment by hedbergj** [comment]
Moon, Sun, and atm Sun:

![OpenSpace_000005](https://user-images.githubusercontent.com/7926907/120672862-ad664f80-c460-11eb-9bac-1dd92a135bb2.png)

**Comment by alexanderbock** [comment]
Fixed in 9981dfd18e6ee69a05f7d34702d22f2cebb5e835 for 0.19.1
