### ISSUE TITLE
Session Recording GUI Menu Doesn't Show Playback File List on Linux

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#1631]
In the web GUI session recording sub-menu, the list of playback files is populated from the contents of user/recordings/. This works on windows, but on linux none of the files appear in the menu (even though they do exist in that directory).

Note: the web GUI must be opened in a separate browser window on linux (localhost:4680). The rest of the menu's functionality works (for example I can type in a filename and start a new recording).

**Comment by hedbergj** [comment]
I think Mac has the same problem. Records just fine, file is in User/Recordings but doesn't show in GUI.

<img width="658" alt="Screen Shot 2021-06-11 at 3 57 07 PM" src="https://user-images.githubusercontent.com/7926907/121742365-b8a72400-cacd-11eb-9a5b-8dde8a00bf4b.png">

**Comment by micahnyc** [comment]
Fixed with: https://github.com/OpenSpace/OpenSpace/commit/570484182095a08dc5942a687dfa3abdd25739dd

**Comment by GPayne** [comment]
This fixes it on Linux.
