### ISSUE TITLE
OpenSpace crashes on opening - Mac Mini M1 - problem with install or M1?

### ISSUE THREAD

**Issue by BlueCormonant** [OpenSpace/OpenSpace#1637]
I have a Mac Mini M1 with a new install of OpenSpace (0.16.1). It crashes on launch and has never successfully run.

I get as far as "Loading, Initializing Scene" then something with GL pops up too fast to see and it crashes. Screenshot before the GL attached.

Is this known to run on an M1 successfully? If so, suggestions on how to fix would be welcome.

![Screenshot 2021-06-10 at 16 52 08](https://user-images.githubusercontent.com/85696194/121557304-8e416200-ca0c-11eb-8822-4dee91246f93.png)

**Comment by micahnyc** [comment]
Hi @BlueCormonant as of right now, the OpenSpace builds are not supporting the M1 Macs. I have M1 macbookpro and the only way I was able to get OpenSpace to even start up was to include only the stars, and even then it only ran at 4 FPS. 

When possible I have been looking into building OpenSpace natively on the M1, and just was able to make it compile and run in the last few weeks, however some things are still not working and it's also only running at <5 fps.

**Comment by BlueCormonant** [comment]
Thanks @micahnyc that's very helpful as it saves me trying to work out what I did wrong on the install. I'll sit tight and wait in that case.
