### ISSUE TITLE
Screenshots directory being created every startup

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1639]
![image](https://user-images.githubusercontent.com/708535/121694986-a1017880-ca98-11eb-9a12-f754fb2156c1.png)

**Comment by alexanderbock** [comment]
Yea;  either
1. Don't create the folder until we actually take the first screenshot
2. When shutting down OpenSpace remove all empty folders

I'd prefer #1

**Comment by alexanderbock** [comment]
Some smart cookie was already thinking about this:
https://github.com/OpenSpace/OpenSpace/blob/master/src/rendering/renderengine.cpp#L1107
