### ISSUE TITLE
model animation not playing on macos

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1640]
Setting the AnimationModel to BounceInfinitely for jwst model animates it on Windows, but not on MacOS.

Interestingly, when checking/unchecking "Enable Animation" the model does change frames.

**Comment by alexanderbock** [comment]
*sniff sniff*   Smells like an uninitialized GLM object

**Comment by micahnyc** [comment]
fixed with: 611f7b6ef4e223b5a5e27fc5db92eb4a8aab3ef6
