### ISSUE TITLE
Investigate whether the Additional Script section of a profile is initialized at the wrong time

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1644]
Enabling the joystick input in the "additional scripts" section of a profile does nothing

**Comment by GPayne** [comment]
I verified in the code and with testing that:

- contents of "additional scripts" are processed after every other category of a profile. A scene .asset file is generated and the additional scripts are at the very end.
- Any script(s) in `GlobalCustomizationScripts` of openspace.cfg will run _after_ the additional scripts of the profile, so a command in such a script should overwrite anything in the profile if there's a conflict.

I don't know the specifics of the joystick problem. In the test case, were there joystick-specific commands in `GlobalCustomizationScripts` (i.e. scripts/customization.lua)?

**Comment by micahnyc** [comment]
closed with working as expected.
