### ISSUE TITLE
OSIRIS-REx profile issues

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1651]
- Before OSIRIS-REx arrives at Bennu (always occurs):
- Bennu has most of its surface made up of white triangles with no surface
imagery/features
- The rest of the surface is black
- Triggering “Clear Projections” causes no change in triangulated surface of Bennu
whether “Perform Projections” is on or not
- After OSIRIS-REx arrives at Bennu:
- ~half of Bennu has low resolution image surface data, other half is black
- There is a 2D image of Bennu floating in space approximately 46km away
(possibly the missing half of Bennu surface imagery). It orbits Bennu at Bennu’s
rate of rotation.
- After triggering “Clear Projections” the low resolution imagery (and floating 2D
image) disappears and a few small patches of higher resolution imagery appear,
most of Bennu is still black
- At a certain point as OSIRIS-REx is orbiting Bennu, all surface imagery
disappears, and then many small, darkened patches of surface imagery appear

-- As reported by Alex E. --

**Comment by GPayne** [comment]
Updated SPICE spk kernels to resolve the position jumps in commit e40125a. The other complaints listed were fixed back in 2021.
