### ISSUE TITLE
Atmosphere Sun / Sun node position mismatch

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1659]
After the SSB change, the sun in the atmosphere doesn't  match the sun orb position. 
![Screen Shot 2021-06-18 at 5 20 52 PM](https://user-images.githubusercontent.com/708535/122797168-2f41df80-d28d-11eb-9fa6-8898519de008.png)

**Comment by alexanderbock** [comment]
Closed in 20aa307
