### ISSUE TITLE
Faulty documentation for globebrowsing.getGeoPosition

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1662]
The documentation says that it returns lat, long altitude coordinates, but the function actually computes the cartesian x y z coordinates from a given lat long and altitude. 

Before fixing we should decide which behavior we actually expect.

**Comment by micahnyc** [comment]
consider also printGeoPosition

**Comment by micahnyc** [comment]
fix to return lat/lon/alt as we consider that 'GeoPosition' otherwise its 'SphericalPosition'

**Comment by WeirdRubberDuck** [comment]
I don't agree that it should be called "SphericalPosition", as this implies a spherical coordinate system and not a Cartesian as is the case for this function. My suggestion is "LocalPosition", as the position returned is in the globe's local Cartesian coordinate system

Created a PR that just updates the function name and docs to correspond to the current implementation: (see #1677)

Do we really want a function that gets a GeoPosition ? The input would then be some kind of Cartesian coordinates, but local or global?🤔 Anyhow, if we want this then we should make a new issue for it
