### ISSUE TITLE
Session Recording 'Output Frames' Playback GUI Control Not Saving Frames

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#1670]
Expected Behavior:
In the Session Recording GUI: checking the "Output Frames" box and then clicking playback should generate screenshots in the user/screenshots/ directory.

Observed Behavior:
Playback works but no screenshots are saved.

Looking at the script log, it appears that the problem is that the GUI sends the command:
`return openspace.sessionRecording.enableTakeScreenShotDuringPlayback("30")`
which results in error:
"Requested type i for parameter 1 was not the expected type String"
If the parameter is passed as an integer rather than a string then this should fix it.

Note: This has only been tested on linux.

**Comment by micahnyc** [comment]
working on win/mac

**Comment by micahnyc** [comment]
fixed with https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/commit/829260614bb95e236d23cb500f6ec0fb2e3bdf51
