### ISSUE TITLE
Remake Digital Universe grids with grid class

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1683]
The grids from digital universe are made with the RenderableDUMesh class. Since we now have a RenderableGrid class, they should be remade with that for consistency.

**Comment by WeirdRubberDuck** [comment]
Related issue: #1244, but actually, I guess the labels could be implemented just using a RenderableBillboardsCloud, similarly to the Spherical DU grids. 

If we want to bake in the labels with the renderables, maybe we can make a subclass of the RenderableGrid and RenderableSphericalGrid that includes the labels. If we don't, then we should just close issue #1244
