### ISSUE TITLE
Ambiguity when loading 1D textures where a 2D texture is expected

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1684]
Right now, the type of a `ghoul::opengl::Texture` is determined automatically based on its dimensions. This leads to problems when a renderable expects a 2D texture, but is provided a texture with a height of only one pixel.  

For example, coloring a RenderableSphere using the `openspace.createSingleColorImage` helper does not work, as this generates a 1 pixel and will be interpreted as a 1D texture when the sphere's shader expects a 2D texture. 

Suggested solution: Let each renderable dictate what type of texture should be loaded as, by implementing different loading functions (`Load1DTexture`, `Load2DTexture`, etc..)

**Comment by alexanderbock** [comment]
Closed in https://github.com/OpenSpace/OpenSpace/pull/1794
