### ISSUE TITLE
Update assets with old RenderableModel version

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1685]
We have a few assets that still use the old  `RenderableModel` implementation (with `MultiModelGeometry`). They result in errors when added and should be updated

Examples: 
examples\globetranslation.asset
scene\solarsystem\missions\apollo\17\bouldersstation2.asset
scene\solarsystem\missions\apollo\17\boulderstation6.asset
scene\solarsystem\missions\apollo\17\boulderstation7.asset
scene\solarsystem\missions\pioneer\pioneermodel.asset

**Comment by Roxeena** [comment]
Fixed in #1692?
