### ISSUE TITLE
The Sun is not rendering anymore

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1694]
Currently, the default Sun is not showing up anymore in the default profile

**Comment by hedbergj** [comment]
It peeks through the atmosphere sun at sunset.

![OpenSpace_000001](https://user-images.githubusercontent.com/7926907/126626389-6d84a643-ae30-4b6d-ac24-13d451522ed9.png)

**Comment by alexanderbock** [comment]
Very strange... for me, as soon as I load the glare, the Sun doesn't show up any more 🤯

**Comment by alexanderbock** [comment]
I actually introduced that issue with a diffeerent change.. whoops

**Comment by hedbergj** [comment]
Just imagine how confusing life on Earth would be if we had three different suns all competing for our attention.
