### ISSUE TITLE
MacOS issue

### ISSUE THREAD

**Issue by SpaceyJME** [OpenSpace/OpenSpace#1696]
<< potential malware in beta for MacBooks  >>

<< I did not expect my Mac to crash, which is showing symptoms of a virus has infected my harddrive including the recovery drive as well >>

<< 4 days after install of the newest beta (first install of it altogether as well). The system was running much slower than usual and I’ve have had this Mac for a little over six years never once had an issue until running this beta. Four days after download the missing folder icon appeared and I haven’t been able to recover it since. The reason I believe it was something with this beta, it is the only thing I’ve done differently,plus, with how it needs to be installed on macs it takes away the ability for the system to check for the malware. I just wanted to let y’all know there was potential problem for Mac users with the newest beta>>

<< didn’t think to take screenshots because I shipped it off to hopefully be fixed.>>

**Comment by SpaceyJME** [comment]
This is my MacBook Pro serial number C02SW9J0FVH3 and I’m not sure if malware was the proper term but I believe there is something in the code harmful to MacOS systems. I’ve been in connection with others in the pc community who suggested i give y’all my Mac version.

**Comment by alexanderbock** [comment]
We'll check the installer again, but we have been using the same machine to package the Mac application for about 2 years now and I'd be surprised if something had snuck in.
What do you mean by "how it needs to be installed on macs it takes away the ability for the system to check for the malware"?  A virus/malware scanner will check the installed directory even if it is marked as trusting an unidentified developer.

Could you give some more specific information about the symptoms that you have seen so that we can narrrow down the places on our end where might could have occurred?

**Comment by SpaceyJME** [comment]
Hi! Thank you for reaching out, so what I mean by installed (also, I am a Solar System Ambassador that attended the training a couple weeks ago), usually when I download such applications it will automatically download. When I tried to run it, the application opened up with how it couldn’t check for malware, so I followed the instructions giving on the website that state to give security permissions to trust an unidentified developer. I followed the steps from installation website.

My laptop is roughly six years old so it may be my hardware couldn’t handle the system as the main symptom I experienced was how slow it was once opening the navigation, my laptop would start running immensely hot. Which isn’t unusually considering it would do the same with NASA Eyes software as far as the heating aspect (my fans would turn on) but those applications never ran slow. I tried a few times to get the application to run but it would just get the laptop too hot and I would close it out to prevent overheating. About four days after download and two days after my last attempt was when the missing folder icon appeared on my Mac startup.

Through multiple attempts of trying to run recovery assist, I noticed my fans wouldn’t turn on, which prevented internet recovery of my hard drive as well. In all my years of having this laptop I have never experienced an issue such as it losing the hard drive nor have I ever opened security permissions in that particular way for an application (it was my first time doing so). About 12 hours before that missing icon folder the internet pages were incredibly slow, they weren’t uploading like they usually would.

Like mentioned, it may very well be that my laptop just couldn’t handle the system but through multiple people in the tech community suggested it could have been bad code that brought a virus in. I wasn’t sure so I wanted to reach out because I’m a content creator for TikTok in science communications with 89.8K followers, and I was very excited to share this with them. However after what happened to my Mac, I didn’t feel I should share it until I know that there isn’t something that could harm other Mac systems.

Note: my Mac system didn’t have much on it, I’ve only ever used it for online research so not many other application had taken up space. Since last shutting down the open space application, I never reopened it and that’s when roughly two days later the Mac couldn’t find the harddrive (12 hrs after the webpages we’re running slow).

Thank you for reaching out I greatly appreciate it
-Jamie Ellis

Sent from my iPhone

On Jul 26, 2021, at 5:39 AM, Alexander Bock ***@***.***> wrote:

﻿

We'll check the installer again, but we have been using the same machine to package the Mac application for about 2 years now and I'd be surprised if something had snuck in.
What do you mean by "how it needs to be installed on macs it takes away the ability for the system to check for the malware"? A virus/malware scanner will check the installed directory even if it is marked as trusting an unidentified developer.

Could you give some more specific information about the symptoms that you have seen so that we can narrrow down the places on our end where might could have occurred?

**Comment by micahnyc** [comment]
Hi Jamie, thank you for reaching out to us. We are very sorry that you computer is not working now.

As Alex mentioned above, we do have some older mac computers that we have still be installing OpenSpace on and have never come across an issue like this. In addition, we have many macos users and have never heard of this occurring for previous version and no other reports of issues with this version.
  
We are going to find additional mac computers to try installing OpenSpace on in the next week to confirm that there are no issues with our current release, and will report back here with results. 

Thank you and we really appreciate your interest in OpenSpace,
=micah
