### ISSUE TITLE
Automatically reload the WebUI after a drag&drop event

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1703]
Most of the drag&drop events cause some change to the scene graph and the user needs to manually reload the UI to account for that.  We can just blanked reload the UI and save this hassle

**Comment by hedbergj** [comment]
Same thing with openspace.asset.add() I believe. And maybe a deeper reload of the GUI when you quit and restart the application. If you restart with different assets the old ones are still in the GUI when it starts running again.

**Comment by alexanderbock** [comment]
👍 

The second part sounds like a bigger issue;  the UI will ask OpenSpace at startup about the scene graph nodes that are available and it doesn't keep any of it's own state between application states.

**Comment by hedbergj** [comment]
I mean when using the localhost in a browser as the GUI, not the CEF gui in OS. 

EG. If I launch with default scene, then quit, then remove satellites from the default scene, and relaunch, the localhost browser GUI keeps the satellites in the menus. Only a hard reload of the browser removes them (which of course is not that hard to do manually) but it does through up some warnings. 

<img width="1524" alt="Screen Shot 2021-08-04 at 7 46 15 AM" src="https://user-images.githubusercontent.com/7926907/128175625-66209cc2-f81c-4f44-97f7-d75262759e66.png">
