### ISSUE TITLE
Individual shader per asset

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1711]
Allow shader file to be specified in asset file. Currently filename is hardcoded into c++.

**Comment by alexanderbock** [comment]
Either allow the customization on a per-renderable basis or for all Renderables with the ability to selectively disallow individual subclasses

**Comment by alexanderbock** [comment]
We wouldn't aim to document the API into the shader and not include it in the versioning of the software

**Comment by alexanderbock** [comment]
Closed as duplicate of #2920
