### ISSUE TITLE
Offline profile

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1714]
There has been a lot of desire to use OpenSpace w/o internet. 

While a network connection is not required for OpenSpace there are a few items which want connection:

- some globes with web-loaded maps will appear blank. 
- TLE files will not load or be outdated

In order to improve the experience while operating w/o a network connection:

- A .profile should be prepared that don't include the assets requiring network.
- Fallbacks for the moon and other globes with webloaded maps should be prepared

**Comment by GPayne** [comment]
Rather than provide an offline profile, I would prefer only going with your second option of providing a fallback for any asset that requires a network connection, with a log messages indicating each fallback being used.

**Comment by micahnyc** [comment]
bump from support user: https://openspacesupport.slack.com/archives/C65DVB1EY/p1641930932006700?thread_ts=1641913257.000900&cid=C65DVB1EY
