### ISSUE TITLE
Lua function to cycle focus nodes

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1717]
For the joystick, we can make a function that would change the function to the "next" node in the "intersting nodes" list created by the profile.

**Comment by alexanderbock** [comment]
:+1:  I think this will have to wait until we fully integrate the profile struct into OpenSpace.  The way the interesting nodes right now are handled is that the SGN that are marked interesting get a Tag called "GUI.Interesting".  Which means that the order in which we would traverse the scene graph nodes is not the same as the array that we passed into the profile.

Once the profile is fully integrated, we have access to the original list and can use that directly
