### ISSUE TITLE
Remove duplicated actions in shortcuts UI list

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1729]
When the actions were separated from the keybindings, each action was added to the UI, in addition to the keybindings. So, in the UI the actions are duplicated. 

The UI should be updated to account for actions in a better way

**Comment by alexanderbock** [comment]
Is this still an issue?  I believe since the Shortcuts menu has been removed the duplication is gone?

**Comment by WeirdRubberDuck** [comment]
Nope, no longer a problem
