### ISSUE TITLE
Stereo separation is written out in lower precision than the camera position

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1732]
See last number in:
camera 4798.03 705.528 650206054.672 -509745858415537961304064000.0000000 66234545708782336595722240.0000000 -403872298448226894636646400.0000000 0.5882504 0.6804915 -0.2406900 -0.3646383 1.2237786e-26 - MilkyWayVolume

**Comment by GPayne** [comment]
The last number in the ascii session recording line is the scale; stereo separation isn't included in session recording. Do you want the `std::setprecision(7)` to be applied to the scale, or the stereo separation to be added to session recording file format?

**Comment by alexanderbock** [comment]
ah yes, sorry.  I meant to say "scale" instead of stereo separation

**Comment by GPayne** [comment]
Using `std::setprecision(7)` won't preserve the scale value when it gets really small (zoomed out far). A scale of 1E-8 would just be saved as 0.0, but for rendering purposes that should be fine. Do you agree?

**Comment by GPayne** [comment]
Resolved in commit 2abf191
