### ISSUE TITLE
Drag and drop session recording only works if file is in user folder

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1735]
Tried dragging and dropping a downloaded session recording file into OpenSpace, but was met with an error. Seems like the SessionRecording is only looking for the file in the user folder

![image](https://user-images.githubusercontent.com/8808894/131305540-00655e1a-fb8d-4485-90f8-cbe32c0bd86d.png)
The `spiritposition.osrec` file was actually in my Downloads folder

Expected behavior to me is that a file could be located anywhere and it should still work (but only file sin the user folder should show up in the Session recording UI)

**Comment by alexanderbock** [comment]
drag_drop handler should use `filename` instead of `basename`?  Maybe?

**Comment by GPayne** [comment]
Resolved in commit 6c5a81a
