### ISSUE TITLE
RenderableGlobe objects only receive illumination from the Sun and ignore other light sources

### ISSUE THREAD

**Issue by danrtell** [OpenSpace/OpenSpace#1745]
Renderableglobe objects are hardcoded to be illuminated by the Sun and even specifying additional/alternative lightsources has no effect.

For exoplanets in particular it would be good to be able to specify their lightsource as their parent stars for proper display (including transit demos). This could also have long-term visualization use intra-solar system for lunar/planetary reflection as an illumination source for planets & moons.

**Comment by WeirdRubberDuck** [comment]
Related issue: #921
