### ISSUE TITLE
FadeDistance appears to only respond to distances relative to the Sun/absolute origin

### ISSUE THREAD

**Issue by danrtell** [OpenSpace/OpenSpace#1746]
The FadeDistance value for objects (such as renderablestar or renderableplaneimage) only appears to respond to distance from the absolute origin of the universal coordinate space in software--that is, the Sun/Solar System barycenter. For approaching exoplanet systems it would be good to be able to set a distancefade to replicate the effect of the milky way version of the star fading out and being replaced with the local in-system star glare. FadeDistance should be relative to local distance from the origin of the specified object, not the Sun.

**Comment by danrtell** [comment]
This would also be really good to have eventually so that trails could, for example, autofade when approaching planets

**Comment by WeirdRubberDuck** [comment]
Good point. And yeah you seem to be right about that renderablestars, renderableplanescloud and renderablebillboardscloud use the distance from the camera to the origin. Thanks for pointing it out

Regarding autofade when approaching planets, there is currently a PR up (#1741) for an event system that would be really useful for this. It even includes an example that hides the trail of the current focus node when moving the camera within a certain distance to it

**Comment by WeirdRubberDuck** [comment]
This has been partailly fixed by the recent point cloud update  https://github.com/OpenSpace/OpenSpace/commit/c165098cdcfc6afe97f6c71af76042ebd18c1af7, but not for RenderablePlanesCloud, yet
