### ISSUE TITLE
Invert property lua function

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1749]
Rather then having the property inversion being a separate lua function to include, we could create a function 

openspace.invertPropertyValue("Scene.Earth.Renderable.Enabled");

using min/max values, we could even apply this to the trail opacity etc, While logic may not be ideal for every situation, feels helpful enough for the situations where it would apply.

**Comment by WeirdRubberDuck** [comment]
The case for bool properties is fixed 202781515769e49c228e6799d2ab969e32fd9c01

Although, does not invert numeric properties using min/max values.
