### ISSUE TITLE
Starting with simulation time paused breaks FixedRotation

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1751]
The fixed rotation only updates when the simulation time is changed, which can lead to problems at startup when a node's rotation depends on an attached node. 

For example, ISS is not correctly oriented against Earth if simulation time is paused on startup. But as soon as the time is unpaused or changed, it is correctly reoriented.

**Comment by alexanderbock** [comment]
Maybe introducing a last-updated timestamp and only update rotation matrix if the current time is different
