### ISSUE TITLE
Profile Properties Fails to Properly Handle a Table Value

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#1757]
If a lua table value is provided in the Properties profile editor, it will result in an error because that value isn't being properly handled. It currently treats the table as a string rather than a table of values.

Example of settings in the profile editor:
```
setPropertyValue
Scene.EarthTrail.Renderable.Appearance.Color
{0.5, 0.0, 0.0}
```

will result in an error:
**Property 'Scene.EarthTrail.Renderable.Appearance.Color' does not accept input of type 'String'. Requested type: 'Table'**

A change to the profile processing code needs to be made in order to push the value as a table rather than a string.

**Comment by alexanderbock** [comment]
Additional feature for the property window:    Adding a line edit where users can paste the ScriptLog.txt line, which gets dissected and the components are automatically entered into the respective fields (type, property uri, value)

**Comment by GPayne** [comment]
The problem with tables in profile properties has been fixed. Moved Alex's suggestion to new issue #1780
