### ISSUE TITLE
Release mode for master, Debug mode for develop

### ISSUE THREAD

**Issue by EricMyers47** [OpenSpace/OpenSpace#176]
As per discussion in the developer's meeting on Monday, the master branch should be configured to build in Release mode, which gives a performance improvement, while the develop branch should build in Debug mode, which provides more checks and logging.

It's reported that the performance improvement is really most noticeable (or exists at all) only on Windows.  But try to make this adjustment cross-platform.

**Comment by GPayne** [comment]
I spent a little time looking into this but it looks more complicated to specify CMAKE_BUILD_TYPE when generating for IDEs like Xcode or Visual Studio.
I brought up this issue out of concern for people encountering the slow Debug performance in Windows (not realizing that Release would be faster) and losing interest in OpenSpace as a result. However, once we start providing pre-compiled binaries (still a plan?), this may no longer be an issue.

**Comment by EricMyers47** [comment]
We definitely want to distribute pre-made executables packed up and ready to go, eventually with the installer for each platform.   Meanwhile, this looked like a small thing we could easily adjust.   And it should be noted in the documentation for anybody who builds from source.   (I'll see if it's an issue on Mac.  The real slowdown there was the initial download of the scene data the first time I tried it, and that's not just debugging that's a thread issue, or so Alex said.)

**Comment by alexanderbock** [comment]
I think it is fine if we leave it at the default of `Debug` and mention it in the wiki as most people working regularly with Visual Studio will be aware of the debug level checks.
Afaik, the Release version of Mac and Linux will only enable the `-O2` optimization flag, as they do not have any debug iterator checks.

And yes, pre-made executables are definitely on the todo list.
