### ISSUE TITLE
In Profile Editor, Show Simplified Status of Camera Setting in Main Editor Window

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#1767]
When editing a new profile in the editor UI, the status of the camera is not visible unless clicking the camera button to open that dialog.
The potential problem is that a user may forget to add a camera entry, and may not know to check this in the camera UI. Running a profile without camera settings will cause OpenSpace to fail with a log error explaining that the profile has no camera setting.

**Comment by alexanderbock** [comment]
Failing to set a camera location now longer fails to start OpenSpace
