### ISSUE TITLE
Scene menu sizing

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1772]
-Many users do not know that they can resize the scene menu.

-perhaps a slightly larger default with should be considered.

**Comment by alexanderbock** [comment]
I'd like to prevent overloading the getting started guide if possible.  Making it more obvious visually in the menu might be better?

**Comment by alexanderbock** [comment]
- Maybe providing a stronger highlight color
 - Maybe changing the mouse cursor based on feedback from CEF
