### ISSUE TITLE
Make launcher window resizable

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1785]
Currently the launcher window has a fixed size. 

It would be good to be able to resize it so that users can see the full file names. 

As requested: https://team-openspace.slack.com/archives/CKMDHQU07/p1637092035009500

**Comment by alexanderbock** [comment]
![openspace](https://user-images.githubusercontent.com/4921724/188682140-1960e060-06aa-4503-b45b-13bf13b35092.jpg)

**Comment by alexanderbock** [comment]
Options:
 1. Resize the window (problems with maintaining the aspect ratio of the background image)
 2. Resize the dropdown menu (problem: looks ugly)
 3. Hove the entries to show the full names

**Comment by alexanderbock** [comment]
Also:  Scrollbar covers the final bit of the box containing the names
