### ISSUE TITLE
Debug Sphere rendering problems 

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1788]
Steps to reproduce:

1. Go to ISS and check the "Show Debug Sphere" option
2. No bounding sphere is visible :( 
3. With Earth visible in the background, change focus to Earth
4. The bounding sphere for ISS is now visible

The behavior seems to be the same for other renderables

**Comment by alexanderbock** [comment]
Issues with the culling of the spheres while rendering

**Comment by WeirdRubberDuck** [comment]
The problem is actually, again, the stereoscopic depth.... Disabling it, or reducing it, shows the debug spheres

**Comment by WeirdRubberDuck** [comment]
So, closing as a duplicate of the following issues

#1738
#1455
