### ISSUE TITLE
Fails to compile on Linux Ubuntu 20.04

### ISSUE THREAD

**Issue by schwaaweb** [OpenSpace/OpenSpace#1797]
<< Description of the problem >>
I am unable to compile openspace on Ubuntu 20.04

<< What did you expect to happen >>
following the instructions here:
http://wiki.openspaceproject.com/docs/developers/compiling/ubuntu

I expected OpenSpace to compile

<< What did happen? >>
The compile fails at the end is seems to be a problem linking libgdal to libtiff

<< Attach screenshots, if possible >>

(base) darwin@dssss:~/work/tools/openspace/OpenSpace/build$ time make && date && date && date
[  0%] Built target fmt
[  1%] Built target codegen-lib
[  1%] Built target codegen
[  1%] Generating __codegen.h
codegen /home/darwin/work/tools/openspace/OpenSpace/modules /home/darwin/work/tools/openspace/OpenSpace/src
0/290 files changed in 157.227428 ms.  Pure time in codegen: 0 ms
[  1%] Built target run_codegen
[  1%] Built target tracy
[  2%] Built target websocketpp
[  2%] Built target tiny-process-library
[  4%] Built target glbinding
[  4%] Built target glbinding-aux
[  4%] Built target lz4
[  5%] Built target Lua
[ 11%] Built target assimp
[ 11%] Built target stb_image
[ 13%] Built target freetype
[ 16%] Built target Ghoul
[ 16%] Built target GhoulTest
[ 79%] Built target spice
[ 83%] Built target openspace-core
[ 84%] Built target openspace-module-atmosphere
[ 85%] Built target openspace-module-base
[ 85%] Built target openspace-module-debugging
[ 85%] Built target openspace-module-digitaluniverse
[ 86%] Built target openspace-module-space
[ 87%] Built target openspace-module-exoplanets
[ 89%] Built target cfitsio
[ 89%] Built target CCfits
[ 89%] Built target openspace-module-fitsfilereader
[ 89%] Built target openspace-module-gaia
[ 89%] Built target openspace-module-galaxy
[ 90%] Built target openspace-module-globebrowsing
[ 90%] Built target Imgui
[ 91%] Built target openspace-module-imgui
[ 91%] Built target openspace-module-server
[ 91%] Built target openspace-module-spacecraftinstruments
[ 92%] Built target openspace-module-statemachine
[ 92%] Built target openspace-module-sync
[ 92%] Built target openspace-module-toyvolume
[ 92%] Built target openspace-module-vislab
[ 92%] Built target openspace-module-volume
[ 92%] Built target openspace-module-webgui
[ 92%] Generating __codegen_unittest.h
codegen /home/darwin/work/tools/openspace/OpenSpace/support/coding/codegen/tests/execution
0/0 files changed in 3.557671 ms.  Pure time in codegen: 0 ms
[ 92%] Built target run_test_codegen
[ 93%] Built target codegentest
[ 95%] Built target openspace-ui-launcher
[ 95%] Built target glad
[ 96%] Built target zlib1
[ 96%] Built target minizip
[ 97%] Built target glfw
[ 97%] Built target png
[ 97%] Built target tinyxml2
[ 99%] Built target sgct
[ 99%] Linking CXX executable ../../../bin/OpenSpace
/usr/bin/ld: ../../ext/spice/libspice.a(open.c.o): in function `f_open':
open.c:(.text+0x894): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFLastDirectory@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFWriteEncodedStrip@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFIsTiled@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFIsByteSwapped@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFFlushData@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFFreeDirectory@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFWriteEncodedTile@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFWriteBufferSetup@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFTileSize@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFRGBAImageOK@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFClose@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFWriteRawStrip@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFSetTagExtender@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFGetFieldDefaulted@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFReadRGBATileExt@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFStripSize@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFMergeFieldInfo@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFSetWarningHandler@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFGetConfiguredCODECs@LIBTIFF_4.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgeotiff.so.5: undefined reference to `_TIFFmalloc@LIBTIFF_4.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgeotiff.so.5: undefined reference to `_TIFFmemcpy@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFClientdata@LIBTIFF_4.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgeotiff.so.5: undefined reference to `_TIFFrealloc@LIBTIFF_4.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgeotiff.so.5: undefined reference to `_TIFFmemset@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFReadRGBAStripExt@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFWriteCheck@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFSetWriteOffset@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFDefaultStripSize@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFIsBigEndian@LIBTIFF_4.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpoppler.so.97: undefined reference to `TIFFFdOpen@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFWriteScanline@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `_TIFFfree@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFGetField@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFNumberOfStrips@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFWriteDirectory@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFReadEncodedTile@LIBTIFF_4.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgeotiff.so.5: undefined reference to `TIFFClientOpen@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFFlush@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFErrorExt@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFNumberOfDirectories@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFWriteRawTile@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFCreateDirectory@LIBTIFF_4.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgeotiff.so.5: undefined reference to `TIFFOpen@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFSetSubDirectory@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFUnlinkDirectory@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFReadEncodedStrip@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFSetField@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFCurrentDirOffset@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFIsCODECConfigured@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFUnsetField@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFDataWidth@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFRewriteDirectory@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFGetSizeProc@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFSetDirectory@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFReadScanline@LIBTIFF_4.0'
/usr/bin/ld: /usr/lib/libgdal.so: undefined reference to `TIFFNumberOfTiles@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
make[2]: *** [apps/OpenSpace/CMakeFiles/OpenSpace.dir/build.make:165: ../bin/OpenSpace] Error 1
make[1]: *** [CMakeFiles/Makefile2:3021: apps/OpenSpace/CMakeFiles/OpenSpace.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by GPayne** [comment]
Hi @schwaaweb, I saw that you had posted about this in our OpenSpace Support #linux slack channel. I have not been able to reproduce this, but [my response there](https://openspacesupport.slack.com/archives/CLMQXJJDQ/p1631740574012800?thread_ts=1631560295.008500&cid=CLMQXJJDQ) is still my best guess as to what is happening. I'll summarize it here as well in case others experience this.
This seems like a problem with installed libraries outside of OpenSpace. The errors are because the linker is not finding the TIFF functions, which are provided by libtiff. I would look closely at this library on your system. Or you could try building some other application that links with libtiff to see if that works.
You might want to tell your compiler where to find libraries. Maybe your linker doesn't know where to look for **libtiff** on your system. Look at `echo $LD_LIBRARY_PATH`; you might need to modify it (check this out if interested).
Also, have a look at this [github issue](https://github.com/eclipse/sumo/issues/4668). It isn't OpenSpace related, but it is about **libgdal** having problems linking with **libtiff** which sounds very similar to your issue.
