### ISSUE TITLE
Constellations - Ability to turn on/off specific constellations

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1807]
As a user, I would like to be able to show just one, or a specific subset of the stick constellations. Right now this is achievable for our constellation images, and constellation bounds, but not for our constellation lines.

**Comment by alexanderbock** [comment]
Maybe for now;  adding a SelectionProperty to be able to select submeshes from the constellations.speck file

**Comment by WeirdRubberDuck** [comment]
Related to https://github.com/OpenSpace/OpenSpace/issues/1682 (maybe even duplicate?)
