### ISSUE TITLE
Cardinal Directions for Globes

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1813]
Users would desire to show the cardinal directions, NESW, on globes such as exampled in the attached video. 

This is a feature used by a lot of planetariums when showing the night sky.

The example was made with a RenderableSphere for a static location.

Different approaches could be taken to implement this:
- A feature of the RenderableGlobe which knows the camera position in relation to globe and can draw them with the FontRenderer. Potential issue with this could be that maybe you would be required to be focused on the globe.
- This could be done with a RenderableSphere or even some RenderableModel's. Issues with this would be that it would only work when at a fixed location on the ground (as demonstrated in png, however maybe this is a 'feet on the ground' feature and so it could fade out when elevation is changed. This would require a way of updating the position dynamically.   

https://user-images.githubusercontent.com/708535/149025952-25535931-658e-46f9-9f5d-95d1ae66c172.mp4

![OpenSpace_000000](https://user-images.githubusercontent.com/708535/149025960-8563883b-d693-4136-8100-169a23cbc095.jpg)

**Comment by alexanderbock** [comment]
- Being able to show the difference between true north and magnetic north (/south)
 - Only support for RenderableGlobe
