### ISSUE TITLE
Globebrowsing - Fallback layers not working

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1819]
When not connected to the internet, the fallback layers provided for earth/mars etc should be used by the layers that specify them, that is not happening anymore

**Comment by WeirdRubberDuck** [comment]
> When going through the layers, I was wondering if we still want the concept of a fallback layer at all or if we just want to have them as as regular layers instead? Would simplify the globebrowsing since we don't need to take care of them

This makes sense to me. The fact that we have to specify a fallback layer per individual layer is a little cumbersome and I can imagine that the handling is not trivial. Instead we could have that layer as a regular layer that maybe has a name that implies that it's the "fallback".

**Comment by GPayne** [comment]
I think that the fallback layers is an elegant solution (when it works). However, for the sake of simplicity, I agree with removing the fallback concept and just having "regular" layers only.

**Comment by alexanderbock** [comment]
Performance impact of leaving an image-based layer turned on?
