### ISSUE TITLE
DarkUniverse URL problem 

### ISSUE THREAD

**Issue by EricMyers47** [OpenSpace/OpenSpace#182]
While syncronizing with newhorizons and osirisrex selected the file DarkUniverse_mellinger_8k.jpg fails with -1/-1 and the error message "URL using bad/illegal format or missing URL".
This is on the feature/openvr branch, but that recently came from develop and I suspect it's also a problem in develop (should be tested).

**Comment by alexanderbock** [comment]
Fixed serverside;  the URL contained a carriage return that was not accounted for
