### ISSUE TITLE
Finish GeoJson renderable

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1826]
With the work for the installation for the wisdome movie "Stort", work was started on a renderable that supports GeoJSON. This work should be finished and merged

The code for the renderable exists in the branch `feature/geojson-renderable` and at the time of writing it supports lines and points (`LineString`, `Point`, `MultiPoint`) and 2D geodesic coordinates (lat long). Before merge, the follwing should also be supported: 

* Altitude, i.e. support 3D coordinates
* Simple `Polygon`s (need to determine how these are to be rendered)
* Probably also `MultiPolygon` and `MultiLineString`

**Comment by alexanderbock** [comment]
Cosed in c714a7f57dbc8eb5ced4d8116e81341b5441c058
