### ISSUE TITLE
GUI feature to fade in object when enabled and out when disabled

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1827]
Often when enabling things in the scene, we also want them to fade in nicely. The way this is done now is by 
1. Set opacity to 0
2. Enable renderable
3. Change opacity from 0 to 1 over a number of seconds

It would be nice if this could be done automatically by just one click in the GUI. For example by holding CTRL when clicking the checkbox to enable the renderable

The GUI could check if the SGN has an opacity property and handle the logic for the fading

**Comment by alexanderbock** [comment]
Can now be implemented with the new `Fade` property introduced in 02adcf570e5182c4bb682af3b5f558968ed71c66
