### ISSUE TITLE
NASM Build Problem

### ISSUE THREAD

**Issue by pedrocolon93** [OpenSpace/OpenSpace#183]
Hi,

Whenever I go to build the software there is a problem in CMake where the NASM variable is not correctly set (even though it is set as a path variable pointing to the executable).  This creates problems when trying to build the sgct dependency.  

I just manually fixed it by going into 
D:\MovedData\git\OpenSpace\build\ext\sgct\src\deps\libjpeg-turbo\simd\simd.vcxproj

and replacing the NASM path to the correct one.  Maybe the variable is not set correctly or something.

**Comment by GPayne** [comment]
Step 4 [here](https://github.com/OpenSpace/OpenSpace/wiki/Guides-Compile-OpenSpace-on-Windows#build-openspace-1) lists this step for setting the NASM variable. However, are you saying that you _did_ set `NASM` CMake variable to the nasm.exe path, but even with that change you had to go into simd.vcxproj and set NASM to the nasm.exe path. Am I understanding your problem?

**Comment by pedrocolon93** [comment]
Yes, perfectly.  I will clean the project and restart again in a while.

**Comment by pedrocolon93** [comment]
I think I see the problem.  I create the variable, but it needs to be modified instead of created.  Let me check.

**Comment by pedrocolon93** [comment]
You can mark this as closed.  In the instructions, you should change the wording to modify the NASM variable so that it points to the nasm.exe.  One can misinterpret the wording and create a new variable which for some reason does not propagate correctly in the CMake configuration.

**Comment by GPayne** [comment]
I changed the wording, which hopefully will prevent confusion in the future. Thanks for the feedback.
