### ISSUE TITLE
Confusing behavior when adding assets with errors during runtime

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1830]
This is best shown using the drag and drop (DnD) feature:

Steps to reproduce:
1. Add an asset that contains an error using DnD, which leads to the asset not being initialized
2. Try to add the asset again by dragging and dropping it
3. Nothing happens (the asset is silently ignored)

The problem is that the asset first has to be removed before it can be added again, which to me is unexpected behavior. If I get an error when adding an asset, I expect to be able to just fix the error and try again 

Either way, adding the same asset twice should lead to some kind of warning saying that the asset is already added, at least when adding things during runtime. Maybe this could be handled by the function that is used for the DnD?

**Comment by alexanderbock** [comment]
Todo:  provide a warning when trying to drag-n-drop an already loaded asset
