### ISSUE TITLE
Add events for camera path start and finish

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1834]
Add a new event type that can be used to notify/do something whenever a camera path has finished or started

**Comment by alexanderbock** [comment]
Adding a parameter that shows to which anchor node SceneGraphNode the camera path was flying

**Comment by alexanderbock** [comment]
Also providing information whether we flew to a navigation state or a node

**Comment by alexanderbock** [comment]
Left out the navigation state or node since in both cases, the target scene graph node is known and they are indistinguishable when the camera path ended
