### ISSUE TITLE
UrlSynchronization no longer includes hash in folder name

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1840]
At some point and for some reason, `UrlSynchronization` stopped using hash in the folder name, even if `useHash` is used. This means that the synced files don't update automatically :( 

Noticed when updating the WebGuiFrontend hash

**Comment by WeirdRubberDuck** [comment]
Could potentially have come from the Assets PR ? https://github.com/OpenSpace/OpenSpace/pull/1784 

@alexanderbock

**Comment by alexanderbock** [comment]
That's weird... it looks to me as if the hash is still used:

https://github.com/OpenSpace/OpenSpace/blob/master/modules/sync/syncs/urlsynchronization.cpp#L107


I remember someone talking about the `UseHash` vs `useHash`  or some other key-based mix-up.  And that the default value for the UseHash .

Just remembering that there was some issue with the URL sync for the ISS not updating.



Sorry for being rambly :D

**Comment by WeirdRubberDuck** [comment]
Yeah, had a quick look at the code and also thought everything looked fine. But after some breakpoint-based debugging, it appears like when it gets to the actual syncing, the identifier no longer includes the hash. It all seems very weird 🙃
