### ISSUE TITLE
Focus node changes undesirably after session recording has finished recording

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1851]
Once a session recording is finished recording, it sets the focus node to the node that was the focus when the recording started. This leads to undesirable behavior, especially if simulation time is running. I would expect the current focus node to be kept as focus after the recording is finished

See the video below. Note that the change of focus node leads to the currently visible node moving as a result of the simulation speed(simulation speed is here 60 seconds/second)

https://user-images.githubusercontent.com/8808894/150373906-bdd1dd83-97ab-44a2-9c2a-cd76624c7210.mov

**Comment by GPayne** [comment]
Fixed in PR#2070
