### ISSUE TITLE
Horizons and SPICE data does not line up when it should

### ISSUE THREAD

**Issue by Roxeena** [OpenSpace/OpenSpace#1862]
When using Horizons data of JWST from the 2021 launch, the trail relative to the Sun and the trail relative to L2 doesn't line up when they should. 

![jwst_precision](https://user-images.githubusercontent.com/16215103/151515265-980cbcca-0c5a-4e2a-ac09-dc9556d4d236.png)

Blue trail is of JWST relative to the Sun (SSB) and yellow trail is of JWST relative to L2. Have already checked if it could be a problem with Sun vs SSB, that is not the problem.  It is probably not the problem with loss of precision in the Horizons data either since that is on the millimeter magnitude and the gap is much bigger than that. Alex had an idea that it might be that somewhere in the pipeline is a `float` when it should be a `double` that might be causing the problem.

Here is the data used for the trails in the image
[horizons_jwst_L2.txt](https://github.com/OpenSpace/OpenSpace/files/7957489/horizons_jwst_L2.txt)
[horizons_jwst_sun.txt](https://github.com/OpenSpace/OpenSpace/files/7957490/horizons_jwst_sun.txt)

**Comment by Roxeena** [comment]
Seems to not just be a problem with JWST, here is another example with earth data from Horizons (purple) compared to the SPICE trail we normally have (blue). Seems to also wobble with an earth day in time but always behind the SPICE data.

![511a60c712074c4d02b7b544885b9999](https://user-images.githubusercontent.com/16215103/151567449-0e9104c0-47e0-4bcf-b76a-569051246468.gif)

**Comment by alexanderbock** [comment]
Could it be an issue with Earth vs Earth Barycenter?  If the Moon is off the the side maybe?

**Comment by Roxeena** [comment]
I tried with that too but the movement and gap is bigger than that

**Comment by Roxeena** [comment]
I found that the source of the problem is that we do different assumptions regarding light time aberration for SPICE and Horizons.  

On Horizons documentation it says "_The output values in observer tables are “as seen” by an observer, being **compensated for aberrations such as light-time** and other significant perspective-dependent effects_". This means that the Observer Table data type from Horizons (that we use) automatically compensates for light-time aberrations. 

At the same time (by default) we **don't** compensate for light-time aberrations when we use SPICE. https://github.com/OpenSpace/OpenSpace/blob/797a81dbe64360c88ad8c0a613c28eb45fc79147/modules/space/translation/spicetranslation.cpp#L183  

Switching on light-time aberration compensation in SPICE would be complicated and @alexanderbock can explain more about why that is. However, an alternative, would be to switch from using the Observer Table type from Horizons to Vector Table type (#1434). Since that has a setting for turning off the compensation for light-time aberrations, and this setting doesn't exist in the Observer Table type. Or we could support both and show a warning for the Observer Table type that it may not look 100% correct in relation to SPICE.

**Comment by alexanderbock** [comment]
@Roxeena   I guess we can close this?
