### ISSUE TITLE
ScreenSpaceRenderable Identifer issues on creation from drag-drop 

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1874]
When dragging an image onto openspace, the ScreenSpaceRenderable gets an identifier that only contains of underscores... See image: 

![image](https://user-images.githubusercontent.com/8808894/152154511-c3aaa9b9-4248-416e-a02b-ab4fb4134845.png)

And example from the script log:
```
openspace.addScreenSpaceRenderable({
    Identifier = "___________",
    Type = "ScreenSpaceImageLocal",
    TexturePath = "C:/Users/Emma Broman/Pictures/interesting.PNG"
  }); if openspace.hasProperty('Modules.CefWebGui.Reload') then openspace.setPropertyValue('Modules.CefWebGui.Reload', nil) end 
```

**Comment by alexanderbock** [comment]
Oops... my bad.    I never got warm with RegExps it seems
