### ISSUE TITLE
Ability to render the dashboard on the dome surface

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1879]
Adding the ability to render a subset of the dashboard on the dome surface

**Comment by alexanderbock** [comment]
Considers only the DashboardItem types, not the RenderEngine text (version information)

**Comment by hedbergj** [comment]
Yeah! I was just wondering earlier today how I could put the date/time on the dome during a show.

**Comment by alexanderbock** [comment]
An example for this was fixed in 99a976a53cde1c29c129cacfc023c9ccec8a0302

File is: data/assets/examples/screenspacedate.asset
