### ISSUE TITLE
Make default window size based on monitor resolution

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1883]
Right now we default to 720. 

Instead lets default to 80% (or some other number) of the screensize.

**Comment by alexanderbock** [comment]
Set it now to 66% as that matches a lot of the default resolutions:
3840x2160 (4K UHD) * 66% = 2560x1440 (QHD)
2560x1440 (QHD) * 66% = 1706.5x960 ( :'( )
1920x1080 (FUD) * 66% = 1280x720 (HD)
1280x720 (HD) * 66% = 854x480 (FWVGA)
