### ISSUE TITLE
RenderableTrailTrajectory on planet surface culled if too small

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1888]
Since the trail located at the center of the planet, but the bounding sphere is based on the distance between the min/max points, when the path is too short, its culled.  see line https://github.com/OpenSpace/OpenSpace/blob/9e69300642edb42f761db4ab0d69ad8608bcfee9/modules/base/rendering/renderabletrail.cpp#L442

**Comment by alexanderbock** [comment]
That culling is gone now
