### ISSUE TITLE
Bounding/interaction sphere set from asset odes not show up in UI 

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1899]
For example, ISS has both the interaction sphere and bounding sphere set from the UI, but they both show up as -1 in the UI. This should imply that the bounding/interaction sphere should be computed in the renderable, which it is not in this case.  

ISS asset:
![image](https://user-images.githubusercontent.com/8808894/156338401-e3b6676b-8342-466d-92c3-e72f72e2d12d.png)

And how it looks in the UI:
![image](https://user-images.githubusercontent.com/8808894/156338569-e4aa88f0-758d-401f-b20e-8d99260afe4f.png)

**Comment by alexanderbock** [comment]
Is it actually a problem if we don't have the correct bounding sphere displayed (for the camera path for example)
