### ISSUE TITLE
Skybrowser: "Look at target" does not work

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1919]
Guessing this is being worked on, but thought I'd add an issue for it for completeness, as this is a feature I really think should be working 

Clicking the "Look at target" button the UI currently does nothing

**Comment by ylvaselling** [comment]
Removed lock button since with the new renderable target the lock functionality is lost

**Comment by WeirdRubberDuck** [comment]
The "Look at target" och the "Lock" button is not the same though?

**Comment by ylvaselling** [comment]
True - i guess unrelated this specific issue but more generally related to "buttons that currently doesnt work"
