### ISSUE TITLE
Skybrowser: Lazy loading of "All images" list 

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1921]
This list is rerendered often and renders all 7000 or so images at once. Lazy-loading should be used to increase the performance of the list. Maybe the lazy loading can even be implemented on all FilterLists in the UI? 

(Already mentioned it in the WebGuiFrontend PR, but thought it might deserve its own issues :) )

**Comment by alexanderbock** [comment]
Or if @micahnyc  has some ideas on how the loading could be improved

**Comment by WeirdRubberDuck** [comment]
The problem is not the loading, but that the component get's re-rendered waay too often. Will updat ethe code in the Gui so the list only updates when it needs to

**Comment by WeirdRubberDuck** [comment]
Closing this, as performance is significantly improved after OpenSpace/OpenSpace-WebGuiFrontend@010447fb2de6fe0e3c79b11892eeffa44bf26cd7 and lazy loading of the images was done in OpenSpace/OpenSpace-WebGuiFrontend@ba52207eea761790804824fafc65036de938629b (the latter hardy affects the performance though). The "All images" list now rerenders only when it needs to 


However, building the full images list is still very slow (noticable when switching between close images and all images tab). So later on we probably need to do some updating to deal with rendering lists with thousands of items. Will create a separate issue for this
