### ISSUE TITLE
Skybrowser: Multiple overlapping browsers interaction is a bit weird

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1922]
See the video below. But at least the correct border gets highlighted, so it's possible to see which one is going to move when interacting

https://user-images.githubusercontent.com/8808894/159443409-39e486d0-62fd-431f-aacd-f3926e54d618.mov

**Comment by ylvaselling** [comment]
Fixed by placing the wwt application in the GUI and by only using one window for all browsers, that you can just change with selecting different tabs
