### ISSUE TITLE
Skybrowser: Misalignment in image list when image not loaded

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1924]
Se video. Alignment of images breaks when image not found

https://user-images.githubusercontent.com/8808894/159444097-a1c568f1-4732-44c0-8ee1-3119f0376ade.mov

**Comment by alexanderbock** [comment]
- Filter out the collection of images that don't have a thumbnail
 - Add a placeholder image to be used if the thumbnail does not load
 - Fix the CSS problem that makes the columns/rows not aligned
