### ISSUE TITLE
Skybrowser: Target appearance more confusing than before

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1926]
Not sure if this is really a problem, but I miss how the target used to match the ratio and size of the view in the browser. It was very intuitive

I also find it a bit confusing that the crosshair always stays the same size, no matter how much I zoom in. This no longer provides the information I need to understand how big a portion of the night sky I'm looking at in the browser

See video. Target is completely square, but browser is very rectangular

https://user-images.githubusercontent.com/8808894/159446443-c869df93-30e7-4e4a-a0d9-e2a9af0989e9.mov

**Comment by alexanderbock** [comment]
We should have a way to represent the size of the object in the target window.  Question is "How large is the thing that we are currently looking at?"
