### ISSUE TITLE
Day-Night Simultaneous Layers

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#193]

**Comment by kbladin** [comment]
What is this?

**Comment by alexanderbock** [comment]
It was a wish by Carter.. I'll question him about it

**Comment by alexanderbock** [comment]
Added the VIIRS_SNPP_DayNightBand_ENCC as an additional night layer in 644ba0a3e213d21ac00ec9b987a5dd52caae8202
