### ISSUE TITLE
Skybrowser: Sorting order of the "Images within view"

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1935]
It would be neat to sort the images of the "Images within view" by field-of-view value so that the smallest FOV images are at the top or the bottom.  That way it would be easier to find the "next level" of image when flying into something small.

![image](https://user-images.githubusercontent.com/4921724/159464227-5ccff826-ed38-462e-8055-108049734785.png)

**Comment by WeirdRubberDuck** [comment]
Secondary sorting could be the field of view  (after proximity)
