### ISSUE TITLE
Skybrowser:  Resizing the settings portion of the window

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#1936]
It would be nice to be able to resize the portion of the Skybrowser UI that contains the properties.  Particularly on large screens it can get pretty small
![image](https://user-images.githubusercontent.com/4921724/159464519-2e16ede2-6f64-4e6d-8c9e-2d31e3d9d6c6.png)

**Comment by Roxeena** [comment]
I can resize it but only to a limited amount

https://user-images.githubusercontent.com/16215103/159713031-9aba2d35-31f4-4225-99f8-078b086d806e.mp4
