### ISSUE TITLE
Skybrowser: make animations of target and camera depend on system time instead of frame delta time

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#1958]
Currently, the animations for the target and the camera in the sky browser module depend on the delta time. 

For the target: in order for the animation not overshoot, there is a check for when the frame rate drops too low. When the framerate is deemed to low (below 60 fps), the animation is discarded and there is instead a simple translation. This makes the target "jump" in an ugly way. 

Instead, to prevent animation overshoots, the animations should depend on the system time rather than the frame delta time.

**Comment by WeirdRubberDuck** [comment]
60 fps is still a pretty high framerate. Maybe the limit could be reduced ?
