### ISSUE TITLE
RenderableDiscs no longer visible

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#1965]
Could it be a problem with the pixel image used for coloring, perhaps?

Steps to reproduce:
1. Drag and drop `examples/discs.asset` inot OpenSpace
2. Retarget to look at the added SGNs and observe lack of color (see image)

![image](https://user-images.githubusercontent.com/8808894/160458740-ca7008a3-8428-4aaf-8501-454938ded58e.png)

**Comment by alexanderbock** [comment]
Potential AMD issue maybe?

![OpenSpace_000000](https://user-images.githubusercontent.com/4921724/160832037-2027fd16-e86c-4ffd-a29a-2cc0a86b47b4.png)

**Comment by WeirdRubberDuck** [comment]
That does indeed seem to be the case... Works on my office-computer 😅

**Comment by WeirdRubberDuck** [comment]
The problem is that on my AMD, the 1x1 pixel PPM image to use for color does not load correctly. According to RenderDoc, the color loads as black. 

Converting it to a 1x1 pixel PNG image works just fine
