### ISSUE TITLE
SimpleSphere should be renamed to SimpleSphereGeometry

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1967]

**Comment by micahnyc** [comment]
maybe the planetgeometry class as a whole gets removed as we only have one type of it.

**Comment by WeirdRubberDuck** [comment]
Hasn't been conceptually changed since 8 years ago https://github.com/OpenSpace/OpenSpace/commit/a86d54481272d8a0a6c4c3f16a2bf5ecdfdfab19

**Comment by alexanderbock** [comment]
Wow... a blast from the past..


Yea, I think the PlanetGeometry class has outlived it's usefulness since 2017 and should die.  Then also the sphere name would be still good

**Comment by alexanderbock** [comment]
`SimpleSphereGeometry` Is registered in the template factory as a `SimpleSphere`.  It should be registered as `SimpleSphereGeometry`

**Comment by alexanderbock** [comment]
Closed in bbc20062db7b9846050645af6099d965d5a2f2ef
