### ISSUE TITLE
Access violation in RenderablePlanesCloud uploadDataToTexture function

### ISSUE THREAD

**Issue by ElonOlsson** [OpenSpace/OpenSpace#1976]
I have had this happen a few times before, but not thought to much about it. It happens very rarely. 
It crashes right on startup before launcher opens.

Crash happens at:
ghoul\ext\glbinding\source\glbinding\include\glbinding\Function.inl
shown in screenshot 

![Screenshot (17)](https://user-images.githubusercontent.com/16134394/161827907-a2954d38-a373-40aa-9f3d-1cad4c6a1a97.png)

**Comment by alexanderbock** [comment]
I have only encountered this when compiling in Debug mode when the initialize(?) function is taking too much time to finish

**Comment by alexanderbock** [comment]
Closing as duplicate of #2482
