### ISSUE TITLE
Compilation Documentation

### ISSUE THREAD

**Issue by schwaaweb** [OpenSpace/OpenSpace#1982]
The link to compilation instructions is dead:

http://wiki.openspaceproject.com/docs/developers/compiling/general.html

Does this info exist somewhere else?

Thanks
- Darwin

**Comment by micahnyc** [comment]
Hi @schwaaweb we actually moved the compling instructions to the github wiki here: https://github.com/OpenSpace/OpenSpace/wiki/Compiling 

I will leave this issue open until we update the main wiki to point to here and not have that broken link

**Comment by micahnyc** [comment]
https://github.com/OpenSpace/openspace.github.io/issues/16

**Comment by alexanderbock** [comment]
Thanks @schwaaweb  for reporting the issue.  I fixed all of the broken links I could find

**Comment by schwaaweb** [comment]
Awesome! Thanks for the info and updated links!!!
