### ISSUE TITLE
Volumetric rendering not showing up

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#1995]
mercury magnetosphere and mas density do not render

**Comment by alexanderbock** [comment]
Data seems to be there but not rendered correctly (see gray mist on the right side)

![OpenSpace_000000](https://user-images.githubusercontent.com/4921724/162802294-b520a4a9-4f45-4fe3-bfe3-b457e721dca9.png)

**Comment by alexanderbock** [comment]
![OpenSpace_000001](https://user-images.githubusercontent.com/4921724/162802492-a04fefc5-033d-48a5-a0f1-fd057e2b5e19.png)

**Comment by micahnyc** [comment]
Now we know the origin story of the gray goo...

**Comment by WeirdRubberDuck** [comment]
Just FYI, if it helps with figuring out the problem: The generated cartesian and spherical example volumes do not have the same problem. They show up fine

I.e. these assets: 
https://github.com/OpenSpace/OpenSpace/tree/master/data/assets/examples/volume/generated
