### ISSUE TITLE
Wiki documentation specificity request

### ISSUE THREAD

**Issue by mik3cap** [OpenSpace/OpenSpace#2]
Can you add version numbers for all utilities and libraries in the Getting Started Guide portion of the wiki?

**Comment by EricMyers47** [comment]
That's the plan.   In fact, I want to make a table of dependencies similar to how BOINC does it: http://boinc.berkeley.edu/trac/wiki/SoftwarePrereqsUnix   and include minimum version numbers in that table.   Unfortunately, the developers have not been tracking this detail too much, so this could be where having lots of volunteers try the software on various versions of Windows and Mac could be very helpful.  (I also want to track licenses, but it's not clear if that should be in that same table or just in a spreadsheet.)

**Comment by alexanderbock** [comment]
Added version numbers to the getting started guide
