### ISSUE TITLE
GUI doesn't automatically display new Renderables 

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2000]
When adding a new Renderable, they aren't automatically added to the GUI. The expected behavior would be that it Renderable would appear in the GUI without the user having to manually press F5. This happened after a renderable was created in a new folder in the Scene ("SkyBrowser")

**Comment by alexanderbock** [comment]
Depending on where you are doing it, you'll have to execute the following snippet right now:
https://github.com/OpenSpace/OpenSpace/blob/master/scripts/drag_drop_handler.lua#L32

The longer term goal is to use the `SceneGraphNodeAdded` event to make the UI reload
