### ISSUE TITLE
Simplified GUI

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#202]

**Comment by alexanderbock** [comment]
Related to #973   in so far as when it is possible to easily switch the endpoint that is served, we can create a second UI that is much simpler for the first-time usage, which can also include a tutorial view

**Comment by alexanderbock** [comment]
GUI that is not based on showing all/filtered property list, but something more specialized

**Comment by ylvaselling** [comment]
Closing since the PR mentioned in this issue is merged
