### ISSUE TITLE
SGCT GUI: Changing window dimensions should update fov values

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2020]
Just like we do when someone resizes the single window config.

**Comment by alexanderbock** [comment]
Closing this as it seems to already work?  The lock next to the "Planar" will recalculate the FOVs based on a 16/9 aspect ratio ideal

1.
![image](https://user-images.githubusercontent.com/4921724/163808248-a8e6d590-2402-4d79-b97f-e765b7bb9866.png)

2.
![image](https://user-images.githubusercontent.com/4921724/163808273-d5c6b91f-689c-45fa-b308-7ce1b408c3b1.png)
