### ISSUE TITLE
Display Copies show up darker than the UI based sky browser

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2022]
The Display Copies are showing up a bit darker than the UI-based display.  It would be nice to add value and saturation sliders to the display copies to adjust the brightness of the display copy

**Comment by ylvaselling** [comment]
They are also rendered with the light from the light sources in the engine - it would be nice to have them rendered with the same light at all times (like we do for planets when we don't want shadows). 

Also, gamma correction could be nice to add

**Comment by alexanderbock** [comment]
Ah... that's probably the reason for the darker image then. Agreed, adding the ability to disable the light interaction would make a relatively simple solution for this
