### ISSUE TITLE
Using the left/right arrow in the UI to change the property value also triggers a change in delta time

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2028]
Example:
Selecting an IntProperty and then pressing the left/right key, the property would increase/decrease by 1

**Comment by WeirdRubberDuck** [comment]
This seems to be a problem with the CEF key handling, which currently includes no capture information. The key events are simply passed to the CEF browser and are never captured. 

My thought is that we would somehow need to get information from CEF about whether a key should be captured. Seems a bit tricky though...

Note to self: Next time looking at this, give `OnPreKeyEvent` a look: https://github.com/OpenSpace/OpenSpace/blob/160eab1c1ea1a2738e001cc223ede0dc84299683/modules/webbrowser/src/webkeyboardhandler.cpp#L35 
http://cefsharp.github.io/api/71.0.0/html/M_CefSharp_IKeyboardHandler_OnPreKeyEvent.htm

**Comment by alexanderbock** [comment]
Is this still an issue?  @WeirdRubberDuck @ylvaselling

**Comment by WeirdRubberDuck** [comment]
> Is this still an issue? [@WeirdRubberDuck](https://github.com/WeirdRubberDuck) [@ylvaselling](https://github.com/ylvaselling)

Yep, still an issue - when changing the slider value using left/right arrow keys
