### ISSUE TITLE
Perseverance location is opposite side of solar system

### ISSUE THREAD

**Issue by ElonOlsson** [OpenSpace/OpenSpace#2038]
![OpenSpace_000000](https://user-images.githubusercontent.com/16134394/164316029-ee52f6b2-8461-4096-be64-bb2f9fdd1028.png)

**Comment by alexanderbock** [comment]
Closed in 6b814b17ac3b232d8e20371e09b17919031dfc33 by introducing a TimeRange to restrict Perseverance to the time where we have Spice information available
