### ISSUE TITLE
Height information for Perseverance is incorrect

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2049]
Steps to reproduce:
1. Load the `mars.profile`
2. `openspace.action.triggerAction("profile.setup.perseverance")`
3. Unpause and play time forward

![OpenSpace_000000](https://user-images.githubusercontent.com/4921724/165273607-f76ac263-e1eb-49f3-a46b-32a1974b4720.png)
![OpenSpace_000001](https://user-images.githubusercontent.com/4921724/165273617-b198354c-e891-400a-ae7f-e44d3c6a9f79.png)

**Comment by Roxeena** [comment]
Just want to add that Insight is also having the problem that it lands beneath the surface of Mars

**Comment by alexanderbock** [comment]
The problem remains and is a bigger issue with the globebrowsing.
The culling of the globebrowsing is behaving weird when using negative height offsets (culling tiles when they shouldn't)

**Comment by micahnyc** [comment]
related: https://github.com/OpenSpace/OpenSpace/issues/2096
