### ISSUE TITLE
Skybrowser: Errors when loading skybrowser asset without the module enabled 

### ISSUE THREAD

**Issue by Roxeena** [OpenSpace/OpenSpace#2052]
When loading any profile that includes the Skybrowser asset without the Skybrowser module enabled it gives these errors on start up

![skybrowser-module-errors](https://user-images.githubusercontent.com/16215103/165720944-073d701b-b98c-4864-99ed-2be46e10517d.png)

**Comment by WeirdRubberDuck** [comment]
Not sure this should be considered an issue (hover, as these assets are included in base maybe we should include the sky browser as a default module)

**Comment by Roxeena** [comment]
Yes it seems strange to me that the asset is included by default but not the module

**Comment by WeirdRubberDuck** [comment]
This will not be a problem for the end-users however, as they cannot choose to not include the module :)

**Comment by WeirdRubberDuck** [comment]
Made it a default module (https://github.com/OpenSpace/OpenSpace/commit/19507981b4cabaa74bf1375c839b536daca3c92e). Closing this issue
