### ISSUE TITLE
Bastille day profile encounters errors when loading fieldlines

### ISSUE THREAD

**Issue by Roxeena** [OpenSpace/OpenSpace#2053]
The three first errors are due to the Skybrowser module not being enabled see #2052.

![bastileday-errors](https://user-images.githubusercontent.com/16215103/165722814-51866e2b-1696-49e6-ad84-a17f6c3813d2.png)

Has the class name for the fieldlines changed recently?

**Comment by WeirdRubberDuck** [comment]
Looks like you maybe might miss the required modules? Guessing these two: 
![image](https://user-images.githubusercontent.com/8808894/165734716-29c6e052-1b6d-4354-a1b8-c13bf12a7d75.png)

**Comment by Roxeena** [comment]
Yes, with the modules enabled, the profile loads without any issues.
