### ISSUE TITLE
Skybrowser: Hover circle placed around solarsystem

### ISSUE THREAD

**Issue by Roxeena** [OpenSpace/OpenSpace#2056]
The hover circle is by default placed around the solarsystem and is enabled.

![hover-circle-gaia](https://user-images.githubusercontent.com/16215103/165737554-55c3e99e-27fc-4048-a2b2-daf8e9e36e29.png)

**Comment by WeirdRubberDuck** [comment]
This is fixed in https://github.com/OpenSpace/OpenSpace/pull/2050
