### ISSUE TITLE
Skybrowser: Target doesn't reappear when coming back to solarsystem

### ISSUE THREAD

**Issue by Roxeena** [OpenSpace/OpenSpace#2057]
When leaving the solarsystem the Skybrowser windows are faded away, but when coming back to the solarsystem the target doesn't reappear with the other windows.

https://user-images.githubusercontent.com/16215103/165739179-0e3f06f0-c7da-4f59-8c56-69dd0279b746.mp4

**Comment by WeirdRubberDuck** [comment]
Also fixed in https://github.com/OpenSpace/OpenSpace/pull/2050

Recommend waiting for that PR before doing the official testing of the Skybrowser. Quite a lot has been fixed/changed
