### ISSUE TITLE
RenderableTrail - Line Fade mapping/values

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2072]
When using the line fade slider, the values are too weighted towards the low end. 

1-10 gets me 85% of the trail. Then I have to go from 10-30 to get 95% of the trail. Can't even get 100% of the trail at fade 30.

**Comment by WeirdRubberDuck** [comment]
The property should really just be a float from 0 to 1 to fade a portion of the trail

**Comment by Arohdin** [comment]
Resolved as part of PR #3193
