### ISSUE TITLE
Setting layer offset creates disappearing tiles for RenderableGlobe

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2096]
In this case. I created an offset for the Lola Dem layer, then I got close to the surface, and the tiles disappear.

![OpenSpace_000000](https://user-images.githubusercontent.com/708535/167675563-9444db6a-f10f-4bf8-8426-290b62c1639f.png)

**Comment by alexanderbock** [comment]
Could be related to the culling of globebrowsing tiles in relation to the camera FOV setting
