### ISSUE TITLE
Python library for OpenSpace scripting

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2100]
We should create a phyton openspace library that functions similar to the openspace-js-api library for javascript

**Comment by alexanderbock** [comment]
Goal is to design it analogous to the JavaScript API so that it queries the list of available functions when connecting

**Comment by alexanderbock** [comment]
I think it might need a pip install package, but otherwise this is done in https://github.com/OpenSpace/openspace-api-python
