### ISSUE TITLE
Bookmarks file should live in user folder

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2101]
Just like anything else the user would want to persist between versions of openspace, we should move the data/assets/customizaiton/localbookmarks.csv file into the user folder.

**Comment by micahnyc** [comment]
Consider a way to support different bookmark files

**Comment by alexanderbock** [comment]
Short explanation:
Different bookmark files that can either be combined while loading or loaded independently, being able to select different files depending on the profile/show

**Comment by micahnyc** [comment]
Slides also should be in user folder

Also the data/assets/customization/globebrowsing

**Comment by micahnyc** [comment]
customization.lua should also come from the user folder

**Comment by engbergandreas** [comment]
fixed in 7e65a3a 9011f7f
