### ISSUE TITLE
Reverse rate of time command/action

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2106]
Either as an action or as part of the addDeltaTimesKeybindings in the timemanager, it would be nice to easily set the detla time to the reverse of what it is currently set to.

**Comment by alexanderbock** [comment]
Do you mean just having an action that does:
`openspace.time.setDeltaTime(-openspace.time.deltaTime())`
?

**Comment by micahnyc** [comment]
> 

yes exactly
