### ISSUE TITLE
GIBS panel in ImGUI no longer working

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2108]
As a result, any assets or profiles  that were created using scripts generated from it are no longer working.

This is due to a breaking change in the layer specification.

**Comment by micahnyc** [comment]
<html>
<body>


2022-05-12 | 12:02:29.404 | print | Error | "Unknown resolution: 2002-07-01"
-- | -- | -- | -- | --
2022-05-12 | 12:02:29.405 | TemporalTileProvider | Error | Error in specification
2022-05-12 | 12:02:29.406 | Mode | Error | Missing key


</body>
</html>

**Comment by alexanderbock** [comment]
The ImGUI panel is now fixed to generate the correct script to add the layer,  existing scripts that have been saved into profiles will have to be manually adjusted.  The new format for them is:
```lua
openspace.globebrowsing.addLayer(
  'Earth',
  'ColorLayers',
  {
    Identifier = 'VIIRS_SNPP_DayNightBand_At_Sensor_Radiance',
    Type = 'TemporalTileLayer',
    Mode = 'Prototyped',
    Prototyped = {
        Time = {
            Start = '2012-01-01',
            End = 'Yesterday'
        },
        TemporalResolution = '1d',
        TimeFormat = 'YYYY-MM-DD',
        Prototype = openspace.globebrowsing.createTemporalGibsGdalXml(
          'VIIRS_SNPP_DayNightBand_At_Sensor_Radiance',
          '500m',
          'png'
        )
      }
    }
)
```
