### ISSUE TITLE
Linker error building OpenSpace version 0.18.0 in ubuntu 20.04

### ISSUE THREAD

**Issue by wtbgagoa** [OpenSpace/OpenSpace#2110]
I have been running successfully the earlier 0.17.2 release that I built from source under ubuntu 20.04.
To update to the newest 0.18.0 I did a fresh checkout of all sources from github. After some tweaks I managed to
set up the cmake build and compile almost to the end, when final linking of the OpenSpace executable fails:
```
[ 97%] Linking CXX executable ../../../bin/OpenSpace
/usr/bin/ld: ../../../../ext/spice/libspice.a(open.c.o): in function `f_open':
open.c:(.text+0x894): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
/usr/bin/ld: ../../../../modules/skybrowser/libopenspace-module-skybrowser.a(browser.cpp.o): in function `base::subtle::Barrier_AtomicIncrement(int volatile*, int)':
/home/alfonso/OpenSpace/build/modules/webbrowser/ext/cef/cef_binary_91.1.23+g04c8d56+chromium-91.0.4472.164_linux64/include/base/internal/cef_atomicops_x86_gcc.h:92: undefined reference to `AtomicOps_Internalx86CPUFeatures'

```
After this one there are several similar error messages about undefined references to symbols. I already tried to disable the webbrowser module but cmake just ignores the switch `OPENSPACE_MODULE_WEBBROWSER=OFF` and it gets included in the build.
Any help would be much appreciated. Thank you very much.

**Comment by GPayne** [comment]
@wtbgagoa A fix for this is coming very soon, which contains the CMake changes needed to resolve this.

**Comment by wtbgagoa** [comment]
Thank you for fixing this.
