### ISSUE TITLE
Error when adding debris assets

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2127]
![image](https://user-images.githubusercontent.com/8808894/169769652-b537fd14-b90f-4681-8912-6e7247948865.png)

reported by @liuloppan 

The problem exists for two assets, the `debris_asat` and `debris_breezem`

More detailed log:
![image](https://user-images.githubusercontent.com/8808894/169772416-9018ac7c-8886-47ed-a96e-35a2bcba7173.png)

**Comment by WeirdRubberDuck** [comment]
Looks like the files might not exist anymore? The links:

http://www.celestrak.com/NORAD/elements/2012-044.txt (breezem)
http://www.celestrak.com/NORAD/elements/2019-006.txt (asat)

do not lead to text files

**Comment by GPayne** [comment]
This is correct, the celestrak.com no longer serves these specific TLE files.
Updating the URLs in the corresponding asset files will fix this. Elon or I will pick some new satellite debris sets from celestrak.

**Comment by micahnyc** [comment]
https://celestrak.com/NORAD/elements/gp.php?INTDES=2012-044
https://celestrak.com/NORAD/elements/gp.php?INTDES=2019-006

Seems that celestrak changed their api and this is their new url schema.

**Comment by micahnyc** [comment]
When pulling up these urls, it came to our attention that this data changes over time as the orbits of the debris decay. I could be of interest to provide some historical data for these assets.

(celestrak has a for where you can request histroical data, which I did for the iss once)

https://celestrak.com/NORAD/archives/request.php

**Comment by alexanderbock** [comment]
That's really good to know. I didn't know they supported that!
