### ISSUE TITLE
Now button in GUI does not clear scriptScheduler

### ISSUE THREAD

**Issue by ElonOlsson** [OpenSpace/OpenSpace#2131]
If a loop is in progress, set with scriptScheduler.loadScheduledScript(), then the "now" button in the time manager part of the GUI doesn't have expected behavior because the time immediately gets set back to whatever the loop says.

An easy fix would maybe be to call `openspace.scriptScheduler.clear();` before openspace.time.setTime("now") on the button click

**Comment by alexanderbock** [comment]
Maybe we should move this into a discussion, as I'm not sure that we want to clear the script scheduler automatically when we set the time back to now.   A user would opt-in to setting up a scriptschedule and it might be surprising that we disable it for them automatically without giving good feedback

**Comment by alexanderbock** [comment]
Instead, we would want to include a new UI component that gives the user access to the scheduled scripts which would then include a "Clear schedule" button and then also either a checkbox to clear on "now" or a "now with clear"
