### ISSUE TITLE
Celestrak is returning an empty file occasionally for ISS

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2135]
Since yesterday or so, the URL we use for ISS seems to return a wrong result occasionally, which leads to the ISS disappearing:

http://celestrak.com/NORAD/elements/gp.php?CATNR=25544

**Comment by GPayne** [comment]
Looks like the link is working again. What are the symptoms, does it download a blank file? Hopefully an error is logged with a TLE format problem, without any other adverse effects.

**Comment by micahnyc** [comment]
Its that their API has changed.

Instead of http://celestrak.com/NORAD/elements/tle.php?CATNR=25544

we need 

http://celestrak.com/NORAD/elements/gp.php?CATNR=25544

**Comment by WeirdRubberDuck** [comment]
Reopening as the same fix is needed for some other assets, such as Hubble
