### ISSUE TITLE
Add the ability to query the OpenSpace version via Lua

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2136]
Adding a `openspace.version()` function that returns the current OpenSpace version will allow users to build assets that can support multiple versions

**Comment by garrettsummerfi3ld** [comment]
Expanding on this idea, there could be other related functions that can output commit hash or branch as well.

**Comment by micahnyc** [comment]
When this is done, the version topic should be looked at, perhaps we don't need the version topic anymore if we have the lua call.

**Comment by alexanderbock** [comment]
Added new function `openspace.version()` that returns a new table:
```lua
{
  Version = {
    Major = <number>
    Minor = <number>
    Patch = <number>
  },
  Commit = <string>
  Branch = <string>
}
```
