### ISSUE TITLE
Crash when adding joystick asset with different number of axis

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2137]
[Extreme-3D-pro.txt](https://github.com/OpenSpace/OpenSpace/files/8855358/Extreme-3D-pro.txt)

When adding this asset, I'm getting a crash. 

It seems that the number of axis is wrong, maybe that the values are tried to be read before the system has determined the number of axis....

**Comment by micahnyc** [comment]
(note this crash occurs when adding the asset at runtime, not when including the asset in the profile.

**Comment by Roxeena** [comment]
Hmm I can't reproduce this.
I downloaded your file and put it next to all other joystick assets (util/joysticks) and dragged it onto OpenSpace during run-time. I didn't get any crash. Is there something I missed?
