### ISSUE TITLE
Key mapping changed between 0.17 and 0.18

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2138]
In 0.17  `KP0` etc were valid keys, which are now `KP_0` (i believe) which results in some unexpected errors:
![Photo 11 05 22, 08 52 32](https://user-images.githubusercontent.com/4921724/172584326-57fa308c-c909-4a11-9919-8feb4ff467b5.jpg)

**Comment by micahnyc** [comment]
Removed in this commit : https://github.com/OpenSpace/OpenSpace/commit/34985f64a666b237803b122c8a8173558076757d#diff-acc170bfa9a30c5457fff76a1d319f63f1ef3720540a5aad59d382fd98e270daL518

**Comment by alexanderbock** [comment]
On load update the profile from KP0 -> KP_0
