### ISSUE TITLE
Planar Projection FOV settings max out at arbitrary values in the Window Configuration Editor

### ISSUE THREAD

**Issue by garrettsummerfi3ld** [OpenSpace/OpenSpace#2148]
<< Description of the problem >>

On the Planar Projection settings, the values for horizontal FOV maxes out at 90 degrees, and vertical FOV maxes out at 99.99 degrees. If wanting to go higher than the max values you would need to open the Window profile in a text editor to change these settings.

<< What did you expect to happen >>

Any float value would be accepted for the specific FOVs in the editor.

<< What did happen? >>

FOV hits a limit unless I open an editor to change the values manually.

<< Attach screenshots, if possible >>

Steps to recreate:

1. Launch OpenSpace
2. Create a new Window Option
3. Select Planar Projection for the projection type
4. Unlock FOV settings
5. Try to set it higher than 90 for horizontal FOV and 99.99 for vertical FOV

![image](https://user-images.githubusercontent.com/7040719/173891321-9b7fee0f-68be-4e61-9d08-aefda330b8fe.png)

**Comment by alexanderbock** [comment]
That was a copy and paste error which has been fixed now
