### ISSUE TITLE
Constant Velocity Flight at Low Altitudes 

### ISSUE THREAD

**Issue by hedbergj** [OpenSpace/OpenSpace#2150]
An option to somehow ignore the terrain height map when doing low altitude flying would be cool. Currently, if you fly over an elevated area, the orbital navigation speed slows down in proportion to the distance between the camera and the surface (so when you just graze a feature, you nearly come to a complete halt)

Example:
https://youtu.be/isSCXZcVyPw

A while ago I made a version that had something like this and it made for more realistic (and fun) flights (with some negative consequences like crashing through mountains). 

<img width="279" alt="screen_shot_2020-05-19_at_8 18 11_am" src="https://user-images.githubusercontent.com/7926907/174112182-a491f676-ed70-4165-b429-19557a45c9e6.png">

My hacky version added this: 

```
    const glm::dvec3 centerToActualSurface = glm::dmat3(modelTransform) *
                                             centerToActualSurfaceModelSpace;
    const glm::dvec3 centerToReferenceSurface = glm::dmat3(modelTransform) *
                                             positionHandle.centerToReferenceSurface;

    const glm::dvec3 actualSurfaceToCamera = posDiff - centerToActualSurface;
    const glm::dvec3 referenceSurfaceToCamera = posDiff - centerToReferenceSurface;

    double distFromSurfaceToCamera = glm::length(actualSurfaceToCamera);
    if (_constantVelocityTranslate){
      distFromSurfaceToCamera = glm::length(referenceSurfaceToCamera);
    }
```
But, I'm sure someone could make a more robust version.

**Comment by alexanderbock** [comment]
Maybe adding separate settings for a constant velocity and a constant height above the reference ellipsoid
