### ISSUE TITLE
Improve connection between fade and enabled/disabled

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2170]
Discussion to be had, but in general, if the object is not visible due to a parameter that is not visible to the user (e.g. using "Fade" instead of "Opacity"), we should consider it as being disabled. 

Work is being done on making the GUI's"Enabled checkbox" take this into account, but it could be a concept that we build into the c++ parts of the code as well. For example, not running the rendering code if Fade == 0

**Comment by WeirdRubberDuck** [comment]
Needs a discussion in a developer meeting, on what should be considered a "disabled" thing

**Comment by WeirdRubberDuck** [comment]
From developer meeting discussion: 
Current decision is to "remove" the enabled property and handle all the disabled logic on the C++ using the fade property. The property is saved for intuitiveness, but is mapped to fade == 0 or fade > 0 (fade == 1)

In GUI: 
- hiding the enabled property
- show fading status somehow in the checkbox icon (represents how much we're fading). Note: Should be apparent what direction it is fading
- keep track of fading direction, so that aborting the fading when clicking the checkbox goes back to the previous value. 
- if fade is not currently changing, check if value is > 0.5 or < 0.5 and then fade in or out


In engine: 
- Every renderable gets a fade property
- Change enabled checks 
- Fade > 0 => enabled

**Comment by WeirdRubberDuck** [comment]
also add fading for layers?

**Comment by WeirdRubberDuck** [comment]
What about the dimming in atmosphere? (and later, other more complex fading behaviors in renderables. E.g. time range)

 - Non-obtrusive info icon that shows only when the thing might not be visible (e.g. fade > 0, opacity > 0 and fadeInAtmosphere is true), and hovering shows info about why that is the case

**Comment by micahnyc** [comment]
User has expressed the desire to have this same functionality when enabling/disabling constellations in the constellation selection.

**Comment by WeirdRubberDuck** [comment]
Conclusion from discussion: Make it clear that the checkbox means "Is Visible", and bring back the regular Enabled property into the GUI.
