### ISSUE TITLE
Skybrowser - Starting Radius for display copy

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2182]
When using "Use Radius Azimuth Elevation" the user has the display copy starting with a radius of 0, but that makes the copy invisible.

It seems the copy should start with 1 or 2.

**Comment by alexanderbock** [comment]
Should we have two different properties for the RA/DEC and the XYZ so that we can set the defaults independently?  Right now, we are reusing the same property for both

**Comment by WeirdRubberDuck** [comment]
Maybe we could just convert the default XYZ value to its corresponding Radius Azimuth Elevation value if the setting is Use Radius Azimuth Elevation true? (the same as it would do when clicking the "Use Radius Azimuth Elevation" checkbox)

**Comment by alexanderbock** [comment]
Yea, i think that could be a viable solution as well.  @ylvaselling ?
