### ISSUE TITLE
examples/luastatemachine no longer works

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2193]
Binding of the keys is using the old function-style format and it is not clear whether it could be transformed into an action

**Comment by WeirdRubberDuck** [comment]
I have a post-it somewhere that says "Reimplement old luastatemachine using the new state machine". Maybe it is time to do so?

Note that the new state machine also has to be adapted to the actions system: https://github.com/OpenSpace/OpenSpace/issues/1731

**Comment by alexanderbock** [comment]
Decided to remove the asset
