### ISSUE TITLE
Add Triton texture 

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2198]
From Carter: https://astrogeology.usgs.gov/search/map/Triton/Mosaic/Triton_Voyager2_ClrMosaic_GlobalFill_600m

for use with voyager profile

**Comment by alexanderbock** [comment]
The projection of the image seems to be wrong in my view;  should check that

**Comment by micahnyc** [comment]
I am working a fix for this, which also will fix: https://github.com/OpenSpace/OpenSpace/issues/2653
