### ISSUE TITLE
ImageSequenceTileLayer current image does not follow index order

### ISSUE THREAD

**Issue by hedbergj** [OpenSpace/OpenSpace#2205]
When using an ImageSequenceTileLayer (SOS non temporal image sequence) on Mac, the current image order does not follow the index order. (i.e. the images as loaded are not in the correct order based on numeric values in the file name.)

https://user-images.githubusercontent.com/7926907/184390599-ad52b7ed-e7b4-4800-8cbd-8c240e6e4736.mp4

**Comment by alexanderbock** [comment]
Alphabetical vs numerical ordering ..... the bane of my existence :'(

**Comment by hedbergj** [comment]
(I think I tried renaming to aa.jpg, ab.jpg, ac.jpg ... but still had no sorting, in case that helps when you're under the hood)
