### ISSUE TITLE
Setting date/time manually on January 1st is affected by time zone offset

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#2208]
If the date/time is set to January 1st of any year, and the hour of the time set is equal to or less than the UTC offset (during non-daylight savings), then the result is one year ahead of the entered time. This depends on the computer's time zone setting. This happens if the date/time is set via the GUI or by lua command.

How to reproduce:
Set computer to eastern time zone (UTC-5). Using the GUI or console, set the date to `2010-01-01T04:50:50`, and the resulting date will be 201**1**-01-01 04:50:50.
If the time is set to 05:00:00 or above, the problem will not occur. If set to 4:59:59 the problem _will_ occur, but the year corrects itself in 1 second when the time increments.

**Comment by ylvaselling** [comment]
Fixed with https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/commit/b6de72c6d3087ec26707c9647771d36b7b421eac
