### ISSUE TITLE
Session Recording playback conversion for older versions has stopped working 

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#2209]
Normally if a session recording file of an older version is played-back, it first gets converted to the latest session recording file format version, and then playback starts.

However in the latest master branch, trying to play-back an older session recording file format (in this case v00.85) fails and causes a fatal crash. The converted session recording file (from v00.85 to v1.00) is supposed to be written to user/recordings/ but is never written to disk.

**Comment by alexanderbock** [comment]
Is it a problem only in the `master` or in the 0.18.0 release as well?
