### ISSUE TITLE
Add option to specify a lat, long (,altitude?) value in geo position panel

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2210]
In addition to searching for places on a globe, it would be nice to be able to target any lat long position

The "fly to "/"go-to"/"add scene graph node" toggle is also perfect for this feature

**Comment by ylvaselling** [comment]
Implemented in https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/pull/103
