### ISSUE TITLE
Path navigator has out of range variable for easing function

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2211]
When selecting a path the following error appears:

![image](https://user-images.githubusercontent.com/24265984/186496052-b32196d2-6bb9-4c1c-8969-81db97f6aecf.png)

It is then needed to enter "I" in the OS console to make the program continue running

To reproduce, fly to this coordinate (happens to me to all coordinates I've tried however)
![image](https://user-images.githubusercontent.com/24265984/186508755-05080c32-5687-412a-bae1-62ee846c41d9.png)

**Comment by WeirdRubberDuck** [comment]
Good find. Note that this only happens in debug mode
