### ISSUE TITLE
The Sun light source uses SSB instead of SUN as location

### ISSUE THREAD

**Issue by Roxeena** [OpenSpace/OpenSpace#2223]
The light source exported from the sun asset uses SSB instead of SUN as its location, which makes the light come from the wrong location.

**Comment by WeirdRubberDuck** [comment]
Note that just fixing the light source in the asset does not solve all the problems. In addition, it seems like the shading of the RenderableGlobes use (0, 0, 0) for the light source position. [See computation here](https://github.com/OpenSpace/OpenSpace/blob/44f7bd922526b606721ccb93aa1b5ed5d853a25c/modules/globebrowsing/src/renderableglobe.cpp#L1080)

**Comment by WeirdRubberDuck** [comment]
Fixed the scene graph node in the asset, but ofc the light source position is till wrong for the globes. Maybe close this anyways, since we have another issue that deals with light sources for globes?

#1745
