### ISSUE TITLE
Ghoul struct lua_State broken

### ISSUE THREAD

**Issue by territo-sci** [OpenSpace/OpenSpace#223]
Compiler error. Seems to be `class` typo instead of `struct`.

**Comment by territo-sci** [comment]
I already updated this in Ghoul -- this is just rolling the submodule forward to meet it

**Comment by singingsingh** [comment]
I am getting this error

fatal error: ghoul/lua/luastate.h: No such file or directory

and there is no luastate.h in <OpenSpace>/ext/ghoul/include/ghoul/lua

ᐧ

**Comment by territo-sci** [comment]
If you missed Alex's slack, double check that your submodules are up to date. It's a new commit/file in GHOUL.
