### ISSUE TITLE
Hide Skybrowser target and hover circle when closing WWT UI panel

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2230]
Now the users have to remove all skybrowsers to make them disappear, or disable the renderables in the GUI

**Comment by ylvaselling** [comment]
This is a setting in the general sky browser settings called "Hide Sky Browser and Target with GUI"

![image](https://user-images.githubusercontent.com/24265984/189866936-3293e95d-763c-4854-97d1-66d4b4cf917b.png)

**Comment by WeirdRubberDuck** [comment]
Nice! Maybe just enable it per default then? :)

**Comment by alexanderbock** [comment]
The default to true was confusing as images in the rendering disappeared based on closing a UI panel
