### ISSUE TITLE
Getting started tour: Click indicator problem when scrolled to the bottom of scene menu

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2233]
See video. Small thing, but makes it very difficult to click the desired location when it happens

Not that the problem only occurs if the scene menu is scrolled all the way to the bottom, so it can be worked around. But ideally, the indicator should not affect the size of the scroll content

**Comment by ylvaselling** [comment]
Missing video

**Comment by WeirdRubberDuck** [comment]
Thanks for noticing! Here's the video

(Note that no interaction is happening in the video, the scrolling is just because the resizing of the indicator ring)

https://user-images.githubusercontent.com/8808894/189925244-30ae1f52-581e-40e8-ac75-281f8955c5c5.mov

**Comment by ylvaselling** [comment]
https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/pull/107

**Comment by ylvaselling** [comment]
https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/pull/110
