### ISSUE TITLE
RenderableOrbitalKepler: Make Fade property more intuitive

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2235]
Found when trying out the satellites based on a message in the Support Slack: 

"Hi everyone, I'm playing around with the satellites and I'd just like to clarify a few things. What do the Fade , SegmentQuality , and Resolution  properties of Renderable actually specify? I've had a play around with it and I can't figure it out exactly. Also, along those lines, how would I get it so that the satellites are rendered as only dots (and not trails)? Thanks!"
[Link to message](https://openspacesupport.slack.com/archives/C65DVB1EY/p1663232713236769)

Some things we should fix: 
1. I cannot get the trails to render as points instead of lines, when chaing the Render Mode property during runtime
2. The description of the `Fade` property does not describe the actual behavior, just "the amount of fading applied". And the value itself is pretty confusing; hte max value is 30 and shows the full orbit, and the less the value is the less of the trail is shown (more is faded out). Maybe change it to a value 0-1?

Tested with the "Beido" satellites

**Comment by hedbergj** [comment]
Yes! Points! An earlier discussion about some of this: https://github.com/OpenSpace/OpenSpace/issues/1472

**Comment by WeirdRubberDuck** [comment]
For this issue, just do number 2 above, as we already have an issue for the points rendering :)

**Comment by Arohdin** [comment]
Resolved as part of PR #3193
