### ISSUE TITLE
Adjusting the SegmentQuality property Causes Crash

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#2236]
OpenSpace crashes if the Segment Quality property in a Satellite or Asteroid is adjusted to a different value.

Crashes with exception:
    File:       .../OpenSpace/modules/space/rendering/renderableorbitalkepler.cpp, line 205
    Function:   virtual void openspace::RenderableOrbitalKepler::initializeGL()
    Assertion:  _vertexArray == 0    Vertex array object already existed

**Comment by WeirdRubberDuck** [comment]
Hm, I changed the Segment Quality property of a RenderableOrbitalKepler a bit yesterday and did not get this. What asset did you use when observing this?

**Comment by GPayne** [comment]
Here are few ways to reproduce the crash. Confirmed in the latest master, on both windows and linux.

1. Start Default profile, and enable GPS satellites at **Solar System/Planets/Earth/Satellites/GPS**, then modify the **Renderable/Segment Quality** slider.

2. Start Asteroids profile, and modify the **Solar System/Small Bodies/Amor Asteroids/Renderable/Segment Quality** slider.
