### ISSUE TITLE
SkyBrowser: Target box not displaying on certain channels

### ISSUE THREAD

**Issue by meganvilla** [OpenSpace/OpenSpace#2240]
The target box was not displaying on certain channels (nonexistent on channel 2). Sometimes the image was only loading on some channels like on 1,4 not 2,5,6. Different Field of view show up possibly because they need to take master field of view and they’re all taking their own FOV. Same FOV shows but different magnitudes. The same test twice appeared on different channels (1,4,3 showed WWT; 2,5,6 did not work). Additionally, the target box rotated 180 degrees on channel 2. Not consistent on which channels image appears. Possibly changing the scale been crashing it? Micah tried to change size before creating.

![IMG_2695](https://user-images.githubusercontent.com/99894471/190676945-235c4a98-074f-499c-ba8d-b58c11fa6813.JPG)
![IMG_2696](https://user-images.githubusercontent.com/99894471/190676952-369285b3-dfec-42e7-abea-bfebf8298a4d.jpg)

**Comment by ylvaselling** [comment]
Created three specific issues for this issue: #2313 #2280 and #2425.
