### ISSUE TITLE
Rename ISS scene graph node

### ISSUE THREAD

**Issue by Roxeena** [OpenSpace/OpenSpace#2245]
Right now if you set focus on ISS you cannot directly change the settings of its model since the node in focus is the position of ISS and not the node that holds the model. This is annoying and should be changed to use the model node as the focus and not the positioning node. Which would require a rename of the nodes.

**Comment by micahnyc** [comment]
Keep note of the identifiers for trail hiding: https://github.com/OpenSpace/OpenSpace/blob/master/data/assets/actions/trails/toggle_trail.asset
