### ISSUE TITLE
Camera path can result in zooming away from object instead of towards

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2257]
I was not able to replicate but see video on support slack: https://openspacesupport.slack.com/archives/C65DVB1EY/p1664799440991849

**Comment by Roxeena** [comment]
Adding this entry to the list of properties in the profile makes it work
```
{
      "name": "Scene.JWSTFov.Renderable.Enabled",
      "type": "setPropertyValueSingle",
      "value": "false"
},
```
Not a solution but a temporary fix for now at least

**Comment by WeirdRubberDuck** [comment]
The problem happens when a node with a small bounding sphere and a child with a veeery large bounding sphere. This is the relationship between the JWST model and the JWSTFov
