### ISSUE TITLE
Vesta bounding sphere set to a way too small value

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2259]
This makes the camera fly through the asteroid when flying to it

![image](https://user-images.githubusercontent.com/8808894/194248993-037f19cc-38af-4caa-8f1e-ac887e7eced5.png)

Note that the bounding pshere property of the RenderableModelProjection should be updated. right now it always overrides the bounding sphere set for the scene graph node, even if no value is set: https://github.com/OpenSpace/OpenSpace/blob/866b37fac3b575198d0cb11431e179e4628e9873/modules/spacecraftinstruments/rendering/renderablemodelprojection.cpp#L108

Also, it currently has no correctly computed implementation for the bounding sphere

To reproduce, open the dawn profile and fly to Vesta

**Comment by Roxeena** [comment]
> Also check orion nebula

Since the Orion Nebula is a model, the bounding sphere is set. I tested a camera path to it now and it looks great 👍
