### ISSUE TITLE
Testing OpenVR branch on Windows

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#226]

**Comment by EricMyers47** [comment]
If we could get someone to test it on Linux too that would help.   I'm not yet set up to do that.    Two things (for both Windows and Linux):  check out the branch and verify 1) it builds, and 2) it launches without crashing.

**Comment by GPayne** [comment]
I pulled the latest from this branch yesterday, and it built & ran fine on windows

**Comment by EricMyers47** [comment]
It's now failing to build on Jenkins, because of something called GLM.
