### ISSUE TITLE
Move Ceres, Dawn and Vesta to dwarf planets folder instead of dawn missions folder in assets?

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2261]
The natural place to search for these is under dwarf planets, not necessarily under the dawn mission

Experienced by user in support slack: https://openspacesupport.slack.com/archives/C65DVB1EY/p1664684240963699

**Comment by micahnyc** [comment]
yes and https://github.com/OpenSpace/OpenSpace/issues/1712
