### ISSUE TITLE
SkyBrowser doesn't show latest imagery from WWT

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2265]
At www.worldwidetelescope.org, there are 15 images in the JWST folder, but in OpenSpace, only 8. The wtml file downloaded from the server only contains 8 images. It seems the hashing and updating of the wtml files is currently not working currently. Maybe this is a problem with servers being down/ Jenkins being down?

![image](https://user-images.githubusercontent.com/24265984/195363511-efe848f2-6949-4b15-8158-793978a6660a.png)
![image](https://user-images.githubusercontent.com/24265984/195363620-8a4166b5-7de3-4252-9c36-245f22aa1523.png)

**Comment by WeirdRubberDuck** [comment]
I think this might be fixed now? At least there are a bunch more JWST images showing up and they seem to match the ones in the WWT Web Application 

Guess it was fixed when the Jenkins went up again

**Comment by alexanderbock** [comment]
The JS app that is updating the files has restart 66 times;  last one was <19h ago.   There is no message in the log that would explain it though.

**Comment by ylvaselling** [comment]
WorldWideTelescope:
![image](https://user-images.githubusercontent.com/24265984/200883062-8346639e-6843-45c2-940b-3d8bd74108d9.png)
![image](https://user-images.githubusercontent.com/24265984/200883096-a7a223cf-c94d-4401-acbf-6c946590851e.png)

OpenSpace:
![image](https://user-images.githubusercontent.com/24265984/200883182-e23c5c76-8743-44ad-8588-867b352fb492.png)

Some images are still missing 🤔

**Comment by ylvaselling** [comment]
Did some more research - images are not missing, searching for JWST just didn't display them
