### ISSUE TITLE
Actions not showing with out initial / in GuiPath  

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2275]
Actions like https://github.com/OpenSpace/OpenSpace/blob/524b78f5d274909bd790e82cbeffdb84eb3a585d/data/assets/scene/solarsystem/heliosphere/2012/reset_loop_action.asset#L1 do not show in the GUI if their GUI path doens't start with /  

We should adjust so that actions don't need the initial / in their path.

**Comment by WeirdRubberDuck** [comment]
Closen in https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/commit/c87b94d6b44f44f049cf33c3b85cdcf38a8c3c9b
