### ISSUE TITLE
SkyBrowser has huge performance hit when increasing scale, sometimes leading to crash

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2280]
If you increase the scale of the display copy of the SkyBrowser, there is a big performance hit and the framerate drops. Sometimes it even makes OpenSpace crash.

**Comment by alexanderbock** [comment]
If the scale value is about 1-1.5 the performance drops

**Comment by alexanderbock** [comment]
Identifying whether there is a dependency on "resizing" vs "creating with large size" in Display Copys
