### ISSUE TITLE
QT Grid editor

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2284]
It would be nice to provide an editor for column/row based data (such as .csv or .speck files) in QT. 

It feels like this type of component should be available already from QT and not something we should need to build from scratch.

**Comment by alexanderbock** [comment]
https://doc.qt.io/qt-6/qtableview.html

**Comment by alexanderbock** [comment]
Needs some critical thinking on how much work it is to implement vs the benefit we are getting from it over a standalone editor.

How would a typical user want to edit these files (potential 'replace all' feature, etc)

**Comment by alexanderbock** [comment]
Instead of spending the time to implement a half-baked editor, we should just support file formats that other existing editors can read/export
