### ISSUE TITLE
Profile Editor: Binding the same action to two different keys results in "unknown action"

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2288]
This is done without presenting any warnings/ errors to the user. Result in list looks like this:
![image](https://user-images.githubusercontent.com/8808894/198955353-2bf26e05-4e5e-43fa-826f-73d59a8ea9f8.png)

Expected behavior: Either bind successfully (why not?), or present a warning error message to the user

**Comment by alexanderbock** [comment]
Seems to have been fixed along the way
