### ISSUE TITLE
Profile Editor: Help users create valid identifiers when creating actions, etc

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2289]
The keybindings window in the profile editor requires the user to manually write an identifier for the action. Since we have restrictions on what is a valid identifier, we could give hints to help the user to come up with a valid one. Currently, it's possible to create invalid identifiers, very easily

Some suggestions:
- Check for invalid characters in the input string and provide error messages in GUI
- Hint for what we mean by an identifier, and what characters it cannot include. E.g. through a tooltip for the "identifier" label

Could be implemented in a way so that it can be reused for the asset builder later on :) 

OBS: Should also be more apparent what fields are required in this editor. Currently, the error messages for this only pop up when trying to save

**Comment by alexanderbock** [comment]
Provide an optional default value that uses the name as a standin unless manually overwritten
