### ISSUE TITLE
Pressing F12 in debug mode triggers breakpoint

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2297]
Pressing F12 for a screenshot triggers a breakpoint in Debug mode. It is possible to just continue, but it seems like pressing F12 should not trigger a breakpoint

![image](https://user-images.githubusercontent.com/24265984/199318488-4da6ce5e-b305-4553-b853-422d57484bfe.png)

**Comment by alexanderbock** [comment]
That's not really anything we can change :(   It's the default key when running an application from within Visual Studio to break.

If someone comes across this later, there is a Registry entry that can you can change in Windows to change it to a different debugger.

https://stackoverflow.com/questions/18997754/how-to-disable-f12-to-debug-application-in-visual-studio-2012
