### ISSUE TITLE
OpenSpace Crashes On Startup

### ISSUE THREAD

**Issue by liujincheng111** [OpenSpace/OpenSpace#2298]
After compiling，OpenSpace Crashes On Startup.

Process name：OpenSpace.exe : D:\OpenSpace\OpenSpace-Master\bin\Release\OpenSpace.exe
Process architecture：x64
Exception Codes：0xC0000005
Exception  Info：The thread attempted to read or write to a virtual address to which it did not have appropriate access.
Heap information：not exist
![1](https://user-images.githubusercontent.com/39893816/199987816-ea935609-da26-477d-844e-42f557465e82.PNG)

**Comment by alexanderbock** [comment]
Can you try building in `RelWithDebInfo` mode?  We are having some issues with the `Release` mode (#1760)

**Comment by alexanderbock** [comment]
Maybe duplicate of #1657

**Comment by alexanderbock** [comment]
Closing as duplicate
