### ISSUE TITLE
Launcher Configuration File Settings

### ISSUE THREAD

**Issue by territo-sci** [OpenSpace/OpenSpace#231]
Launcher should have a configuration section in openspace.cfg.

Options should cascade, i.e.

- Command line flags
    - Launcher settings in config
        - Overall OpenSpace settings in config.

Originally intended to disable the debug messages from the sync widget.

**Comment by territo-sci** [comment]
**branch features/launcherconfigs**

Config file working in 154ff289a39072a68013cfe79e2e5726dc9dbe23.

New `Launcher` key in Configuration manager recognizes the same keys as the `Logging`:

```const string ConfigurationManager::KeyLogging = "Logging";
const string ConfigurationManager::PartLogLevel = "LogLevel";
const string ConfigurationManager::PartImmediateFlush = "ImmediateFlush";
const string ConfigurationManager::PartLogs = "Logs";
const string ConfigurationManager::PartAppend = "Append";
const string ConfigurationManager::PartCapabilitiesVerbosity = "CapabilitiesVerbosity";

const string ConfigurationManager::KeyLauncher = "Launcher";
```

**Comment by alexanderbock** [comment]
It's better to use const char* instead of std::string here.  Compare assembly in

https://godbolt.org/g/cqgK3a
vs
https://godbolt.org/g/k21sdE
