### ISSUE TITLE
Handle slash before GUI paths in the profile/asset editor

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2318]
To avoid problems with Scene graph nodes or actions not showing in UI because of missing `/` in front of GUI path

To decide: 
- Present a warning? Or help the user create the correct path format through UI features?
- What should be the default? Should the user have to know about it

**Comment by alexanderbock** [comment]
1. Slash should be obligatory in the beginning of the `GuiPath`
2. The `GuiPath` should be optional and defaulting to `/` path

**Comment by WeirdRubberDuck** [comment]
And also add the slash automatically in the profile editor :)
