### ISSUE TITLE
Add "interesting time" support and UI panel

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2327]
Similarly to "mark interesting node", we have a "mark interesting time" feature, but it's not exposed in the profile system. It should be :)

And as part of this we should add a GUI panel with a list of the interesting times, that can be opened from the time picker. We had some discussions about this during a Monday dev meeting. Here's a sketch from that one: 

![image](https://user-images.githubusercontent.com/8808894/203121720-f7680747-fa30-437a-9f88-e9c822645606.png)

But the exact placement of the buttons is still to be determined

**Comment by WeirdRubberDuck** [comment]
Yesterday should always be interesting

**Comment by micahnyc** [comment]
Thinking this could be closed with the addition of the mission gui that supports "interesting" times

**Comment by WeirdRubberDuck** [comment]
Makes sense to me.  We could also remove the already existing code, in that case, IMO

**Comment by alexanderbock** [comment]
Agreed :+1:

**Comment by alexanderbock** [comment]
Issue for the removal #2991
