### ISSUE TITLE
GlobeTranslation issue with HeightLayer settings

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2328]
When I had gamma/multiplier settings set on a height layer, they didn't seem to be accounted for in the globe translation because my item that was supposed to be on the surface was actually 1/2 under the surface.

**Comment by alexanderbock** [comment]
#1624

**Comment by WeirdRubberDuck** [comment]
Which version of OpenSpace did this occur on? I'm struggling to reproduce it on the latest master

**Comment by WeirdRubberDuck** [comment]
Note that the "Use heightmap" property must be enabled. In that case the translation is updated every frame
![image](https://user-images.githubusercontent.com/8808894/207084321-06797ebc-5bb6-4ef7-bdc3-e964a604aa6a.png)

**Comment by alexanderbock** [comment]
Marking this as closed as it does not appear anymore

https://user-images.githubusercontent.com/4921724/224447736-8d593431-0351-40c9-a47f-ad55d9b84cf7.mp4
