### ISSUE TITLE
Dates before 1000 are Invalid

### ISSUE THREAD

**Issue by hedbergj** [OpenSpace/OpenSpace#2338]
Using the GUI to go to a date pre-1000 causes the date/time display to fail.
![OpenSpace_000000](https://user-images.githubusercontent.com/7926907/154567844-ed788fc1-8f33-4cfd-80bf-433a73f8c367.png)

**Comment by WeirdRubberDuck** [comment]
Have a look at this: https://stackoverflow.com/questions/5863327/tips-for-working-with-pre-1000-a-d-dates-in-javascript

**Comment by ylvaselling** [comment]
Fixed with https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/commit/b6de72c6d3087ec26707c9647771d36b7b421eac
