### ISSUE TITLE
Dev Gui marker is eating mouse input

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2341]
Super tiny thing;  when clicking on the Dev Gui marker, the mouse input is not passed into OpenSpace and no mouse interaction happens:

![image](https://user-images.githubusercontent.com/4921724/187400908-b1241c22-6204-458a-a726-a000ada04ecb.png)

**Comment by WeirdRubberDuck** [comment]
Just fixing this with the current look will be tricky. The way one would do it in a webpage is to set `pointer-events: none;` in the CSS. However, this does not work here as the way we determine whether a pixel has webpage content in the CEF rendering is [based on the alpha value of the rendered webpage pixel](https://github.com/OpenSpace/OpenSpace/blob/ad5389bc87e2d05690e06e2ebdd50e9665eea259/modules/webbrowser/src/webrenderhandler.cpp#L158)... So the mouse events are captured even with `pointer-events: none;`.

Made it "disappear" on hover instead :)
