### ISSUE TITLE
Navigation / Focus Panel should close after selection

### ISSUE THREAD

**Issue by carteremmart** [OpenSpace/OpenSpace#2342]
After selecting new target, I have to manually close the Navigation panel.  It would be great if it automatically disappears after selection. 
This could be an option if not all users want this behavior.

**Comment by WeirdRubberDuck** [comment]
This also goes for when flying somewhere; when the camera path finished the panel will open again

**Comment by ylvaselling** [comment]
PR here https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/pull/14
