### ISSUE TITLE
Performance issues with the UI

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2344]
For me, the performance of the UI is much worse when OpenSpace has focus and is rendering at full speed.  When selecting a different window (for example Visual Studio Code), the UI becomes more responsive.   Recording with OBS makes the situation worse:

https://user-images.githubusercontent.com/4921724/200051801-313e9c89-08c5-4748-b15b-3b16e5bc4794.mp4

I'm assuming it is because we are rendering at full-bore when the application has focus, not leaving any resources for the CEF UI process?

**Comment by WeirdRubberDuck** [comment]
I have also experienced these performance issues recently and it seems like they are dependent on the OpenSpace framerate (the higher the framerate, the less responsive the UI is, I think)

Capping the FPS to 60 or so makes the UI much more responsive.
