### ISSUE TITLE
Sync window checkboxes could be used for download status

### ISSUE THREAD

**Issue by EricMyers47** [OpenSpace/OpenSpace#235]
The checkboxes in the Launcher's synchronization window could be used for status information after or maybe even during the sync.   If there is any problem (eg. file sizes don't match, or eventually MD5 doesn't match, or just that the file cannot be downloaded or is not yet downloaded), then the checkbox could be red.   If everything is fine, it could be green.   If that scene has not yet been downloaded just keep it grey.

One potential problem is confusion between status after a sync versus selecting what to sync.  One way to clear this up is to use an explicit check mark to show what has been selected for download.

**Comment by emiax** [comment]
Outdated - closing.
