### ISSUE TITLE
Add the ability to export the documentation as a JSON file

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2355]
It would be useful to export the documentation information in JSON format so that other parts can learn about parameters structs

**Comment by ylvaselling** [comment]
Some questions: 

- Where do we want to control this? As a command line argument? 
- Do we just want to export the JSON format as it is (the documentation data right now is almost json already) or make changes? 
- What are the other "parts"?

**Comment by alexanderbock** [comment]
Could we add a separate (C++) application whose only job it is to export the documentation?  Alternative we could add it as a flag into the `openspace.cfg` file.

I'd say we export it in the same form as we currently put it into the documentation.  Having two different structures might be difficult to handle and document.

One of the things that could use this export is a (doesn't exist yet) script that takes the JSON and converts it into a form so that we can put it on the docs.openspaceproject.com page

**Comment by ylvaselling** [comment]
Closing this as we can do this now with the docs writer
