### ISSUE TITLE
Exception is thrown when trying to bind and action to the `+` key

### ISSUE THREAD

**Issue by Roxeena** [OpenSpace/OpenSpace#2358]
This happens both when using the profile editor, and when doing it manually in the profile file. It seems that the parser that extracts the key and modifier, separates the string with the `+` character.

**Comment by alexanderbock** [comment]
Fixed for "Keypad +" note that "+" is not a valid key since it doesn't appear without a modifier key on a US keyboard;  it should be "Shift+=" instead
