### ISSUE TITLE
Some window settings do not work when configured inside openspace.cfg

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#2364]
Some window settings will not work if configured inside the openspace.cfg file rather than in a .json window configuration file. This includes `fullscreen`, `border`, and others.

Some background:
SGCT uses a .json file to define all possible window settings. A .json file in the config/ directory can be used, or manually edited in a custom configuration. Another option is to use the window config GUI from the launcher, which creates a .json file in user/config/.

There are two ways to specify settings inside openspace.cfg. The first is to simply reference an existing .json file. Another way is to call the `sgct.config.single` or `sgct.config.fisheye` functions which reside in **scripts/configuration_helper.lua**. Arguments can be passed to the function, which will then generate a .json file in the filesystem /tmp directory. The issue is that some of these arguments are incorrectly ignored.

The problem is likely in the function `generateWindow`, where arguments such as `border` and `fullscreen` are handled.

**Comment by WeirdRubberDuck** [comment]
Note that fullscreen works, but it has to be `fullScreen` when given to the configuration_helper

We should probably make it so that the keys are consistent with the SGCT documentation and the config files

**Comment by WeirdRubberDuck** [comment]
The problem is that bool properties that are set to "false" are not included in the configuration due to the checks in the configuration_helper.
