### ISSUE TITLE
Jenkins server is using IP address not domain name

### ISSUE THREAD

**Issue by EricMyers47** [OpenSpace/OpenSpace#237]
The Jenkins server, which is using port 8080 on dev.openspaceproject.com, is not using the name everywhere, only the IP address.   It _is_ using the domain name dev.openspaceproject.com in offering embeddable build status icons, as are being used in the Build Status table at https://github.com/OpenSpace/OpenSpace/wiki/Jenkins-Build-Status, but when you follow one of those links it does not take you to the deep link for that particular project.  For some reason the server doesn't recognize it as it's own and so it just takes you to the top level on that port, http://130.236.132.168:8080/

I also see an intermediate full URL with the name jenkins.openspaceproject.com before the final redirect, so there seems to be some confusion there too.   

Deep links that use the IP address but not the name dev or jenkins work, in that they take you where they are supposed to.

**Comment by alexanderbock** [comment]
Fixed
