### ISSUE TITLE
Profile editor doesn't communicate what is included the base asset

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2374]
we should have a way for the users to know what is included in the profile

**Comment by GPayne** [comment]
The Profile Editor's asset window only shows a tree view of the directories and the asset files they contain.

We could add a preview window at the bottom that would, when an asset file is highlighted in the list, display all of the `asset.require( )` lines in the highlighted file.

**Comment by alexanderbock** [comment]
Requires #2394
