### ISSUE TITLE
Add option to invert idle behavior direction

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2379]

**Comment by micahnyc** [comment]
Note from user, would be nice to have “smart” option that goes in the direction that will make it show the lit side first

**Comment by micahnyc** [comment]
bump from user: https://team-openspace.slack.com/archives/CKMDHQU07/p1676582744157819

**Comment by WeirdRubberDuck** [comment]
Fixed by both allowing to set negative speed factor through the UI, and through a bool property that can be used to quickly invert the value

Note that the "smart" option was left out for now, as we don't want to add that kind of complexity yet. But should maybe be considered when looking at issues like: https://github.com/OpenSpace/OpenSpace/issues/1946, which potentially involves giving scenegraph nodes more information about their surroundings and state in the scene
