### ISSUE TITLE
Configuration_helper does not support all parameters available in SGCT

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2381]
As a user, it is difficult to know which parameters I can pass to the configuration helper functions that can be used in openspace.cfg, e.g. `sgct.config.single` or `sgct.config.fisheye`. Not all parameters available in the SGCT documentation is available through the  helper, for example `draw2d` is not

Reported by a user: https://openspacesupport.slack.com/archives/C8YNSMD35/p1669848089011599

**Comment by WeirdRubberDuck** [comment]
Note that we might want to remove the use of the configuration helper in the future? As it is now "replaced" with the new config creation interface. 

So maybe this is not a problem

**Comment by alexanderbock** [comment]
Yea, I'll close this as a won't fix.  The for the configuration_helper was to create a _subset_ of the SGCT configuration options, not as a replacement
