### ISSUE TITLE
Star Labels and Star Labels Alternate don't match. 

### ISSUE THREAD

**Issue by hedbergj** [OpenSpace/OpenSpace#2400]
It looks like the data used by Star Labels and Star Labels Alternate are different, at least in the distance from Earth dimension. 

Eg. Alcyone and eta Tau should be the same star. 

![OpenSpace_000000](https://user-images.githubusercontent.com/7926907/207412158-08d8cad6-0516-4ffe-9e9c-b3ad7e3d0a45.png)

**Comment by hedbergj** [comment]
It might just be a mismatch in DU versions. From `stars.speck` eta Tau is located at:

```-100.6370    23.8487   -44.8736```

while in `stars.label` it is 

```-110.5814 26.2053 -49.3081```

and in `stars-altlbl.label` it is

```   -100.64      23.85     -44.87```

**Comment by WeirdRubberDuck** [comment]
Yes that's exactly the case

We are currently waiting for an updated version of the DU, where the stars positions will match

**Comment by WeirdRubberDuck** [comment]
👍 We're currently communicating with AMNH about updating the DU. I'll include this issue in that discussion
