### ISSUE TITLE
Navigation "fly to" controls not accessible when using touch

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2402]
As the "fly to" controls are shown on hover, they are not accessible when using a touch-screen to interact with OpenSpace

**Comment by alexanderbock** [comment]
The WebGUI module could have another property that would be set to true if we are interested in a touch-focused UI which the components can look out for

**Comment by WeirdRubberDuck** [comment]
This has bene fixed.  The buttons in the Focus menu are now always visible
