### ISSUE TITLE
Apollo boulders offset incorrect 

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2407]
With the a master build from this month I visited the Apollo 17 station 6 boulders and they were slightly under the height map. So that the footprints are no longer visible

**Comment by alexanderbock** [comment]
@micahnyc Which height map was that against?

With the USGS & station6 heightmaps I'm seeing the opposite:
![image](https://user-images.githubusercontent.com/4921724/213881417-d1e2e5a2-7e17-4987-bdd3-58f048a43272.png)

**Comment by micahnyc** [comment]
![OpenSpace_000001](https://user-images.githubusercontent.com/708535/225331418-1bb7cb60-d158-4eeb-8b0b-7603289f701d.png)

0.17.2 vs 19

![OpenSpace_000000](https://user-images.githubusercontent.com/708535/225331563-47147e50-c827-47e3-8da0-33abb63648f6.png)


looking it might just be a result of the stairstepping issue

**Comment by alexanderbock** [comment]
Fixed with 475f3c63c2e090ca23df4764d690ca955d3e561e
