### ISSUE TITLE
Profile Editor: Unexpected behavior when saving actions / keybindings

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2417]
Problem: 
- Edit a profile and open the Action and Keybindings window
- Creating a keybind/action and saving
- Closing the Actions and Keybindings window using the 'X' button of the window (top right)
=> the keybind/action is not actually saved, as I did not click the final "save" button at the bottom of the page

**Comment by WeirdRubberDuck** [comment]
A suggested solution, that might also solve some finisky behavior with the "+" and "-" button on Save/cancel, would be to use modal dialogs for the keybind or action creation instead

**Comment by GPayne** [comment]
This is very closely-related to issue #2362, which I merged a fix for in f6988ea. I haven't yet closed that issue, and will wait to do so until this is better understood.
Are saying you closed the window using the window frame's top 'X' button? If that is what you are referring to, then I don't think this is unexpected behavior. To me it would be like clicking cancel at the bottom of the dialog.
However, I did notice the finicky behavior with the "+" and "-" buttons that you mentioned. I will create a fix for the behavior of those buttons.

**Comment by WeirdRubberDuck** [comment]
Yes, exactly. I closed the window using the x button at the top. Updated the steps in the description to clarify

**Comment by alexanderbock** [comment]
For now, removing the extra Save/Cancel button at the bottom that causes the _actual_ save.  Instead, Saving the actions part directly changes it

**Comment by GPayne** [comment]
Resolved in commit a0a42ee
