### ISSUE TITLE
Add Fade property to more things

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2421]
Such as globe layers, components, labels, etc. All of which we want to be able to programmatically fade in/out. 

And while looking at this, maybe also add a `openspace.fadeIn(IdentifierOfRenderedThingy)` function (and fade out)

**Comment by WeirdRubberDuck** [comment]
One thought would be to have a general interface/abstract class to handle this for all things we want to be able to fade, either something like `RenderComponent`, or `Fadeable` or something

**Comment by WeirdRubberDuck** [comment]
Things that should be fadeable:
* renderables
* layers
* ring components 
* labels (essentially all components that are part of other things)
* screenspace renderables


There has also been desire for the selection property of renderable components to fade-in and out the individual components (e.g. constellations). That's probably going to have to be implemented some other way though, as this just turns on and off pieces of the rendering and are not individual property owners

**Comment by WeirdRubberDuck** [comment]
It's currently not possible to set the opacity of the rings, so ended up not looking at that for now. Should be made a separate issue

**Comment by alexanderbock** [comment]
I just pushed a change for that in #2557, too
