### ISSUE TITLE
Image with odd pixel dimensions cases crash in renderablesphere

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2428]
When creating a renderablesphere with a texture where the dimensions had odd pixels, openspace was crashing. When I resaved the image with one less pixel width, openspace didnt crash when loading it.

**Comment by alexanderbock** [comment]
@micahnyc  Can you provide the texture?  I couldn't replicate the problem:

```lua
openspace.addSceneGraphNode({Identifier="abc", Renderable={Type="RenderableSphere", Size=10000, Segments=40, Texture="A:/openspace/OpenSpace/data/small-cat.png"}});
```
with the attached image of size 123x123
![small-cat](https://user-images.githubusercontent.com/4921724/213873360-b8b8bb5d-6739-4cfc-83a7-d7d93b1b7b58.png)

**Comment by micahnyc** [comment]
Well, From slack: "I resaved it with 6892 instead of 6893 and it worked" but looking at the files, the resaved version was 12mb instead of 45mb, so maybe it was the filesize
