### ISSUE TITLE
Npm version 8.6.0 dependency install problems

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2443]
Installing dependencies with npm version 8.6.0 (the one you get with Node at the time of writing) leads to errors. Specifically, with webpack. See image below

Did not look into detail why. For now, a working workaround is to use npm version 8.5.5. To downgrade, run `npm install -g npm@8.5.5`

![image](https://user-images.githubusercontent.com/8808894/162695338-29e888ca-a748-45ab-b70c-149414bd1b3a.png)

**Comment by alexanderbock** [comment]
@WeirdRubberDuck  Still an issue?

**Comment by WeirdRubberDuck** [comment]
Should not be. And if it reappears we should address the dependency conflicts.
