### ISSUE TITLE
Spice data conversion does not convert years before <1000 BC

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2448]
https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/FORTRAN/spicelib/timout.html

Exception 2: If PICTUR contains the numeric marker 'YYYY' and the magnitude of year is too large to be displayed as a four-digit integer, TIMOUT will replace it by '****'.

Maybe there is a way around it;  if not, we can close as a wontfix

**Comment by micahnyc** [comment]
Related: https://github.com/OpenSpace/OpenSpace/issues/2338

**Comment by alexanderbock** [comment]
Fixed by using the et2utc_c function in cases where timout fails;  But there is a problem left (for @ylvaselling maybe), that causes the datetime component to not show the time correctly.

For >=-1000 years it works:
![image](https://user-images.githubusercontent.com/4921724/214905255-67c3c0e0-0bfe-44be-958e-707d96c792c2.png)

But for the ones below the string is not parsed correctly:
![image](https://user-images.githubusercontent.com/4921724/214905358-05932648-0341-4821-ae03-8f31edfbc371.png)

For the years <-1000 the expected date string is:
`YYYY B.C. MON DAY HR:MN:SS.###`

**Comment by alexanderbock** [comment]
As @micahnyc   now it is basically a duplicate of #2338

**Comment by alexanderbock** [comment]
closing it in favor of #2338
