### ISSUE TITLE
Update static data

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2450]
For v19 we should update the data that we have pulled from other sources:

- [x] exoplanet data (@WeirdRubberDuck)
- [x] sssb data (@GPayne)
- [x] generic kernels (@alexanderbock)

----- a note from DWeigal, we should consider updating out wwt-webclient code base
- [ ] wwt-webclient

**Comment by micahnyc** [comment]
From dan: 

there's already and updated kernel for the Jupiter system with the 12 new moons: jup345 as well as some moons in the jup344 kernel that aren't currently in OpenSpace https://ssd.jpl.nasa.gov/sats/ephem/ (current kernels are 310 and 341). Looks like an easy update for the next version and we could share our updated minor moons asset

**Comment by alexanderbock** [comment]
Exoplanets should be updated again
