### ISSUE TITLE
GUI allows, and crash, when input field has NaN value

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2452]
This may be two separate issues in tandem.

1. In some number fields you're able to submit empty string - this results in _NaN_.
Example of this is for `MinMaxSize` and `FadeDistances` in `RenderableLabel`.
Other input of similar type always reverts to the last set value if you try to input an empty string.

2. When the input as value of _NaN_ the GUI crashes if you try give it another input or increment/decrement it using keyboard/GUI arrows.

Demonstration:

https://user-images.githubusercontent.com/9076357/215051665-a786e800-0775-4adb-9221-ea409e457be7.mp4

**Comment by WeirdRubberDuck** [comment]
Expected behavior: Empty input should just reset the previous value
