### ISSUE TITLE
Items in actions panel should be ordered alphabetically

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2457]
Now they are not and that makes the lists pretty difficult to navigate when looking for somwthing specific

Example, order of the folders here: 
![image](https://user-images.githubusercontent.com/8808894/215452410-d9f88572-6d9f-46af-a162-c93342ef9bc3.png)

**Comment by alexanderbock** [comment]
Fixed in 3d955542220817f9ee11fc90d46947c75b8cd664

**Comment by alexanderbock** [comment]
Double check that the folders are sorted by GuiPath first, then stable sort on name
