### ISSUE TITLE
Globebrowsing support on Intel cards

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#246]
When trying to render the `globebrowsing.scene` on an integrated GPU in the Alienware 13", no rendering shows up for the planets.
Potentially related to AMNH dome bug?

To test:  get a hold of Anders' Alien and set the GPU to "integrated" in the Nvidia control panels

**Comment by kbladin** [comment]
Have we tried on any non-Alienware integrated Intel GPUs?

**Comment by alexanderbock** [comment]
The only one who I know has one is @jonathanbosson 

I have tried it on the Intel integrated GPU on my MacBook (but only in MacOS, where it works)

**Comment by jonathanbosson** [comment]
I have an Intel NUC6I7KYK with integrated Iris Pro Graphics 580 and for me the `globebrowsing.scene` is working without graphics issues.

**Comment by MichaelSjostrom** [comment]
I have one with intel HD 4400. Will try it this weekend if i get OpenSpace up and running.

**Comment by jonathanbosson** [comment]
As of yesterday with the new HTTPS link to GDAL will no rendering show up for the planet on my Intel computer. Why this wasn't the case for me when the ESRI images could be downloaded but is now could be interesting to investigate.

**Comment by alexanderbock** [comment]
It is working these days
