### ISSUE TITLE
Spout configs not working 

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2461]
I download the demo reciever app from here: https://github.com/leadedge/Spout2/releases and tried our configs but it was not able to receive.

**Comment by alexanderbock** [comment]
All of the configurations either worked or didn't even load, so closing this:
 - single_gui_spout
 - spout_output_cubemap
 - spout_output_equirectangular
 - spout_output_fisheye
 - spout_output_flat didn't work at all (fixed in 3f35fa992af6b599473a4bbc636d8234b18dda7a)
