### ISSUE TITLE
GeoLocation Panel - error adding focus node with whitespace in name

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2468]
It resulted in this script:
openspace.addSceneGraphNode({["GUI"] = {["Path"] = "/GeoLocation"},["Identifier"] = "Middleburgh, NY, USA",["InteractionSphere"] = 300000,["Parent"] = "Earth",["Transform"] = {["Translation"] = {["Altitude"] = 0,["Globe"] = "Earth",["Latitude"] = 42.59808000000004,["Longitude"] = -74.33440999999993,["Type"] = "GlobeTranslation"}}})

with this error:

Error executing script '': [string "return openspace.addSceneGraphNode({["GUI"] =..."]:1: Error loading scene graph node: Identifier must not contain any dots or whitespaces

**Comment by alexanderbock** [comment]
Identifiers with spaces have never been allowed but were previously only checked in Debug mode.  The script that generates the table should using the current identifier "Middleburgh, NY, USA" as the `Name` and convert the name into a proper identifier by removing spaces, for example to be used as the `Identifier`
