### ISSUE TITLE
GettingStartedTour - Goto position section too hard.

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2471]
When using this I had a hard time for 2 reasons.

1 - at first I ignored the 'goto greenland' and only looked at the orange text and the highlighted dashboard item. Then it was hard to get the globe to goto the right numbers as the grid is sperical and not intuative. 

2 - If you do see the 'goto greenland' part, but the time is wrong, then it won't be visible on the map, and can be hard to get to. 

My proposed solution would be to more emphasize the text 'Lets goto Greenland' and then set the earth layers and llighting conditions to be global during the tour

**Comment by alexanderbock** [comment]
Maybe increasing the acceptance radius as well?

**Comment by ylvaselling** [comment]
I increased the acceptance radius [in ](https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/tree/f53494f752a157eb13ede789875de12dda4e9196)

Would be good with some feedback if this is enough

**Comment by alexanderbock** [comment]
Looks good :+1:
