### ISSUE TITLE
Skybrowser -better handling of sky survey images in "All images" list

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2479]
I saw that we have a little note in the UI if the image is a sky survey. As a sky survey does not have any position on the sky it does not make the sky target move. This makes sense, but I had a sense of confusion when clicking a sky survey image without realising it, as I expected the target to move. 

Perhaps we could split the "All images" list into two: One with "regular" images and one with sky surveys? Or have some button that hides the sky survey images from the list. Since we already have the classification, it should not be too difficult

Needs more discussion on what would be a good solution

**Comment by carteremmart** [comment]
Yes, categories would be "Sky Surveys" and "Images", to keep it brief.  I figured the design might be a roll-over or drop down from a "categories" top level menu item in the WWT GUI.

**Comment by ylvaselling** [comment]
To discuss: will there be more categories in the future?

**Comment by WeirdRubberDuck** [comment]
@alexanderbock we would like to discuss this at some Tuesday meeting :)

**Comment by alexanderbock** [comment]
![image](https://user-images.githubusercontent.com/4921724/218521084-3d42943b-12f5-445d-9aff-ed84856dd137.png)
