### ISSUE TITLE
Error in factory pattern for TileIndexTileProvider

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#248]
MOLA heightmap not working

```
"Class 'class openspace::globebrowsing::tileprovider::TileIndexTileProvider' does not provide a constructor receiving a Dictionary"
```

**Comment by kbladin** [comment]
How is the TileIndexTileProvider related to the MOLA heightmap?
Is the MOLA issue related to #242 ?

**Comment by alexanderbock** [comment]
The factory error is just something that showed up at the same time as MOLA disappearing.  It might also be a server error;  haven't investigated yet
