### ISSUE TITLE
Missing images in skybrowser?

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2480]
Currently, in the "All images" list, I get about 1500 images. I have a sense that there used to be more?

I also get a bunch of CORS related messages that images have been blocked in the log. Don't remember that these used tobe there

This all needs some more investigation. Does anyone else experience the same "problems?"

![image](https://user-images.githubusercontent.com/8808894/216293322-e339bc3f-3519-4a0d-9fee-d8927b9e8fda.png)

**Comment by alexanderbock** [comment]
Investigate whether the addition of the eso "fixed" it.

Talk with WWT to see if the underlying data changed

**Comment by alexanderbock** [comment]
It's >5000 now
