### ISSUE TITLE
Reoccurring crash during launch when loading DigitalUniverse Deepsky Texture M9

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2482]
OpenSpace crashes quite consistently during launch when trying to load resource: `...sync\http\digitaluniverse_deepsky_textures\1\M9.png`

Specifically the crash always happen during the "initializing OpenGL" phase when it tries to create image planes of the texture.
![crash_m9](https://user-images.githubusercontent.com/9076357/216307270-b70fd1f9-0deb-456e-b7bb-bd3dc8457f24.png)

This has happened for several times during the last week for me using different stages of the master branch.
After a crash it will load perfectly fine the following times.

I've attached three log-files
[log_crash.zip](https://github.com/OpenSpace/OpenSpace/files/10568126/log_crash.zip)

**Comment by Arohdin** [comment]
Got same crash again but this time it was for texture M80.png

**Comment by alexanderbock** [comment]
Seems to be related to https://github.com/OpenSpace/OpenSpace/issues/2428

I updated the images to be of even pixel sizes and the crash no longer happens
