### ISSUE TITLE
Crash during startup when trying to bind undefined action to key in profile

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2485]
OpenSpace crashes during startup if you try to bind an undefined action to a key in the profile.

example snippet from profile that would make OpenSpace crash:
```
.....
"keybindings": [
    {
      "action": "thisActionDoesNotExist",
      "key": "E"
    }
....,
```
![undefinedaction](https://user-images.githubusercontent.com/9076357/216563112-5d0286a6-1a81-43cb-9b1e-0b0688d6d96b.png)

OpenSpace does not crash if you try to do the same within an asset.
In this case you just get "failed to initialize asset" in error logs instead.

**Comment by Arohdin** [comment]
Maybe a non-issue of if the profile editor becomes the de facto way of creating and editing profiles.

**Comment by WeirdRubberDuck** [comment]
You could still bind an action that is not shown in the UI to a key through the profile editor, so definitely still a problem :)
