### ISSUE TITLE
Adding layers without identifier in info file, creating checkbox on color layers in UI

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2490]
Calling this is working to add the layers to mars, but when I add them, then in the UI the ColorLayers gets a checkbox (presumably code around the group enabling?) and then I can no longer open the color layers.

openspace.globebrowsing.addBlendingLayersFromDirectory("C:/OpenSpace/OpenSpaceData/Mars/CTX", "Mars");

**Comment by micahnyc** [comment]
This is happening for me in v18

**Comment by micahnyc** [comment]
![image](https://user-images.githubusercontent.com/708535/217057061-52f39482-20b8-4bf9-ad95-18caba42b881.png)

**Comment by micahnyc** [comment]
Actually turned out to be that one of the .info layers in the folder didn't contain an identifier...when adding an identifier into the .info file, it worked as expected.

**Comment by WeirdRubberDuck** [comment]
Still a bit weird that the Property Owners gets checkboxes in the UI >.>
