### ISSUE TITLE
Keybindings not working 

### ISSUE THREAD

**Issue by Roxeena** [OpenSpace/OpenSpace#2500]
Start OpenSpace and press any key with a keybinding bound to it, then get disappointed when nothing happens  :(

**Comment by Arohdin** [comment]
Fixed in: [cb45f96](https://github.com/OpenSpace/OpenSpace/commit/cb45f962e5f5cf344981b72323e0eb7c37889493)

**Comment by Arohdin** [comment]
Note: updated solution in [e69ec8a](e69ec8ac4d9606202a8d055d81e9a4495608a03d)
