### ISSUE TITLE
Add the ability to load a Fisheye image as a screenspace image

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2506]
Being able to load a fisheye image and render it so that it covers the entire dome

Potential solution:
Loading a fisheye image and automatically placing it on the top half of a RenderableSphere, for example.

**Comment by hedbergj** [comment]
https://github.com/OpenSpace/OpenSpace/issues/995

**Comment by alexanderbock** [comment]
*cough*  should be thinking before typing!

Closing as duplicate of #995
