### ISSUE TITLE
saveNavigationState provides no error when writing to file fails

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2508]
Seems like openspace.navigation.saveNavigationState does not save-to-file properly.
The correct function is being called and it seems to be doing what it is supposed to be doing, however,  `ofstream` does not produce any file in specified output folder.

No addition errors are given.

**Comment by WeirdRubberDuck** [comment]
It does save to file, when it works :) However, better error messages could be provided when saving to weird places

**Comment by WeirdRubberDuck** [comment]
The saveToNavigationState function should provide errors/warnings if the printing to file did not work
