### ISSUE TITLE
Rosetta mission's comet 67P should have shading enabled by default

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#2514]
In the Rosetta profile, comet 67P looks like this on startup:
![Screenshot from 2023-02-16 20-16-41](https://user-images.githubusercontent.com/3966290/219541092-254c9ef4-46f2-47c9-8501-52170234bfb8.png)

"Perform Shading" should be enabled by default so the user doesn't have to go into the menu to enable it:
![Screenshot from 2023-02-16 20-17-29](https://user-images.githubusercontent.com/3966290/219541098-095d6a3c-f1e6-4d2d-98c6-70b9709b2bb6.png)

**Comment by Arohdin** [comment]
PerformShading is being set to false in the profie for rosetta.
@alexanderbock Do you know if there is any specific reason for this?
If not, I'll just update the profile and close this issue.

**Comment by GPayne** [comment]
@Arohdin thanks for offering to update it and close this, but the main reason I made this issue (instead of just fixing it because it's pretty simple) was to discuss it at next week's issue meeting to see if there are reasons to have it disabled it by default. I'm fine waiting until Tuesday.

**Comment by Arohdin** [comment]
Makes sense, let's discuss on Tuesday

**Comment by GPayne** [comment]
Apparently the reason for shading disabled by default was to prevent interference with image projections on the surface.
However, there seem to be no image projections performed in this mission, even though the 67p.asset file is written to do a series of them.

**Comment by GPayne** [comment]
Closed in eacc5b2 using scheduled scripts to enable/disable shading before/after image acquisitions.
