### ISSUE TITLE
Epicycle asset 

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2518]
For educational purposes we could create and asset for showing the earth centric model. We have the trails, need to make and asset, actions, and add the sun-from-earth trail

**Comment by hedbergj** [comment]
Not sure what happened to mine, but it's somewhere...

<img width="471" alt="Screen Shot 2023-02-20 at 12 29 29 PM" src="https://user-images.githubusercontent.com/7926907/220170684-7e5051f9-9279-48f1-b343-cd3c02f94d3a.png">
