### ISSUE TITLE
Property owners get wrong name in GUI

### ISSUE THREAD

**Issue by Roxeena** [OpenSpace/OpenSpace#2521]
I gave a property owner a GUI name that was different from its identifier, but in the GUI the identifier shows up instead of the GUI name I provided, see image.

![propertyOwnerName](https://user-images.githubusercontent.com/16215103/220312101-61dad117-1117-4465-b1ac-c759cd389142.PNG)

Also, do we use the description of the property owners at all in the GUI?

**Comment by WeirdRubberDuck** [comment]
Mind reader? I just looked at this and the name problem is fixed. Just gotta update the GUI hash
https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/commit/d4ae62b33d674a3b39a86058bee62359fbcd67e5

Good timing, wanted to talk about the description part at our next meeting. Just made a comment for discussing it in the commit above
