### ISSUE TITLE
Earth has wrong position depending on asset require order

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2526]
## Explanation
When including `Voyager2.asset` the Earth gets a weird position between 1977 AUG 20 at 23:59:12 to 1977 AUG 24th at 23:59:12.
This happens only when `Voyager2.asset` is loaded **_after_** `scene/solarsystem/planets/planets.asset` .

## Working

```
asset.require("base_blank")
asset.require("scene/solarsystem/missions/voyager/voyager2")
asset.require("scene/solarsystem/sun")
asset.require("scene/solarsystem/planets/planets")

```
![asset-order-right](https://user-images.githubusercontent.com/9076357/220957082-375718c8-1ebe-4672-80e2-7771c1c5d0fa.png)

## Non Working

```
asset.require("base_blank")
asset.require("scene/solarsystem/sun")
asset.require("scene/solarsystem/planets/planets")
asset.require("scene/solarsystem/missions/voyager/voyager2")

```
![asset-order-wrong](https://user-images.githubusercontent.com/9076357/220957051-6002295c-96dc-4926-ac8d-52a902b80a2a.png)

**Comment by Arohdin** [comment]
Issue still remains in latest commit 2189a71

**Comment by Arohdin** [comment]
This issue was encountered again where _required_ order messed up Apollo 8 capsule (it was missing) and Earth Rise position action (wrong position in space).

**Comment by Arohdin** [comment]
Does not seem to happen in master at the moment.

**Comment by alexanderbock** [comment]
@micahnyc will provide a new example to reproduce

**Comment by engbergandreas** [comment]
Can't be replicated other example was using 0.19.2
