### ISSUE TITLE
Property owners with only enable property does not show up in GUI

### ISSUE THREAD

**Issue by Roxeena** [OpenSpace/OpenSpace#2528]
If a property owner only has 1 property and that property has identifier `Enabled` (to make a pretty checkbox), the property owner does not show up in the GUI. However, if I change the property's identifier to `isEnabled`, it shows up in the GUI. 

Property exists:
![enabledProperty](https://user-images.githubusercontent.com/16215103/221223601-e19f05f4-77e7-411d-b78f-0c51f596415d.PNG)

No Cosmic View Sonification property owner in `GUI:`
![enabledPropertyGui](https://user-images.githubusercontent.com/16215103/221222737-97098522-7fb0-4596-a1eb-196279b479aa.PNG)

**Comment by WeirdRubberDuck** [comment]
Found the problem: Currently we have a check in the GUI when creating the tree for whether the propertyowners it's a "dead end", which it is when it only has hidden properties, either only the "Enabled" ()which we currently always hide in the list of properties) or if all properties are hidden through the user visibility setting. 

I could fix it pretty easily, but think the desired solution requires some discussion, to not result in weird behavior when changing the visibility setting, e.g. a bunch of empty property owners showing up that novice users shouldn't have to care about. 

One suggestion would be to not hide the Enabled property in the list. This is the easiest solution, as it requires no extra checking and would work well with the visibility setting (as the enabled property would also listen to the visibility setting then, which it currently does not, really). It would also make the property info for the enabled property visible in the UI, it currently isn't. See video for example: 

https://user-images.githubusercontent.com/8808894/222394125-0e560624-e05c-4090-a477-b1e196f4bbd3.mov

However, I understand if people thinks this looks weird/confusing with having the Enabled property existing twice in the UI

**Comment by WeirdRubberDuck** [comment]
Not in the video that we also get the "Is Enabled" property for the renderables.... However, we could actually check for that specifically and not include the property for renderables, but for other propertyowners   (whihc is actually how the "Show only enabled" setting does it now. It only checks for enabled _renderables_, not other propertyowners)

**Comment by WeirdRubberDuck** [comment]
Ended up keeping the chevron icon for empty property owners, as any alternative looked weird or was very confusing.
