### ISSUE TITLE
Several viewports for one windows does not work

### ISSUE THREAD

**Issue by Roxeena** [OpenSpace/OpenSpace#2542]
A configuration file with one window and two side-by-side viewports no longer works. It looks like this:

![OpenSpace_000000](https://user-images.githubusercontent.com/16215103/224296943-7fc2c51f-4b54-470a-b87a-8fd296f9f98f.png)

Here is the configuration file I tested with:
[issue-viewports.zip](https://github.com/OpenSpace/OpenSpace/files/10941254/issue-viewports.zip)

**Comment by GPayne** [comment]
Reproduced on linux
