### ISSUE TITLE
SGCT editor creates stretched image for portrait windows

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2546]
I tried to create a window fitted for 1080 x 1920 pixels. That created a stretched image in OpenSpace. I had expected a regular image

![image](https://user-images.githubusercontent.com/24265984/225118879-ab2988ea-30b5-4138-a93d-071201f9d813.png)
![image](https://user-images.githubusercontent.com/24265984/225118927-4b27ca25-1adc-4510-bbf7-61459e12d1eb.png)

**Comment by GPayne** [comment]
The window GUI's FOV calculations for window size need to be fixed for handling portrait windows like this.
For now, you can get it to look right by unlocking the FOV values and entering your own. Keeping the horizontal FOV of 80 and setting the vertical to 110 degrees looks about right.

**Comment by GPayne** [comment]
Closing this upon merging PR#2554
