### ISSUE TITLE
RenderableStars/SpeckLoader- error message not informative

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2549]
When loading a speck file that had an issue with the headers, we wound up getting an error from the RenderableStars `Could not find required variable 'luminosity'"`

from this line:
https://github.com/OpenSpace/OpenSpace/blob/d8ff505f338520041abcd81e99c8662a3b205368/modules/space/rendering/renderablestars.cpp#L1343

In reality, the issue was that the dataset was empty because of the issue with the headers, but we spent time trying to figure out the luminosity problem. We should provide an error message like "dataset emtpy" or "error loading dataset" from the speckloader (or even better "error with header columns" if we can figure that out). 

[test.speck.txt](https://github.com/OpenSpace/OpenSpace/files/10981585/test.speck.txt)

**Comment by alexanderbock** [comment]
Side-effect of this implementation is now that we no longer allow optional keywords in the header block of Speck files.
The only allowed keywords are `datavar`, `texturevar`, `polyorivar`, `texture`, and `maxcomment`.
