### ISSUE TITLE
Ensure the Parallel Connection is still working

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2561]
We should check that we can still connect to the new version of the Wormhole server and make sure that the message sending and receiving is still working correctly.

**Comment by engbergandreas** [comment]
I have not tested connecting multiple users to a session. However, but there are package losses related to a low Camera- and Keyframe interval value. Logging error messages gives the following output (img)

**Comment by alexanderbock** [comment]
Did test the multiple users and didn't get any messages and camera works as expected
