### ISSUE TITLE
If you create an actions that is set to not local, it creates a local function

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2566]
To reproduce: 
1. Create an action. Don't set it to local.
2. In the GUI it shows up as not synchronized (local)

![image](https://user-images.githubusercontent.com/24265984/228277862-5473203f-a0bf-49a3-8cce-79d55be75079.png)
![image](https://user-images.githubusercontent.com/24265984/228277998-da8927fa-7db1-48ea-9d4f-407c85c071d2.png)

The function doesn't seem to be local from the profile however:
![image](https://user-images.githubusercontent.com/24265984/228369716-09e2d388-8577-4a7d-9493-0b5b613a139f.png)

**Comment by alexanderbock** [comment]
The `is_local` is ready correctly out of the profile file

**Comment by WeirdRubberDuck** [comment]
Wanted to verify that it was not any problem with the UI coinvertedde, so looked at this quickly. This looks like it could be the problem: https://github.com/OpenSpace/OpenSpace/blob/9fd70834e6fca339c26d4a3d89331674fc5c9a64/src/engine/openspaceengine.cpp#L1814 

Th synchronization value is set to the "isLocal" value from the profile, but it should be the inversted value. In the midst of doing work in another branch, so maybe @alexanderbock could fix it?

Note that the synchronization value is sometimes undefined in the UI code (e.g. for setting the delta time and toggle friction). I don't know why, but as long as undefined means that it should not be local, the cehck should work as expected. Think we should verify that they are all correct, though. Some examples
![image](https://user-images.githubusercontent.com/8808894/228832993-1e6fbdf2-9c94-410f-b9a9-d8612fced295.png)
