### ISSUE TITLE
Add the ability to jump to a path endpoint

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2568]
It would be nice to be able to jump directly to a scene graph node.  Suggested way would be to use Shift+Air plane icon to jump directly to the endpoint of the path instead of flying to it.

**Comment by WeirdRubberDuck** [comment]
Good idea! And would actually be very easy to implement in the UI

**Comment by WeirdRubberDuck** [comment]
Implemented to apply when holding SHIFT and clicking the fly to buttons in the GUI.

Note that it is also possible to call the `openspace.pathnavigation.skipToEnd()` function during a path to jump to the path endpoint
