### ISSUE TITLE
Orbiting around an object without a defined bounding sphere fails

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2572]
From Slack
> When I have a Local Bookmark targeted and I try to apply idle behavior, with the idle behavior set to "OrbitAtConstantLatitude" or "OrbitAroundUp", it sends the camera out to inf Gigaparsecs. Works as expected for the "Orbit" idle behavior. Then when I try to get back I can jump there with scripting but using the automatic flight/zoom it seems like its never going to get back (or take infinite amount of time?)

**Comment by WeirdRubberDuck** [comment]
Additional comment from slack: 

> Just to add, I see now that using Zoom-To takes an infinite amount of time but trying Fly-To makes openspace unresponsive

**Comment by WeirdRubberDuck** [comment]
Started looking at this but have come to no solution yet. Just as described we get a really quick increase in position values when triggering "OrbitAtConstantLatitude" or "OrbitAroundUp", for any added Bookmark. This eventually becomes NaN positions for the camera
