### ISSUE TITLE
Rendering artefact when close to space craft w stereoscopic depth

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2582]
A rendering artefact appeared when using stereoscopic depth close to a spacecraft

https://user-images.githubusercontent.com/24265984/230194315-64088c33-4e16-4097-86de-8b666143d835.mp4

**Comment by ylvaselling** [comment]
https://user-images.githubusercontent.com/24265984/232581558-471bfc5c-8b2b-4d17-ae8e-e8d53e0ae770.mp4

**Comment by alexanderbock** [comment]
Duplicate of #1455
