### ISSUE TITLE
New default property values for path navigator

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2584]
Suggestions for new default property values for the path navigator:

Rotation Speed Factor: `1.5` - `2`
Apply Idle Behaviour on Finish: `true`

The current default for rotation speed is very fast in a dome environment, and something we have talked about many times in Hayden. Changing the value makes the rotation a lot slower and should be the default in my opinion. I also think the idle behavior on finish looks super polished and would be a nice thing to have as default (should be a discussion of course)

**Comment by alexanderbock** [comment]
:+1: on the new rotation speed factors

:-1: on enabling it by default from my side, but yea. Let's talk about it tomorrow

**Comment by WeirdRubberDuck** [comment]
Was a bit confused about this, but apparent the rotation speed factor actually does the opposite of what it says it does... A higher value => slower (longer duration), and a lower value means faster (shorter duration)

Created a new issue for it: https://github.com/OpenSpace/OpenSpace/issues/2838

But yes, I agree on changing the default value to something slower 👍 

But not enabling the idle behavior on finish per default

**Comment by WeirdRubberDuck** [comment]
Conclusion from issue meeting: Just update the rotation speed factor
