### ISSUE TITLE
Crash in JWST profile when going to date 14th of April 2021

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2617]
OpenSpace crashes (out-of-range iterator for Vector) when going to date 14/04/2021
![image](https://user-images.githubusercontent.com/9076357/232041416-ec055934-00f9-443c-a87f-db116449a97c.png)

The crash comes from ScriptScheduler.cpp (row 227):

![image](https://user-images.githubusercontent.com/9076357/232041823-124b9f47-b48f-4b71-8c6b-5196e2203a42.png)

**Comment by Arohdin** [comment]
Issue can be avoided by changing

```
auto start = _scripts.begin() + prevIndex - 1;
```
to
```
const auto startOffset = prevIndex == static_cast<size_t>(0) ? prevIndex : prevIndex - 1;
auto start = _scripts.begin() + startOffset;
```

Not sure if this is a correct approach as I am not 100% sure what the expected outcome would be in this case - seems to work OK though...

**Comment by alexanderbock** [comment]
Yep, that worked!
