### ISSUE TITLE
All of GUI bottom bar becomes opaque when hovering over a popup

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2618]
Reported by @alexanderbock 

The expected behavior is that only the picker gets opaque? Should be discussed

![image](https://user-images.githubusercontent.com/24265984/232137072-adddc123-34a5-488e-895f-2e86caeabecb.png)

![image](https://user-images.githubusercontent.com/24265984/232136881-90d0649e-3c8e-4b3d-9879-99fabc772b9f.png)

**Comment by alexanderbock** [comment]
That was a dumb idea by @alexanderbock
