### ISSUE TITLE
Add search to Profile Editor

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2623]
I was trying to find an asset that didn't load and found it difficult to find it in the Profile Editor. A search would be great for cases like this
![image](https://user-images.githubusercontent.com/24265984/232516492-0ffe4004-1cb9-448a-80a8-66cea5af786c.png)

**Comment by micahnyc** [comment]
It would need this issue too: https://github.com/OpenSpace/OpenSpace/issues/2374 since the asset you were looking for was actually included by another file that was included by the base

**Comment by alexanderbock** [comment]
No need for Micah's part yet (but would be awesome).

This means filtering, rather than searching
