### ISSUE TITLE
Mars trail is not visible in Asteroids profile

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2626]
When loading the asteroids profile the Mars trail is no visible even though it is loaded in the GUI. Tried changing the settings in the trail but no success

![image](https://user-images.githubusercontent.com/24265984/232589742-6e873e54-e46d-4cd6-b989-1f8728cc1562.png)

**Comment by GPayne** [comment]
I cannot replicate this. In the latest master branch build, I am seeing the Mars orbital trail.
