### ISSUE TITLE
Adding a limit on the Globebrowsing cache

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#263]
Otherwise, it will eventually overflow the available RAM and kill the application.  I think it would be best if there it would make use of the available RAM * a user definable factor (for example, allowing the cache to maximally use 50% of the available RAM.

As a secondary safeguard, it should detect when memory has run out and stop allocating new memory.

**Comment by kbladin** [comment]
Any suggestion for the secondary safeguard? I guess we don't want to override the new / malloc operations to keep track of all allocated memory. Right now the cache is able to keep track of the memory stored for tiles in the LRU cache but then there are a bunch of other data we can't keep track of, like the GDAL cache among other things.

I have set the "maximum maximum size" of the tile cache to 25% of the total RAM and the "maximum maximum size" of the GDAL cache also to 25%. The default maximum is significantly smaller though (assuming you don't have very little available RAM).

**Comment by alexanderbock** [comment]
In the best case (for performance as well), we could give GDAL a preallocated block of memory to write the textures in..   or alternatively give it an allocator function to call (which we would then use to manage a preallocated block of heap memory). 

A very crude safeguard would be catching the out of memory exception.

**Comment by kbladin** [comment]
Hm ok. Not sure how that would be implemented. GDAL does its own heap allocations. How do I give GDAL a preallocated block of memory? I haven't found a way to set a custom allocator function either.
Catching an out of memory exception can be done I guess but it will not be completely safe since the exception can potentially be thrown outside of the globebrowsing module as well from where we can't clear the cache.

**Comment by kbladin** [comment]
Tried this code for testing but windows forze completely, had to force a reboot:

	std::vector<int*> testData;
	try {
		if (!didAllocations) {
			didAllocations = true;
			while (true)
			{
				testData.push_back(new int[512]);
			}
		}
	}
	catch (std::bad_alloc) {
		for (size_t i = 0; i < testData.size(); i++)
		{
			delete [] testData[i];
		}
		testData.clear();
		LWARNING("Out of memory! Clearing tile cache.");
	}

I think it had time to allocate around 6 GB then it froze..

**Comment by alexanderbock** [comment]
For me it works in a separate program:
```cpp
#include <vector>
#include <iostream>

int main(int argc, char** argv) {


    std::vector<int*> testData;
    testData.reserve(1024*1024);
    try {
        while (true)
        {
            testData.push_back(new int[2048*1024]);
            std::cout << '.';
        }
    }
    catch (std::bad_alloc) {
        for (size_t i = 0; i < testData.size(); i++)
        {
            delete [] testData[i];
        }
        testData.clear();
        std::cout << "Out of memory! Clearing tile cache.";
    }
    return 0;
}
```

So it might be some complications.  Also try to catch the exception by reference, otherwise it might need to hit the heap (not sure if it does with the construction) and that might be bad if you a _already_ out of memory.

**Comment by kbladin** [comment]
Did you also try to do it inside OpenSpace? Can it be the amount of data? Since you allocate 2048*1024 ints, is there more room for movement so to say?
