### ISSUE TITLE
Artifacts and blinking trails with AMD integrated graphics

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2642]
There are a lot of blocking/artifacting and blinking trails when you get close to planets using AMD integrated graphics.

Hardware Specifics:
APU: AMD 7735HS
Integrated Graphics: AMD Radeon 680M
Software Version: 23.4.2 Adrenalin Edition
AMD Drivers: 22.40.51.01 Adrenalin Edition
AMD Windows Driver: 31.0.14051.1000

(Could not screen capture video as OBS ran under Nvidia and OpenSpace ran under AMD)

https://user-images.githubusercontent.com/9076357/234000813-95792d9a-3efc-4941-9e77-04fa63f1d31f.mp4

**Comment by micahnyc** [comment]
Dupe of https://github.com/OpenSpace/OpenSpace/issues/1142 and https://github.com/OpenSpace/OpenSpace/issues/1145

**Comment by Arohdin** [comment]
Closed as duplicate
