### ISSUE TITLE
Interpolated value treated different than set value

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2655]
Somehow, when i use

```
openspace.setPropertyValueSingle("RenderEngine.HorizFieldOfView", 80.000000) 
openspace.setPropertyValueSingle("RenderEngine.HorizFieldOfView", 25.0, 2) 
```

The fov seems to go up first, then down

However when I use this

```
openspace.setPropertyValueSingle("RenderEngine.HorizFieldOfView", 80.000000, 2) 
openspace.setPropertyValueSingle("RenderEngine.HorizFieldOfView", 25.0, 2) 
```
it doesn't

https://user-images.githubusercontent.com/708535/234699982-425e6aaf-a594-4d84-bf4a-6531979b41da.mp4

**Comment by WeirdRubberDuck** [comment]
When starting the second interpolation, you interrupt the previous one. So the 
```
openspace.setPropertyValueSingle("RenderEngine.HorizFieldOfView", 80.000000, 2) 
```
won't happen, as your two interpolated lines try to change the same property

**Comment by alexanderbock** [comment]
I don't think I understand what the problem is since it behaves exactly as it should.
First use-case:
Frame 1: 
```lua
```
