### ISSUE TITLE
Improved search in GUI - also include properties that are hidden based on user visiblity 

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2659]
Suggestion is to start listing all properties that are shown based on the current visibility, and then list the matching properties for other user visibility levels, including what level they would be visible for

Regards the settings UI

**Comment by alexanderbock** [comment]
How about gating this behavior behind an eye icon in the search bar so that by default we respect the visibility settings, but can override them for the search result with that extra button?

Presumably a user chose a visibility setting for a reason
