### ISSUE TITLE
Decide if we want to interpolate time when changing seconds

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2661]
Creating a new issue for the discussion in #2651. Do we want to change the seconds immediately or interpolate when pressing the buttons for changing the seconds in the GUI (not shift-click)?  Currently, there is an interpolation happening

**Comment by alexanderbock** [comment]
I'd say an interpolation since it gives less of an abrupt change that might be jarring;   analogous to how we have a slow ramp up of the camera movements
