### ISSUE TITLE
Camera path - show countdown in dashboard 

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2665]
In the dashboard the camera path could display how many seconds until it reached the target, approaching 0 as it arrives. This would give the presenter an idea of how long they should be talking

**Comment by WeirdRubberDuck** [comment]
related to https://github.com/OpenSpace/OpenSpace/issues/2331, if we want to show it in the UI

**Comment by WeirdRubberDuck** [comment]
How about doing this based on distance instead?  Will be easier to implement than time

**Comment by alexanderbock** [comment]
I think the distance would be a bit harder for a person to judge.  How about doing backwards-differences between the distance to get a speed and then showing distance/speed?  It's not going to be super accurate, but all we need is a good estimate

**Comment by WeirdRubberDuck** [comment]
Sure thing: that computation we already have in the camera path code. 

Just wanted to bring up the option :)
