### ISSUE TITLE
Constellation art flicking between channels 

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2669]
When enabling the constellation art in the dome, the larger images were flickering seemingly when moving between channels

**Comment by alexanderbock** [comment]
Duplicate of #1951, related to #1455, and would be fixed by #1738

Better workaround to make them not flicker is to _not_ disable the "Adaptive Stereoscopic Depth" and set the "Stereoscopic Depth of the Surface In Focus" to a lower value
