### ISSUE TITLE
Major Moon actions

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2675]
We are missing actions to turn on the major moons. 

For example, if you want to show the jupiter system, but not have trails of other planets, you would have to hide the planet/moon trails, show the minor moon trails, and then turn on the major moons individually yourself.

**Comment by Arohdin** [comment]
I can create these.
While doing so, do we want toggles or on/off actions for the moon trails?
Currently for the minor moons we've got on/off, but maybe toggles would be nicer (less visual clutter)?

**Comment by Arohdin** [comment]
Created PR #2734
