### ISSUE TITLE
Video player on globe rendering flickering

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2683]
The whole scene gets a rendering issue when close to a space craft and playing a video on globe

https://github.com/OpenSpace/OpenSpace/assets/24265984/c51e6dae-c2f6-4e76-80c5-ca940a4ed700

**Comment by alexanderbock** [comment]
This looks like a framebuffer handling to me. @Roxeena ?

**Comment by Roxeena** [comment]
I tried reproducing this with JWST and our example video for Earth but I don't get the issue.

https://github.com/OpenSpace/OpenSpace/assets/16215103/54ed4971-651e-4651-bb53-72ba6aecdab5
