### ISSUE TITLE
Add video layer to Jupiter for Juno profile

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2684]
Thought it could be nice to have the video of Jupiter in the Juno profile

https://github.com/OpenSpace/OpenSpace/assets/24265984/0fe9c11c-86aa-48f2-8386-7cfea417744a

**Comment by alexanderbock** [comment]
Do you mean the video as a screenspace or plastered on the Globe?  I'd prefer the second in that case

**Comment by micahnyc** [comment]
yes this would be awesome!
