### ISSUE TITLE
Rosetta image projections stopped appearing

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2695]
For some reason, the images for the Rosetta mission don't appear anymore.

![image](https://github.com/OpenSpace/OpenSpace/assets/24265984/b9f1b5bb-934b-4c2f-9fd7-252d8455b62d)

**Comment by alexanderbock** [comment]
Mh... for me it works:
![image](https://github.com/OpenSpace/OpenSpace/assets/4921724/802cfb34-512f-42da-8f12-e80f9da2bb80)
