### ISSUE TITLE
OpenSpace ignores SGCTConfig commandline argument

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2697]
OpenSpace ignores the SGCT config from the command line. This is a problem when using C-troll.

`OpenSpace.exe --config BypassLauncher=true SGCTConfig=[[${CONFIG}/2020-02-07-with-bezel.xml]]` results in the default sgct config set from the cfg file. It does howver bypass the launcher, which overrides the cfg file. I don't know if this printout could mean something:

```
(D) Configuration        BypassLauncher=true;
(D) main                 SGCT Configuration file: C:\Users\ylvas\AppData\Local\Temp\s5tg.0.json
```

**Comment by alexanderbock** [comment]
Can you try if either:
`OpenSpace.exe --config BypassLauncher=true;SGCTConfig=[[${CONFIG}/2020-02-07-with-bezel.xml]]`
or
`OpenSpace.exe --config BypassLauncher=true --config SGCTConfig=[[${CONFIG}/2020-02-07-with-bezel.xml]]`

works?  Both of those should.


The reason yours didn't work is that `--config`` takes exactly one argument, so --config will get BypassLauncher=true and then the SGCTConfig=...  will go to the unnamed commandline argument instead
