### ISSUE TITLE
Mars CTX map dataset does not show highest resolution for some tiles

### ISSUE THREAD

**Issue by kbladin** [OpenSpace/OpenSpace#270]
Some tiles do not split to use higher resolution textures.

![image](https://cloud.githubusercontent.com/assets/4128312/23648333/897ad868-031a-11e7-93cf-72e53cfb88b7.png)

To investigate: maybe the children of the tile are unable to successfully read tile data at some points and therefore the tile will not split.

**Comment by kbladin** [comment]
Turns out that this is not a bug in OpenSpace but rather in the wms server application. Instead of returning an empty block where there is no data, the server does not return anything. When OpenSpace tries to read certain tiles GDAL returns an error code and the tile does not split because we limit the tile level depending on available data.

Fix:
1. Solve the bug on the server side so that the server can return empty tiles.
2. Perhaps GDAL can be specified to write no-data values instead of returning error codes where there is no data.
3. Add the ability to toggle the use of the chunk level evaluator that limits the level depending on available data (Does not solve the issue completely since there still will be missing tiles and it will also make the application run slower due to unnecessary splits and tile draw calls).

**Comment by alexanderbock** [comment]
What is the status of this?

**Comment by kbladin** [comment]
Fixed by adding `<ZeroBlockOnServerException>true</ZeroBlockOnServerException>` to the gdal wms specification!
