### ISSUE TITLE
Interpolate normals for camera space tile rendering

### ISSUE THREAD

**Issue by kbladin** [OpenSpace/OpenSpace#271]
To avoid cracks that appear between tiles when rendering them using the camera space (also known as local rendering) method, not just linearly interpolate positions, also do it with normals. The problem appears at high altitudes where the curvature of the globe is significant enough to cause cracks (a good example is Olympus Mons where the cracks appear even without changing the multiplier for the height map).

**Comment by alexanderbock** [comment]
I think @jccosta  would benefit from this as well

**Comment by alexanderbock** [comment]
Might not be an issue anymore?

**Comment by alexanderbock** [comment]
Not an issue anymore
