### ISSUE TITLE
Mismatch between Makemake position and trail  

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2717]
The Makemake dwarf planet does not end up at the end of its trail. I think it should? :) 

Note: Observed this in the feature/asset-cleanup branch, but I think it should happen on master as well.

**Comment by WeirdRubberDuck** [comment]
See image. Note that Makemake is scaled up 100 times for it to be more visible
![image](https://github.com/OpenSpace/OpenSpace/assets/8808894/cd5ecc74-e745-4462-9f56-37349a890639)

**Comment by Roxeena** [comment]
The dwarf planets Eris and Haumea also have this issue in master

**Comment by alexanderbock** [comment]
All three affected bodies are RenderableModels
