### ISSUE TITLE
BastilleDay2000 - Cutplane Meridial not displaying

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2737]
The Equitorial cutplane is showing but the meridial is not.

![image](https://github.com/OpenSpace/OpenSpace/assets/708535/62f242a8-c6d4-422c-94c5-0fb0a40dd71e)

**Comment by alexanderbock** [comment]
Can't replicate.  Did create a new sync folder but cutplanes do show up

https://github.com/OpenSpace/OpenSpace/assets/4921724/fd0f76c4-c1d6-40a7-97f0-a89a1a648ab9

**Comment by micahnyc** [comment]
after nuking my sync folder it shows up as well
