### ISSUE TITLE
Error when trying to change Property Visibility in GUI

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#2746]
When trying to change the GUI view from "User" to any other type using menu option:

`Settings->OpenSpace Engine->Property Visibility`

it fails to change the visibility and logs the error:
**(E) property_setValue    [string "openspace.setPropertyValueSingle("OpenSpaceEn..."]:1: : Property 'OpenSpaceEngine.PropertyVisibility' does not accept input of type 'Nil'. Requested type: 'Number'**

Running commit 3414dc5 on master

**Comment by WeirdRubberDuck** [comment]
It's a problem with all option properties (IdleBehavior gives the same problem). I'll look at it

**Comment by WeirdRubberDuck** [comment]
Already fixed by @ylvaselling 
https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/commit/25951dda63b17d8db85dfa5b56fb697d4cac3c31
