### ISSUE TITLE
Time interpolation starts when unpausing

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2749]
If you pause time and then shift-click to advance/go back in time, the time will start interpolating when time is resumed again.

Steps:

1.  Pause
2. Shift+click to advance/go back in time for, example, month or day
3. Resume time

https://github.com/OpenSpace/OpenSpace/assets/9076357/8644370d-b9a4-49bc-ba19-b59bab421acd

**Comment by WeirdRubberDuck** [comment]
Note: Your pausing and unpausing using the space key, correct? 

So the error may be related to the action. Just pausing/unpausing in the UI only works as expected

**Comment by Arohdin** [comment]
> Note: Your pausing and unpausing using the space key, correct? 
> 
> So the error may be related to the action. Just pausing/unpausing in the UI only works as expected

Yes, I am using the SPACE-key

**Comment by Arohdin** [comment]
> Opening again, as I apparently did not fix it after all (oops)

I think the issue is that the web element (the arrow you click) keeps being "selected" on the web page. So when you then click space it acts like a button press.

Same thing happens for expand/collapse arrows in the side menu.

**Comment by WeirdRubberDuck** [comment]
That's some good insight! Thanks
