### ISSUE TITLE
Need to follow shortcuts to data folder on Windows

### ISSUE THREAD

**Issue by EricMyers47** [OpenSpace/OpenSpace#275]
I copied the data folder from a previous installation on a Mac to my Windows machine, and instead of putting it in the top level directory I wanted to put it somewhere else and use a Windows shortcut instead (like a soft link on Unix).    OpenSpace ignored the shortcut file and could not find the data folder, and so created a new one.

The code that looks for files in the data folder needs to be able to follow Windows shortcuts.

**Comment by alexanderbock** [comment]
Changed to wontfix due to the complications of following shell links in Windows.  We'd need to dissect each path everytime  someone asks for an absolute path and test each path component whether there is a shell link involved.  For the time being, we just disallow shell links instead.

**Comment by alexanderbock** [comment]
```cpp
    if (!realpath(path.c_str(), buffer.data())) {
        // Find the longest path that exists
        string fullPath(path);
        string::size_type match;
        string::size_type lastMatch = std::string::npos;
        while ((match = fullPath.rfind(PathSeparator, lastMatch - 1)) != string::npos) {
            string before = fullPath.substr(0, match);
            string after = fullPath.substr(match, string::npos);
            if (realpath(before.c_str(), buffer.data())) {
                string resolvedPath = string(buffer.data()) + after;
                return resolvedPath;
            }
            lastMatch = match;
        }
        // Nothing in the relative path was found, use current directory
        string before = ".";
        string after = fullPath;
        if (realpath(before.c_str(), buffer.data())) {
            string resolvedPath = string(buffer.data()) + PathSeparator + after;
            return resolvedPath;
        }
    }
```
