### ISSUE TITLE
Globe rendering is stuttering in Norrköping Dome

### ISSUE THREAD

**Issue by emiax** [OpenSpace/OpenSpace#276]
Configurations where the problem appear:
- Running regular alpha config in the dome.
- Running alpha config in the dome with swap lock disabled. (Stuttering is then not global, but happens asynchronously on different machines)

The stuttering starts when doing globe browsing and a lot of textures are loaded (moving around a lot on the surface). Especially visible when Hirise data is enabled.

I was not able to reproduce the problem with this configuration:
  - Solo alpha1.
  - Machine with similar hardware as alpha machines set up in cluster with my dev machine as master.
    - Regardless of whether the machine is master or slave

What is left to try?
  - Change graphcis settings on dome nodes. (disable hardware syncing altogether)
  - Make more extensive tests with one dome node.

**Comment by kbladin** [comment]
TODO: PBO texture uploading.

**Comment by alexanderbock** [comment]
Carter saw the same issue on three of the nodes at Hayden. He'll make a video and send it

**Comment by alexanderbock** [comment]
Is this still open?  I remember that it was partially fixed by reusing the textures?

**Comment by alexanderbock** [comment]
Potentially a problem with frame locking in synchronized mode?
