### ISSUE TITLE
Can't write properly if some properties/-holders are expanded in the search

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2763]
If certain properties/-holders are expanded in the side menu while you're doing a search, that input field captures the keyboard and you start typing there instead of in the search field.

https://github.com/OpenSpace/OpenSpace/assets/9076357/cc76ab22-7512-4b6e-a89a-922008b0d57d

**Comment by WeirdRubberDuck** [comment]
Potentially related with this issue: https://github.com/OpenSpace/OpenSpace/issues/2716
