### ISSUE TITLE
Layer types are missing documentation

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2767]
I was going to look up the name of the new caching property and discovered the layer docs are empty 

![image](https://github.com/OpenSpace/OpenSpace/assets/708535/289e4651-d7a2-493a-8e1e-893ac4970bce)

**Comment by WeirdRubberDuck** [comment]
Could be a naming mismatch. The layer classes are registered with the name "Layer" instead of "Provider"

![image](https://github.com/OpenSpace/OpenSpace/assets/8808894/c6e5aa31-8c42-4887-9cd3-7f505642747b)
