### ISSUE TITLE
Triggered actions are running twice on rendrer

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2768]
Output from on my gui machine:

openspace.action.triggerAction("os.solarsystem.ToggleSatelliteTrails")
    local list = openspace.getProperty("{earth_satellites}.Renderable.Enabled")
    for _,v in pairs(list) do
      openspace.setPropertyValueSingle(v, not openspace.getPropertyValue(v))
    end
  

ouput from dome renderer:

openspace.action.triggerAction("os.solarsystem.ToggleSatelliteTrails") 
    local list = openspace.getProperty("{earth_satellites}.Renderable.Enabled")
    for _,v in pairs(list) do
      openspace.setPropertyValueSingle(v, not openspace.getPropertyValue(v))
    end
  
    local list = openspace.getProperty("{earth_satellites}.Renderable.Enabled")
    for _,v in pairs(list) do
      openspace.setPropertyValueSingle(v, not openspace.getPropertyValue(v))
    end

**Comment by micahnyc** [comment]
(This happens when I trigger the action with the console, or the gui, but when using the S key, the actions command is just run, the "openspace.action.triggerAction("os.solarsystem.ToggleSatelliteTrails")" doens't show up in the script log

**Comment by alexanderbock** [comment]
The actions were triggered in the non-local way and the action commands were non-local, too, so both the action and the resulting functions were both executed on the image generators

**Comment by micahnyc** [comment]
I believe I had this issue again when using the action for toggling the MAS density asset from the bastille day profile. I pressed the button for the action and it only displayed on the control computer not on the dome. When using the scene menu to turn on and off the item it worked
