### ISSUE TITLE
Table parameters not parsed into documentation

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2770]
One example is the "Tessellation" object of the GeoJsonProperties class. See missing documentation below

![image](https://github.com/OpenSpace/OpenSpace/assets/8808894/87d8273c-e78a-42a9-89b4-f88175e719b5)

VS documentation in codegen parameters
![image](https://github.com/OpenSpace/OpenSpace/assets/8808894/5f33f64d-b06a-44ec-b822-203b0f74525e)

**Comment by alexanderbock** [comment]
Related to #2270?
