### ISSUE TITLE
Keep momentum while refocusing

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2779]
Would be nice if you could keep the camera momentum when refocusing.
Currently if you are zooming and then try to refocus to another target, the zoom will stop in order to do the refocus.

Would make transitions between targets smoother an look nicer.

**Comment by micahnyc** [comment]
you can use ctrl + shift when clicking on an item in the focus menu to acheive this.

**Comment by alexanderbock** [comment]
Does this solve the issue for you @Arohdin ?

**Comment by Arohdin** [comment]
> Does this solve the issue for you @Arohdin ?

I think so, yes. I will let you know otherwise.
