### ISSUE TITLE
A Profile with time entry but missing is_paused will cause OpenSpace to terminate with error

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#2783]
User reported that a profile that previously worked in version 0.18.2 no longer works in 0.19. On startup, the launcher reports error:

**ParsingError exception in file.profile: profile, 'time.is_paused' field is missing**

If the profile is selected in the launcher, and Start is clicked, OpenSpace starts but then quickly terminates with error in the terminal:

**terminate called after throwing an instance of 'openspace::Profile::ParsingError'
  what():  (profile) 'time.is_paused' field is missing
Aborted (core dumped)**

The profile file has `type` and `value` entries, but no `is_paused` entry within `time { }`.
Possible solutions for this could include inserting an assumed `is_paused=false` entry in the profile, or disabling the Start button in the launcher if an invalid profile is selected.

**Comment by alexanderbock** [comment]
Would be good to get the profile so that we can add a unit test for this case.  The profile version should be automatically updated when trying to load a profile with an older version:

https://github.com/OpenSpace/OpenSpace/blob/master/src/scene/profile.cpp#L605-L613

**Comment by GPayne** [comment]
This is a simplified version of the profile that reproduces the problem:

```
{
  "assets": [
    "base_blank",
    "scene/solarsystem/planets/earth/earth"
  ],
  "time": {
    "type": "relative",
    "value": "-1d"
  },
  "version": {
    "major": 1,
    "minor": 2
  }
}
```

**Comment by GPayne** [comment]
Recommending that this issue be closed with no action.

The problem occurs because the json `time` entry is missing the `is_paused` field, and the nlohmann json parser throws an exception.

As mentioned above, there are functions in place to up-convert from versions 1.0, 1.1, and 1.2. These conversions do work correctly. If the version in the example profile above is set to 1.1, the failure does not occur because the `is_paused` field is provided when the 1.1->1.2 conversion runs. The code assumes that any v1.2 profile will have an `is_paused` field if it has a `time` entry, and that is a safe assumption. This was confirmed by running a pre-v1.3 version of OpenSpace, in which case any profile that was created or saved had this field.

The most likely explanation for this error is that the profile was manually edited, and the wrong version was provided (perhaps copy-pasted from another file).

**Comment by alexanderbock** [comment]
Agreed :+1:
