### ISSUE TITLE
Location of the Statue of Liberty is incorrect

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2787]
The Statue of liberty is placed at the location of the Arc de Triomphe

**Comment by micahnyc** [comment]
Correrct coordinates in previous commit: https://github.com/OpenSpace/OpenSpace/commit/705c898ccd3c3c49e80e8e639466071e36929295#diff-4e778b88826b434ae248f7e7aed37d21e8d32bccd43c5cc657ecea98c1e8b63c
