### ISSUE TITLE
Atmosphere sun scale property

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2791]
When looking at the sun from inside an atmosphere, if you scale up the normal sun, the sun in the atmosphere doesn’t increase size. 

We should have a property in the atmosphere to scale it’s sun 

(as requested by PE)

**Comment by alexanderbock** [comment]
The ability to specify the Sun's angular size was added in 61a69490fbcbe991ac4190bf95195a0c29b90041
