### ISSUE TITLE
Add support for animated GIFs in OpenSpace

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2792]
Request from multiple users. Currently, imported GIFs are treated as stills

Would be great if these also supported transparency, to be able to load animated "overlays" on the screen

Can we already do this (without transparency) using the video support?

**Comment by ylvaselling** [comment]
This can be done with video support - just added the transparency property for libmpv. However, there seems to be an issue with globes and spheres so will create a new issue for that
