### ISSUE TITLE
User Interface Icons disappear when starting OpenSpace without an internet connection

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2794]
I looks like we don't have a local copy of the new icons that we are using in the UI, so when we start OpenSpace without an internet connection a lot of the UI becomes hard to use:

![OpenSpace_000000](https://github.com/OpenSpace/OpenSpace/assets/4921724/1c9ea43f-a267-436f-9e41-8ac59c2db3b3)

**Comment by ylvaselling** [comment]
Some various routes we can take:

1) We can host the iconify API ourselves (will require running another npm application with an HTTP server)
2) We can download the SVGs as files 
3) We can switch to another package

**Comment by alexanderbock** [comment]
In that case I'd vote for #2 as it seems less complex than #1 and we like the package (?)

**Comment by ylvaselling** [comment]
Ended up going with 3)
