### ISSUE TITLE
cmake command typo? and in-source build error in ghoul module

### ISSUE THREAD

**Issue by jfass** [OpenSpace/OpenSpace#2806]
**Describe the bug**
In compiling on Ubuntu 22.04, I think the cmake command is missing ".." in the text block that includes cloning and creating a build dir. Also, cmake fails when trying to build ghoul(?) with an "in-source builds not permitted" error.

**To Reproduce**
Following the compile instructions:
```
openSpaceHome="$HOME/source/OpenSpace"

git clone --recursive https://github.com/OpenSpace/OpenSpace "$openSpaceHome"

mkdir -p "$openSpaceHome/build"
cd "$openSpaceHome/build" || exit

cmake \
-DCMAKE_BUILD_TYPE:STRING="Release" \
-DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-11 \
-DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-11 \
-DASSIMP_BUILD_MINIZIP=1 "$openSpaceHome/build"
```
... results in:
```
CMake Error: The source directory "/home/jfass/source/OpenSpace/build" does not appear to contain CMakeLists.txt.
 Specify --help for usage, or press the help button on the CMake GUI.
```
... after cd'ing up one directory:
```
# [...]
 End dependency: WebSocketPP

 --- Module: FontRendering ---
 CMake Error at ext/ghoul/ext/freetype2/CMakeLists.txt:182 (message):
   In-source builds are not permitted! Make a separate folder for building,
   e.g.,

     cmake -E make_directory build
     cmake -E chdir build cmake ..

   Before that, remove the files created by this failed run with

     cmake -E remove CMakeCache.txt
     cmake -E remove_directory CMakeFiles
```

**Expected behavior**
NA

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04

**Additional context**
NA

**Comment by GPayne** [comment]
@jfass I made a change in the wiki page to remove the trailing **/build** from the CMake command, which fixes it.

**Comment by jfass** [comment]
Perfect, thank you. My only additional comment is that, in order to get cmake at least 3.25, I installed via snap:
```
sudo apt install snapd  # if not installed already
sudo snap install cmake --classic
```
