### ISSUE TITLE
Artifact colored tile issue

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2820]
Sometimes when loading layers on mars (presumably this can happen on other planets but I have only seen it with Mars Viking and CTX blended) there can be tiles that have weird issues loading and create color artifacts on the surface

![image](https://github.com/OpenSpace/OpenSpace/assets/708535/e286954b-72b2-434b-a11f-bbdb63eb70f8)

It can be hard to replicate sometimes but happens enough  that I was able to make it happen within 5 minutes of starting to make this issue. 

As reported by user: https://openspacesupport.slack.com/archives/C04TY4ZKXV2/p1689423418206709

**Comment by micahnyc** [comment]
![image](https://github.com/OpenSpace/OpenSpace/assets/708535/71724376-bd81-4c38-8682-1c578db4f439)

**Comment by alexanderbock** [comment]
Closed in favor of #2913
