### ISSUE TITLE
Reset camera feature

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2825]
Sometimes you can get the camera in a state where the rendering is all black, and there is no way to get back to a regular view w/o quitting openspace. It would be nice to have a "Reset camera" feature in the seetings->orbitalNavigator that sets its to focus on the root with a distance of 1AU

**Comment by WeirdRubberDuck** [comment]
I guess the question here is "Reset to what?". The start-up state perhaps? 

Also, for note: Setting the camera to a globe position works. So a potential workaround for people encountering it now is to use the go-to globe location feature (but not flying!)
