### ISSUE TITLE
Error loading obj mesh for viewport in 0.19

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2829]
When upgrading a user to v19, we were unable to load their alignment mesh files.

In the log the error was: "Illegal face format in OBJ file"

Here were the mesh files 
[mesh.zip](https://github.com/OpenSpace/OpenSpace/files/12198565/mesh.zip)

**Comment by alexanderbock** [comment]
Moving this to the SGCT repository
