### ISSUE TITLE
openspace.cfg - windowPos not working

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2833]
In `openspace.cfg` we have examples for `sgct.config.single` where we use parameter `windowPos={0,0}` .
However, this is not correct as `configuration_helper.lua` expects `pos={0,0}` instead.

Not sure if we should correct `openspace.cfg` or `configuration_helper.lua` script.

**Correct:** `SGCTConfig = sgct.config.single{1920, 1080, border=false, pos={0,0}}`

**Wrong:** `SGCTConfig = sgct.config.single{1920, 1080, border=false, windowPos={0,0}}`

**Comment by WeirdRubberDuck** [comment]
Seem to me like this is a matter of just updating the example in the openspace.cfg file?

**Comment by Arohdin** [comment]
Most likely yes.
Just wanted to make sure that `pos` is the parameter name we want to actually use.

**Comment by alexanderbock** [comment]
Yea, it was `windowPos` before, but I prefer `pos`, so 👍  for changing the example

**Comment by Arohdin** [comment]
Updated `openspace.cfg` to use `pos` instead of `windowPos`: [8a68825](https://github.com/OpenSpace/OpenSpace/commit/8a68825d48cc5109b406ec3ebbeeffbcfec786f0)
