### ISSUE TITLE
Crash on loading TIF file

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2848]
I was trying to show a tif file as a slide/screenspace renderable. When dragging it in, openspace crashed. 

https://people.math.sc.edu/Burkardt/data/tif/at3_1m4_01.tif

**Comment by WeirdRubberDuck** [comment]
Apparently, the texture reader in Ghoul does not have TIF support

Trying to load unsupported textures should be handled more gracefully, with error catching and useful error messages.
