### ISSUE TITLE
Add the ability to load custom webpages into the toolbar

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2855]
It would be very useful to be able to add custom toolbar icons from asset files.  I would imagine that an asset file can specify a local webpage that gets hosted and shown when a user opens the button.  This would allow users to directly integrate custom user interfaces without much hassle

One use-case for this would be the ability to include program guides into the software that can combine text-scripts with the ability to execute actions to be able to give a more seamless presentation

**Comment by engbergandreas** [comment]
This exists now with the webpanels
