### ISSUE TITLE
RenderableTrail has a property called Fade which shadows renderable property Fade

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#2856]
**Describe the bug**
RenderableTrail has a property called Fade (under Appearance) which shadows renderable property Fade. This leads to undefined behavior when using the URI for fade - it is unclear which fade is accessed. To fix - rename the fade property in RenderableTrails and everywhere it is used.

**Comment by WeirdRubberDuck** [comment]
As discussed during developer review: An alternative solution for the underlying cause of this problem would be to improve the check in the GUI code, instead of just doing the renaming

E.g., to check whether an "Enabled" property exists on the same level as the "Fade" property
