### ISSUE TITLE
Keep screenspace renderable during blackout

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2858]
Would be nice to keep screenspace renderable s visible when using blackout factor. 
Currently the screenspace renderable s are visible until blackout factor reaches 0.0, at which point the completely disappear.

**Comment by Arohdin** [comment]
Maybe add an option to the screenspace renderable that makes blackout factor effects it too.

**Comment by alexanderbock** [comment]
Clarification;  assuming we have the option to toggle it, you'd want the screenspace renderable to be visible at full opacity during the fading of the blackout factor *and* keep them visible until OpenSpace completely closes?

**Comment by WeirdRubberDuck** [comment]
Closed in https://github.com/OpenSpace/OpenSpace/pull/2868
