### ISSUE TITLE
"Show only enabled" showing trails that are faded out

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2869]
![image](https://github.com/OpenSpace/OpenSpace/assets/708535/29b394f6-6847-4a5b-8072-c403a905f01b)

Here I used the H key to fade out the trails. When I use the 'show only enabled', the planet/moon trails still show in the list

**Comment by WeirdRubberDuck** [comment]
The reason here is that fading out the trails only fades them out, not disabled them.  And the checkbox only checks against enabled, not whether it is visible or not. 

Need to discuss what the suggested solution is.  Should the checkbox behavior be updated to show visible instead of enabled?

**Comment by alexanderbock** [comment]
I'd say that the "Show Only Enabled" should actually check the visible; same as the checkbox.  I don't think we need to rename it as the distinction between enabled and visible is not really meaningful non a non-scripting person.

Also probably should be "Show only enabled" regarding capitalization
