### ISSUE TITLE
Profile editor - Actions and keybinds add duplicate button

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2885]
It would be nice to add a duplicate button next to the +/- button for adding new actions.

Often when adding an action like "Turn on mars layers" you would want to add another action for "Turn off mars layers" if we added a duplicate it would save the users a lot of typing.

**Comment by WeirdRubberDuck** [comment]
Duplicate of https://github.com/OpenSpace/OpenSpace/issues/2418?
