### ISSUE TITLE
macOS compile steps are incorrect

### ISSUE THREAD

**Issue by garrettsummerfi3ld** [OpenSpace/OpenSpace#2888]
In the documentation of building for macOS, it states you need to tap `osgeo/osgeo4mac` for `gdal2`.

This is not needed anymore as it is already included in the main Homebrew repositories.

All you need to do now is `brew install gdal` for the `gdal` package.

**Comment by alexanderbock** [comment]
I changed the wiki;  just to double-check , it is `brew install gdal`, not `brew install gdal2`?

**Comment by garrettsummerfi3ld** [comment]
Correct. I have had successful builds with just `gdal` from the regular Homebrew repositories.

**Comment by alexanderbock** [comment]
Great 👍   Much appreciated!
