### ISSUE TITLE
Profile Editor - Choose Scripts selection order

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2889]
Right now the choose scripts dialog adds the scripts in the order in which they are selected. I propose they should be added in the order in which they appear in the log.

**Comment by alexanderbock** [comment]
Did you check this after 880ffde3da7ad588177363e7db4434d537ab4887?  I fixed it already

**Comment by alexanderbock** [comment]
@micahnyc

**Comment by alexanderbock** [comment]
It is working
