### ISSUE TITLE
Scene Menu - Folder for featured nodes

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2892]
When using a profile, it would be nice to have quick access to the featured nodes of that profile. We could create a 'virtual' section in the Scene tree that goes at the bottom and contains the nodes that the profile creator has marked.

**Comment by micahnyc** [comment]
(i.e i'm in the eclipse profile and i want quick access to the shadow

**Comment by ylvaselling** [comment]
So this is essentially making the featured nodes a category in the Scene tree?
