### ISSUE TITLE
Hide constellation line art action not working 

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2901]
"Hide all" action in ...constellation/lines does not work (incorrect brackets or something according to one of the guys from Tekniska).

**Comment by alexanderbock** [comment]
I think it needs more info.  I'm unable to replicate it:

https://github.com/OpenSpace/OpenSpace/assets/4921724/cfafc554-da84-4f34-9f9a-20042fad88e7

**Comment by WeirdRubberDuck** [comment]
It was a problem in 0.19.0, but should have been fixed in 0.19.1

**Comment by Roxeena** [comment]
For documentation purposes, this issue was fixed in commit 72b186b80573246bbf05aeea98a89af31c36e7c9
