### ISSUE TITLE
How to select working GPU in PC?

### ISSUE THREAD

**Issue by gaowutong** [OpenSpace/OpenSpace#2903]
I have two GPU in my PC: Intel Graphics 770 and Nvidia RTX 3080. When I start the app, it uses the first GPU by default thus the performance is very bad. I want to use the second GPU instead. How can I do that?

**Comment by GPayne** [comment]
Hi @gaowutong, is it possible that your Intel graphics 770 is driving the windows display of your OS? What OS are you running?

**Comment by gaowutong** [comment]
> Hi @gaowutong, is it possible that your Intel graphics 770 is driving the windows display of your OS? What OS are you running?

Windows 10. I just found a solution in [Microsoft community](https://answers.microsoft.com/en-us/windows/forum/all/how-can-i-set-the-default-gpu-for-all-apps-on/adce04b5-e4b4-4015-8ae1-4dc385e1a37c) and it works. Thanks for your reply!

**Comment by alexanderbock** [comment]
Just FYI, that ther eis also an option in the Nvidia Control Panel to do this
