### ISSUE TITLE
Updating the SaveNavigationState function

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2909]
1. Right now, the function just saves a file directly that uses the old Lua style of `return {...}`
2. Also addressing #1715 at the same time
3. The function should probably not save the file directly but just create a Dictionary and we can have another function to save it instead

**Comment by WeirdRubberDuck** [comment]
There is already a function that generates the dictionary :)

**Comment by alexanderbock** [comment]
`openspace.navigation.navigationState()` creates and returns the dictionary
