### ISSUE TITLE
Orbital Navigator: "Speed mode" toggle

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2910]
When trying to make smooth flights over planets with varying height data (Mars...) it's sometimes difficult to get a constant speed as it will change when mountain and valleys appear underneath the camera (as speed seems to be based on altitude).

Would be nice to have a toggle that instead sets relative speed based on distance-to-focus instead.

**Comment by WeirdRubberDuck** [comment]
I actually think we added this in 0.19.0?

https://github.com/OpenSpace/OpenSpace/commit/6fa589c8801bf74ba666162eefe27fe4126201be

https://github.com/OpenSpace/OpenSpace/issues/2150
