### ISSUE TITLE
ESRI World Imagery not being cached when access through combo layer

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#2928]
When I enabled caching, and browse the earth, the Combo doens't show up in the cache, and the ESRI World Imagery folder doens't get larger, leading me to believe that the caching is not happening for the combo layer.

I would expect that with a combo layer the cache would go into the respective layers mrf

**Comment by hedbergj** [comment]
For me it ends up in a folder called "unspecified".

<img width="1703" alt="Screenshot 2023-10-30 at 3 15 42 PM" src="https://github.com/OpenSpace/OpenSpace/assets/7926907/1c6cc0d9-ca8b-43ca-ba6b-e17cb3f09056">

**Comment by alexanderbock** [comment]
Might be fixed and needs checking by @alexanderbock

**Comment by alexanderbock** [comment]
It is caching correctly now into the Earth/Color Layers/ESRI_World_Imagery.   Also when using the Combo layer, it is correctly using the individual folders that make up the combo
