### ISSUE TITLE
Outdated documentation - Users/FAQ

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2935]
This part of the documentation still refers to `.scene` files: https://docs.openspaceproject.com/en/latest/dev/faq.html#configuration

Should be updated

There are also a couple of odd links at the bottom

**Comment by alexanderbock** [comment]
Fixed in OpenSpace/OpenSpace-Docs@b3c24aa9411a5b6935b60036a279db562d4760c5
