### ISSUE TITLE
Eclipse shadow hard edges with ESRI VIIRS Combo layer

### ISSUE THREAD

**Issue by Arohdin** [OpenSpace/OpenSpace#2944]
Shadow from eclipse gets weird shadow when using ESRI VIIRS Combo layer.
Seems to work fine with other layers for earth

![image](https://github.com/OpenSpace/OpenSpace/assets/9076357/68f95920-c939-41b1-b458-77ca7c8ca1a3)

**Comment by alexanderbock** [comment]
That's in the VIIRS image actually as the satellite was taking one of the images during the solar eclipse:

https://worldview.earthdata.nasa.gov/?v=-210.87869507016316,-37.24846675644614,22.305268320903537,79.25242745338758&l=Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor,MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor(hidden)&lg=true&t=2017-08-21-T15%3A08%3A02Z
