### ISSUE TITLE
"Jump to" navigation mode does not trigger events

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#2949]
When directly jumping to a node, their corresponding enter-exit event are not triggered:

In `default` profile:
1. Being at Earth
2. Shift+Left click on the Plane menu for the Sun
3. Screen is white as the Sun Glare is not faded out with the event

**Comment by alexanderbock** [comment]
This problem seems to have been fixed, but the reverse is still an issue, so following the steps above:
4. Shift+Left click on the Plane near Earth
5. Sun glare does not come back

**Comment by WeirdRubberDuck** [comment]
The same goes for any direct transition, such as "goToGeo"
