### ISSUE TITLE
ESRI world image color layer causes assertion message on deinitialize: "write region of bounds

### ISSUE THREAD

**Issue by ElonOlsson** [OpenSpace/OpenSpace#2968]
When closing OpenSpace i get an assertion at modules/global/src/rawtiledatareader.cpp line 595
with message: "write region of bounds

I've only noticed it happening with having the ESRI_World_Imagery Earth color layer activated, so I don't know if the same bug is with other layers.
I assume this is related to #2928 

The assertion message in the log only shows up after hitting i for Ignore one time first.

![Screenshot (53)](https://github.com/OpenSpace/OpenSpace/assets/16134394/de76cfef-f9ed-4bd8-a925-1ffffb9f411a)

**Comment by alexanderbock** [comment]
I also get this just on loading:
1. Start the default profile in Debug
2. Disable ESRI VIIRS Combo
3. Enable ESRI World Imagery

```
File:       A:\openspace\OpenSpace\modules\globebrowsing\src\rawtiledatareader.cpp, line 469
Function:   openspace::globebrowsing::RawTileDataReader::rasterRead
Assertion:  isInside(io.read.region, io.read.fullRegion)    write region of bounds
(I)gnore / Ignore (P)ermanently / (A)ssertion / (S)tacktrace / (E)xit: 
```
