### ISSUE TITLE
Add a general method to be able to fade individual renderables

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#298]
After this is done, remove the `_performFade` from RenderableModel

**Comment by kbladin** [comment]
Would it make sense for all renderables to have a property value for opacity and then have a general lua method to fade property values? Then it could be used for other things such as fading globe layers or even time.

**Comment by alexanderbock** [comment]
Yes!  The only problem I see with this is writing the updating code for the properties.  Is there a better way of either registering the "currently changing" properties somewhere and calling an update function for them?

Having a Lua function to fade properties would be feasible with the use of coroutines and yielding:  https://www.lua.org/pil/9.1.html

**Comment by alexanderbock** [comment]
Fixed
