### ISSUE TITLE
Official Linux builds

### ISSUE THREAD

**Issue by data-man** [OpenSpace/OpenSpace#2990]
OpenSpace is very interesting software, but why are there no official builds for Linux?
At least in .deb format.

**Comment by GPayne** [comment]
Thank you for your interest. We are testing a debian package for linux that will be released soon.

**Comment by data-man** [comment]
Thank you!
Many projects provide .deb as both releases and "nightly" builds.
Which option will you choose? Or both?

**Comment by GPayne** [comment]
For now it will be incremental releases, as we do with our windows version.

**Comment by alexanderbock** [comment]
The mid-term plan is to have our Jenkins machines make the debian package as well and provide nighty builds for both Linux and Windows, but that is a bit further down the line as it is more of a hobby-thing on the side right now, priority-wise

**Comment by data-man** [comment]
Ok, but why this issue was closed?

**Comment by data-man** [comment]
Is there any news on that?

**Comment by alexanderbock** [comment]
@GPayne  You had a process in place, right?

**Comment by GPayne** [comment]
@alexanderbock Yes I have a process and will do a .deb package for 0.20.0
