### ISSUE TITLE
Add fixed version of our generated documentation to docs.openspaceproject.com

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#2996]
When we release a new OpenSpace version, and hence a new version of the docs.openspaceproject.com page, we should also include the parts of our generated documentation that won't change between runs. E.g the "Scripting API" and "Asset Types" parts. 

A couple of reasons:
1. It will make it easier for the users to find this, if all static user-facing documentation is in one place
1. I often find myself wanting to refer to things in the generated documentation (for example the information about which properties a renderable has) when writing pages for the docs.openspaceproject.com page.

**Comment by ylvaselling** [comment]
We could also include the profile specific generated documentation for each release (list of assets, keybindings, licenses, tags, actions, events, etc).
