### ISSUE TITLE
New codegen enum class attribute "arrayify"

### ISSUE THREAD

**Issue by engbergandreas** [OpenSpace/OpenSpace#3003]
We should add a codegen attribute to make an enum class iterable so that in code it can be e.g., ` std::array<Type> arr = codegen::arrayify<Type>();`

**Comment by WeirdRubberDuck** [comment]
What would be the purpose? Care to elaborate :) (Don't quite understand from the description)

**Comment by engbergandreas** [comment]
In this case, I need to be able to safely iterate over all events (in the case a user subscribes to all events) preferably without having to add a sentinel to the enum class
