### ISSUE TITLE
Blackout scene only

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3012]
As a user I want the ability to blackout the scene only but keep screenspace visible. 

The use case is when showing a slide or video sometimes the scene can be distracting. 

This could be done by adding a "Background Color" property for screenspace that has alpha. it could also be cheated by just using a black jpg that is fullscreen on the bottom of the screenspace stack

**Comment by alexanderbock** [comment]
The ScreenSpaceRenderable has a key/property `RenderDuringBlackout` that controls whether it should be rendered while the scene is blackout-ed
