### ISSUE TITLE
Decouple follow-rotation and interaction-sphere functionalities

### ISSUE THREAD

**Issue by jockekilby** [OpenSpace/OpenSpace#3017]
**Is your feature request related to a problem? Please describe.**
I would like the option of following along a nodes rotation whilst getting closer than the interaction sphere radius to the node.
Specific use case: Going inside of the Apollo 8 command module to look out the window during earthrise moment. This is impossible in the current implementation as one cannot get inside of the model while following along its rotation.

**Describe the solution you'd like**
To decouple interaction sphere and follow rotation modes.

**Additional context**
Suggested implementation here:
https://github.com/OpenSpace/OpenSpace/commit/28491c67cb0c163ae032839c04186fe8f57ba3ea

**Comment by alexanderbock** [comment]
Probably a better idea here would be to tie the co-rotation to the size of the _bounding sphere_, rather than the _interaction sphere_
