### ISSUE TITLE
RenderablePointCloud CSV data loader reads empty lines as point 

### ISSUE THREAD

**Issue by engbergandreas** [OpenSpace/OpenSpace#3025]
Minor bug. I had a CSV file with an extra empty line at the end. This line was read as an empty point, leading to a subscript out-of-bounds crash when loading the dataset. Perhaps it is worth adding some check here to make sure all points have the same amount of data or give users a warning

**Comment by WeirdRubberDuck** [comment]
Could you attach the file that resulted in the crash?  Would be useful to be able to reproduce it. 

Have not seen this issue and have files with empty lines at the end.

**Comment by engbergandreas** [comment]
Tried finding the file/recreating it but can't reproduce the issue
