### ISSUE TITLE
slack channel invite has expired?

### ISSUE THREAD

**Issue by hn-88** [OpenSpace/OpenSpace#3030]
Hello,

@GPayne suggested I look at the Slack Q&A page in this discussion, https://github.com/OpenSpace/OpenSpace/discussions/3028

When I click on the slack channel sign-up link on the Readme of this repo, I get the message "This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link."

Can you please help?

**Comment by hn-88** [comment]
I successfully created a sign-in using the link "join us on slack" on the openspaceproject home page, https://www.openspaceproject.com/

So only the github Readme's link seems to be inactive.

**Comment by alexanderbock** [comment]
I updated the Slack link.  Thanks for the pointer!
