### ISSUE TITLE
Add Web UI panel for adding GIBS layers

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#3033]
**Is your feature request related to a problem? Please describe.**
Right now you need to use the ImGui to add a Gibs layer. It would be better to be able to access it in the webgui.

**Describe the solution you'd like**
To create a new UI panel where you can load a list of the available gibs layers, and then add the layers that you want.

**Describe alternatives you've considered**
* There could be a new panel at the bottom bar, where the time and screen space renderables are. 
**Pros**: Easy to find
**Cons**: Far away in the UI from what it affects (the globe layers)

* It could be placed somewhere near the layers in the Scene. 
**Pros**: Good proximity to what it affects
**Cons**: Hard to find if it's buried in the menus
The gibs layers are only used on Earth - would be strange to have that on other globes.

**Additional context**
[gibs webpage](https://nasa-gibs.github.io/gibs-api-docs/available-visualizations/#visualization-product-catalog)

**Comment by WeirdRubberDuck** [comment]
Duplicate? 
https://github.com/OpenSpace/OpenSpace/issues/2104

**Comment by ylvaselling** [comment]
Duplicate of #2104
