### ISSUE TITLE
Add Web UI for parallell connections 

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#3034]
**Is your feature request related to a problem? Please describe.**
Right now parallel connections only exists as a panel in the ImGui, not in the WebGui. It would be good to have it in the web ui as well.

**Describe the solution you'd like**
Create a new panel in the WebGui, with new topics.

**Describe alternatives you've considered**
The panel could go in the bottom bar or the systems menu in the far left corner.

**Comment by WeirdRubberDuck** [comment]
Duplicate? :) 
https://github.com/OpenSpace/OpenSpace/issues/963

**Comment by ylvaselling** [comment]
Duplicate of #963
