### ISSUE TITLE
Voyager model has box in middle of it

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3035]
<img width="1265" alt="Screenshot 2024-02-20 at 4 16 10 PM" src="https://github.com/OpenSpace/OpenSpace/assets/708535/c69d1d8a-ae52-4062-a3d0-76670d4f72d4">

**Comment by micahnyc** [comment]
also check pioneer

**Comment by alexanderbock** [comment]
@Roxeena  I remember we talking about this and I thought the new version didn't have that anymore?
