### ISSUE TITLE
Type month into date picker doesn't work with string

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3038]
I was trying to change the date, and typed in "Nov" and hit enter, but nothing happened, if I put "11" and hit enter, it worked. 

Entering numbers for other fields like year, hour, date, etc works

**Comment by alexanderbock** [comment]
Change the date where?  In the WebUI?

**Comment by alexanderbock** [comment]
No.

Has been fixed in the meantime
