### ISSUE TITLE
Send feedback link returns 404

### ISSUE THREAD

**Issue by hn-88** [OpenSpace/OpenSpace#3049]
**Describe the bug**
The "Send Feedback" menu item in the default UI on Windows, accessed through System --> Send Feedback goes to https://data.openspaceproject.com/feedback which returns an error 404.

**To Reproduce**
1. Go to the leftmost "3 vertical dots" System menu, click on it,
2. Click on Send Feedback
3. See error 404 page

**Expected behavior**
A redirect to a feedback form would be expected.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 0.19.2

**Comment by micahnyc** [comment]
https://docs.google.com/forms/d/16166SpNlbCAFhHEnofYj9IKx4nbMsIfvmncSmJFxoFA/edit

**Comment by alexanderbock** [comment]
Fixed.  Thanks for the feedback ^_^
