### ISSUE TITLE
manual zoom works, but on playback, getting blank screen

### ISSUE THREAD

**Issue by hn-88** [OpenSpace/OpenSpace#3050]
I'm trying to recreate the classic AMNH "tour of the known universe" by zooming out from our location to the edge of the observable universe and back. I'm facing an issue with playing back this recording. https://github.com/hn-88/openspace-scripts/blob/main/user/recordings/zoom-out-to-edge-of-univ.osrectxt

- When I made the recording, all the elements showed up on screen without any issues as far as I could see. Tully galaxies, Quasars, Cosmic Microwave Background, everything.
- When I play it back, just after zooming out beyond the Milky Way, the screen goes blank, and remains blank until zooming in again within the Milky Way.
- If I hit pause, there is no change, the screen remains blank. If I choose "Output frames", the saved frames are also blank. 
- If I hit Stop, the screen immediately comes on with the relevant imagery. I can manually zoom in and out with no problems.
- As soon as I hit Play for a "Zoom in" recording, https://github.com/hn-88/openspace-scripts/blob/main/user/recordings/zoom-in-fr-edge-of-univ.osrectxt the screen goes blank. As soon as I hit Stop, the screen comes back again.

I understand that this could possibly be due to some hardware limitations on my under-powered computer - as reported by the Sheepit render farm, it is:
CPU	Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz x4
RAM allowed	4.8 GB
RAM available	8.3 GB
GPU	GeForce GTX 1050 Ti
VRAM	4.3 GB

Any workarounds / tips / advice would be welcome.

**Comment by hn-88** [comment]
I've tried with the default profile and this profile - https://github.com/hn-88/openspace-scripts/blob/main/user/data/profiles/default-withoutISSortrails.profile

**Comment by alexanderbock** [comment]
I don't think it is the hardware limitations. Getting the same blank screen on my machine.

Investigating...

**Comment by alexanderbock** [comment]
Bumping this up to Major as it is not just this Session Recording file but I've seen it multiple times now

**Comment by hn-88** [comment]
As you know, @alexanderbock , this is still not fixed in 0.20 RC1. I wonder if this has something to do with the licensing of the underlying data - everything works fine until AMNH's Digital Universe comes into view?

Also, a possible workaround? I see that hitting F12 and saving a screenshot still works.

**Comment by alexanderbock** [comment]
Yea, I haven't managed to fix it yet.  It's definitely nothing that we are doing on purpse and likely some render error

**Comment by hn-88** [comment]
@alexanderbock - I tried to pinpoint where exactly the screen goes blank. It appears to be that if the distance to the focus is > 139.2 kiloparsecs, the rendering is blank. I tried putting the Focus to "Milky Way Sphere" instead of "Earth", and got the same number - between 139.1 and 139.3 kiloparsecs from focus when the screen becomes blank. Possibly this could be some sort of conditional code, like (if the distance to the focus is less than x, check if all the layers are present, and only if present, render) during playback?

**Comment by alexanderbock** [comment]
It was a great tip @hn-88 !  I looked into what else happened roughly around that distance and found the bug. Any new recording will not have that problem.  There was an issue that text-based recording files were losing precision in the scaling factor that we use for the whole universe and it went to 0, meaning that everything would disappear.

If you want to salvage your existing recording, the next release candidate will have a setting in Settings/Session Recording/Ignore Recorded Scale.  If you enable that value, your existing recording will work.  I'd only recommend the setting for saving old recordings though and not to use it for recordings that are done after 0.20.0 rc2

**Comment by hn-88** [comment]
Thank you @alexanderbock ! I was rooting through the osrextxt file and was about to message you:)
