### ISSUE TITLE
Audio file playback

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3066]
Now that we can play video with libmpv, presumably we can also play an audio file. It would be nice to have a scripting function that could play a sound cue that could be tied to an action or event. 

Something like `openspace.playAudioFile("C:/Users/openspace/Desktop/chime.wav")`

**Comment by WeirdRubberDuck** [comment]
Closed with the new `openspace.audio` scripts
https://docs.openspaceproject.com/en/latest/generated/scripting-api/openspace.audio.html

Specifically [`openspace.audio.playAudio`](https://docs.openspaceproject.com/en/latest/generated/scripting-api/openspace.audio.html)
