### ISSUE TITLE
Missing Destructors for Forward Declarations

### ISSUE THREAD

**Issue by territo-sci** [OpenSpace/OpenSpace#307]
Include restructuring has caused some missing destructors to come to light.

**Comment by territo-sci** [comment]
Scene: Merged #305
Renderer: no longer default, created empty
ScreenLog: created empty

**Comment by alexanderbock** [comment]
Issue done?

**Comment by territo-sci** [comment]
Could be. It depends on how you feel on using it as a generic tracker for destructors that haven't caused a compilation error yet. So, yes, the specific problem we bumped up against is done, but no, I haven't confirmed there aren't additional missing implementations which could cause problems.

**Comment by alexanderbock** [comment]
I think it is okay to close it then; prefer not to leave issues lying around.  Though we can create a "FAQ" session in the Wiki
