### ISSUE TITLE
"Start" button uses all-caps which drastically decreases readability

### ISSUE THREAD

**Issue by meganvilla** [OpenSpace/OpenSpace#3096]
The "Start" button uses all-caps which drastically decreases readability for all visitors but poses a particular challenge for those with reading difficulties like dyslexia. It becomes impossible to identify and recognize individual words by their shape, as the uppercase styling causes all words to take on a uniform rectangular appearance. In addition to the visual impact, use of entirely uppercase text can also interfere with the output of screen readers, which may announce certain words as acronyms or abbreviations.

**Suggested Solution:** Instead of relying on all-caps text, consider using a different typeface, weight, and/or color to emphasize layout elements such as important call-to-action buttons. Note that in this case, the relevant label only uses a single word, and hence the decrease in readability Is minimal. However, this issue is included as a pointer to generally avoid all caps text in the interface, regardless of its length.

Severity level 3 from PAC

**Comment by alexanderbock** [comment]
Maybe enough to have the new outline color on it by default.  Alternatively having a larger font + mixed caps?
