### ISSUE TITLE
Focus order in the launcher is unintuitive

### ISSUE THREAD

**Issue by meganvilla** [OpenSpace/OpenSpace#3099]
Screen reader and keyboard users focus the "Properties", "Assets" and "Keybindings" controls in an order which is not meaningful when pressing Tab through the dialog.

First the "Edit" button" is reached for each feature, followed by the read-only form control with the existing settings. 

**Suggested Solution:** Update the order of elements in the code and the visual layout for each feature so that users first encounter the container for the existing settings and then the control(s) to change them.

Severity level 1 from PAC

**Comment by engbergandreas** [comment]
We'll try different designs for the text fiels / edit buttons for what makes most sense readability wise/looks
