### ISSUE TITLE
Console rendering does not work well with multiple line commands

### ISSUE THREAD

**Issue by kbladin** [OpenSpace/OpenSpace#313]
After copying and pasting multiple lines to the console, the rendering does not consider that there are multiple lines.

<img width="1440" alt="skarmavbild 2017-05-23 kl 17 22 48" src="https://cloud.githubusercontent.com/assets/4128312/26361900/a92a3e02-3fdc-11e7-876f-4294507c9baa.png">

They should be rendered as individual commands separated by `endl` right?

**Comment by alexanderbock** [comment]
Should be closed by a commit from @emiax ?
