### ISSUE TITLE
Layers out of order

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3132]
When running the default scene, the layers for the planets are not in their regular order.

**Comment by micahnyc** [comment]
also multiple layers are enabled for the moon: 
![image](https://github.com/OpenSpace/OpenSpace/assets/708535/256ffcee-f7fa-4a58-8574-1fe19e8ebe86)

**Comment by micahnyc** [comment]
I recommend that we keep LayerServer = "Utah" instead of LayerServer = "All" in the .cfg, which will fix the multiple layers, but wouldn't address the layer order issue

**Comment by alexanderbock** [comment]
Adding a z-level to the tileproviders that determines the order in which they are shown and traversed.

**Comment by Roxeena** [comment]
Check if the trigger property "remove layer" causes a crash and potentially fix it.
