### ISSUE TITLE
Fatal: No url found for submodule path 'modules/sound/ext/soloud' in .gitmodules

### ISSUE THREAD

**Issue by garrettsummerfi3ld** [OpenSpace/OpenSpace#3143]
**Describe the bug**

Missing submodule URL in `.gitmodules` causes clone/build failure.

**To Reproduce**

1. Clone project recursively
2. See error

**Expected behavior**

Clone succeeds.

**Screenshots**

N/a

**Desktop (please complete the following information):**
 - OS: All
 - Commit as of notice: d719cf2ef94d420159e4772bb6fa02fa6732b5e8 (at least when I first noticed the issue)

**Additional context**

CI output: https://github.com/garrettsummerfi3ld/OpenSpace/actions/runs/8448727562/job/23141381441

**Comment by micahnyc** [comment]
I also had this problem when running `git submodule update --init --recursive`

**Comment by alexanderbock** [comment]
`git clone http://github.com/OpenSpace/OpenSpace` vs `git clone --recursive http://github.com/OpenSpace/OpenSpace`

**Comment by garrettsummerfi3ld** [comment]
The recursive clone still fails. 

[CI output](https://github.com/garrettsummerfi3ld/OpenSpace/actions/runs/8525549054/job/23352770644) from my fork.

**Comment by alexanderbock** [comment]
Just pushed to master, can you report back?

The reason it didn't trigger our CI build is that
```sh
git clone --recursive https://github.com/OpenSpace/OpenSpace
```
works, but
```sh
git clone https://github.com/OpenSpace/OpenSpace
git submodule update --init --recursive
```
produces that error

**Comment by garrettsummerfi3ld** [comment]
It’s all working now. Clones are successful.
