### ISSUE TITLE
Multiple ZoneScopedN Errors During Compilation

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#3145]
When building on both windows & linux, encountering multiple compile errors:
**identifier "ZoneScopedN" is undefined**

This may simply be due to a mismatch of the Tracy version, but in both of my build tests, all of the submodules are up-to-date with master.

**Comment by alexanderbock** [comment]
Can you `#include <ghoul/misc/profiling.h>` at the top of the file and see if it fixes it?

**Comment by GPayne** [comment]
Yes, adding:
`#include <ghoul/misc/profiling.h>`
fixed this issue. I committed this in 9eb2344. Closing this issue.
