### ISSUE TITLE
Some asteroids files fail to load due to scn::scan errors

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#3148]
Some of the asteroids .csv files fail when being parsed with an error like:
**Error parsing epoch '2023-02-25.0000000'**
In this example from the _sync/http/sssb_data_centaur_asteroid/3/sssb_data_centaur_asteroid.csv_ file, the value of `'2023-02-25.0000000'` in the first data line causes an exception when it is read at:
https://github.com/OpenSpace/OpenSpace/blob/9cf5e55ad6fed5ea0d2c514138cab4ab76052d32/modules/space/kepler.cpp#L270

This is a apparently side-effect of the new C++ format library update.
I tried a few ways to adjust the scan format, but haven't yet been successful. Changing the scan code to the following works for some of the asteroids files:
```
const std::string format = (nDashes == 2) ? "{:4}-{:2}-{}" : "{:4}{:2}{}";
auto res = scn::scan<int, int, double>(e, scn::runtime_format(format));
if (!res) {
    throw ghoul::RuntimeError(std::format("Error parsing epoch '{}'", epoch));
}
auto [year, monthNum, dayOfMonthNum] = res->values();
const int daysSince2000 = countDays(year);
const int wholeDaysInto = daysIntoGivenYear(year, monthNum, static_cast<int>(dayOfMonthNum));
const double daysInYear = static_cast<double>(wholeDaysInto) + (dayOfMonthNum - std::floor(dayOfMonthNum));
```
This treats the day of month as a double rather than trying to read the `25.0000000` day as an integer `25` and then a `.0000000` double. However, now the problem is it throws an exception when `monthNum` has a two-digit string for values less than 10 (e.g. '09').

**Comment by alexanderbock** [comment]
Maybe the same bug as reported in here: https://github.com/eliaskosunen/scnlib/issues/104
