### ISSUE TITLE
Cache file conflict for files with same name in directory

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#3154]
The cache manager uses only the file name, not the full file path, when generating the path for the cached file. 

This leads to two files with the same name, but in different locations, getting the same file name in the cache folder. 

See the example below. The two files represent two entirely different datasets. Here, the seconds asset should use a different file with the same name, but instead loads the previously cached file
![image](https://github.com/OpenSpace/OpenSpace/assets/8808894/a2b9a641-ad7c-40c2-aeef-1a7c116e3840)

**Comment by WeirdRubberDuck** [comment]
Current workaround is to make sure to use different file names

**Comment by alexanderbock** [comment]
Simplest solution would be to replace `baseName` with `file` in https://github.com/OpenSpace/Ghoul/blob/master/src/filesystem/cachemanager.cpp#L238 and 
https://github.com/OpenSpace/Ghoul/blob/master/src/filesystem/cachemanager.cpp#L294

It would mean that if someone moves the files, the cache gets invalidated, but maybe thats not a problem.
