### ISSUE TITLE
(probably due to Windows update) disconnection between user interface and OpenSpace

### ISSUE THREAD

**Issue by hn-88** [OpenSpace/OpenSpace#3171]
Yesterday I had used OpenSpace without issues. After my use, there was a Windows update which restarted windows before shutdown. Today, when I start up Openspace, I get the error message, "Houston, we've had a disconnection between user interface and OpenSpace". Tried with default profile, empty profile, etc.

Any tips on where to start for troubleshooting? Should I open some port in Windows Firewall?
![image](https://github.com/OpenSpace/OpenSpace/assets/6321069/0791f523-84c1-4e89-be87-498120da91a8)

**Comment by alexanderbock** [comment]
I guess the firewall settings have reset with the update.  I'd search for "Windows Defender Firewall", go to "Allowed apps" and then remove "openspace" and "Node.js"  from that list.  That should cause two firewall dialogs to pop up when you start OpenSpace the next time.
![image](https://github.com/OpenSpace/OpenSpace/assets/4921724/359f8cb6-0b52-4ff4-ab02-d045ddadc798)

**Comment by hn-88** [comment]
Thanks @alexanderbock . Windows was not allowing me to delete 2 of the 3 openspace entries. Could delete Node.js and one of the openspace entries in the list as you have shown above. On starting Openspace, only Node.js firewall popup appeared. Openspace firewall popup did not appear. Additionally, there is an error seen in the logs, referring to network service
```
(D) ScriptEngine         Using script log file "C:\\OpenSpace-0.19.2\\logs\\ScriptLog.txt"
[2024-04-12 09:27:30] [connect] WebSocket Connection iostream transport v13 "" / 101
(D) WebSocket            onOpen: WebSocket opened. Client: 127.0.0.1:47313
(W) Logging              Number of Warnings: 2
[0412/092730.544:ERROR:network_service_instance_impl.cc(470)] Network service crashed, restarting service.
[0412/092820.792:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is

```
Maybe some file(s) has/have become corrupted? I have another computer on which Openspace is working. Should I try copying over some files from there to this machine?

**Comment by alexanderbock** [comment]
It feels to me like the issue is that you can't remove those entries.  I'm assuming you have restarted your computer since then?   If not, it'd be worth doing that and trying to remove them again.

If that doesn't work, there seems to be a way to look at the Firewall log (see answer in https://superuser.com/questions/1154812/how-to-re-trigger-windows-firewall-has-blocked-message) which might give some more indication

**Comment by hn-88** [comment]
Hi @alexanderbock - it turned out it was a silly error on my part. In the cfg file, the Webgui ip address was set to something other than localhost, and I had not set the network interface to static. This machine got a different ip address after the DHCP lease expired, since it started up at a different time than usual after the Windows update, and so OpenSpace webgui could not connect:)

Found by comparing the two directories, one from the "working" laptop and one from the "not-working" desktop - only the cfg file was flagged as newer on the desktop, and then I remembered testing out connecting from a different machine.

https://www.howtogeek.com/how-to-compare-two-folders-on-windows-11-and-10/

```
C:\fromlaptop\OpenSpace-0.19.2\bin>robocopy "C:\fromlaptop\OpenSpace-0.19.2" "C:\OpenSpace-0.19.2" /L /NJH /NJS /NP /NS

                        C:\fromlaptop\OpenSpace-0.19.2\
        *EXTRA Dir      C:\OpenSpace-0.19.2\mrf_cache\
            Newer                       ACKNOWLEDGMENTS.md
            Newer                       CITATION.cff
            Newer                       CODE_OF_CONDUCT.md
            Newer                       COMMIT.md
            Newer                       CREDITS.md
            Newer                       LICENSE.md
            Older                       openspace.cfg
            Newer                       README.md
            Newer                       vc_redist.x64.exe
```


I've now set it back to localhost as below.
```
WebGui = {
        Address = "127.0.0.1",
        HttpPort = 4680,
        WebSocketInterface = "DefaultWebSocketInterface"
    },
```
