### ISSUE TITLE
LuaTranslation and LuaRotation log messages as LuaScale

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3176]
https://github.com/OpenSpace/OpenSpace/blob/cd30d5f1d3beab954d7c247de3039fd57f87adb0/modules/base/translation/luatranslation.cpp#L93

https://github.com/OpenSpace/OpenSpace/blob/cd30d5f1d3beab954d7c247de3039fd57f87adb0/modules/base/translation/luatranslation.cpp#L117

**Comment by micahnyc** [comment]
Also the documentation for LuaTranslation mentions 'translate' but the code wants the function to be called 'translation'

**Comment by alexanderbock** [comment]
Would have been faster to fix the issue than to make the issue ;)

**Comment by micahnyc** [comment]
> Would have been faster to fix the issue than to make the issue ;)

I dont want to commit to master without a pull request and I need an issue # to make the pull request
