### ISSUE TITLE
Decreased FPS in v19.2 when low to ground with hi-res DTM on. 

### ISSUE THREAD

**Issue by hedbergj** [OpenSpace/OpenSpace#3186]
**Describe the bug**
Orbital navigation seemed slower in 19.2 when in the dome (with sph.mir or fisheye) compared to previous versions. 

**To Reproduce**
1. Go to Mars. 
2. Turn on a HiRise color and height tile set. Eg. Southwest Candor Chasma. Or Local Set DEM. 
3. Fly low to the ground
4. (Possible I've experienced the same thing on the Moon with the Apollo DTM layers)

**Expected behavior**
I used to get enough FPS to fly smoothly. Anything around 20 is fine with us. Now it gets very sluggish at times, in proportion to how close to the surface the camera is - sometimes as low as 4 or 5. It's basically made flying around the surface at low altitudes impossible. (CEF GUI slows down too)

**Screenshots**
![fps-dtmcompare](https://github.com/OpenSpace/OpenSpace/assets/7926907/019e44bf-341f-49a5-bb5a-2eba2fbdb8a7)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 19.2

**Additional context**

**Comment by alexanderbock** [comment]
I hope that this is not a problem anymore.  I'll leave the ticket open until you can test it, but here are my tests (I had v-sync enabled for the tests, so I didn't get accurate numbers unfortunately):

Version 0.18.0:  60 fps
![win0_000000](https://github.com/OpenSpace/OpenSpace/assets/4921724/7bc718bd-57d8-4162-adbc-5cec0776775e)

Version 0.19.2: 30 fps
![win0_000000](https://github.com/OpenSpace/OpenSpace/assets/4921724/4426ba31-abc4-4fde-96e8-b927b458f685)

Version 0.20.0 (master as of today): 60 fps
![image](https://github.com/OpenSpace/OpenSpace/assets/4921724/df301b6d-6d4b-48dc-ba75-b2d52095b45e)

**Comment by alexanderbock** [comment]
Session Recording for the test:
[issue-3186-test-view.txt](https://github.com/OpenSpace/OpenSpace/files/15012971/issue-3186-test-view.txt)

Color Layers:
 - MOC WA Color [Sweden]
 - CTX Mosaic [Sweden]
 - West Candor
 - Southwest Candor Chasma

Height Layers:
 - HRSC MOLA Blended DEM Global 200m v2
 - West Candor
 - Southwest Candor Chasma

**Comment by alexanderbock** [comment]
Did the issue disappear in 0.20.0 for you, @hedbergj ?
