### ISSUE TITLE
Writing frames from session recording is not working

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#3252]
When trying to render out frames from a session recording, the frames are not actually being generated and the session recording is stuck at the first image without progressing.

Steps to reproduce:
1. Record a session recording
2. Select "Output frames"
3. Play recorded session

It should render out the frames, but right now it just stops without progressing

**Comment by GPayne** [comment]
I am unable to reproduce this problem.
I did builds of the latest master as of today (5ecdd67) and tested this issue in the following builds:
- Linux Release
- Windows RelWithDebInfo
- Windows Debug
I also tested with both binary & ascii recording formats, using framerates from 30 to 60 fps.

One thing I noticed was that with a larger file on Windows Debug, there was a pause of maybe up to 5 seconds when I started playback, so at first it behaved a bit like there was a problem, but then it started playing back and saving the screenshot files.

**Comment by hn-88** [comment]
Hi, @GPayne and @alexanderbock 

I think I might be reproducing this bug in the following manner - 

here is a osrectxt file, generated using https://github.com/hn-88/OSREC-interp/ which plays OK when "Output frames" is disabled, but stops playout after 99 frames (0 to 98) when 'Output frames' is checked.
[India-LAv31kEdit2.zip](https://github.com/user-attachments/files/16012350/India-LAv31kEdit2.zip)

Additional point. When I choose the default profile, which on this computer renders only at 2 fps or so, the recording renders fine, 'output frames' works fine. But when I choose a minimal profile which I have created, with only the Earth and the Sun + shading enabled, and ESRI world imagery, which this computer renders at 120+ fps, then the recording gets stuck at frame number 098.

Here is the profile - 
[EarthandSun.zip](https://github.com/user-attachments/files/16012389/EarthandSun.zip)

So, maybe the bug manifests itself only when the graphics subsystem can render much faster than the hard disk subsystem can write to files?

**Comment by hn-88** [comment]
Hi, I noticed that the machine where I reproduced the bug was actually running 0.20.RC1 and not the final release. Now when I run the exact same files on the office machine which has an NVidia graphics card, 0.20RC1 stops at frame 0098, but 0.20.0 works fine. So maybe the bug was fixed between RC1 and the final release? And maybe this issue can be closed?
