### ISSUE TITLE
Drag-and-drop an .mp4 file would sometimes crash OpenSpace

### ISSUE THREAD

**Issue by engbergandreas** [OpenSpace/OpenSpace#3257]
This is the file used, will see if I can find the crashlog. Worked on some of our workshop machines but not on others, very 50/50
https://github.com/OpenSpace/OpenSpace/assets/48772850/8ba13bc6-4f31-4618-969d-cae113f20116

**Comment by alexanderbock** [comment]
Maybe duplicate of #3163
