### ISSUE TITLE
Add event for order change of Globe Layer 

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#3263]
**Is your feature request related to a problem? Please describe.**
In order to update the UI automatically on different browser windows we need an event to tell the UI that the layer order has been updated. For example, if you have a browser window open and you change the order in the native application, the order doesn't update in the browser window.

**Describe the solution you'd like**
Add an event for the reordering of layers.

**Comment by micahnyc** [comment]
Maybe it would make sense to combine the LayerAdded and LayerRemoved with this LayerReordered, and we can call it GlobeLayerUpdate or something? Then it could have the info + type.
