### ISSUE TITLE
Add address and port to constructor in JavaScript API

### ISSUE THREAD

**Issue by engbergandreas** [OpenSpace/OpenSpace#3264]
We should update the JavaScript API to accept a port and address without having to create and import the socket module separately, similar to what we did we the Python API.

**Comment by engbergandreas** [comment]
Might actually be uneccessary since the module.exports handles it

**Comment by micahnyc** [comment]
yeah I think we have this. Basically when I use the api I do something like this: 

var api = window.openspaceApi(host, 4682);
