### ISSUE TITLE
Profile Editor - "Add from ScriptLog" vs "Choose Scripts" 

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3268]
In the profile editor, we have two different labels for the buttons where you access the scriptlog.

In the Properties panel its called "add from scriptlog" and in the actions panel its called "choose scripts" I think we should name these buttons the same to indicate to the user that they are behaving in the same way.

![image](https://github.com/OpenSpace/OpenSpace/assets/708535/7cd48ce7-5aa1-4ed8-b86b-23f78f966a61)
![image](https://github.com/OpenSpace/OpenSpace/assets/708535/d559e7ba-8dc5-49af-8add-444aca7b673b)

**Comment by micahnyc** [comment]
I was also thinking it might be nice to add a 2nd button that just takes the last line of the script log for them.

**Comment by hedbergj** [comment]
Another idea, related to this, is have a GUI mode called Builder where every property gets another button that when pressed, adds the last scriptlog item to the profile that's open. (I'm never really sure what the intended work flow is for the Add from ScriptLog feature: are we expected to make like hundreds of changes to things until it's all good, then quit, then open again, and then scroll through the ScriptLog looking for the 3 or 4 we want to keep?)

**Comment by alexanderbock** [comment]
Some better UI for it is definitely needed in the long run.

The way I use it is either (a) they way you describe; set all of the settings in one go, go through the scriptlog and pick the ones in one swoop or (b) having OpenSpace running, then start OpenSpace a second time and go into the profile editor, do one change at a time and have the profile editor reload the script log after each "pick"
