### ISSUE TITLE
Update README with Contributor Information and Documentation Access

### ISSUE THREAD

**Issue by michellenieto5** [OpenSpace/OpenSpace#3282]
It would be beneficial to update the README to include information on contributing and direct access to documentation. The README is often the first point of contact for users and contributors, so it's important to provide clear guidance.

We could improve the README by:

- Adding a section on contributing with links to the contributing guide and tips for finding suitable issues.
- Including a brief overview of the project's code of conduct (Or the link)
- Providing direct links to documentation resources for easy access.

By doing so, we can make it easier for new contributors to get involved and ensure a welcoming environment for all.

Thank you for considering this update

**Comment by alexanderbock** [comment]
Thanks for the suggestion!  I added some more clarifying text to the CONTRIBUTING file and the README
