### ISSUE TITLE
Console in OpenSpace doesn't consume all keyboard inputs

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#3290]
**Describe the bug**
The console doesn't consume all the keyboard input, so the keyboard input can be inputted in both the console and the web GUI.

**To Reproduce**
1. Open the Scene menu and open the search bar
2. Open the console
3. Type " in the console
4. See error that the " has appeared both in the console and the Scene search

**Comment by alexanderbock** [comment]
I can't reproduce it.  Tried multiple options:

1. As described above, for "Open the console" I tried both the ~ key which required deselecting the Scene menu and also tried opening the console through the ... menu.  In both cases the Search bar lost focus and the " only ends up in the LuaConsole
2. Tried opening the console first, and then the Scene menu.  Even with the Search having focus, the " only appear in the console


https://github.com/OpenSpace/OpenSpace/assets/4921724/6c69d982-dfb7-4e87-8d72-f4690411f5e9

**Comment by WeirdRubberDuck** [comment]
> I can't reproduce it. Tried multiple options:
> 
> 1. As described above, for "Open the console" I tried both the ~ key which required deselecting the Scene menu and also tried opening the console through the ... menu.  In both cases the Search bar lost focus and the " only ends up in the LuaConsole
> 2. Tried opening the console first, and then the Scene menu.  Even with the Search having focus, the " only appear in the console
> 
>  2024-06-23.14-02-13.mp4

I definitely have the issue. See video. Interesting that the behavior is different.

Note that the behavior seems to be different for when removing characters. In the video, only the characters in the scene menu search is removed

https://github.com/OpenSpace/OpenSpace/assets/8808894/ab3528a2-82de-4617-830c-8bfcb3d7ad0b

**Comment by alexanderbock** [comment]
Just a brain dump before I forget.  The problem is that the CEF only marks keyboard input as "consumed" in the `keyboardCallback` function;  the Lua console however is listening to both the `keyboardCallback` for supporting copy-n-paste, etc, but taking the individual keys out of the `charCallback` which is passed to every subsystem that wants to listen to it.
