### ISSUE TITLE
Crash when removing layer

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3297]
When calling `openspace.setPropertyValueSingle("Scene.Earth.Renderable.Layers.ColorLayers.GHRSST_L4_MUR_Sea_Surface_Temperature_Temporal.Remove", nil)` I was getting a crash around the notifyChangeListeners function

**Comment by alexanderbock** [comment]
Was the before or after commit ff9b72c5800ca998e0a67059ff8dae848a03221f?  I fixed a crash there

**Comment by micahnyc** [comment]
Closing because I can confirm fixed on current master
