### ISSUE TITLE
RenderableStars disappear when MilkyWaySphere Opacity set to 1

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3304]
If you set the opacity to 1 on the sphere, the stars go away

![image](https://github.com/OpenSpace/OpenSpace/assets/708535/0265baec-11ec-4ed3-942c-edc9da66cc4e)

at 0.99 they show fine

![image](https://github.com/OpenSpace/OpenSpace/assets/708535/29e0faf8-355b-4668-bb78-a64eecfd88fb)

**Comment by alexanderbock** [comment]
Was a problem in 0.19 already and seems to be a side effect of the additive blending of the stars and them not writing into the depth buffer.  When turning off `{ .automaticallyUpdateRenderBin = false }`, the stars fade smoothly between visible and hidden instead
