### ISSUE TITLE
Exoplanets - label for system

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3318]
When adding an exoplanet system into the scene, it would be nice to have the option of adding a label, this way when you are flying to it in space you can have the label for just that star turned on.

**Comment by WeirdRubberDuck** [comment]
Requires this to be fixed: https://github.com/OpenSpace/OpenSpace/issues/1474

**Comment by alexanderbock** [comment]
This would be a label for the star system as a whole, not for the individual planets, so it might not need #1474

**Comment by WeirdRubberDuck** [comment]
Good point
