### ISSUE TITLE
Crash on startup when capabilities not detected 

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3330]
When installing on a users “superserver” / “capture system”,  openspace wouldn’t start and crashed on detecting capabilities. 

The error was “(WMI) No WMI query result Error Code: -2147217392”

My thoughts are:

A) issue due to the fact there is no physical monitor connected
B) security issue
C) issue with the window size 7680x4320

**Comment by alexanderbock** [comment]
(b) is the most likely one.  If you make a build for the user off of `master` now, the error message will be more informative and will include the WMI SQL query that is executed

**Comment by alexanderbock** [comment]
@micahnyc  Update?

**Comment by gerbendekker** [comment]
same here, recently got a RAM update 32gb -> 64gb on this machine but not sure/unlikely that is the issue, option B) would not surprise me due to work related policies
![image](https://github.com/user-attachments/assets/73dd318d-0c98-486c-981b-635f8be076f7)

**Comment by alexanderbock** [comment]
Thanks for the info?  Did you compile OpenSpace yourself?  If so, would you mind trying out the branch `issue/3330`?  I tried with a fix that hopefully makes its not crash

**Comment by gerbendekker** [comment]
@alexanderbock _"Did you compile OpenSpace yourself?"_ I installed the latest version, I am a software engineer but not familiar with this project code and build process _"I can make some quickly as well"_ that would help and if its possible to share it I'm happy to test it.
btw just tried it with 0.18.2 and got this so has to be option B) issue
![image](https://github.com/user-attachments/assets/a2a4b847-c6a1-4fcc-9d56-a665bd1b2070)

**Comment by alexanderbock** [comment]
No problem at all!  Here is a build:  https://data.openspaceproject.com/release/testing/b1673bb.zip  It will now not fatally crash when failing to detect the available RAM.    I tested it by manually overwriding the detected memory to 0 and the rest of the system seems to work.   I expect there to be other errors where we use WMI as well, but those should be limited to a few instances and I hope nothing breaks 🤞 

Lemme know how it goes!

**Comment by gerbendekker** [comment]
uhm, got the same error als last time, did not expect that assuming "GeneralCapabilitiesComponent""would become the logged Category
```
        LERRORC(
            "GeneralCapabilitiesComponent",
            std::format(
                "Error reading physical memory from WMI. {} ({})", e.message, e.errorCode
            )
        );
```
if the exception type `WMIError` is correct then I'm afraid the build is not based on the `issue/3330` branch?
<img width="845" alt="image" src="https://github.com/user-attachments/assets/60a55b0d-0b71-4727-b564-9c6273d111c1">

**Comment by gerbendekker** [comment]
I thought I'd give it a try and after
- renaming `CMakeLists.txt` L69 `add_definitions(/MP /bigobj)` to `add_compile_options(/MP /bigobj)`
![image](https://github.com/user-attachments/assets/96494ead-f625-4547-8fb1-e528dce06e3b)
- between build errors where all bin are placed here `\OpenSpace\bin\` except a post action is expecting it in `Debug`, so moved `OpenSpace.exe` and `OpenSpace_Helper.exe` to build folder Debug or Release folder
![image](https://github.com/user-attachments/assets/5a80045a-41f9-4d23-a016-61bfe2616ddb)

Don't know if I'm missing something but eventually it works and started to debug.

Found out that the type `WMIError` is not recognised
![Schermafbeelding 2024-08-21 005249](https://github.com/user-attachments/assets/1d8345d4-1cca-4883-b90b-84ae79343f87)
Worked around it by adding additional catch in L365 `generalcapabilitiescomponent.cpp`
```
try {
    std::string memory;
    queryWMI("Win32_ComputerSystem", "TotalPhysicalMemory", memory);
    std::stringstream convert;
    convert << memory;
    unsigned long long value;
    convert >> value;
    _installedMainMemory = static_cast<unsigned int>((value / 1024) / 1024);
}
    
catch (const WMIError& e) {
    LERRORC(
        "GeneralCapabilitiesComponent",
        std::format(
            "Error reading physical memory from WMI. {} ({})", e.message, e.errorCode
        )
    );
}
catch (const std::runtime_error& e) {
    LERRORC("GeneralCapabilitiesComponent", e.what());
}
```
Next error is in `openglcapabilitiescomponent.cpp` where no try catch is, so added in L67
```
    try {
        detectDriverInformation();
    }
    catch (const std::runtime_error& e) {
        LERRORC("GeneralCapabilitiesComponent", e.what());
    }
```

Now I can build and look at space again 😁
Hopefully this give you an idea how to properly fix/workaround this issue

**Comment by alexanderbock** [comment]
It should have worked before, but I can't argue with the results ¯\_(ツ)_/¯

So I just adoped a variant of your solution.  Thanks for checking it out!
