### ISSUE TITLE
UI for ScreenSpaceRenderables does not show PropertySubOwners

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#3331]
ScreenSpaceRenderable types might have PropertySubOwners that are important for the functionality.  Currently these are not shown in the user interface and they should be.  For example the `ScreenSpaceDashboard` is not that usable right now without access to the DashboardItems.

For testing:
```lua
openspace.addScreenSpaceRenderable({
  Identifier = "OpenSpaceGuide",
  Name = "OpenSpaceGuide",
  Type = "ScreenSpaceDashboard",
  UseRadiusAzimuthElevation = true,
  RadiusAzimuthElevation =  { 1.0, -0.45, 0.1 }
})

openspace.dashboard.addDashboardItemToScreenSpace(
  "OpenSpaceGuide",
  {
    Type = "DashboardItemText",
    Identifier = "AI",
    GuiName = "AI",
    Text = "Chat-GPT explanation goes here"
  }
)

openspace.dashboard.addDashboardItemToScreenSpace(
  "OpenSpaceGuide",
  {
    Type = "DashboardItemText",
    Identifier = "User",
    GuiName = "User",
    Text = "User prompt goes here"
  }
)
```

But the screenspace renderables UI only shows the direct properties of the ScreenSpaceDashboard.

**Comment by WeirdRubberDuck** [comment]
Not that it's just the state on the UI that is not updating correctly when a dashboard item is added. Reloading the UI with F5 "fixes" it, and the item shows correctly

The same issue exists from the regular Dashboard as well (e.g. using the `openspace.dashboard.addDashboardItem` function)
