### ISSUE TITLE
Keyboard layout widget stopped working

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#3334]
The keyboard layout no longer shows any mapped buttons.  There are no errors reported

![image](https://github.com/OpenSpace/OpenSpace/assets/4921724/8957137f-7348-4dcd-bcc7-17fef0f90176)

**Comment by ylvaselling** [comment]
Fixed with 3eceefb99bd5f3e97b89958c8aacdacd0db857fd
