### ISSUE TITLE
Missing UI updates for reordering of layers

### ISSUE THREAD

**Issue by WeirdRubberDuck** [OpenSpace/OpenSpace#3339]
Now the UI reloads neatly whenever ad propertyowner is added or removed, but still not when the order are changed for example for layers. 

For example, triggering the script `openspace.globebrowsing.moveLayer("Earth","ColorLayers",4,1)` moves one of the Earth color layers but the change is not reflected in the UI. 

This also means that there are mismatching orders in the two places in the user interface where the layer list is shown, since we no longer reload the UI after the change is made. See video below

https://github.com/OpenSpace/OpenSpace/assets/8808894/70b12133-a294-4d13-9b92-cff793477f89

Maybe we need an event that is triggered when layers (or any propertyowners) are reordered?

**Comment by alexanderbock** [comment]
Mhh.. I thought @ylvaselling  had added those?

**Comment by ylvaselling** [comment]
> Mhh.. I thought @ylvaselling had added those?

Nope, I wrote a note in the PR that layer refresh is not implemented... My proposed solution is to send the layer group property owner to the UI instead of creating a new event. That way we don't have to deal with ordering calculations.
