### ISSUE TITLE
TileIndicies SizeRefence Layer not working in v0.20

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3356]
Working in v19. 
![OpenSpace_000000](https://github.com/user-attachments/assets/2e86a55a-8d5f-4915-9279-75104f384cc7)

but not in 20

![OpenSpace_000000](https://github.com/user-attachments/assets/bbfb6da0-de50-4c96-8c87-6a9acb5ffdba)

**Comment by WeirdRubberDuck** [comment]
"Size Reference" seems to have the same problem
