### ISSUE TITLE
Hard crash when removing a globe layer

### ISSUE THREAD

**Issue by ylvaselling** [OpenSpace/OpenSpace#3357]
There are two issues with deleting the layers from the Remove property from the UI. There is no problem with removing the layer with scripting however.

1. Hard crash when removing a layer that is not a SolidColor. Here is the call stack:

![image](https://github.com/user-attachments/assets/8259c5f7-b627-4ac3-a3db-4b1ba12a7a73)

2. Removing a layer that is a SolidColor will not do anything, as a TileProvider has not been created, and all functions check if there is a TileProvider before it moves on to do other things.

**To Reproduce**
1. Open the UI panel for any of the Layers in Color Layers in Earth that are loaded in the default profile
2. Click on Remove
3. Crash

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by WeirdRubberDuck** [comment]
Observed in 0.19.2 as well as the current version. 

But it does not happen in 0.18.2
