### ISSUE TITLE
RenderableTravelSpeed - can't change color

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#3381]
When using the color picker to change the color for the RenderableTravelSpeed it stays as white (other controls are working like line with and line length

![image](https://github.com/user-attachments/assets/38940063-d4bf-4852-8626-37f03afa14cd)

**Comment by WeirdRubberDuck** [comment]
What system was this issue experienced on?   GPU, Operating system, etc. 

I don't have the issue on my machine 🤔 
![image](https://github.com/user-attachments/assets/34e2aba7-2071-408d-9b1e-f7bad5e9cbd2)

**Comment by WeirdRubberDuck** [comment]
What's the system and setup this was observed on?  OpenSpace version, GPU, operating system

I am unable to reproduce it, in both 0.20.0, 0.20.1 and on a recent commit in the master branch.

**Comment by micahnyc** [comment]
[speed.zip](https://github.com/user-attachments/files/16661997/speed.zip)


confirmed this is only an issue when there are multiple instances RenderableTravelSpeed in the scene
