### ISSUE TITLE
New CEF-Related Build Errors in Linux

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#3391]
There are a few new build errors in linux when building with gcc13 and clang, which are a result of the changes for GPU CEF acceleration (11bb8e7).

A few of the errors:

```
modules/webbrowser/src/webrenderhandler.cpp:165:60: error: ‘const class CefAcceleratedPaintInfo’ has no member named ‘shared_texture_handle’
  165 |         memObj, size, GL_HANDLE_TYPE_D3D11_IMAGE_EXT, info.shared_texture_handle
```

```
modules/webbrowser/ext/cef/cef_binary_127.3.5+g114ea2a+chromium-127.0.6533.120_linux64/include/base/cef_ref_counted.h:487:42: error: expected ‘)’ before ‘,’ token
  487 |   explicit RefCountedData(std::in_place_t - , Args&&... args)
```

**Comment by wtbgagoa** [comment]
Thank you for reporting and working on this. Are you sure this is just the result of the changes for GPU CEF acceleration ?
I already get the second error in the CEF upgrade [67965e8](https://github.com/OpenSpace/OpenSpace/commit/67965e8844912ed8b643709bd522cfaa91b454ee).

**Comment by GPayne** [comment]
I do not get any build errors with commit 67965e8. However, I had to delete my previous build directory and do a fresh CMake configure. Without that step, I hit a runtime CEF error (but I did not get an error similar to the second error above).
