### ISSUE TITLE
no ui 

### ISSUE THREAD

**Issue by JOJOzzw007** [OpenSpace/OpenSpace#3411]
<img width="1279" alt="屏幕截图 2024-09-16 125425" src="https://github.com/user-attachments/assets/b1115a51-de85-4b1e-84d2-ea6c60542a36">

<img width="855" alt="屏幕截图 2024-09-16 130040" src="https://github.com/user-attachments/assets/741d1b26-d628-4739-84cc-c20443ded2d7">

**Comment by JOJOzzw007** [comment]
solarstorm 2012 scene

**Comment by JOJOzzw007** [comment]
![image](https://github.com/user-attachments/assets/ba95e5d0-e9f7-4cd6-8b7a-7684d712f918)

**Comment by alexanderbock** [comment]
Hi!  In order to use the `solarstorm_2012` or `bastille_day` profile, you need to compile OpenSpace with some additional modules.  For that, just enable the `OPENSPACE_MODULE_FIELDLINESEQUENCE` option in CMake before generating the project:

![image](https://github.com/user-attachments/assets/fb6bfdb1-941e-412f-bdeb-008a4c9527a9)

**Comment by JOJOzzw007** [comment]
> Hi! In order to use the `solarstorm_2012` or `bastille_day` profile, you need to compile OpenSpace with some additional modules. For that, just enable the `OPENSPACE_MODULE_FIELDLINESEQUENCE` option in CMake before generating the project:
> 
> ![image](https://private-user-images.githubusercontent.com/4921724/367693348-fb6bfdb1-941e-412f-bdeb-008a4c9527a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0ODY2NjcsIm5iZiI6MTcyNjQ4NjM2NywicGF0aCI6Ii80OTIxNzI0LzM2NzY5MzM0OC1mYjZiZmRiMS05NDFlLTQxMmYtYmRlYi0wMDhhNGM5NTI3YTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTZUMTEzMjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDY5NmJlZDIwYmJlNzg0NGY5MWJiOWI5ZWEyMGI0MTRlODliMjFkYjkzMDlmNWNhZGQ1MDc1OWMzNjk4OTI5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jx_Xf1Ze54fxZC_pgMCleE7WUbdbvUzTRI-iBcWwTtU)

Thank you very much for answering this question. When I configured it using cmake in vscode, I could not find this module.
<img width="588" alt="image" src="https://github.com/user-attachments/assets/8aec0e3a-ea35-4260-b9d1-d78380b46046">

**Comment by alexanderbock** [comment]
The setting is disabled by default.  In the CMake GUI you'd check the checkbox, but I think it should work to change the `.vscode/settings.json` file to include:  `"cmake.configureSettings": { "OPENSPACE_MODULE_FIELDLINERENDERING": "ON" }`

https://vector-of-bool.github.io/docs/vscode-cmake-tools/settings.html#conf-cmake-configuresettings

**Comment by alexanderbock** [comment]
Did this fix the issue @JOJOzzw007 ?
