### ISSUE TITLE
RenderableFieldlinesSequence doesn't set DomainEnabled on asset load

### ISSUE THREAD

**Issue by hedbergj** [OpenSpace/OpenSpace#3437]
**Describe the bug**
When loading a RenderableFieldlinesSequence, attempting to set the DomainLimits to false during asset initialization fails. 

**To Reproduce**

add the line to the Ganymede Magnetosphere, eg:

```
local GanymedeMagnetosphere = {
  Identifier = "GanymedeMagnetosphere",
  Parent = transforms.GPHIO.Identifier,
  Renderable = {
    Type = "RenderableFieldlinesSequence",
    SourceFolder = data,
    LineWidth = 3.0,
    InputFileType = "Json",
    ColorMethod = "By Quantity",
    ColorQuantity = 0,
    ColorTableRanges = { { 62.556353386366766, 1665.5534182835445 } },
    ColorTablePaths = { asset.localResource("CMR-illuminance2.txt") },
    Color = { 0.03, 0.0, 0.0, 1.0 },
    ParticleSpacing = 42.0,
    ParticleSize = 30.0,
    FlowColor = { 1.0, 1.0, 1.0, 0.1 },
    DomainEnabled = false

  },
  GUI = {
    Name = "Ganymede Magnetosphere",
    Path = "/Solar System/Missions/Juice/Fieldlines",
    Description = "Fieldlines showing a simulation of the magnetic fields around Ganymede"
  }
}
```

**Expected behavior**
Should show up on load. But is only visible after manually setting Domain Limits to false in the GUI. 

**Screenshots**
<img width="726" alt="domainlimits" src="https://github.com/user-attachments/assets/88350b62-513c-4b9d-a27d-4e0a6763174c">
then uncheckit
<img width="873" alt="domainlimits2" src="https://github.com/user-attachments/assets/15b4e50a-44cf-479b-ae34-56414818238d">

(Script log shows the expected stuff: `openspace.setPropertyValueSingle("Scene.GanymedeMagnetosphere.Renderable.DomainEnabled", false)`

**Comment by alexanderbock** [comment]
Fixed the issue and also amended the asset to have the domain disabled by default so that it shows up in the Juice profile from the start
