### ISSUE TITLE
Launcher crashes on Windows if multiple scenes are downloaded simultaneously

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#344]
If selecting more than one scene to download for, the DownloadManager tries to open the same file multiple times, resulting in an `EACCESS` error in 
`    errno_t error = fopen_s(&fp, file.path().c_str(), "wb");`
in downloadmanager.cpp:165

**Comment by emiax** [comment]
https://github.com/OpenSpace/OpenSpace/pull/404 improves stability of the Launcher
