### ISSUE TITLE
Data management ideas

### ISSUE THREAD

**Issue by emiax** [OpenSpace/OpenSpace#349]
Some long term goals for data management include (in my opinion)
- Possibility to load data (extend current scene) while OpenSpace is running.
- Make packaging as smooth and unambiguous as possible. Packaging should not depend on which data that was currently downloaded on the developer computer.
- Ability for other users to set up their own servers and have it work seamlessly
- Make sure the same data does not have to be downloaded more than once. (keep track of what is already synced)
- A well defined terminology for what is currently called modules (easily confused with code modules)
- Versioning (being able to update files on the server and have them downloaded to people)
- Having a structure to distribute data both as torrent and http downloads
- ... I'm sure we can add more stuff here...

Suggestions of incremental changes which I think can bring us closer to those targets:

I suggest that we store downloaded data in a separate folder from what is stored in the repository.
Let's rename the current concept of data `module` to `asset`. Data dependencies downloaded through torrent or http, are called `resource`s. I.e.`.mod` files become `.asset` files.

`resource`s are stored in a directory structure identical to the `asset`s. Assets need to explicitly specify their dependencies to other assets in their `.asset` file, using a lua function `import(dep)`. Resources from an asset can be retrieved using a lua method `resource(path)` defined for each asset object. 

In an `.asset` file, we can reference the resource `texture.png` like this:
- for this asset: `resources("texture.png")`
- for an dependency asset `dep`: `dep.resources("texture.png")`

OpenSpace would resolve those paths to `${RESOURCES}/<assetname>/texture.png`.

For example, in `earth.asset`:
```
Sun = import('sun')
BasicSpice = import('basic-spice')

EarthBarycenter = {
    Parent = Sun.SolarSystemBarycenter,
    Transform = {
        Translation = {
            Type = "SpiceTranslation",
            Body = "EARTH",
            Observer = "SUN",
            Kernels = BasicSpice.resource('de430_1850-2150.bsp')
        }
    }
}

Earth = {
    Parent = EarthBarycenter,
    Renderable = {
        Type = "RenderablePlanet",
        Frame = "IAU_EARTH",
        Body = "EARTH",
        Geometry = {
            Type = "SimpleSphere",
            Radius = 6.371E6,
            Segments = 100
        },
        Textures = {
            Type = "simple",
            Color = resource("textures/earth_bluemarble.jpg"),
            Night = resource("textures/earth_night.jpg"),
            Height = resource("textures/earth_bluemarble_height.jpg")
        },
        Atmosphere = {
            Type = "Nishita", -- for example, values missing etc etc
            MieFactor = 1.0,
            MieColor = {1.0, 1.0, 1.0}
        }
    },
    Tag = {"planet_solarSystem", "planet_terrestrial"},
    Transform = {
        Rotation = {
            Type = "SpiceRotation",
            SourceFrame = "IAU_EARTH",
            DestinationFrame = "GALACTIC",
        },
        Scale = {
            Type = "StaticScale",
            Scale = 1,
        },
    },
    GuiName = "/Solar/Planets/Earth"
}

return {
    EarthBarycenter = EarthBarycenter,
    Earth = Earth
}
```

Let's discuss this at some dev meeting in the near future and hear what people have to say :)

**Comment by alexanderbock** [comment]
I really like the idea of explicitly specifying he dependencies and I think we should go for this.  Basically, that would remove all of the specifications from the data folder and would leave only the data itself.

The only gripe I have is with the `.asset` filename.  I agree that we need a better name for `Module`, but asset is exactly everything that is _not_ in the (current) mod file.  All of the textures, spice kernels, models, etc are assets, while this is the specification of how the assets should be used.

How about `Package` or `Bundle`?   Those words are overloaded too, but that's in a different context

**Comment by alexanderbock** [comment]
For the "... I'm sure we can add more stuff here...":

- Versioning (being able to update files on the server and have them downloaded to people)
- Having a structure to distribute data both as torrent and http downloads
- Ability for other users to set up their own servers and have it work seamlessly

**Comment by emiax** [comment]
Added your points to the list. I agree that asset is not perfect. I like `Bundle`. `Package` is sort-of already occupied by c-pack and the packaging process.

**Comment by alexanderbock** [comment]
`Bundle` is not perfect either as it implies that the assets are included (or... bundled up) with this.. Let's see if someone else has a good idea.

Agree that `Package` is the worse of the two

**Comment by kbladin** [comment]
What about 'Content' or 'Subject'? Not Sure if it is any better than the current suggestions..

**Comment by emiax** [comment]
brainstorming..
names for data module: `pack`, `packet`, `entity`, `resource`, `component`, `group`, `container`, `element`, `item`, `collection`,
thinking more about the fact that it's only the metadata describing the actual asset:
`blueprint`, `skeleton`, `wireframe`, .. nah.

**Comment by patlj09** [comment]
`scene` and possibly `subscene`? Game engine lingo would probably have `level`

**Comment by alexanderbock** [comment]
Probably the closest would be `entity` for an individual entry in that table (http://t-machine.org/index.php/2007/11/11/entity-systems-are-the-future-of-mmog-development-part-2/).  Since it is a group of entities that are specifying together, how about `EntityCollection` or `EntitySpecification` or `EntityGroup`?

We already have a term for `scene` that describes the collection of these newly named items + scripts

**Comment by GPayne** [comment]
I like the suggested changes in the (formerly `module`) lua file with importing dependency and referencing resource(s).
I also really like the idea of resources obtainable from either torrent or http. A scheme to accomplish this could also address the other good points such as versioning and keeping track of what is already synced.

I vote for `entity` to replace `module`.

**Comment by alexanderbock** [comment]
Sleeping over it, i think i'll gravitate towards `Entity Specification` with a file ending of `.spec`.  Just naming it `entity` is a bit misleading I think, since that would normally (read "in game engines") be used for the class name

**Comment by territo-sci** [comment]
I lean toward something like Asset or Object. At least in VFX, game, & graphic design production parlance, "Asset" is used to refer to any self-contained, usable component. Especially since this is for the more outward facing part of OpenSpace, I don't see a problem with having "assets", "texture assets", or "model assets" (or substituting "object" for any of those). In fact, what if I wanted to apply a texture to every planet in a scene? We could load a single texture asset separately and apply it to all model assets currently loaded Why not consider almost everything about building the scene an asset?

There may be some trickiness on the development side to determine the best way to build an asset hierarchy, but I think that should be a task for the development team and not for every user to try to parse. My concern with some of these other ideas is that they tend toward jargon, where assets and objects are more semantic and clear to users.

If "Object" is the preferred flavor, `.obj` probably isn't an ideal extension, but we could still name it "Object" and go with an `.osobj` extension.

**Comment by GPayne** [comment]
Looks great! A few comments:

- Having an absolutePath for local or synced resource is a great feature and a necessary improvement (I'm assuming that resolving the path is not currently possible--if it is I don't know how to do it).
- I would rename 'importToggle' to importAsToggled', a minor thing but seems slightly more intuitive.
- asset.syncResource() is defined in the Asset API, but in the examples there are only calls to asset.syncedResource(). Are these the same thing?

**Comment by nusic** [comment]
Some questions from someone not having worked with openspace and Lua in a
little while. Feel free to ignore this if I lack too much context from any
previous discussions.

   - First of all, what's the problem(s) being addressed exactly? :)

   - I'm not fully clear on the concepts - both "asset" and "resource" is
   used in the API. A "resource" seem to be some kind of file, e.g a texture
   or spice kernel. What is the difference from an asset? Can asset be a
   collection of resources? Is "assetHelper" an "asset" too?

   - To reduce complexity for anyone creating their own scene: Does the
   concept of "synced" need to be exposed in the API? (it means more or less
   "downloaded from openspace owned server", right?) With the design goal of
   explicit dependencies in mind, could the API remain unaware of HOW
   dependencies are resolved, but let resources be referenced simply by a uri?
   It would make sense to be able to do:
   asset.import("/Users/erik/Documents/my-os-resources/sun/sun-3.jpg") for a
   local file, or asset.import("ftp://<...>") or asset.import("http://<...>"),
   and then openspace can do local caching of any synced assets behind the
   scenes?

   - Again, to reduce complexity for anyone creating their own scene: is it
   necessary to have both aset.import and asset.importAsToggled/importToggle -
   or could the importAsToggled functionality be the default functionality for
   asset.import, and the object and the toggle object be merged into the same
   object? e.g. the object "sun" with the defined "sunToggle.onInitialize"
   would simply be "sun.toggle.onInitialize"?


2017-08-01 0:41 GMT+02:00 Gene Payne <notifications@github.com>:
