### ISSUE TITLE
Wormhole Server should have a command to clear the history

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#35]
<a href="https://github.com/alexanderbock"><img src="https://avatars.githubusercontent.com/u/4921724?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexanderbock](https://github.com/alexanderbock)**
_Thursday May 05, 2016 at 21:33 GMT_
_Originally opened as https://github.com/OpenSpace/OpenSpace-Development/issues/46_

---

**Comment by emiax** [comment]
There is no history to clear anymore, so I'll close this.
