### ISSUE TITLE
Some issues with Linux installation instructions

### ISSUE THREAD

**Issue by MatthewTurk** [OpenSpace/OpenSpace#352]
Hi!  As part of https://github.com/openjournals/joss-reviews/issues/281 I'm attempting to follow the linux compilation instructions:

https://github.com/OpenSpace/OpenSpace/wiki/Guides-Compile-OpenSpace-on-Linux

It didn't quite work as described.  The `git clone` command returned that there was no upstream `develop` branch; I think it should be `master`.

A few other minor things I had to do -- I wasn't able to get cmake to be able to detect the right C++17 options; this is not an OpenSpace issue, but it might be helpful to suggest that if an error of the sort:

```
 CMake Error in CMakeLists.txt:
   Target "Launcher" requires the language dialect "CXX17" (with compiler
   extensions), but CMake does not know the compile flags to use to enable it.
```

shows up, to set the CMake variable `CMAKE_CXX_FLAGS` to `-std=c++17`.  This mostly seems to correct the issue, but I am independently attempting to determine why CMake is struggling.

Finally, Ghoul was giving some errors (specifically, arguments like `-Walloc-zero` not being recognized), which look like they are related to GCC 7 features.  I'm not sure where to report those as problems, or if perhaps something has been incorrectly set up in my git submodules.

**Comment by MatthewTurk** [comment]
I've given it a clean try, and I was able to compile with only a few changes to the compilation instructions.

I'm on Ubuntu 16.04.  I was able to get GCC 7 and the toolchain installed by:

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-7 g++-7
```

Setting the CMake variables:

```
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-7
CMAKE_CXX_FLAGS:STRING=-std=gnu++17
CMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-7
```

I was able to get much further, but I'm still running into issues; I've created a gist of the [compilation log](https://gist.github.com/MatthewTurk/d07479804a499065b204cdd4c3c3e634).  Any help would be greatly appreciated -- this looks to me like it might be a `std` namespacing issue, but I'm not completely certain the correct way to address it.

**Comment by alexanderbock** [comment]
I updated the instructions for compilation ingeneral and Linux in particular.  

The compilation errors look to me as if a pre C++17 standard library is used.   `std::enable_if_t`, `std::remove_cv_t`, ... are all defined in C++14.

On our Jenkins system, I have performed the same toolchain install, but then made `g++-7` the default through: `sudo rm /usr/bin/g++ && ln -s /usr/bin/g++-7 /usr/bin/g++` and `sudo rm /usr/bin/gcc && ln -s /usr/bin/gcc-7`.  That worked for me on three Ubuntu systems.  Not sure how Linux handles the different standard libraries though, but I think that is the most likely culprit

**Comment by MatthewTurk** [comment]
Thanks!  I was able to get it to work using `update-alternatives` to point to the other GCC.

**Comment by alexanderbock** [comment]
@MatthewTurk Bump
