### ISSUE TITLE
[Batch Scripting] Command line access to all configuration keys

### ISSUE THREAD

**Issue by territo-sci** [OpenSpace/OpenSpace#372]
For batch runs, it's cleaner & easier to have access to override specific settings in a single script rather than creating multiple config files then batching the config files.

Let's create a way to add command line flags for any configuration option. Something in the vein of
`-<overrideFlag> <configContainer>::<configKey>="<value>"`

**Comment by territo-sci** [comment]
Alex suggest explicitly parsing Lua commands as well, i.e.
 `OpenSpace.exe -<flag>["Path"]["Logs"] = "newpath"; ["Paths"]["Fooo"] = "bar";`

**Comment by alexanderbock** [comment]
What is the status of this?

**Comment by alexanderbock** [comment]
@territo-sci   ping
