### ISSUE TITLE
Use absolute file paths for globe layers

### ISSUE THREAD

**Issue by kbladin** [OpenSpace/OpenSpace#384]
As of now, file paths for globe layers are defined as paths relative to the mod file. Better would be to specify them as global paths and require that. Could use the ${SCENE} path as wildcard. This would make resetting layers work as there is never a need to change the runtime path.

For future:
* Never change the runtime path and use global paths for all files.
* Look at how this will work with the new scene/asset structure.

To be done:
* Update all layers to use global paths.
* Remove the special case in the `DefaultTileProvider` class where there is a need of a base path. This should not be needed after we have updated to only use global paths.

**Comment by alexanderbock** [comment]
No need for the wildcard... if you use the `openspace.absPath` Lua function with a relative path, it will convert it into an absolute path relative to the location of the mod file

**Comment by kbladin** [comment]
Cool, yes that should work just as well!
