### ISSUE TITLE
Loading a camera position saved to a file is not working properly.

### ISSUE THREAD

**Issue by jccosta** [OpenSpace/OpenSpace#391]
In order to reproduce this error one must save the camera's parameters (preferable in a location close from the Earth's ground) to a file (using the console command). Exit from OS and start it again. Load the camera data from the previous saved file through the command console

**Comment by kbladin** [comment]
The camera position is defined in the solar system space. Is the date set the same or has the planet moved relative to the Sun since the position was saved?

**Comment by alexanderbock** [comment]
MAybe it would make more sense to specify the camera position in the scene of the object that the camera is closest instead of the solar system scene?
