### ISSUE TITLE
Software Tool for Fine-Tuning Alignment on E&S Digistar System

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#399]
OpenSpace now displays on the E&S Digistar system using MPCDI support, but some minor tuning is required to get "seamless" alignment between projectors. Software tool(s) for aligning an SGCT calibration grid to the Digistar calibration grid (in raw projector frame images) can be developed to address this problem. It may also turn out that E&S discovers an error in their conversion to MPCDI that ultimately fixes this problem.

**Comment by alexanderbock** [comment]
I guess this can be closed now?
