### ISSUE TITLE
cmake failure (macOS Sierra) - related to assimp?

### ISSUE THREAD

**Issue by solarismaria** [OpenSpace/OpenSpace#410]
When trying to configure OpenSpace with the cmake App in a clean build directory, I get the following errors: 
<img width="603" alt="screen shot 2017-10-27 at 3 25 42 pm" src="https://user-images.githubusercontent.com/32748357/32124130-56f9f6c4-bb2c-11e7-88c1-d7d0718373b5.png">
<img width="718" alt="screen shot 2017-10-27 at 3 26 02 pm" src="https://user-images.githubusercontent.com/32748357/32124165-679d1538-bb2c-11e7-8cd3-8503bad8e776.png">
<img width="546" alt="screen shot 2017-10-27 at 3 26 31 pm" src="https://user-images.githubusercontent.com/32748357/32124166-67aaaa40-bb2c-11e7-80ec-b95083ae4d41.png">
<img width="970" alt="screen shot 2017-10-27 at 3 28 30 pm" src="https://user-images.githubusercontent.com/32748357/32124167-67ba4de2-bb2c-11e7-846c-9520afc77386.png">

At the moment, I'm able to identify files named AssimpConfig.cmake.in and assimp-config.cmake.in, which live in:
/Users/myusername/OpenSpace/ext/ghoul/ext/assimp

FIndassimp.cmake is here:
/Users/myusername/OpenSpace/ext/ghoul/ext/assimp/cmake_modules

There is no AssimpConfig.cmake, and assimp-config.cmake lives here, only after I've clicked configure in the cmake app for the first time:
/Users/myusername/OpenSpace/build/ext/ghoul/ext/assimp

Also, I can't find any OpenSSL directories associated with my OpenSpace version. There is, however, one SSL directory:
/Users/myusername/OpenSpace/apps/Launcher/ext/libtorrent/test/ssl

I would be appreciate it if someone could help me sort these errors so I can move forward. In particular, what should I set the following directories to? - Assimp_DIR, OPENSSL_INCLUDE_DIR, OPENSSL_ROOT_DIR, CMAKE_MODULE_PATH, CMAKE_PREFIX_PATH

I have cmake version 3.9.4. 

BTW...I just started playing with OpenSpace yesterday afternoon. I saw there were some changes regarding macOS and assimp that were just committed yesterday.

**Comment by alexanderbock** [comment]
As a quick fix, you should be able to get it working by installing Assimp using `port` or `brew` while I have a look at the detection of the find file

**Comment by alexanderbock** [comment]
The warning should be fixed now and it should hopefully compile.  Let me know if the problem persists and thanks for the feedback!

**Comment by solarismaria** [comment]
I no longer get the first error (thanks for that!), although the latter three still persist in the first cmake attempt. cmake still can't find Assimp_DIR, ILUT_Libraries, ILU_Libraries, IL_Libraries, OPENSSL_INCLUDE_DIR

But, I am able to configure and generate OpenSpace if I try a second time in cmake. The debug build in Xcode is successful. However, the release version fails. I get the following error: 
<img width="1138" alt="screen shot 2017-10-31 at 4 39 11 pm" src="https://user-images.githubusercontent.com/32748357/32250522-daf47ec8-be5a-11e7-926b-9476201b5d49.png">

And a directory: /Users/myusername/OpenSpace/Release does not exist. Have I missed a step?

**Comment by alexanderbock** [comment]
Sorry for dropping the ball on this.  Does this problem persist with a more recent checkout?

**Comment by solarismaria** [comment]
Yup, still persists. When configuring, I now only get the errors 'Info RT-extension not found', and 'Cannot set CMAKE_PREFIX_PATH', but I can still generate without issue. Again, the debug build is successful, but the release build fails in Xcode with the same complaints as above.

**Comment by CarlHostetter-NASA** [comment]
Same here: LUA link errors on Release build.

**Comment by alexanderbock** [comment]
@micahnyc   Is this still an active issue?

**Comment by micahnyc** [comment]
closing as no longer and issue. did a fresh clone and build today
