### ISSUE TITLE
Usage of textMinSize in FontRenderer

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#436]
The uniform `textMinSize` is not used anymore(?) in the shader if the `IgnoreUniformLocationError` is disabled.  Should it be used in the shader or does it depend on the shader used?  If the uniform location is not needed anymore, the commented out lines/values in the header and source can be removed

**Comment by WeirdRubberDuck** [comment]
Think this issue can be closed.  The `textMinSize` uniform is nowhere to be found

**Comment by alexanderbock** [comment]
Agreed. Probably an old stale message
