### ISSUE TITLE
Uniform usage in RenderableBillboardsCloud

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#439]
The uniforms `projection`, `modelViewTransform`, and `sides` are set in RenderableBillboardsCloud but not used in `billboard2_*s.glsl`.  Can their setting be completely removed?

Also:  Can `billboard_*s` be removed and `billboard2_*s` be renamed?

**Comment by jccosta** [comment]
Removed uniforms in 9667b6e and removed files in c320abb.
