### ISSUE TITLE
Asset system crashes intermittently in Lua

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#441]
Sometimes on application close (for OpenSpace) or finishing of one synchronization task (for Sync), OpenSpace crashes in lmem.c line 86 

`  newblock = (*g->frealloc)(g->ud, block, osize, nsize);`

**Comment by WeirdRubberDuck** [comment]
Is this still a problem?

**Comment by alexanderbock** [comment]
Nope
