### ISSUE TITLE
The voyager scene does not deinitialize properly on removeSceneGraphNode

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#444]
When loading the `voyager.scene`, some of Voyager 2's trails do not deinitialize properly. The `removeSceneGraphNode` fails for
```
    VoyagerTrailEncounterUranus,
    VoyagerTrailCruiseUranusNeptune,
    VoyagerTrailEncounterNeptune,
    VoyagerTrailCruiseNeptuneInf
```
only for the Voyager 2.

Tried the following without effect:
1. Switch the order of Voyager 1 and Voyager 2
2. Copied a different trail and renamed

Tried the following and it worked:
1. Reordering the trails to merge the last four of `voyager2.asset` intermixed between the previous ones

Having done that doesn't log the error on removeSceneGraphNode, but still crashes the application every time (most times the same (I think) as #441)

**Comment by emiax** [comment]
I tested the voyager scene now and was not able to reproduce the crash. @alexanderbock did you try this recently?
