### ISSUE TITLE
Add status information to the sync display in the launcher

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#469]
For example:
Being able to hover over a name to show the status of the download, speed, connection, ETA, etc.  Same information should be available when running the sync tasks

Reason:
At the moment the user has no idea whether a download will ever finish or not.

**Comment by emiax** [comment]
I agree this is a problem. I have added a percentage to torrent downloads: https://github.com/OpenSpace/OpenSpace/commit/001dea3a620f6f76882c5e6bacaae7b86ba39306

I will look into adding more information, like connection status. However, I think it makes sense to wait with implementing hovering/expanding/more interaction etc until we have the web gui merged in.

**Comment by alexanderbock** [comment]
I'd like to keep the webgui dependency out of that and keep it with a pure OpenGL rendering for now, since it would be best to display the loading screen as early as possible.

**Comment by emiax** [comment]
I have added progress percentage to the http syncs on the loading screen in https://github.com/OpenSpace/OpenSpace/pull/671
