### ISSUE TITLE
Delta time spring slider

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#479]
Replacing the slider with a "spring back to 0 slider" + dropbox

**Comment by GPayne** [comment]
This usually works with the "Reset time after shuttle" option enabled. However, sometimes upon releasing the mouse button the simulation increment doesn't return to 1.0 sec/sec, but instead goes to some other positive or negative value.
Environment: Windows running master branch 583c5b1

**Comment by WeirdRubberDuck** [comment]
What is meant by "spring back to 0 slider"? Is this not what the "quick adjust" is?

**Comment by alexanderbock** [comment]
Yes it is
