### ISSUE TITLE
macOS build failure

### ISSUE THREAD

**Issue by treuthardt** [OpenSpace/OpenSpace#504]
Hi! 

I tried to build the OpenSpace.app using the instructions found here: https://github.com/OpenSpace/OpenSpace/wiki/Guides-Compile-OpenSpace-on-macOS

I received many warnings and 2 errors (see attached screenshot). How do I correct the errors to successfully build OpenSpace.app?

Thanks!

![errors](https://user-images.githubusercontent.com/19392443/36116591-c8ca8192-1004-11e8-8a25-7fe9f5eb0536.jpg)

**Comment by alexanderbock** [comment]
Could you try building with `make` and see if you get the error as well?

Running CMake using a different destination folder and selecting `Makefile` as the target platform, going to that new folder and executing `make -jX` where X is the number of cores on Rachel's machine

**Comment by treuthardt** [comment]
1. I moved the contents of the build directory to a build_old directory.
2. In build, I did `ccmake -G Makefile ..`. I then configured with `c` and then generated with `g`.
3. In build, I then did `make -j6` and received the following message: "no targets specified and no makefile found".

**Comment by treuthardt** [comment]
Hi Alex. Any suggestions on how to get OpenSpace running?

**Comment by mariaweber** [comment]
I'm also having this same problem (picture above from Feb 12), compiling on a mac. I'm attending the OpenSpace workshop next week, and no working version of it!

**Comment by emiax** [comment]
Hi @treuthardt, @mariaweber 

I was not able to reproduce the error on my mac, but I have made some changes that I think may help. Can you check out the latest master (as of 04ff9d1) and see if it helped?
