### ISSUE TITLE
Atmosphere Module Causes Crash in Debug Mode with Some Nvidia Hardware

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#505]
Problem occurs when building Openspace master branch (commit `1bd1b18`) in Debug x64 configuration, and starting a Debug session in Visual Studio. Debug session crashes with error:

> Unhandled exception at 0x000000005CE0EC7C (nvoglv64.dll) in OpenSpace.exe: Fatal program exit requested.

Last log messages before the crash are:

> AtmosphereDeferredcaster (Debug)   Starting precalculations for scatering effects... 
> AtmosphereDeferredcaster (Debug)   Enabled precalculations for Atmosphere effects...

Rebuilding with `OPENSPACE_MODULE_ATMOSPHERE` disabled, then running in Debug mode prevents this crash from occurring.
Ran on Windows 10 laptop with Nvidia GeForce GT 635M, latest 390.77 nvidia driver installed.

**Comment by jccosta** [comment]
OpenGL driver issue or hardware support.
