### ISSUE TITLE
Ability to defer assets to the end

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#506]
For instance in the case of the customization, we want to load it at the very end.  Essentially an
`asset.require(not everything else)`

1. If multiple assets are deferred, the execution order can be undefined, but each is loaded after all explicitly  required or requested assets
2. If an asset is deferred and required ->  load it at required time
3. If an asset is deferred and requested -> load it at defer time

Use case:
1. Customization script would no longer need `require` edits
2. Keybinding scripts would work a bit smoother

Food for thought:
How about an "before all others" symmetrical option as well?

**Comment by emiax** [comment]
How about exporting a function from the customization asset, and let the scene assets invoke that method upon initialization?

`customization.asset`:
```
local init = function ()
    -- perform customization here.
end

local deinit = function ()
    -- tear down customization here.
end

asset.export("init", init)
asset.export("deinit", deinit)
```
`default.scene`:
```
local customization = asset.require("customization")
asset.onInitialize(function ()
  ...
  customization.init();
end)
asset.onDeinitialize(function ()
  customization.deinit();
  ...
end)
```

This will delay execution of the customization until all required child assets (recursively) have been initialized.

**Comment by emiax** [comment]
I'm closing this now. If there is need for anything like this, feel free to reopen.
