### ISSUE TITLE
For now, place the ABufferRenderer in a conditional compilation

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#509]
We are effectively not using that renderer anymore and if there is only extactly one subclasss of Renderer, the compiler can devirtualize function calls and speed up the rendering.

Comments @emiax  @jccosta ?

**Comment by territo-sci** [comment]
I still use it for the TSP volumes. As long as I can activate it on my own builds though, it sounds OK to me.
