### ISSUE TITLE
HttpSynchronization

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#539]
```lua
local kernels = asset.syncedResource({
    Name = "SDO Kernels",
    Type = "HttpSynchronization",
    Identifier = "sdo_kernels",
    Version = 1
})
```

fails without error message if `Identifier` is not a valid identifier

**Comment by alexanderbock** [comment]
Same thing if the server returns invalid URLs.  The "Assets" UI will show that they are rejected, but a log message would be great

**Comment by emiax** [comment]
Fixed in https://github.com/OpenSpace/OpenSpace/pull/546
