### ISSUE TITLE
macOS problem building Release version and running Debug version

### ISSUE THREAD

**Issue by mariaweber** [OpenSpace/OpenSpace#571]
I recently upgraded to macOS High Sierra (10.13.3). I'm able to build the Debug version in Xcode, but get the following error when building the Release version:

<img width="1138" alt="screen shot 2017-10-31 at 4 39 11 pm" src="https://user-images.githubusercontent.com/8711041/37879898-8c606c1a-3045-11e8-91ca-8de9a687e46c.png">

When I try to run the Debug version of OpenSpace.app, I get the following error:
LSOpenURLsWithRole() failed with error -10810 for the file /Users/mariaweber/OpenSpace/bin/Debug/OpenSpace.app.

I've been following the instructions on the wiki. I see a few other issues that are related to mine (#504 #477 #476 kinda), but no clear solutions.

**Comment by emiax** [comment]
Hi Maria,

I was not able to reproduce the error on my mac, but I have made some changes that I think may help. Can you check out the latest master (as of 04ff9d1) and see if it helped with the Release compilation?

**Comment by mariaweber** [comment]
I checked out the latest master and was able to build the Release version without problem. (Thank you!) I then still had some trouble launching OpenSpace (with the same -10810 error as above). A colleague at Adler helped me - it seems that it was looking for a different version of the gdal library than I have on my computer (see also #504). And I'm now launching the app from within: /Users/myusername/OpenSpace/bin/Release/OpenSpace.app/Contents/MacOS

**Comment by alexanderbock** [comment]
Nice :)  You can also start `open ~/OpenSpace/bin/Release/OpenSpace.app` or double click on it; that will open it without the commandline

**Comment by mariaweber** [comment]
Clicking on it or opening it with the method you mention works now, but it didn't work the first time I launched it for some reason.
