### ISSUE TITLE
Figure out where the dependency on Visual C++ 2013 comes from and remove it

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#573]

**Comment by emiax** [comment]
Could it be the GDAL dll that is compiled and put in the repo?

**Comment by alexanderbock** [comment]
Dependency Walker does not mention it anymore; maybe it has been removed?  Test on a system without the redistributable installed

**Comment by alexanderbock** [comment]
Culprit is the precompiled FreeImage that is in the ext folder of Ghoul

**Comment by alexanderbock** [comment]
Problem not longer exists
