### ISSUE TITLE
Focussing on 100kly grid moves the camera to infinity?

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#575]

**Comment by GPayne** [comment]
This may or may not be similar to an issue that both Matt and I have seen where the camera either starts at "NaN" distance from focus node, or suddenly jumps there. Matt saw this working on volume rendering module, and I saw it with the touch interface module. Could it be related to modules somehow?

**Comment by GPayne** [comment]
For Matt it seemed that 1 out of 4 times OpenSpace would start with this problem.
For Gene it seems to happen at random times after startup. I never changed focus to anything but the default Earth. It doesn't seem to correlate with any specific gesture.

**Comment by alexanderbock** [comment]
Alright!  Thanks you both

**Comment by alexanderbock** [comment]
Fixed;
problem was in the interpolation of the camera position.  When it was getting **really** close to the target, the angle between current direction and desired direction was going super close to 0, which means that the `w` component of the quaternion is close to 1, and when computing the angle of the quaternion, it uses an `arccos` call which overflows floating point values in that case.  So yes, @GPayne    it was related :)
