### ISSUE TITLE
Reorder layers from top->bottom to bottom->top

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#578]
Similar to photoshop etc

**Comment by WeirdRubberDuck** [comment]
Should this be a setting in the Globebrowsing module? That allows us to change whether the layers are applied from top to bottom or bottom to top? 🤔  Would be good with some more details on this issue

Dynamic reordering of layers during runtime was added in 26f5ce4c78c34720b1c905a576815d4e64e073e4 as a GUI feature

**Comment by alexanderbock** [comment]
I think rather it would be better to have a discussion which direction we would like instead.   Personally, we've been using this layer ordering for so long, I'd prefer to just close it and stick with the order that we have.
