### ISSUE TITLE
No renderable Ganymede

### ISSUE THREAD

**Issue by ronhip** [OpenSpace/OpenSpace#581]
There is not even an option to enable Ganymede, only its trail.

**Comment by alexanderbock** [comment]
That was fixed in c1c6e1397c90ff61948cf3152e37aeab6b3e803c and will be in the next release.  For a hotfix:
in `data/assets/scene/solarsystem/planets/jupiter/ganymede/ganymede.asset`, remove the comma in line 49:

`},` -> `}`
