### ISSUE TITLE
Jupiter: No eclipse shadows from moons

### ISSUE THREAD

**Issue by ronhip** [OpenSpace/OpenSpace#583]
Seems like you can enable this in the menus, but nothing renders. Should work for Io, Europa, Ganymede and Callisto.

**Comment by jccosta** [comment]
You just need to configure the casters and sources in the asset file of each body. E.g., for eath:

ShadowGroup = {
            Source1 = {
                Name = "Sun",
                -- All radius in meters
                Radius = 696.3E6
            },
            --Source2 = { Name = "Monolith", Radius = 0.01E6, },
            Caster1 = { 
                Name = "Moon",
                -- All radius in meters
                Radius = 1.737E6
            }
            --Caster2 = { Name = "Independency Day Ship", Radius = 0.0, }
}
