### ISSUE TITLE
Pluto

### ISSUE THREAD

**Issue by ronhip** [OpenSpace/OpenSpace#586]
Can we at least get a Pluto and orbit that we can enable? You can default it to disabled given current views (which could change!), but there's a lot to talk about there.

**Comment by alexanderbock** [comment]
Waiting for a WMS server from CalAcademy;  as soon as that arrives, I'll put it in

**Comment by alexanderbock** [comment]
Added in 3e107fa370cff21d035d2782516b399950a122df
