### ISSUE TITLE
Exoplanets rendering texture gets screwed up sometimes

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#622]
https://i.imgur.com/5UeFa6K.jpg

Rough reproducing steps:
1. Enabling Exoplanets
2. Enabling globular clusters
3. Disabling globular clusters

-> Exoplanets have globular clusters textures in them

Has also happened with seeing other texture; maybe lingering GL_TEXTURE state from other draw call?

**Comment by jccosta** [comment]
Fixed at 921db13
