### ISSUE TITLE
Setting Property Values via regex does not work

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#624]
The values are popped when iterating over the list of properties to be set

**Comment by emiax** [comment]
This is still an issue, or may have been reintroduced. For example:
`openspace.setPropertyValue("Scene.*Trail.Renderable.Opacity", 0)`
will only set the opacity of one of the trails. The `FloatProperty::fromLuaConversion` and `DoubleProperty::fromLuaConversion` currently pops from the stack, while  `BoolProperty::fromLuaConversion` does not. Can all the pops be safely removed, or are there side effects?
