### ISSUE TITLE
Some BitTorrent-synchronised assets are not downloading

### ISSUE THREAD

**Issue by timjrd** [OpenSpace/OpenSpace#626]
Hi :) , I am trying to [package](https://github.com/NixOS/nixpkgs/pull/42149) OpenSpace 0.11.1 for the [NixOS](https://nixos.org/) Linux distribution.

After a few patches (I will open separate issues to discuss them), I managed to compile OpenSpace under Linux. OpenSpace correctly loads most of the default assets on launch, but a few ones (all of which are torrents) remain stalled. I managed to launch OpenSpace by "disabling" those torrents in the scene scripts.

For example, the asset `Saturn Spice Kernels (sat375)` with magnet `magnet:?xt=urn:btih:79083d2069df389e65d7688bb326c7aaf1953845&dn=sat375.bsp` is not downloading. I tried with a regular BitTorrent client with DHT support, but it can't find other peers to download the torrent's metadata from. Sometimes one peer or two are appearing, but they rapidly go offline. It's not a network issue since I can download other magnets just fine.

Thanks!

**Comment by alexanderbock** [comment]
Thanks!   We are currently in the process of fixing the last things for a new release that is upcoming before the end of this month.  In that new version, the torrent-based download is completely removed in favor of HTTP synchronization.  If you can wait that long with creating the package, this will be fixed.

In the meantime, I restarted our torrent server that serves these files, so it should not stall anymore for the moment

**Comment by timjrd** [comment]
Ok it's working now, thank you!

**Comment by timjrd** [comment]
Should I wait the new version before reporting the other linux-related issues ?

**Comment by parkerjon** [comment]
Good to know someone is out there working on sci-viz tools for NixOS!
