### ISSUE TITLE
Support subfolder structure in HTTP synchronization

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#628]
Maybe updating the application version and support a stateful download file that supports the definition of a folder structure

@emiax ?

**Comment by alexanderbock** [comment]
Implement by detecting common prefix and using the rest of the path as folder structure

**Comment by emiax** [comment]
Similar behaviour to this can now be achieved by downloading a zip file, and unzip it when the asset initializes, as in: https://github.com/OpenSpace/OpenSpace/blob/04eef2086895bd400397c6038dea9b7ba6f081c4/data/assets/util/webgui.asset#L27

I can see that subfolder structure downloads may be useful in cases when zipping is not desirable. However, I will close this for now until we see a concrete need for it.
