### ISSUE TITLE
Add support for zip file-based download through HTTPSynchronization

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#632]
As an alternative to the individual download of files, it would be better to support single zip files that can be downloaded completely and locally unzipped.
Implementation:  Have another parameter passed to the cgi script from the client that tells whether the user wants a zip file or individual files

**Comment by GPayne** [comment]
I used the **minizip** library in SGCT for zip compression.

**Comment by alexanderbock** [comment]
That's good enough for government work ;)
