### ISSUE TITLE
Textures with n bytes per line, where n is not divisible by 4, display incorrectly

### ISSUE THREAD

**Issue by emiax** [OpenSpace/OpenSpace#638]
Reproduce by loading an RGB 8bit per channel image using freeimage, where the width*3 is not divisible by 4. 

Found this (https://www.khronos.org/opengl/wiki/GLAPI/glPixelStore):

> GL_UNPACK_ALIGNMENT
> Specifies the alignment requirements for the start of each pixel row in memory. The allowable values are 1 (byte-alignment), 2 (rows aligned to even-numbered bytes), 4 (word-alignment), and 8 (rows start on double-word boundaries).

I tried setting the `GL_UNPACK_ALIGNMENT` to 1, but that didn't help. @alexanderbock do you know from the top of your head how this should be taken care of?

**Comment by alexanderbock** [comment]
This has been fixed a while ago by setting the pack alignment
