### ISSUE TITLE
Issues with Image loading

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#645]
What are the current issues with image loading on different platforms?

**Comment by territo-sci** [comment]
With the DU enabled on Mac:
`(IO) No reader was found for extension 'pbm'`

**Comment by territo-sci** [comment]
My issue in https://github.com/OpenSpace/OpenSpace/issues/645#issuecomment-403959315 is resolved by installing `freeimage`. Don't know if we need to make `freeimage` or some other image package a requirement with the DU or if there's a way to load properly process `pbm`'s without one.
