### ISSUE TITLE
Spout input texture on ScreenSpaceSpout is flipped

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#654]
When using the ScreenSpace option of getting Spout into OpenSpace, the texture has a y-flip.  Is it always flipped?  It might be a DirectX vs OpenGL texture layout issue?

Any ideas, @MarcoMarquesSilva?

**Comment by alexanderbock** [comment]
Yes, it's a DirectX-OpenGL interop thing:
 - https://github.com/benkuper/Unity-Plugins/issues/6
 - https://forum.unity.com/threads/spout-syphon-on-windows-unity-plugin.249985/
 - https://answerhub.lightact.io/t/ue4-spout-problems-black-textures-memory-share-texture-share-opengl-directx-interop-warnings/72

**Comment by micahnyc** [comment]
Thinking to leave this open for posterity. Even thought we can't fix it, it's still an issue for us.
