### ISSUE TITLE
Virtual property declaration needs a better interface

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#658]
Currently, it is too easy to miss the description when declaring a virtual property and get obscure Lua errors in your face

**Comment by WeirdRubberDuck** [comment]
Is this issue still relevant? (I got the impression that we don't want to keep the virtual properties)

**Comment by alexanderbock** [comment]
Yes, I think we can close this as the virtual property mechanism is very finicky in the best-case scenario
