### ISSUE TITLE
Joystick input is not reliable when moving quickly

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#678]

**Comment by alexanderbock** [comment]
When moving the analog stick on a gamepad/joystick quickly between left-right or up-down, the movement sometimes gets stuck in one direction and does not recognize that the joystick is already in the other position.

Example:
```
< : Analog stick moved to the left
> : Analog stick moved to the right

< > < > < > < > < 
```
even though the stock is moved to the left in the end, the camera continues moving as if the analog stick was moved to the right

**Comment by GPayne** [comment]
Would applying a filter/threshold to the amount of joystick movement be an acceptable fix for this? The movement description sounds like unacceptable navigation behavior.

**Comment by alexanderbock** [comment]
Currently, it definitely is unacceptable.   I feel that the issue is happening if we switch from the right side of the stick to the left in a single frame,m eaning that we "miss" the signal to start turning.  Maybe we are only storing the last change and if multiple happen per frame, that last change gets overwritten
