### ISSUE TITLE
Display issue in planetarium dome

### ISSUE THREAD

**Issue by archiekinnane** [OpenSpace/OpenSpace#688]
When using OpenSpace in a planetarium dome, the orientation of points in a RenderableBillboardsCloud is forward-facing towards the point of interest rather than down towards the dome, causing some images to appear side-on rather than face-on.

**Comment by alexanderbock** [comment]
Thanks for the report; that is a known problem that will have been addressed in the next release by @jccosta 

In the meantime, you can switch the billboard orientation if you navigate to the scene graph node's property "Render Option" and change it from "Camera View Direction" to "Camera Position Normal".

If you don't want to do that manually, you can execute the following script in the `onInitialize` function of your scene:
`openspace.setPropertyValue('Scene.*.renderable.RenderOptionInfo', 1);`
