### ISSUE TITLE
Add ability to modify zooming speed using keybinds

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#709]
For example:
Zooming + Shift key:  1/10th of the zoom speed
Zooming + Ctrl key : 1/100th speed

mayby apply to orbital motion, too?

This would provide the user with the ability to fine-tune navigation, when needed

**Comment by emiax** [comment]
I think this is a good idea, but Shift and Ctrl are already used to control roll and pan, so I think we need to come up with some other modifier/shortcut to change the zoom/orbital speed. There is a `MouseSensitivity` property that perhaps could be divided into several properties - orbital, zoom, pan, roll etc. If we do this, the user can bind any key to modify these parameters in runtime.
