### ISSUE TITLE
Earth's night side is rendered bright if the night layer is disabled

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#713]
If just disabling "Earth at Night 2012" on Earth, the night side is rendered as bright as the front side

**Comment by micahnyc** [comment]
Even with performshading on? It feels like you just have performed shading off (which is default for earth)

**Comment by alexanderbock** [comment]
:+1:  That was the issue.

Should we add a `onChange` flag to the Earth that toggles the "perform shading" when the last/first night layer is toggled to prevent this from happening?

**Comment by micahnyc** [comment]
Recommend closing and roll into #1008

**Comment by GPayne** [comment]
I support the idea of rolling this into #1008 also.

**Comment by alexanderbock** [comment]
Yea;  closed in favor of #1008
