### ISSUE TITLE
Simulation Time Day of Month Doesn't Update with UTC

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#719]
I started OpenSpace at 19:10 my time, which is 01:10 UTC time "tomorrow". When OpenSpace starts, it has the correct 01:10 time, but the day of the month according to my time zone (which is -1 day from the UTC time zone's day).
Clicking "Now" in the GUI restores the correct UTC date, but rewinding time using the slider control does not restore the correct date. 
Environment: Windows, master branch commit 583c5b1

**Comment by alexanderbock** [comment]
That is expected behavior, see default.scene:
```lua
    local now = openspace.time.currentWallTime()
    -- Jump back one day to show a complete planet
    openspace.time.setTime(openspace.time.advancedTime(now, "-1d"))
```
