### ISSUE TITLE
Text rendering on the grids does not scale for one of the arcs

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#732]
Reproducing:
1. enable any of the grids + labels
2. one of the arcs is rendered in larger font:

https://imgur.com/a/aEKvUHA

**Comment by jccosta** [comment]
It is just a matter of configuration.
Increase the value of the "Text Max Size" variable and decrease the value of the "Text Size" variable.
Let me know if you prefer a different behavior for this.

**Comment by alexanderbock** [comment]
:+1:  Can you change the values so that they give a consistent result and commit them to `master`?

**Comment by jccosta** [comment]
Updated.
