### ISSUE TITLE
Enable Animated Textures for Planets

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#76]
<a href="https://github.com/alexanderbock"><img src="https://avatars.githubusercontent.com/u/4921724?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexanderbock](https://github.com/alexanderbock)**
_Thursday May 05, 2016 at 21:39 GMT_
_Originally opened as https://github.com/OpenSpace/OpenSpace-Development/issues/53_

---

Having the opportunity to animate the textures for a planet. For example, having a texture that shows the rotation on Jupiter etc

http://svs.gsfc.nasa.gov/vis/a000000/a003600/a003610/frames/3601x1801_2x1_30p/

@kbladin @nusic

**Comment by kbladin** [comment]
Example of a temporal specification:
```
<OpenSpaceTemporalGDALDataset>
    <OpenSpaceTimeStart>2016-11-21T13:00:00</OpenSpaceTimeStart>
    <OpenSpaceTimeEnd>2016-11-22T09:00:00</OpenSpaceTimeEnd>
    <OpenSpaceTimeResolution>30m</OpenSpaceTimeResolution>
    <OpenSpaceTimeIdFormat>YYYY-MM-DDThh_mm_ssZ</OpenSpaceTimeIdFormat>
    <FilePath>/Users/kbladin/Documents/C++projects/OpenSpace/data/scene/lodglobes/lodearth/map_datasets/3600/imergert_composite.${OpenSpaceTimeId}.png</FilePath>
</OpenSpaceTemporalGDALDataset>
```
${OpenSpaceTimeId} gets replaced with a time stamp upon loading the files. This time stamp follows the format `OpenSpaceTimeIdFormat` which need to be implemented as a class that extends TimeFormat (see temporaltileprovider.h)

**Comment by kbladin** [comment]
Another issue: FilePath needs to be relative to the openspace directory. Right now it can't be for loading images (but it can for loading wms specification if I remember correctly).
