### ISSUE TITLE
OpenSpace crashes on close using web-gui

### ISSUE THREAD

**Issue by liuloppan** [OpenSpace/OpenSpace#764]
The application throws a read access exception error upon closing when the web-gui is being used. This only occurs when closing the application  shortly after starting it.

![errorjson](https://user-images.githubusercontent.com/6057854/48446611-b2126d80-e767-11e8-848d-6b09fe1f4b5d.PNG)

**Comment by emiax** [comment]
Thanks for reporting! This should now be fixed in https://github.com/OpenSpace/OpenSpace/commit/52060ab0066137ba6675a015253bf6ca933c9585
Will close this now, but please reopen if the problem persists
