### ISSUE TITLE
Atmosphere shader to take normals in view space

### ISSUE THREAD

**Issue by liuloppan** [OpenSpace/OpenSpace#775]
Currently the atmosphere shader takes in the normals in object space. This is not very intuitive when overwriting the normal in other shaders since the other positions have been transformed into view space. It makes it harder to debug issues with normals occurring within the atmosphere.
Suggested fix: Rewrite the atmosphere shader to take view space normals

**Comment by alexanderbock** [comment]
We'll want to leave the normals in camera space as is and maybe provide a function to make the transformation easier
