### ISSUE TITLE
Earth Weather Layer not caching, even with 'CacheEnabled = true' in openspace.cfg

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#800]
I have set `ModuleConfigurations / GlobeBrowsing / CacheEnabled` to `true` in openspace.cfg. This should make caching work for all globebrowsing layers. It does make tile caching work on Mars, but the Earth weather layers are not caching. I'm testing this by jumping to the same date/times on Earth, when the weather data should be the same.
Am running branch 'feature/gui-for-touch' fb809c2, which was updated from master branch on 2019-01-19.

**Comment by alexanderbock** [comment]
The problem with this is that for the temporal layers (which the weather on Earth is), each day is an entirely separate dataset.  So each day should be separately cached, but there shouldn't be any caching between days.
Is that what you experience?
