### ISSUE TITLE
session recording does not support ${VARIABLE} type filepaths

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#801]
Such as ${BASE}/recordings/file.osrecording instead of C:/OpenSpace/recordings/file.osrecording

**Comment by GPayne** [comment]
This is no longer an issue because the new version stores all recording/playback files in the **recordings/** directory.
The wiki page on this (http://wiki.openspaceproject.com/components/session-recording-playback/general) has just been updated with more information on this.
