### ISSUE TITLE
Fails to build with CMake generator "Ninja"

### ISSUE THREAD

**Issue by hansfilipelo** [OpenSpace/OpenSpace#803]
OpenSpace fails to build when using the generator "Ninja" (https://ninja-build.org/). 

```
cmake ..\..\src\OpenSpace -G Ninja
ninja
```

On Windows 10, ninja outputs the following: 

```
ninja: error: build.ninja:27752: multiple rules generate cmake_object_order_depends_target_zlibstatic [-w dupbuild=err]
```

This could possibly be related to that the library target `zlibstatic` is created in two separate CMakeLists, listed below: 

```
apps/OpenSpace/ext/sgct/src/deps/zlib/CMakeLists.txt <-- line 176
ext/ghoul/ext/assimp/contrib/zlib/CMakeLists.txt <-- line 194
```

If I replace the name of the library within the ext/ghoul subfolder - OpenSpace seems to build when using ninja along with MS cl.exe as compiler (with a lot of warnings) as well as start.

---------------------

Building with ninja on Windows is a great way to de-couple the build system from the Visual Studio IDE and MSBuild (note: IDE != toolchain) while still being able to build in a native environment (not using some form of POSIX compatibility layer), and it would be nice if it were supported when building. The Chromium project is an example that uses ninja to bootstrap their build, which has allowed them to more easily use clang/LLVM to compile and deliver on all platforms (https://chromium.googlesource.com/chromium/src/+/lkgr/docs/clang.md).

**Comment by hansfilipelo** [comment]
Addition: A "proper" way to solve this is possibly to not compile zlib twice during build but rather use the same binary as dependency to multiple consumers - unless it is two distinct versions of zlib that other libraries are depending on.

**Comment by alexanderbock** [comment]
Fixed by now
