### ISSUE TITLE
Globe browsing layers multiply setting no longer functions correctly. 

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#807]
In the globe browsing changes from 0.12 to 0.13 it seems we lost the ability to use the multiply setting on the globe browsing layers.  

Test data can be found here: https://drive.google.com/file/d/1bgyS7gHoZYCTZpetkLO2GbCJbw8X93Ic/view

The first 2 images are 0.12 with multiply, then with normal. The next 2 images are 0.13 with multiply, then with normal.  

![0 12_crism_mult](https://user-images.githubusercontent.com/708535/53913704-efa64980-4029-11e9-8cbc-cd5c80b64cfd.png)
![0 12_crism_norm](https://user-images.githubusercontent.com/708535/53913705-f03ee000-4029-11e9-9195-c886abc589fe.png)
![0 13_crism_mult](https://user-images.githubusercontent.com/708535/53913714-f59c2a80-4029-11e9-901e-1a676839645d.png)
![0 13_crism_norm](https://user-images.githubusercontent.com/708535/53913715-f59c2a80-4029-11e9-8500-ca451329f15e.png)

**Comment by alexanderbock** [comment]
I think it was wrong before;  the Alpha channel in your example doesn't have a NoDataValue for the Alpha channel;
if I add
`    <NoDataValue>256</NoDataValue>` to the 4th rasterband, the Multiply works as expected
