### ISSUE TITLE
Write a support files for log.html

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#81]
<a href="https://github.com/alexanderbock"><img src="https://avatars.githubusercontent.com/u/4921724?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexanderbock](https://github.com/alexanderbock)**
_Thursday May 05, 2016 at 21:43 GMT_
_Originally opened as https://github.com/OpenSpace/OpenSpace-Development/issues/60_

----

Adding a CSS file to make the log a bit more pretty and readable.

Add some JavaScript? as well to be able to filter out messages by severity

**Comment by emiax** [comment]
added in 6b64400cdf4f9515125f3460e2a722773c98f99a
