### ISSUE TITLE
Reduced globebrowsing resolution when mixing resolutions

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#812]
When looking at a HiRISE patch on Mars without CTX enabled and then enable CTX, the HiRISE resolution drops a level or two.  The problem persists even if disabling CTX afterwards

**Comment by emiax** [comment]
@alexanderbock and I identified that the uniform `distanceScaleFactor` is currently not updated on shader recompilation. However, it gets updated when the `LodScaleFactor` property gets updated.
