### ISSUE TITLE
TaskRunner generates wrong filenames when reading multiple FITS files

### ISSUE THREAD

**Issue by Venustiano** [OpenSpace/OpenSpace#817]
in gaia_read.task, given a folder as follows
        OutFileOrFolderPath = dataFolder .. "/binFits/",

TaskRunner generates filenames such as

ReadFitsTask (Info)	First write for Octant_0
ReadFitsTask (Info)	Write 480264 values to /home/venustiano/dev/astro/environment/data/binFitsoctant_1.bin
ReadFitsTask (Info)	First write for Octant_1
ReadFitsTask (Info)	Write 10392 values to /home/venustiano/dev/astro/environment/data/binFitsoctant_2.bin
...

where a slash is missing between the folder 'binFits' and the file name octant_n.bin

Similar results appear when using when using gaia_octree.task but this time filenames are like

ocfitsindex.bin

where is missing a slash between ocfits / and index.bin

**Comment by alexanderbock** [comment]
No longer an issue
