### ISSUE TITLE
Atmosphere rendering coupling with HDR

### ISSUE THREAD

**Issue by emiax** [OpenSpace/OpenSpace#829]
Right now, the atmosphere is tighly coupled with the HDR. There are a few problems with this:

- When atmospheres are disabled, the HDR settings are not working
- With default settings, the atmosphere makes all other objects (trails, models, globes, volume rendering etc) appear with less contrast/saturation.

My guess is that this is being addressed in the upcoming HDR work, but I thought it would be good to also document this problem as a separate issue.

**Comment by alexanderbock** [comment]
This should be addressed before the 0.14.0 release as well .. at the very least there shouldn't be a difference in image fidelity depending on whether the HDR rendering is enabled or not

**Comment by emiax** [comment]
This was fixed in the HDR branch which is now merged.
