### ISSUE TITLE
Bug in relative position of camera vs renderables

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#83]
<a href="https://github.com/alexanderbock"><img src="https://avatars.githubusercontent.com/u/4921724?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexanderbock](https://github.com/alexanderbock)**
_Thursday May 05, 2016 at 21:44 GMT_
_Originally opened as https://github.com/OpenSpace/OpenSpace-Development/issues/62_

----

Calculation of new positions of renderables is done in post sync function, AFTER the updated position of the camera has been calculated. The camera is therefore one frame off, this is noticable when a very high time-step is being used.

Position updates should be moved to pre-sync and separated from openGL related updates. (which must occur in post-sync)

**Comment by alexanderbock** [comment]
<a href="https://github.com/emiax"><img src="https://avatars.githubusercontent.com/u/1081118?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emiax](https://github.com/emiax)**
_Friday May 20, 2016 at 11:57 GMT_

----

I suppose this could also be solved by updating the camera matrices after the object positions were updated? I think that would make more sense. Like this:

1. Sync 
2. Update scene graph positions
3. Update camera matrices according to objects

What do you think @alexanderbock ?

**Comment by alexanderbock** [comment]
Any news about this?

**Comment by nusic** [comment]
This is fixed in this branch:
https://github.com/OpenSpace/OpenSpace/commits/syncing

The update scheme used is the following:

    1. Presync: 
        1. Update time on Master
        2. Update scene graph nodes wrt time on Master
        3. Update camera wrt graph nodes and time on Master

    2. Sync: time and camera (and other stuff, but not entire scene graph states)

    3. Postsync:
        1. Time and Camera is now updated on Master and Slaves
        2. Update Scene graph nodes wrt time on Slaves only

However, this branch is not ready for merge by as of now
