### ISSUE TITLE
CEF failing on macOS

### ISSUE THREAD

**Issue by territo-sci** [OpenSpace/OpenSpace#835]
In 2dec3f3640a00329a7117b2d6bb8361a706322cf, the XCode build expects to find a Debug version of `OpenSpace Helper.app` even when building for Release. Looks like a CMake issue in https://github.com/OpenSpace/OpenSpace/blob/master/modules/webbrowser/CMakeLists.txt?

```
Error copying directory from "OpenSpace/bin/Debug/OpenSpace Helper.app" to "OpenSpace/bin/Debug/OpenSpace.app/Contents/Frameworks/OpenSpace Helper.app".
make: *** [OpenSpace_buildpart_0] Error 1
Command PhaseScriptExecution failed with a nonzero exit code
```

Building the Debug version first allows a Release build to succeed, but OpenSpace fails in both Debug and Release fail with

```
dyld: Library not loaded: @executable_path/../Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework
  Referenced from: OpenSpace/bin/Release/OpenSpace.app/Contents/MacOS/OpenSpace
  Reason: image not found
Program ended with exit code: 6
```

**Comment by territo-sci** [comment]
Issue still present in 6a6db9aa7843614222140f9e869410f33ae14304

**Comment by emiax** [comment]
I was able to reproduce this issue in xcode. As of https://github.com/OpenSpace/OpenSpace/pull/873 compilation in xcode should work in both release and debug. An issue remains for unix makefiles.

**Comment by emiax** [comment]
https://github.com/OpenSpace/OpenSpace/pull/875 fixes the makefile issue as well. Closing this.
