### ISSUE TITLE
Stereo Sun

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#838]
When rendering OpenSpace in stereo, the Sun has a massive stereo offset when inside the atmosphere.
Reproduce:
1. Start with any stereo configuration
2. Go to, for example, the surface of Mars
3. Move time so that a sunset occurs
-> Sun is too far away

**Comment by emiax** [comment]
Fixed in https://github.com/OpenSpace/OpenSpace/commit/a75bb5a5aeff195f66abb28e8541ef2ea3ae70dd
