### ISSUE TITLE
Being able to edit an existing playback path

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#839]

**Comment by GPayne** [comment]
Does this refer to the filesystem path of the playback file? The latest openspace session recording version supports having all files in the 'recordings' directory in the base OpenSpace directory.
I just submitted pull request #840 to get that version into master.

**Comment by alexanderbock** [comment]
Ah.. no, this is completely separate..  it's the ability to to later edit already recoded playbacks using some kind of user interface.  It's a longer-term project.  I just moved it out of the other issue as this one is definitely not fit for 0.14.0

1. Simplifying the recordings
2. Providing some spline-based editing of camera movements
3. Some kind of timeline-based editor

**Comment by alexanderbock** [comment]
Duplicate of #1184
