### ISSUE TITLE
Saving a camera path and being able to play it back

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#84]
<a href="https://github.com/alexanderbock"><img src="https://avatars.githubusercontent.com/u/4921724?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexanderbock](https://github.com/alexanderbock)**
_Thursday May 05, 2016 at 21:46 GMT_
_Originally opened as https://github.com/OpenSpace/OpenSpace-Development/issues/64_

---

**Comment by GPayne** [comment]
Notes from the April 2018 Dev Meeting Discussion:

Upon starting playback, the contents of a save file are inserted into a timeline object. Each event is pulled from the timeline at its proper time. We discussed the need to have a limited number of entries in the timeline, requiring periodic reads from the file to keep the timeline full.

We discussed the ability of having different playback rates. An example of this might be playing back a sequence of camera poses at twice the normal rate, while playing back the script commands at normal speed. This will be accomplished by manipulating the way that scripts are read from the saved file during playback. Each event in the timeline has a timestamp, and there will be separate multipliers for camera, time, and scripts. In this way, the playback rate of events can be scaled with time.

Some of the code for session recording/playback was borrowed from parallelPeer. The time packets that parallelPeer uses are mostly for networking latency reasons, and so won't be included. If simulation time changes, this will be captured through the execution of the associated script command.

We discussed three different timestamps for the software to keep track of:
1. Simulation time - the past, present or future date/time that is driving the positions of all renderable nodes (e.g. orbit) in the simulation.
2. Relative time - the time offset relative to the start of the session recording (e.g. a specific camera position happens 10 seconds into the playback of the session, and is not tied to a specific simulation time).
3. Wall-clock time - the actual date/time at the moment of session playback.

A playback session can be performed in simulation or relative time mode.
