### ISSUE TITLE
On-screen marker for communication purposes

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#85]
<a href="https://github.com/alexanderbock"><img src="https://avatars.githubusercontent.com/u/4921724?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexanderbock](https://github.com/alexanderbock)**
_Thursday May 05, 2016 at 21:46 GMT_
_Originally opened as https://github.com/OpenSpace/OpenSpace-Development/issues/65_

---

Having a screen-space marker rendered whose location is synchronized between all remote nodes

-> Screen-space renderable

**Comment by jonathanbosson** [comment]
The `TouchMarker` class from #358 can probably be the base for this once refactor work has been done to merge Touch and Mouse&keyboard interaction into the same input class

**Comment by alexanderbock** [comment]
Support for integration of laser pointers (for example infrared tracking)
