### ISSUE TITLE
Add the WAC v3 global mosaic to the WMS servers that removes the black stripe on the backside

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#886]

**Comment by alexanderbock** [comment]
https://astrogeology.usgs.gov/search/map/Moon/LRO/LROC_WAC/Lunar_LRO_LROC-WAC_Mosaic_global_100m_June2013

**Comment by GPayne** [comment]
Added a Wac3 layer to the Utah server. Looks the same as Wac but without the black stripe:

![Wac](https://user-images.githubusercontent.com/3966290/226045313-579deac4-0b24-4939-8394-53eee92a50dc.png)

![Wac3](https://user-images.githubusercontent.com/3966290/226045517-069bf258-7b6b-4033-8fd5-06c125bd5a2b.png)
