### ISSUE TITLE
spherical mirror projection -> partial rendering

### ISSUE THREAD

**Issue by hedbergj** [OpenSpace/OpenSpace#904]
Since the aspect ratio/FOV updates to SGCT, the spherical mirror viewport doesn't seem to work with multiple displays on Mac with a retina main monitor and regular projector for the dome. All looks well on the single monitor, but when the SphMir viewport is put on the projector, it looks like only 1/4 of the frame is rendered. Some guesses after my cursory examinations: 
a) Might be related to retina+non-retina displays? 
b) Or perhaps the undefined `update` function in `SphericalMirrorProjection.cpp` line 42. 

Here's a video showing what happens at the critical moment it goes from the main monitor to the projector: 

[https://youtu.be/MTUI4WPzKsw](https://youtu.be/MTUI4WPzKsw)

And, what the viewport normally looks like:

<img width="1097" alt="normal" src="https://user-images.githubusercontent.com/7926907/59462926-bd5b7380-8df2-11e9-9a74-ab0980315172.png">

I've tried many different SGCTconfig.xml iterations and none seem to make any difference.

Thanks

**Comment by hedbergj** [comment]
More testing suggests it might be related to #30 . Here's a image of what happens when I just use the single.xml SGCTConfig with two displays. 
![openspace-viewports](https://user-images.githubusercontent.com/7926907/59526801-deca6700-8ea7-11e9-8203-93c99a2706de.jpg)

**Comment by hedbergj** [comment]
Found a work around - if I build without CEF&Webbrowser Modules and set CEF&WebBroswer to false in cfg, then I get the full rendering on both retina and non-retina displays.

**Comment by Roxeena** [comment]
Suggesting to close this since it seems to be a duplicate of #30

**Comment by hedbergj** [comment]
Ok - I'm not even using the mac with the dome anymore so I can't explore it much, but yeah, it does seem related to #30 .
