### ISSUE TITLE
WebUI rescaling on Mac

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#914]
Maybe connected to retina/non-retina display mixup.

After starting OpenSpace the UI scaling looks correct, but when dragging the window to resize, the scaling is off

**Comment by emiax** [comment]
In case we don't get time to solve this before the release, users may be able to get around the problem by forcing OpenSpace to start in non-retina mode: http://osxdaily.com/2016/04/16/improve-performance-games-mac-retina-display-trick/

**Comment by micahnyc** [comment]
closed as working in 0.15.1
