### ISSUE TITLE
Correctly aligning the ENLIL volumetric rendering

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#92]
<a href="https://github.com/alexanderbock"><img src="https://avatars.githubusercontent.com/u/4921724?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexanderbock](https://github.com/alexanderbock)**
_Friday May 06, 2016 at 14:30 GMT_
_Originally opened as https://github.com/OpenSpace/OpenSpace-Development/issues/75_

---

**Comment by alexanderbock** [comment]
@emiax  I guess this is fixed by now?

**Comment by alexanderbock** [comment]
@emiax  Bump

**Comment by alexanderbock** [comment]
@ElonOlsson   Do you know about this?   The issue was that some ENLIL volume rendering that we were using before (not sure where the data is or how to access it either) was not aligned correctly.
Imho, we can almost think about closing this without a fix if we don't even have the data anymore

**Comment by GPayne** [comment]
This could use a simple description and a link for background. The first post's link to issue 75 no longer exists.

**Comment by ElonOlsson** [comment]
Even if this implementation will be revisited, very much will be outdated and will need to be redone anyway. Also we don't have that exact data anymore. Closing
