### ISSUE TITLE
Add atmospheric configuration for Venus, Jupiter's Moons and Saturn.

### ISSUE THREAD

**Issue by jccosta** [OpenSpace/OpenSpace#922]
Add atmospheric configurations for those bodies. A small pre-calculated texture should be used when possible.

**Comment by alexanderbock** [comment]
I closed this for now as the ticket is a bit too widely formulated.  If the need for individual atmospheres for planets comes up again, I'd say to create an issue for each instead.  261f3d9 added the Titan atmosphere
