### ISSUE TITLE
WebGUI on Dome Slaves

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#923]
Investigate whether the WebGUI is used on the dome slaves or when the UI is disabled in the config file

**Comment by emiax** [comment]
I've been digging through this today, and found that the browser code is not touched on slaves nor when the UI is disabled in the config file.

I also found that the reason why OpenSpace seems to be faster when compiling without CEF is that retina mode is turned off, so the rendering is done at half res per axis. Will close this issue, but we may want to think about ways to force OpenSpace to render in non-retina mode through a future launcher or similar. Until then, we can recommend this trick to macbook users, if they face bad performance: http://osxdaily.com/2016/04/16/improve-performance-games-mac-retina-display-trick/ (manually forcing non-retina mode)
