### ISSUE TITLE
Build TUIO server from scratch and specify as a dependency

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#928]

**Comment by Mik-pe** [comment]
As of https://github.com/OpenSpace/OpenSpace/pull/1015, this is done and an obsolete issue.
#1015 integrates the TUIO server into the touch module on Windows touchscreens. If the TUIO server was windows-only then this issue can be seen as closed. If we want a TUIO server on multiple platforms, we might reopen this issue.
