### ISSUE TITLE
HTTP Data sync does not handle slow connections well

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#933]
If a http request is slow to respond and still being handled when the application is closed, the thread destructor of the asynchttprequest leads to a crash

**Comment by alexanderbock** [comment]
It's only a problem if the connection is slow, not if the connection fails outright

**Comment by emiax** [comment]
It seems that this was a problem with the version checker only. I added a cancel call when the engine deinitialized, which fixes the problem.
