### ISSUE TITLE
crashes when file's are not present on disk

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#936]
In a few places we will crash if we try to load a non existing file.

One example is with the slide deck helper, another is with the tletranslation

**Comment by GPayne** [comment]
Release 0.15 will use a new satellite renderable that will not crash if a TLE file is missing or corrupt, so the tletranslation case will be covered/fixed. We will still leave the TLE Translation type in the space module for legacy compatibility, but the probability of it being used after the new release is very low.

**Comment by liuloppan** [comment]
Will there still not be a use case of having TLEtranslation for single objects?
