### ISSUE TITLE
SGCT ReadConfig set brightness

### ISSUE THREAD

**Issue by OlexandrI** [OpenSpace/OpenSpace#941]
ReadConfig when read window config attribute "brightness" setting "contrast".
ReadConfig.cpp line 368:
```
float brightness = -1.0f;
if (element[1]->QueryFloatAttribute("brightness", &brightness) == tinyxml2::XML_NO_ERROR && brightness > 0.0f)
    tmpWin->setContrast(brightness);
```

**Comment by alexanderbock** [comment]
Can you clarify?  When looking at the code, it seems to be doing what i'd expect:
```
                    float contrast = -1.0f;
                    if (element[1]->QueryFloatAttribute("contrast", &contrast) == tinyxml2::XML_NO_ERROR && contrast > 0.0f)
                        tmpWin.setContrast(contrast);

                    float brightness = -1.0f;
                    if (element[1]->QueryFloatAttribute("brightness", &brightness) == tinyxml2::XML_NO_ERROR && brightness > 0.0f)
                        tmpWin.setContrast(brightness);
```

**Comment by OlexandrI** [comment]
ReadConfig - first, read _contrast_ value from config `QueryFloatAttribute("contrast", &contrast)` and call `setContrast(contrast)`. After, read _brightness_ value `QueryFloatAttribute("brightness", &brightness)` and call `setContrast(brightness)`, maybe need call `setBrightness(brightness)`?

In SGCTWindow.cpp, method sgct::SGCTWindow::updateTransferCurve(), line 1987:
```
        float c = ((static_cast<float>(i)/255.0f) - 0.5f) * mContrast + 0.5f;
        float b = c + (mBrightness - 1.0f);
```
**mContrast** and **mBrightness** - different variables

**Comment by alexanderbock** [comment]
Oh wow.. of course!  I copy-pasted the code and *still* didn't see the change.  Thanks and good eyes!!

Fixed in https://github.com/opensgct/sgct/commit/25c8d30bde216066840d197e4443def196c70e17
and updated here in 0e1bc9950d4ca3ac533173208947712407d8fc96
