### ISSUE TITLE
trails are not depth sorting with planets

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#946]
As seen in attached screen shot. Easy to see when visiting Uranus as reported here: https://team-openspace.slack.com/archives/CKKJ2C753/p1565201561002100

![OpenSpace_000001](https://user-images.githubusercontent.com/708535/62650665-602cfb80-b925-11e9-8c56-49ee1290fa85.png)

**Comment by emiax** [comment]
This is implemented in https://github.com/OpenSpace/OpenSpace/commit/1cba7e1d88bb0c6c508ce39b0d46fdc59ce01030, and will be merged when the hdr branch is merged.
