### ISSUE TITLE
macos doesnt startup by default

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#947]
Something in this commit: https://github.com/OpenSpace/OpenSpace/commit/5079f3fc60f809820fb8d781baa080d49cfec385 makes macos startup hang

**Comment by emiax** [comment]
MacOS does not seem to like that the server process is being restarted, which happens when endpoints are added and removed. I have pushed a quick fix to master which should improve stability, but a better way would be to only startup the server once - when all the endpoints are determined.

**Comment by micahnyc** [comment]
fixed in current master
