### ISSUE TITLE
Error Log for Openspace in Windows 10

### ISSUE THREAD

**Issue by SamuelJadhav** [OpenSpace/OpenSpace#948]
[log.docx](https://github.com/OpenSpace/OpenSpace/files/3485110/log.docx)
Attached log.docx error file.
Cannot run Openspace.

**Comment by emiax** [comment]
Hi @SamuelJadhav, 
Thank you for reporting this problem. We are experiencing problems with our data server and are working on fixing those. I think those may be related to this issue.
