### ISSUE TITLE
The Hue slider behaves strangely

### ISSUE THREAD

**Issue by emiax** [OpenSpace/OpenSpace#958]
The hue slider introduced with HDR does not behave like a "normal" hue slider:

- I think it would make sense to change the range to [-180, 180] but [0, 360] might also work.
- Regardless of the range, the default value should be 0, not 180.
- Not all colors are currently affected by the hue: MarsTrail (dark red) looks completely unaffected.
- 180 and -180 should be equivalent. (or 0 and 360 should be equivalent). Example:
    Right now, blue becomes magenta-ish at 180 and green at -180. In my book, blue should become the complementary color (yellow) when rotated 180 degrees in either direction. 

An alternative, that I actually think I would vote for, is to remove the hue setting altogether, unless there is a clear use-case. I don't think a hue-slider is going to be helpful for anyone in terms of calibrating a projection system. Thoughts?

**Comment by alexanderbock** [comment]
I agree with the first four points; I'd also expect the slider to be defaulting to 0 and `h mod 360 = h`

From my point of view, the hue slider is there to make the HSV tripled complete.  If there are three sliders for Hue, Saturation, and Value, people are primed to understand what the Saturation and Value mean, if the Hue is missing, it might be not as intuitive to grasp

**Comment by emiax** [comment]
Yeah, I don't have a strong position against keeping the hue slider, but if it's hard to make it behave like the one in Photoshop (and similar applications), then I'd suggest removing it for now and add it back in later.

**Comment by alexanderbock** [comment]
Taking this over to free up time for jccosta
