### ISSUE TITLE
Cannot create a member of type AyncHttpFileDownload

### ISSUE THREAD

**Issue by ettlitetlov** [OpenSpace/OpenSpace#964]
Error C2280:	
'openspace::WebFieldlinesWindow &openspace::WebFieldlinesWindow::operator =(const openspace::WebFieldlinesWindow &)': attempting to reference a deleted function	

Missing operator= ?

Code snutt: `std::unique_ptr<AsyncHttpFileDownload> ptr;`

**Comment by emiax** [comment]
Fixed in https://github.com/OpenSpace/OpenSpace/commit/93c6bf3429cf836bdfc632521b38ab3b8d0a8885. Will close issue now, but let me know if there are remaining issues.
