### ISSUE TITLE
Mars dimmed when zooming in and perform shading is disabled

### ISSUE THREAD

**Issue by liuloppan** [OpenSpace/OpenSpace#966]
Mars dimmed when zooming in. This error occurs when atmosphere is enabled and performshading is disabled. Seems like the shading "kicks in" when you get close even when disabled since the dimming is pitch black on what would be the dark side of Mars and only slightly darker than normal on the side towards the sun.

To reproduce bug: Go to Mars. Have atmosphere enabled and `Scene.Mars.Renderable.PerformShading` disabled. Zoom in to approximately 3400km from focus.

**Comment by micahnyc** [comment]
Recommend closing and roll into #1008

**Comment by GPayne** [comment]
I also support closing & rolling into #1008 (same as is proposed with issue #713)

**Comment by alexanderbock** [comment]
Agree. Closed in favor of #1008
