### ISSUE TITLE
Easy interface necessary for determining the webgui endpoint

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#973]
It is currently not very intuitive for an end user to change the WebUI endpoint.  I guess you'd have to copy the webgui.asset and replace the hardcoded string in there with a new string, but that requires too much effort.

It would be better to have a helper asset that exposes a single function that can be called from the initialize of the `.scene` that determines the startup endpoint

**Comment by emiax** [comment]
Yeah, I agree it's not ideal with the way it's set up with a stringlistproperty of pairs.
Do you have a specfic use case in mind? Choosing between regular and touch gui?

**Comment by alexanderbock** [comment]
Would also need the creation of a new webgui asset that makes use of the simplified frontend, in exchange to `webgui.asset`

**Comment by alexanderbock** [comment]
This usecase is solved by changing the `Modules.CefWebGui.GuiUrl` property in either a profile or as a separate asset
