### ISSUE TITLE
Saturn rings rendered behind Saturn on zoom

### ISSUE THREAD

**Issue by liuloppan** [OpenSpace/OpenSpace#975]
Sometimes while moving away from or towards Saturn its rings are rendered behind the planet. 
To reproduce this error,  set "Adaptive Stereoscopic Depth" to false and tweak the "Static View Scale Component".

**Comment by jccosta** [comment]
@liuloppan Can you provide me with a saved record file with an example of it happening? I am having trouble replicating this issue.

**Comment by liuloppan** [comment]
http://weber.itn.liu.se/~lovha71/vids/2020-05-28%2022-57-30.mp4

**Comment by micahnyc** [comment]
This only happens for me when I set the Static View Scale to negative values < -8.5. 

Perhaps the rings are not using the scaled worldspace for their calculations.

**Comment by alexanderbock** [comment]
Cannot reproduce anymore
