### ISSUE TITLE
Solarsystem sun flare limited to a single monitor in multi-monitor display

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#977]
Running OpenSpace master (commit 67757a9) on multi-monitor display wall at SCI.

When zooming away from solar system, the sun flare only appears on a single monitor (whichever monitor the sun's position is in). This moves to a different monitor if I pan the camera to move the sun into that one.
Note that this is not a problem with the sun itself, which has a similar flare; if I zoom close to the sun, then all monitors on the wall show the flare correctly.

**Comment by alexanderbock** [comment]
Just verifying whether this is fixed in your branch @jccosta ?

**Comment by jccosta** [comment]
It is working fine on the master branch on a fisheye rendering configuration. If he is talking about the star rendering for the sun, that is fixed in the issue/981 branch. The correction is only waiting for your approval in the PR.

**Comment by alexanderbock** [comment]
Yea, that's what I thought..  Thanks!

**Comment by GPayne** [comment]
I tested with issue/981 branch on the multi-monitor display and the problem is now fixed.
