### ISSUE TITLE
Master node behavior problems when running multi-monitor display wall

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/OpenSpace#978]
(Running OpenSpace master (commit 67757a9) on multi-monitor display wall at SCI)

There is correct rendering on the display nodes but not on the master node (note that the master display is not disabled in the SGCT config file). The WebGUI does display correctly, and mouse controls can be used to navigate OpenSpace as well as interact with the WebGUI.

**Comment by GPayne** [comment]
This ceased to be a problem in newer versions, but as I recall there was interest in discovering what had originally caused the problem. I recommend closing this since it is getting harder to replicate.

**Comment by alexanderbock** [comment]
Yea, I agree.  We can reopen if it is still an issue when we have access to the powerwall again
