### ISSUE TITLE
Star rendering is cut on cubemap borders

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#981]

**Comment by alexanderbock** [comment]
![OpenSpace_000000](https://user-images.githubusercontent.com/4921724/64989461-df6f0100-d8cd-11e9-96bd-73ed86fc0dbc.png)


To reproduce:
`SGCTConfig = sgct.config.fisheye{1024, 1024}`
and place a star on the boundary between two cubemap faces

**Comment by jccosta** [comment]
Fixed in commit 78eb673611.
