### ISSUE TITLE
OpenSpace crashes if other layers are enabled on Earth in MacOS

### ISSUE THREAD

**Issue by alexanderbock** [OpenSpace/OpenSpace#992]
when you turn on any color layer on Earth other than the default, OpenSpace crashes. We only tested this on the Mac, not sure if others are having the issue.

**Comment by alexanderbock** [comment]
Probably a related issue:

[log.pdf](https://github.com/OpenSpace/OpenSpace/files/3686043/log.pdf)

**Comment by alexanderbock** [comment]
Notes;  maybe it is related to the `modules/globebrowsing/gdal_data` not being available?

asherp reported
"Unable to open EPSG support file gcs.csv. Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files." in the slack

**Comment by micahnyc** [comment]
closed as fixed in 0.15.1
