### ISSUE TITLE
Assetize globebrowsing files

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace#997]
We would like the extra globebrowsing layers that are added via the customization asset (downloaded from osp.com) to be added as assets the way the apollo globebrowsing is added.

**Comment by micahnyc** [comment]
Some ones that Carter want's to add are here: 

Tycho Central Peak:
On Moon Trek: search "tycho"
LRO LROC DEM, Tycho Crater
LRO LROC Image Mosaic, Tycho Crater

Surveyor 7, which landed on the northwestern flank of Tycho:
http://wms.lroc.asu.edu/lroc/view_rdr/NAC_DTM_SURVEYOR7   array of NAC's, single DEM

**Comment by alexanderbock** [comment]
Potential connection with the license merging;  how do we handle different licenses for different image layers of the `.info` files?
